#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_gem_BeamOnTarget_BLshielding_E_right_fork_debug(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_18deg_LD_21m_30degcut_poly/HallC_beamtest_bggen_LH2_pim_18deg_LD_21m_30degcut_poly_filenum29270_output_preshower_theta_rate_tid1_ELess500MeV.root");
	TFile *f7 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_18deg_LD_21m_30degcut_poly/HallC_beamtest_bggen_LH2_pip_18deg_LD_21m_30degcut_poly_filenum33740_output_preshower_theta_rate_tid1_ELess500MeV.root");
	TFile *f17 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3_poly_beamline/HallC_beamtest_eAll_LD2_18deg_filenum9991_9.991e8_10.6GeV_shielding_30x30x2.5cm3_poly_beamline_output_preshower_reconstructtheta_rate_tid1_finerbin.root");
	//TFile *f17 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3_poly_beamline/HallC_beamtest_eAll_LD2_18deg_filenum9991_9.991e8_10.6GeV_shielding_30x30x2.5cm3_poly_beamline_output_preshower_difftheta_rate_tid1_finerbin.root");
	//TFile *f27 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3_poly_beamline/HallC_beamtest_eAll_LD2_18deg_filenum9991_9.991e8_10.6GeV_shielding_30x30x2.5cm3_poly_beamline_output_preshower_difftheta_rate_tid1_EL5GeV_finerbin.root");
	TFile *f27 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3_poly_beamline/HallC_beamtest_eAll_LD2_18deg_filenum9991_9.991e8_10.6GeV_shielding_30x30x2.5cm3_poly_beamline_output_preshower_reconstructtheta_rate_tid1_EL5GeV_finerbin.root");
	//TFile *f17 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3_poly/HallC_beamtest_eAll_LD2_18deg_filenum993_9.93e7_10.6GeV_shielding_output_preshower_theta_rate_tid1_ebug.root");
	TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_18deg_LD_21m_30degcut_poly/HallC_beamtest_bggen_LH2_pim_18deg_LD_21m_30degcut_poly_filenum29270_output_preshower_theta_rate_tid1.root");
	TFile *f15 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_18deg_LD_21m_30degcut_poly/HallC_beamtest_bggen_LH2_pip_18deg_LD_21m_30degcut_poly_filenum33740_output_preshower_theta_rate_tid1.root");
	TH1F *hprocid_gem1;       
	TH1F *hpf_gem1;
	TH1F *hE_gem1;
	TH1F *hpf_gem1_1cmAl;
	TH1F *hE_gem1_1inpoly;
	TH1F *hhit_Egem1_procID[11];
	TH1F *hhit_Egem1;
	TH1F *hhit_Egem1_gamma;
	TH1F *hhit_Egem1_electron;
	TH1F *hhit_Egem1_other;
	TH1F *hhit_Egem1_pi0;
	TH1F *hhit_Edepgem1_procID[11];
	TH1F *hhit_Edepgem1;
	TH1F *hhit_Edepgem1_gamma;
	TH1F *hhit_Edepgem1_other;
	TH1F *hhit_Edepgem1_pi0;
	TH1F *hhit_Edepgem12_electron_noTB;
	TH1F *hhit_Edepgem12_electron;
	TH1F *hhit_Edepgem12_electron_test;
	TH1F *hhit_Egem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_1cmAl;
	TH1F *hhit_Edepgem1_electron_1inpoly;
	TH1F *hhit_Edepgem1_electron_25cm;
	TH1F *hhit_Edepgem1_electron_35cm;
	TH1F *hhit_Edepgem1_electron_35cmL;
	TH1F *hhit_Edepgem1_electron_45cm;
	TH1F *hhit_Edepgem1_electron_55cm;
	TH1F *hhit_Edepgem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_noB;
	TH1F *hhit_Edepgem1_electron;

	TH1F *hhit_Edepgem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_noB;
	TH1F *hhit_Edepgem2_electron;
	TH1F *hhit_Egem2_electron;
	TH1F *hhit_Egem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_1cmAl;
	TH1F *hhit_Edepgem2_electron_1inpoly;
	TH1F *hhit_Edepgem2_electron_25cm;
	TH1F *hhit_Edepgem2_electron_35cm;
	TH1F *hhit_Edepgem2_electron_35cmL;
	TH1F *hhit_Edepgem2_electron_45cm;
	TH1F *hhit_Edepgem2_electron_55cm;

	TH1F *hhit_theta_noTB;
	TH1F *hhit_theta_noB;
	TH1F *hhit_theta;
	TH1F *hhit_theta_1cmAl;
	TH1F *hhit_theta_1inpoly;
	TH1F *hhit_theta_25cm;
	TH1F *hhit_theta_25cm_electron;
	TH2F *hhit_theta_vs_E_25cm;
	TH2F *hhit_theta_vs_E_25cm_electron;
	TH1F *hhit_theta_35cm;
	TH1F *hhit_theta_35cmL;
	TH1F *hhit_theta_45cm;
	TH1F *hhit_theta_45cm_electron;
	TH1F *hhit_theta_55cm_electron;
	TH1F *hhit_theta_55cm;
	TH2F *hhit_theta_vs_E_45cm;
	TH2F *hhit_theta_vs_E_45cm_electron;
	TH2F *hhit_theta_vs_E_55cm_electron;
	TH2F *hhit_theta_vs_E_55cm;
	TH1F *hhit_theta_gem2_noTB;
	TH1F *hhit_theta_gem2_noB;
	TH1F *hhit_theta_gem2;
	TH1F *hhit_theta_1cmAl_gem2;
	TH1F *hhit_theta_1inpoly_gem2;
	TH1F *hhit_theta_25cm_gem2;
	TH1F *hhit_theta_25cm_gem2_electron;
	TH1F *hhit_theta_35cm_gem2;
	TH1F *hhit_theta_35cmL_gem2;
	TH1F *hhit_theta_45cm_gem2;
	TH1F *hhit_theta_45cm_gem2_electron;
	TH1F *hhit_theta_55cm_gem2_electron;
	TH1F *hhit_theta_55cm_gem2;
	TH1F *hhit_Edepgem1_gamma_noTB;
	TH1F *hhit_Edepgem1_gamma_noB;
	TH1F *hhit_Edepgem1_gamma;
	TH1F *hhit_Egem1_gamma_noTB;
	TH1F *hhit_Edepgem1_gamma_1cmAl;
	TH1F *hhit_Edepgem1_gamma_1inpoly;
	TH1F *hhit_Edepgem1_gamma_35cm;
	TH1F *hhit_Edepgem1_gamma_45cm;
	TH1F *hhit_Edepgem1_gamma_55cm;
	TH1F *hhit_Edepgem1_gamma_25cm;
	TH1F *hhit_Edepgem1_gamma_15deg;
	TH1F *hhit_Edepgem1_gamma_20degv;
	TH1F *hhit_Edepgem2_gamma_15deg;
	TH1F *hhit_Edepgem2_gamma_20degv;

	TH1F *hhit_Edepgem2_gamma_noTB;
	TH1F *hhit_Edepgem2_gamma_noB;
	TH1F *hhit_Edepgem2_gamma;
	TH1F *hhit_Egem2_gamma;
	TH1F *hhit_Egem2_gamma_noTB;
	TH1F *hhit_Edepgem2_gamma_1cmAl;
	TH1F *hhit_Edepgem2_gamma_1inpoly;
	TH1F *hhit_Edepgem2_gamma_35cm;
	TH1F *hhit_Edepgem2_gamma_25cm;
	TH1F *hhit_Edepgem2_gamma_45cm;
	TH1F *hhit_Edepgem2_gamma_55cm;
	TH1F *hhit_theta_noTB_electron;
	TH1F *hhit_theta_noB_electron;
	TH1F *hhit_theta_electron;
	TH1F *hhit_theta_1cmAl_electron;
	TH1F *hhit_theta_1inpoly_electron;
	TH1F *hhit_theta_35cm_electron;
	TH1F *hhit_theta_gem2_noTB_electron;
	TH1F *hhit_theta_gem2_noB_electron;
	TH1F *hhit_theta_gem2_electron;
	TH1F *hhit_theta_1cmAl_gem2_electron;
	TH1F *hhit_theta_1inpoly_gem2_electron;
	TH1F *hhit_theta_35cm_gem2_electron;
	TH1F *hhit_Edepgem1_Moller_noTB;
	TH1F *hhit_Edepgem1_Moller_noB;
	TH1F *hhit_Edepgem1_Moller;
	TH1F *hhit_Edepgem1_Moller_1cmAl;
	TH1F *hhit_Edepgem1_Moller_1inpoly;
	TH1F *hhit_Edepgem1_Moller_35cm;
	TH1F *hhit_Edepgem1_compton_noTB;
	TH1F *hhit_Edepgem1_compton_noB;
	TH1F *hhit_Edepgem1_compton;
	TH1F *hhit_Edepgem1_compton_1cmAl;
	TH1F *hhit_Edepgem1_compton_1inpoly;
	TH1F *hhit_Edepgem1_compton_35cm;

        hhit_Edepgem1_electron_25cm = (TH1F*)f4->Get("hit_Egem1");
        hhit_Edepgem1_electron_45cm = (TH1F*)f7->Get("hit_Egem1");

        hhit_Edepgem1_gamma_45cm = (TH1F*)f17->Get("hit_Egem1");
        hhit_Edepgem1_gamma_25cm = (TH1F*)f14->Get("hit_Egem1");
        hhit_theta_25cm = (TH1F*)f4->Get("gen_Theta_gem1");
        hhit_theta_25cm_electron = (TH1F*)f14->Get("gen_Theta_gem1");
        hhit_theta_45cm = (TH1F*)f7->Get("gen_Theta_gem1");
        hhit_theta_55cm = (TH1F*)f27->Get("gen_Theta_gem1");
        hhit_theta_45cm_electron = (TH1F*)f17->Get("gen_Theta_gem1");
        hhit_theta_55cm_electron = (TH1F*)f15->Get("gen_Theta_gem1");

        hhit_theta_vs_E_25cm = (TH2F*)f4->Get("gen_ThetaP_gem1");
        hhit_theta_vs_E_25cm_electron = (TH2F*)f14->Get("gen_ThetaP_gem1");
        hhit_theta_vs_E_45cm = (TH2F*)f7->Get("gen_ThetaP_gem1");
        hhit_theta_vs_E_55cm = (TH2F*)f27->Get("gen_ThetaP_gem1");
        hhit_theta_vs_E_45cm_electron = (TH2F*)f17->Get("gen_ThetaP_gem1");
        hhit_theta_vs_E_55cm_electron = (TH2F*)f15->Get("gen_ThetaP_gem1");
        hhit_Edepgem2_electron_25cm = (TH1F*)f4->Get("hit_Egem2");
        hhit_Edepgem2_electron_45cm = (TH1F*)f7->Get("hit_Egem2");
        hhit_Edepgem2_gamma_45cm = (TH1F*)f17->Get("hit_Egem2");
        hhit_Edepgem2_gamma_25cm = (TH1F*)f14->Get("hit_Egem2");
        hhit_theta_25cm_gem2 = (TH1F*)f4->Get("gen_Theta_gem2");
        hhit_theta_55cm_gem2 = (TH1F*)f27->Get("gen_Theta_gem2");
        hhit_theta_25cm_gem2_electron = (TH1F*)f14->Get("gen_Theta_gem2");
        hhit_theta_45cm_gem2 = (TH1F*)f7->Get("gen_Theta_gem2");
        hhit_theta_45cm_gem2_electron = (TH1F*)f17->Get("gen_Theta_gem2");
        hhit_theta_55cm_gem2_electron = (TH1F*)f15->Get("gen_Theta_gem2");

        hhit_theta_vs_E_25cm_gem2 = (TH1F*)f4->Get("gen_ThetaP_gem2");
        hhit_theta_vs_E_55cm_gem2 = (TH1F*)f27->Get("gen_ThetaP_gem2");
        hhit_theta_vs_E_25cm_gem2_electron = (TH1F*)f14->Get("gen_ThetaP_gem2");
        hhit_theta_vs_E_45cm_gem2 = (TH1F*)f7->Get("gen_ThetaP_gem2");
        hhit_theta_vs_E_45cm_gem2_electron = (TH1F*)f17->Get("gen_ThetaP_gem2");
        hhit_theta_vs_E_55cm_gem2_electron = (TH1F*)f15->Get("gen_ThetaP_gem2");
	TCanvas *c_gem[10];
	c_gem[4] = new TCanvas("c_gem[4]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
        //hhit_theta_noTB->SetLineColor(6);	
/*        hhit_theta_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");	
        hhit_theta_noTB->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_noTB->SetTitle("#gamma in front of gem1");	
        hhit_theta_noTB->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_noTB->Scale(0.00000001);
        hhit_theta_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
       // hhit_theta->Draw("HISt");	
        hhit_theta_noTB->SetLineColor(kGreen+1);	
       // hhit_theta_noTB->Scale(0.00000001);
        hhit_theta_noTB->Draw("HISt");	
        hhit_theta_noB->SetLineColor(6);	
        hhit_theta_noB->Scale(0.00000001);
        hhit_theta_noB->Draw("same HISt");	
        hhit_theta_1cmAl->SetLineColor(4);	
        hhit_theta_1cmAl->Scale(0.00000001);
        hhit_theta_1cmAl->Draw("same HISt");	
        hhit_theta_1inpoly->SetLineColor(1);	
        hhit_theta_1inpoly->Scale(0.00000001);
        hhit_theta_1inpoly->Draw("same HISt");	
        double rate_theta_linpoly= hhit_theta_1inpoly->Integral();
        hhit_theta_35cm->SetLineColor(2);	
        hhit_theta_35cm->Scale(0.00000001);
        hhit_theta_35cm->Draw("same HISt");	
        hhit_theta_1inpoly->Draw("same HISt");*/	
        hhit_theta_45cm->SetLineColor(1);	
        hhit_theta_45cm->GetYaxis()->SetTitle("rate (MHz/cm2)");	
        hhit_theta_45cm->GetXaxis()->SetTitle("#theta_{track}-#theta_{hit}");	
        hhit_theta_45cm->SetTitle("in front of preshower");	
        hhit_theta_45cm->GetXaxis()->SetRangeUser(0,60);	
        hhit_theta_45cm->GetYaxis()->SetRangeUser(1e-5,1e1);	
        //hhit_theta_45cm->Draw("HISt");	
        hhit_theta_25cm->SetLineColor(2);	
       // hhit_theta_25cm->Draw("same HISt");	
        hhit_theta_45cm_electron->SetLineColor(6);	
        hhit_theta_45cm_electron->Scale(1000);	
        hhit_theta_45cm_electron->GetYaxis()->SetTitle("rate (Hz)");	
        //hhit_theta_45cm_electron->GetXaxis()->SetTitle("#theta_{track}-#theta_{hit}");	
        hhit_theta_45cm_electron->GetXaxis()->SetTitle("#theta_{reconstruct} deg");	
        hhit_theta_45cm_electron->SetTitle("in front of preshower");	
        hhit_theta_45cm_electron->GetYaxis()->SetRangeUser(1e-5,1e1);	
        //hhit_theta_45cm_electron->GetXaxis()->SetRangeUser(-3,3);	
        hhit_theta_45cm_electron->GetXaxis()->SetRangeUser(0,60);	
        hhit_theta_45cm_electron->Draw(" HIST");	
        hhit_theta_25cm_electron->SetLineColor(4);	
       // hhit_theta_25cm_electron->Draw(" same HIST");	
        hhit_theta_55cm->SetLineColor(3);	
        hhit_theta_55cm->Scale(1000);	
        //hhit_theta_55cm->GetXaxis()->SetRangeUser(-3,3);	
        hhit_theta_55cm->GetXaxis()->SetRangeUser(0,60);	
        hhit_theta_55cm->Draw(" same HIST");	
        hhit_theta_55cm_electron->SetLineColor(kOrange-3);	
      //  hhit_theta_55cm_electron->Draw(" same HIST");	
	TLegend *leg1 = new TLegend(0.15,0.7,0.4,0.85);
	//leg1->AddEntry(hhit_theta_45cm,"40uA LD2 #pi^{+} from bggen #pi^{+} E<500 MeV","l");
	//leg1->AddEntry(hhit_theta_25cm,"40uA LD2 #pi^{-} from bggen #pi^{-} E<500 MeV","l");
	leg1->AddEntry(hhit_theta_45cm_electron,"40uA LD2 e^{-}*1e3 from eAll","l");
	leg1->AddEntry(hhit_theta_55cm,"40uA LD2 e^{-}*1e3 from eAll E>5 GeV","l");
	//leg1->AddEntry(hhit_theta_25cm_electron,"40uA LD2 p^{-} from bggen #pi^{-}","l");
	//leg1->AddEntry(hhit_theta_55cm_electron,"40uA LD2 p^{+} from bggen #pi^{+}","l");
	leg1->SetTextSize(0.035);
	leg1->SetBorderSize(0);
	leg1->SetFillColor(0);
	leg1->Draw("text same");

	c_gem[5] = new TCanvas("c_gem[5]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
      //  hhit_theta_gem2->SetLineColor(6);	
       // hhit_theta_gem2->Scale(0.00000001);
        /*hhit_theta_gem2_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");	
        hhit_theta_gem2_noTB->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_gem2_noTB->SetTitle("#gamma in front of gem2");	
        hhit_theta_gem2_noTB->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_gem2_noTB->Scale(0.00000001);
        hhit_theta_gem2_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
       // hhit_theta_gem2->Draw("HISt");	
        hhit_theta_gem2_noTB->SetLineColor(kGreen+1);	
        hhit_theta_gem2_noTB->Draw(" HISt");	
        hhit_theta_gem2_noB->SetLineColor(6);	
        hhit_theta_gem2_noB->Scale(0.00000001);
        hhit_theta_gem2_noB->Draw("same HISt");	
        hhit_theta_1inpoly_gem2->SetLineColor(1);	
        hhit_theta_1inpoly_gem2->Scale(0.00000001);
        hhit_theta_1inpoly_gem2->Draw("same HISt");	
        double rate_theta_linpoly_gem2= hhit_theta_1inpoly_gem2->Integral();
        hhit_theta_1inpoly_gem2->Draw("same HISt");	*/
        hhit_theta_45cm_gem2->SetLineColor(1);	
        hhit_theta_45cm_gem2->GetYaxis()->SetTitle("rate (Hz/cm2)");	
        hhit_theta_45cm_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_45cm_gem2->SetTitle("in front of SC_D");	
        hhit_theta_45cm_gem2->GetXaxis()->SetRangeUser(0,60);	
       // hhit_theta_45cm_gem2->Scale(0.00000000716);
        hhit_theta_45cm_gem2->GetYaxis()->SetRangeUser(1e-5,1e1);	
       // hhit_theta_45cm_gem2->Draw(" HISt");	
        hhit_theta_25cm_gem2->SetLineColor(2);	
      //  hhit_theta_25cm_gem2->Scale(0.00000000716);
       // hhit_theta_25cm_gem2->Draw("same HISt");	
        hhit_theta_45cm_gem2_electron->SetLineColor(6);	
        hhit_theta_45cm_gem2_electron->Scale(1000);	
        hhit_theta_45cm_gem2_electron->GetYaxis()->SetTitle("rate (Hz/cm2)");	
        hhit_theta_45cm_gem2_electron->GetXaxis()->SetTitle("#theta_{track}-#theta_{hit}");	
        hhit_theta_45cm_gem2_electron->SetTitle("in front of SC_D");	
        hhit_theta_45cm_gem2_electron->GetYaxis()->SetRangeUser(1e-5,1e1);	
        hhit_theta_45cm_gem2_electron->GetXaxis()->SetRangeUser(-3,3);	
        hhit_theta_45cm_gem2_electron->Draw(" HIST");	
        hhit_theta_25cm_gem2_electron->SetLineColor(4);	
       // hhit_theta_25cm_gem2_electron->Draw(" same HIST");	
        hhit_theta_55cm_gem2->SetLineColor(3);	
        hhit_theta_55cm_gem2->Scale(1000);	
        hhit_theta_55cm_gem2->GetXaxis()->SetRangeUser(-3,3);	
        hhit_theta_55cm_gem2->Draw(" same HIST");	
        hhit_theta_55cm_gem2_electron->SetLineColor(kOrange-3);	
       // hhit_theta_55cm_gem2_electron->Draw(" same HIST");	
	TLegend *leg01 = new TLegend(0.15,0.7,0.4,0.85);
//	leg01->AddEntry(hhit_theta_45cm_gem2,"40uA LD2 #pi^{+} E<500 MeV","l");
//	leg01->AddEntry(hhit_theta_25cm_gem2,"40uA LD2 #pi^{-} E<500 MeV","l");
	leg01->AddEntry(hhit_theta_45cm_gem2_electron,"40uA LD2 e^{-}*1e3 ","l");
	leg01->AddEntry(hhit_theta_55cm_gem2,"40uA LD2 e^{-}*1e3 E<5 GeV","l");
//	leg01->AddEntry(hhit_theta_25cm_gem2_electron,"40uA LD2 #pi^{-}","l");
//	leg01->AddEntry(hhit_theta_55cm_gem2_electron,"40uA LD2 #pi^{+}","l");
	leg01->SetTextSize(0.035);
	leg01->SetBorderSize(0);
	leg01->SetFillColor(0);
	leg01->Draw("text same");
	c_gem[6] = new TCanvas("c_gem[6]", "flux #theta",1800,1000);
        c_gem[6]->Divide(2,3);
        c_gem[6]->cd(1);
        hhit_theta_vs_E_55cm_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_55cm_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_55cm_electron->SetTitle("SC_A #pi{+} from bggen #pi^{+}");	
        hhit_theta_vs_E_55cm_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_55cm_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_55cm_electron->Draw("COLZ");	
        c_gem[6]->cd(2);
        hhit_theta_vs_E_45cm->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_45cm->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_45cm->SetTitle("SC_A #pi{+} from bggen #pi^{+} E<500 MeV");	
        hhit_theta_vs_E_45cm->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_45cm->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_45cm->Draw("COLZ");	
        c_gem[6]->cd(3);
	hhit_theta_vs_E_25cm_electron->SetTitle("SC_A #pi^{-} from bggen #pi^{-}");
        hhit_theta_vs_E_25cm_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_25cm_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_25cm_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_25cm_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_25cm_electron->Draw("COLZ");	
        c_gem[6]->cd(4);
	hhit_theta_vs_E_25cm->SetTitle("SC_A #pi^{-} from bggen #pi^{-} E<500 MeV");
        hhit_theta_vs_E_25cm->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_25cm->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_25cm->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_25cm->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_25cm->Draw("COLZ");	
        c_gem[6]->cd(5);
        hhit_theta_vs_E_45cm_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_45cm_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_45cm_electron->SetTitle("SC_A e^{-} from eAll");	
        hhit_theta_vs_E_45cm_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_45cm_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_45cm_electron->Draw("COLZ");	
        c_gem[6]->cd(6);
        hhit_theta_vs_E_55cm->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_55cm->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_55cm->SetTitle("SC_A e^{-} from eAll E>5 GeV");	
        hhit_theta_vs_E_55cm->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_55cm->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_55cm->Draw("COLZ");	

	c_gem[7] = new TCanvas("c_gem[7]", "flux #theta",1800,1000);
        c_gem[7]->Divide(2,3);
        c_gem[7]->cd(1);
        hhit_theta_vs_E_55cm_gem2_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_55cm_gem2_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_55cm_gem2_electron->SetTitle("SC_D #pi^{+} from bggen #pi^{+}");	
        hhit_theta_vs_E_55cm_gem2_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_55cm_gem2_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_55cm_gem2_electron->Draw("COLZ");	
        c_gem[7]->cd(2);
        hhit_theta_vs_E_45cm_gem2->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_45cm_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_45cm_gem2->SetTitle("SC_D #pi^{+} from bggen #pi^{+} E<500 MeV");	
        hhit_theta_vs_E_45cm_gem2->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_45cm_gem2->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_45cm_gem2->Draw("COLZ");	
        c_gem[7]->cd(3);
	hhit_theta_vs_E_25cm_gem2_electron->SetTitle("SC_D #pi^{-} from bggen #pi^{-}");
        hhit_theta_vs_E_25cm_gem2_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_25cm_gem2_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_25cm_gem2_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_25cm_gem2_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_25cm_gem2_electron->Draw("COLZ");	
        c_gem[7]->cd(4);
	hhit_theta_vs_E_25cm_gem2->SetTitle("SC_D #pi^{-} from bggen #pi^{-} E<500 MeV");
        hhit_theta_vs_E_25cm_gem2->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_25cm_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_25cm_gem2->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_25cm_gem2->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_25cm_gem2->Draw("COLZ");	
        c_gem[7]->cd(5);
        hhit_theta_vs_E_45cm_gem2_electron->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_45cm_gem2_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_45cm_gem2_electron->SetTitle("SC_D e^{-} from eAll");	
        hhit_theta_vs_E_45cm_gem2_electron->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_45cm_gem2_electron->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_45cm_gem2_electron->Draw("COLZ");	
        c_gem[7]->cd(6);
        hhit_theta_vs_E_55cm_gem2->GetYaxis()->SetTitle("log10(E) (MeV)");	
        hhit_theta_vs_E_55cm_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_vs_E_55cm_gem2->SetTitle("SC_D e^{-} from eAll E>5 GeV");	
        hhit_theta_vs_E_55cm_gem2->GetXaxis()->SetRangeUser(0,90);	
        hhit_theta_vs_E_55cm_gem2->GetYaxis()->SetRangeUser(0,4);	
        hhit_theta_vs_E_55cm_gem2->Draw("COLZ");	


	c_gem[2] = new TCanvas("c_gem[2]", "gem1",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	/*hhit_Edepgem1_electron_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem1_electron_noTB->SetTitle("#gamma on gem1 virtual plane");
        hhit_Edepgem1_electron_noTB->Scale(0.00000001);
        hhit_Edepgem1_electron_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
	hhit_Edepgem1_electron_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_electron_noTB->Draw("HIST");
	hhit_Edepgem1_electron_noB->SetLineColor(6);
        hhit_Edepgem1_electron_noB->Scale(0.00000001);
	hhit_Edepgem1_electron_noB->Draw("same HIST");
	hhit_Edepgem1_electron_1cmAl->SetLineColor(4);
        hhit_Edepgem1_electron_1cmAl->Scale(0.00000001);
	hhit_Edepgem1_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem1_electron_1inpoly->SetLineColor(1);
        hhit_Edepgem1_electron_1inpoly->Scale(0.00000001);
	hhit_Edepgem1_electron_1inpoly->Draw("same HIST");
        double rate_Edepgem1_electron_1inpoly= hhit_Edepgem1_electron_1inpoly->Integral();
	hhit_Edepgem1_electron_35cm->SetLineColor(2);
        hhit_Edepgem1_electron_35cm->Scale(0.00000001);
	hhit_Edepgem1_electron_35cm->Draw("same HIST");*/
	hhit_Edepgem1_electron_45cm->SetLineColor(1);
	hhit_Edepgem1_electron_45cm->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem1_electron_45cm->SetTitle("#gamma on SC_A virtual plane");
        hhit_Edepgem1_electron_45cm->Scale(0.0000000267);
        hhit_Edepgem1_electron_45cm->GetYaxis()->SetRangeUser(1e-4,1e1);	
	hhit_Edepgem1_electron_45cm->Draw("HIST");
        double rate_Edepgem1_electron_45cm= hhit_Edepgem1_electron_45cm->Integral(hhit_Edepgem1_electron_45cm->GetXaxis()->FindBin(0),hhit_Edepgem1_electron_45cm->GetXaxis()->FindBin(4));
	hhit_Edepgem1_electron_25cm->SetLineColor(2);
        hhit_Edepgem1_electron_25cm->Scale(0.0000000267);
	hhit_Edepgem1_electron_25cm->Draw("same HIST");
        double rate_Edepgem1_electron_25cm= hhit_Edepgem1_electron_25cm->Integral(hhit_Edepgem1_electron_25cm->GetXaxis()->FindBin(0),hhit_Edepgem1_electron_25cm->GetXaxis()->FindBin(4));
	TLegend *leg11 = new TLegend(0.12,0.68,0.5,0.88);
	leg11->AddEntry(hhit_Edepgem1_electron_45cm,Form("40uA LD2 target no shielding; rate=%f MHz/cm2",rate_Edepgem1_electron_45cm),"l");
	leg11->AddEntry(hhit_Edepgem1_electron_25cm,Form("40uA LD2 target 1 inch poly shielding; rate=%f MHz/cm2",rate_Edepgem1_electron_25cm),"l");
	leg11->SetTextSize(0.035);
	leg11->SetBorderSize(0);
	leg11->SetFillColor(0);
	leg11->Draw("text same");
	c_gem[3] = new TCanvas("c_gem[3]", "gem2",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
//	hhit_Edepgem2_electron->SetLineColor(6);
/*	hhit_Edepgem2_electron_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem2_electron_noTB->SetTitle("#gamma on gem2 virtual plane");
  //      hhit_Edepgem2_electron->Scale(0.00000001);
        hhit_Edepgem2_electron_noTB->Scale(0.00000001);
        hhit_Edepgem2_electron_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
//	hhit_Edepgem2_electron->Draw("HIST");
	hhit_Edepgem2_electron_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem2_electron_noTB->Draw(" HIST");
	hhit_Edepgem2_electron_noB->SetLineColor(6);
        hhit_Edepgem2_electron_noB->Scale(0.00000001);
	hhit_Edepgem2_electron_noB->Draw("same HIST");
	hhit_Edepgem2_electron_1cmAl->SetLineColor(4);
        hhit_Edepgem2_electron_1cmAl->Scale(0.00000001);
	hhit_Edepgem2_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem2_electron_1inpoly->SetLineColor(1);
        hhit_Edepgem2_electron_1inpoly->Scale(0.00000001);
	hhit_Edepgem2_electron_1inpoly->Draw("same HIST");
        double rate_Edepgem2_electron_1inpoly= hhit_Edepgem2_electron_1inpoly->Integral();
	hhit_Edepgem2_electron_35cm->SetLineColor(2);
        hhit_Edepgem2_electron_35cm->Scale(0.00000001);
	hhit_Edepgem2_electron_35cm->Draw("same HIST");*/
	hhit_Edepgem2_electron_45cm->SetLineColor(1);
	hhit_Edepgem2_electron_45cm->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem2_electron_45cm->SetTitle("#gamma on SC_D virtual plane");
        hhit_Edepgem2_electron_45cm->Scale(0.00000000716);
        hhit_Edepgem2_electron_45cm->GetYaxis()->SetRangeUser(1e-4,1e1);	
	hhit_Edepgem2_electron_45cm->Draw("HIST");
        double rate_Edepgem2_electron_45cm= hhit_Edepgem2_electron_45cm->Integral();
	hhit_Edepgem2_electron_25cm->SetLineColor(2);
        hhit_Edepgem2_electron_25cm->Scale(0.00000000716);
	hhit_Edepgem2_electron_25cm->Draw("same HIST");
        double rate_Edepgem2_electron_25cm= hhit_Edepgem2_electron_25cm->Integral();
	TLegend *leg31 = new TLegend(0.12,0.68,0.5,0.88);
	leg31->AddEntry(hhit_Edepgem2_electron_45cm,Form("40uA LD2 target no shielding; rate=%f MHz/cm2",rate_Edepgem2_electron_45cm),"l");
	leg31->AddEntry(hhit_Edepgem2_electron_25cm,Form("40uA LD2 target 1 inch poly shielding; rate=%f MHz/cm2",rate_Edepgem2_electron_25cm),"l");
	leg31->SetTextSize(0.035);
	leg31->SetBorderSize(0);
	leg31->SetFillColor(0);
	leg31->Draw("text same");
	c_gem[0] = new TCanvas("c_gem[0]", "gem",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	/*hhit_Edepgem1_gamma_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem1_gamma_noTB->SetTitle("e^{-} on gem1 virtual plane");
        hhit_Edepgem1_gamma_noTB->Scale(0.00000001);
        hhit_Edepgem1_gamma_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
	hhit_Edepgem1_gamma_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_gamma_noTB->Draw("HIST");
        double rate_Edepgem1_gamma_noTB= hhit_Edepgem1_gamma_noTB->Integral();
	hhit_Edepgem1_gamma_noB->SetLineColor(6);
        hhit_Edepgem1_gamma_noB->Scale(0.00000001);
	hhit_Edepgem1_gamma_noB->Draw("same HIST");
        double rate_Edepgem1_gamma_noB= hhit_Edepgem1_gamma_noB->Integral();
	hhit_Edepgem1_gamma_1cmAl->SetLineColor(4);
        hhit_Edepgem1_gamma_1cmAl->Scale(0.00000001);
//	hhit_Edepgem1_gamma_1cmAl->Draw("same HIST");
	hhit_Edepgem1_gamma_1inpoly->SetLineColor(1);
        hhit_Edepgem1_gamma_1inpoly->Scale(0.00000001);
	hhit_Edepgem1_gamma_1inpoly->Draw("same HIST");
        double rate_Edepgem1_gamma_1inpoly= hhit_Edepgem1_gamma_1inpoly->Integral();
	hhit_Edepgem1_gamma_35cm->SetLineColor(2);
        hhit_Edepgem1_gamma_35cm->Scale(0.00000001);
	hhit_Edepgem1_gamma_35cm->Draw("same HIST");
        double rate_Edepgem1_gamma_35cm= hhit_Edepgem1_gamma_35cm->Integral();*/
	hhit_Edepgem1_gamma_45cm->SetLineColor(1);
	hhit_Edepgem1_gamma_45cm->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem1_gamma_45cm->SetTitle("e^{-} on SC_A virtual plane");
        hhit_Edepgem1_gamma_45cm->Scale(0.0000000267);
        hhit_Edepgem1_gamma_45cm->GetYaxis()->SetRangeUser(1e-4,1e1);	
	hhit_Edepgem1_gamma_45cm->Draw(" HIST");
        double rate_Edepgem1_gamma_45cm= hhit_Edepgem1_gamma_45cm->Integral(hhit_Edepgem1_gamma_45cm->GetXaxis()->FindBin(0),hhit_Edepgem1_gamma_45cm->GetXaxis()->FindBin(4));
	hhit_Edepgem1_gamma_25cm->SetLineColor(2);
        hhit_Edepgem1_gamma_25cm->Scale(0.0000000267);
	hhit_Edepgem1_gamma_25cm->Draw("same HIST");
        double rate_Edepgem1_gamma_25cm= hhit_Edepgem1_gamma_25cm->Integral(hhit_Edepgem1_gamma_25cm->GetXaxis()->FindBin(0),hhit_Edepgem1_gamma_25cm->GetXaxis()->FindBin(4));
	TLegend *leg111 = new TLegend(0.12,0.7,0.5,0.88);
	leg111->AddEntry(hhit_Edepgem1_gamma_45cm,Form("40uA LD2 target no shielding;rate %f MHz/cm2",rate_Edepgem1_gamma_45cm),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_25cm,Form("40uA LD2 target 1 inch poly shielding; rate %f MHz/cm2",rate_Edepgem1_gamma_25cm),"l");
	leg111->SetTextSize(0.035);
	leg111->SetBorderSize(0);
	leg111->SetFillColor(0);
	leg111->Draw("text same");
	c_gem[1] = new TCanvas("c_gem[1]", "gem",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
//	hhit_Edepgem2_gamma->SetLineColor(6);
	/*hhit_Edepgem2_gamma_noTB->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem2_gamma_noTB->SetTitle("e^{-} on gem2 virtual plane");
//        hhit_Edepgem2_gamma->Scale(0.00000001);
        hhit_Edepgem2_gamma_noTB->Scale(0.00000001);
        hhit_Edepgem2_gamma_noTB->GetYaxis()->SetRangeUser(1e-3,1e6);	
//	hhit_Edepgem2_gamma->Draw("HIST");
	hhit_Edepgem2_gamma_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem2_gamma_noTB->Draw(" HIST");
	hhit_Edepgem2_gamma_noB->SetLineColor(6);
        hhit_Edepgem2_gamma_noB->Scale(0.00000001);
	hhit_Edepgem2_gamma_noB->Draw("same HIST");
	hhit_Edepgem2_gamma_1cmAl->SetLineColor(4);
        hhit_Edepgem2_gamma_1cmAl->Scale(0.00000001);
	hhit_Edepgem2_gamma_1cmAl->Draw("same HIST");
	hhit_Edepgem2_gamma_1inpoly->SetLineColor(1);
        hhit_Edepgem2_gamma_1inpoly->Scale(0.00000001);
	hhit_Edepgem2_gamma_1inpoly->Draw("same HIST");
        double rate_Edepgem2_gamma_1inpoly= hhit_Edepgem2_gamma_1inpoly->Integral();
	hhit_Edepgem2_gamma_35cm->SetLineColor(2);
        hhit_Edepgem2_gamma_35cm->Scale(0.00000001);
	hhit_Edepgem2_gamma_35cm->Draw("same HIST");*/
	hhit_Edepgem2_gamma_45cm->SetLineColor(1);
	hhit_Edepgem2_gamma_45cm->GetYaxis()->SetTitle("rate (MHz/cm2)");
	hhit_Edepgem2_gamma_45cm->SetTitle("e^{-} on SC_D virtual plane");
        hhit_Edepgem2_gamma_45cm->Scale(0.00000000716);
        hhit_Edepgem2_gamma_45cm->GetYaxis()->SetRangeUser(1e-4,1e1);	
	hhit_Edepgem2_gamma_45cm->Draw("HIST");
        double rate_Edepgem2_gamma_45cm= hhit_Edepgem2_gamma_45cm->Integral();
	hhit_Edepgem2_gamma_25cm->SetLineColor(2);
        hhit_Edepgem2_gamma_25cm->Scale(0.00000000716);
	hhit_Edepgem2_gamma_25cm->Draw("same HIST");
        double rate_Edepgem2_gamma_25cm= hhit_Edepgem2_gamma_25cm->Integral();
	TLegend *leg41 = new TLegend(0.12,0.65,0.5,0.88);
	leg41->AddEntry(hhit_Edepgem2_gamma_45cm,Form("40uA LD2 target no shielding; rate=%f MHz/cm2",rate_Edepgem2_gamma_45cm),"l");
	leg41->AddEntry(hhit_Edepgem2_gamma_25cm,Form("40uA LD2 target 1 inch poly shielding; rate=%f MHz/cm2",rate_Edepgem2_gamma_25cm),"l");
	leg41->SetTextSize(0.035);
	leg41->SetBorderSize(0);
	leg41->SetFillColor(0);
	leg41->Draw("text same");
 	for(int a=4;a<6;a++){
		c_gem[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_Espectrum_full_scattering_18deg_debug.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));
}
