
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_EC_newbeamline_angle_allpart(){
gStyle->SetOptStat(0);
gStyle->SetPalette(1);
TFile *f1 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_sangle/HallC_beamtest_bggen_LH2_pi0_8deg_filenum11840_output_Nphe.root");
TFile *f12 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_sangle/HallC_beamtest_bggen_LH2_pim_35deg_filenum10280_output_Nphe.root");
TFile *f2 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_sangle/HallC_beamtest_bggen_LH2_pim_8deg_filenum10270_output_Nphe.root");
TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_sangle/HallC_beamtest_eAll_sangle_8deg_filenum100_output_Nphe_Q2cut_01GeV.root");
TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_sangle/HallC_beamtest_bggen_LH2_pip_sangle_filenum9520_8deg_output_Nphe.root");
TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_sangle/HallC_beamtest_bggen_LH2_pip_sangle_filenum9530_35deg_output_Nphe.root");
TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim/HallC_beamtest_bggen_LH2_pim_newbeamline_filenum9220_output_Nphe.root");
TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip/output/HallC_beamtest_bggen_LH2_pip_newbeamline_filenum14110_output_Nphe.root");
//TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip/HallC_beamtest_bggen_LH2_pip_newbeamline_filenum23450_output_Nphe.root");
//TFile *f15 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/temp/HallC_beamtest_beamOntarget_80uA_8deg_filenum100_output_Nphe.root");
TFile *f15 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e8_8deg_80uA_output_Nphe.root");
const int rebinfac=1;
const int rebinfac2=1;
TH1F *EC_shower_pim;
TH1F *EC_shower_beamOn;
TH1F *EC_shower_pim_35deg;
TH1F *EC_shower_pim_82deg;
TH1F *EC_shower_pip;
TH1F *EC_shower_pip_35deg;
TH1F *EC_shower_pip_82deg;
TH1F *EC_shower_pip2;
TH1F *EC_shower_pi0;
TH1F *EC_shower_eAll;
TH1F *EC_shower_eDIS;
TH1F *EC_shower_proton;
TH1F *EC_shower_pim_trigger;
TH1F *EC_shower_pip_trigger;
TH1F *EC_shower_pip2_trigger;
TH1F *EC_shower_pi0_trigger;
TH1F *EC_shower_proton_trigger;
TH1F *EC_shower_eAll_trigger;
TH1F *EC_preshower_pim;
TH1F *EC_preshower_beamOn;
TH1F *EC_preshower_pim_35deg;
TH1F *EC_preshower_pim_82deg;
TH1F *EC_preshower_proton;
TH1F *EC_preshower_pip;
TH1F *EC_preshower_pip_35deg;
TH1F *EC_preshower_pip_82deg;
TH1F *EC_preshower_pip2;
TH1F *EC_preshower_pi0;
TH1F *EC_preshower_pi0_all;
TH1F *EC_shower_pi0_all;
TH1F *EC_preshower_pi0_e;
TH1F *EC_preshower_pi0_ep;
TH1F *EC_preshower_pi0_r;
TH1F *EC_shower_pi0_e;
TH1F *EC_shower_pi0_ep;
TH1F *EC_shower_pi0_r;
TH1F *EC_preshower_eAll;
TH1F *EC_preshower_eDIS;
TH1F *EC_preshower_pim_trigger;
TH1F *EC_preshower_proton_trigger;
TH1F *EC_preshower_pip_trigger;
TH1F *EC_preshower_pip2_trigger;
TH1F *EC_preshower_pi0_trigger;
TH1F *EC_preshower_eAll_trigger;
TH1F *EC_preshower_mother_pi0;
TH1F *EC_preshower_mother_pi0_e;
TH1F *EC_preshower_mother_pi0_ep;
TH1F *EC_preshower_mother_pi0_r;
TH1F *EC_shower_mother_pi0_e;
TH1F *EC_shower_mother_pi0_ep;
TH1F *EC_shower_mother_pi0_r;
TH1F *sc1_pim;
TH1F *sc1_beamOn;
TH1F *sc2_pim;
TH1F *sc2_beamOn;
TH1F *sc1_pip;
TH1F *sc1_proton;
TH1F *sc2_proton;
TH1F *sc1_pi0;
TH1F *sc2_pi0;
TH1F *sc2_pip;
TH1F *sc1_eAll;
TH1F *sc2_eAll;
TH1F *hhit_E_pim[7];
TH1F *hhit_p_pim[7];
TH1F *hhit_Edep_pim[7];		  	
TH1F *hhit_E_pip[7];
TH1F *hhit_Edep_pip[7];		  	
TH1F *hhit_E_eAll_nob[9];
TH1F *hhit_p_eAll_nob[9];
TH1F *hhit_E_eAll[9];
TH1F *hhit_p_eAll[9];
TH1F *hhit_Edep_eAll[9];		  	
TH1F *hhit_E_cut_eAll[9];
TH1F *hhit_p_cut_eAll[9];
TH1F *hhit_E_cut_eAll_nob[9];
TH1F *hhit_p_cut_eAll_nob[9];
TH1F *hhit_E_proton[9];
TH1F *hhit_p_proton[9];
TH1F *hhit_E_proton_nob[9];
TH1F *hhit_p_proton_nob[9];
TH1F *hhit_E_proton_cut[9];
TH1F *hhit_p_proton_cut[9];
TH1F *hhit_E_proton_cut_nob[9];
TH1F *hhit_p_proton_cut_nob[9];
TH1F *hhit_Edep_proton[9];		  	
TH1F *hhit_E_pim_LD[9];
TH1F *hhit_p_pim_LD[9];
TH1F *hhit_E_pim_LD_nob[9];
TH1F *hhit_p_pim_LD_nob[9];
TH1F *hhit_Edep_pim_LD[9];		  	
TH1F *hhit_Edep_pip_LD[9];		  	
TH1F *hhit_Edep_pi0_LD[9];		  	
TH1F *hhit_E_pim_cut_LD[9];
TH1F *hhit_p_pim_cut_LD[9];
TH1F *hhit_E_pim_cut_LD_nob[9];
TH1F *hhit_p_pim_cut_LD_nob[9];
TH1F *hhit_E_pip_cut_LD[9];
TH1F *hhit_p_pip_cut_LD[9];
TH1F *hhit_E_pip_cut_LD_nob[9];
TH1F *hhit_p_pip_cut_LD_nob[9];
TH1F *hhit_E_pip_LD[9];
TH1F *hhit_p_pip_LD[9];
TH1F *hhit_E_pip_LD_nob[9];
TH1F *hhit_p_pip_LD_nob[9];
TH1F *hhit_E_pi0[9];
TH1F *hhit_p_pi0[9];
TH1F *hhit_E_pi0_nob[9];
TH1F *hhit_p_pi0_nob[9];
TH1F *hhit_E_pi0_cut[9];
TH1F *hhit_p_pi0_cut[9];
TH1F *hhit_E_pi0_cut_nob[9];
TH1F *hhit_p_pi0_cut_nob[9];
TH1F *hhit_E_pi0_cutr[9];
TH1F *hhit_p_pi0_cutr[9];
TH1F *hhit_E_pi0_cutr_nob[9];
TH1F *hhit_p_pi0_cutr_nob[9];
TH1F *hhit_E_pi0_cute[9];
TH1F *hhit_p_pi0_cute[9];
TH1F *hhit_E_pi0_cute_nob[9];
TH1F *hhit_p_pi0_cute_nob[9];

TH1F *hhit_pid_pip_LD_nob[9];
TH1F *hhit_pid_pim_LD_nob[9];
TH1F *hhit_pid_proton_LD_nob[9];
TH1F *hhit_mpid_pip_LD_nob[9];
TH1F *hhit_mpid_pim_LD_nob[9];
TH1F *hhit_mpid_proton_LD_nob[9];
TH1F *hhit_procID_pip_LD_nob[9];
TH1F *hhit_procID_pim_LD_nob[9];
TH1F *hhit_procID_proton_LD_nob[9];

TH1F *hhit_Edepspd2_proton;
TH1F *hhit_Edepspd2_pim;
TH1F *hhit_Edepspd2_beamOn;
TH1F *hhit_Edepspd1_beamOn;
TH1F *hhit_Edepspd2_pi0;
TH1F *hhit_Edepspd2_pip;
TH1F *hhit_Edepspd2_eAll;
TH1F *hhit_Edepspd1_proton;
TH1F *hhit_Edepspd1_pim;
TH1F *hhit_Edepspd1_pi0;
TH1F *hhit_Edepspd1_pip;
TH1F *hhit_Edepspd1_eAll;
TH1F *hhit_Eend_preshower_r_proc;
TH1F *hhit_Eend_preshower_mother_r_proc;
TH1F *hhit_Eend_preshower_e_proc;
TH1F *hhit_Eend_preshower_mother_e_proc;
TH1F *hhit_Eend_preshower_ep_proc;
TH1F *hhit_Eend_preshower_mother_ep_proc;
TH2F *hit_R_vs_vz_eAll_nob[9];
TH2F *hit_R_vs_vz_eAll[9];
TH2F *hit_R_vs_vz_pim_nob[9];
TH2F *hit_R_vs_vz_pim[9];
TH2F *hit_R_vs_vz_pip_nob[9];
TH2F *hit_R_vs_vz_pip[9];
TH2F *hit_R_vs_vz_proton_nob[9];
TH2F *hit_R_vs_vz_proton[9];
TH2F *hit_R_vs_vz_pi0_nob[9];
TH2F *hit_R_vs_vz_pi0[9];
TH2F *EC_shower_2D_pim;
TH2F *EC_shower_2D_pip;
TH2F *EC_shower_2D_pi0;
TH2F *EC_shower_2D_eAll;
TH2F *EC_shower_2D_proton;
TH2F *EC_shower_2D_pim_trigger;
TH2F *EC_shower_2D_pip_trigger;
TH2F *EC_shower_2D_pi0_trigger;
TH2F *EC_shower_2D_eAll_trigger;
TH2F *EC_shower_2D_proton_trigger;
 EC_shower_2D_pim = (TH2F*)f2->Get("ec_Eend_2D");
 EC_shower_2D_pip = (TH2F*)f10->Get("ec_Eend_2D");
 EC_shower_2D_pi0 = (TH2F*)f1->Get("ec_Eend_2D");
 EC_shower_2D_eAll = (TH2F*)f3->Get("ec_Eend_2D");

 EC_shower_2D_pim_trigger = (TH2F*)f2->Get("ec_Eend_2D_trigger");
 EC_shower_2D_pip_trigger = (TH2F*)f10->Get("ec_Eend_2D_trigger");
 EC_shower_2D_pi0_trigger = (TH2F*)f1->Get("ec_Eend_2D_trigger");
 EC_shower_2D_eAll_trigger = (TH2F*)f3->Get("ec_Eend_2D_trigger");

 hhit_Edepspd2_pim = (TH1F*)f2->Get("hit_Edepspd2");
 hhit_Edepspd2_beamOn = (TH1F*)f15->Get("hit_Edepspd2");
 hhit_Edepspd2_pip = (TH1F*)f10->Get("hit_Edepspd2");
 hhit_Edepspd2_pi0 = (TH1F*)f1->Get("hit_Edepspd2");
 hhit_Edepspd2_eAll = (TH1F*)f3->Get("hit_Edepspd2");
 hhit_Edepspd1_pim = (TH1F*)f2->Get("hit_Edepspd1");
 hhit_Edepspd1_beamOn = (TH1F*)f15->Get("hit_Edepspd1");
 hhit_Edepspd1_pip = (TH1F*)f10->Get("hit_Edepspd1");
 hhit_Edepspd1_pi0 = (TH1F*)f1->Get("hit_Edepspd1");
 hhit_Edepspd1_eAll = (TH1F*)f3->Get("hit_Edepspd1");
 EC_shower_pim = (TH1F*)f2->Get("ec_Eend_shower");
 EC_shower_beamOn = (TH1F*)f15->Get("ec_Eend_shower");
 EC_shower_pim_35deg = (TH1F*)f12->Get("ec_Eend_shower");
 EC_shower_pim_82deg = (TH1F*)f13->Get("ec_Eend_shower");
 EC_shower_pip = (TH1F*)f10->Get("ec_Eend_shower");
 EC_shower_pip_35deg = (TH1F*)f11->Get("ec_Eend_shower");
 EC_shower_pip_82deg = (TH1F*)f14->Get("ec_Eend_shower");
 EC_shower_pi0 = (TH1F*)f1->Get("ec_Eend_shower");
 EC_shower_eAll = (TH1F*)f3->Get("ec_Eend_shower");
 EC_preshower_pim = (TH1F*)f2->Get("ec_Eend_preshower");
 EC_preshower_beamOn = (TH1F*)f15->Get("ec_Eend_preshower");
 EC_preshower_pim_35deg = (TH1F*)f12->Get("ec_Eend_preshower");
 EC_preshower_pim_82deg = (TH1F*)f13->Get("ec_Eend_preshower");
 EC_preshower_pip = (TH1F*)f10->Get("ec_Eend_preshower");
 EC_preshower_pip_35deg = (TH1F*)f11->Get("ec_Eend_preshower");
 EC_preshower_pip_82deg = (TH1F*)f14->Get("ec_Eend_preshower");
 EC_preshower_pi0 = (TH1F*)f1->Get("ec_Eend_preshower");
 EC_preshower_eAll = (TH1F*)f3->Get("ec_Eend_preshower");
 EC_shower_pim_trigger = (TH1F*)f2->Get("ec_Eend_shower_trigger");
 EC_shower_pi0_trigger = (TH1F*)f1->Get("ec_Eend_shower_trigger");
 EC_shower_pip_trigger = (TH1F*)f10->Get("ec_Eend_shower_trigger");
 EC_shower_eAll_trigger = (TH1F*)f3->Get("ec_Eend_shower_trigger");
 EC_preshower_pim_trigger = (TH1F*)f2->Get("ec_Eend_preshower_trigger");
 EC_preshower_pi0_trigger = (TH1F*)f1->Get("ec_Eend_preshower_trigger");
 EC_preshower_pip_trigger = (TH1F*)f10->Get("ec_Eend_preshower_trigger");
 EC_preshower_eAll_trigger = (TH1F*)f3->Get("ec_Eend_preshower_trigger");
 sc1_pim = (TH1F*)f2->Get("hit_Edepsc1_trigger");
 sc1_beamOn = (TH1F*)f15->Get("hit_Edepsc1_trigger");
 sc2_pim = (TH1F*)f2->Get("hit_Edepsc2_trigger");
 sc2_beamOn = (TH1F*)f15->Get("hit_Edepsc2_trigger");
 sc1_pip = (TH1F*)f10->Get("hit_Edepsc1_trigger");
 sc2_pip = (TH1F*)f10->Get("hit_Edepsc2_trigger");
 sc1_eAll = (TH1F*)f3->Get("hit_Edepsc1_trigger");
 sc2_eAll = (TH1F*)f3->Get("hit_Edepsc2_trigger");
 sc1_pi0 = (TH1F*)f1->Get("hit_Edepsc1_trigger");
 sc2_pi0 = (TH1F*)f1->Get("hit_Edepsc2_trigger");
 TCanvas *c[17];
 c[0] = new TCanvas("c[0]","c[0]",1000,1000);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
 EC_shower_pip->Scale(0.001);
 EC_shower_pip->Rebin(rebinfac);
 EC_shower_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
// EC_shower_pip->GetXaxis()->SetRangeUser(0,100);
 EC_shower_pip->GetYaxis()->SetTitle("rate (kHz)");
 EC_shower_pip->SetLineColor(2);
 EC_shower_pip->SetTitle("shower Edep");
 EC_shower_pip->Draw("HIST");
double rate_pip= EC_shower_pip->Integral();
 EC_shower_pim->Scale(0.001);
 EC_shower_pim->Rebin(rebinfac);
 EC_shower_pim->SetLineColor(1);
 EC_shower_pim->Draw(" same HIST");
double rate_pim= EC_shower_pim->Integral();
 EC_shower_pi0->Scale(0.001);
 EC_shower_pi0->Rebin(rebinfac);
 EC_shower_pi0->SetLineColor(kGreen+3);
 EC_shower_pi0->Draw(" same HIST");
double rate_pi0= EC_shower_pi0->Integral();
 EC_shower_eAll->SetLineColor(4);
 EC_shower_eAll->Scale(0.001);
 EC_shower_eAll->Rebin(rebinfac);
 EC_shower_eAll->Draw(" same HIST");
double rate_eAll= EC_shower_eAll->Integral();
 EC_shower_beamOn->Scale(0.0001);
 EC_shower_beamOn->Rebin(rebinfac);
 EC_shower_beamOn->SetLineColor(6);
 EC_shower_beamOn->Draw(" same HIST");
double rate_beamOn= EC_shower_beamOn->Integral();
  TLegend *leg8 = new TLegend(0.25,0.7,0.8,0.88);
  leg8->AddEntry(EC_shower_eAll,Form("eAll 8 deg with Q^{2}>10 MeV^{2}; total rate=%f kHz",rate_eAll),"l");
//  leg8->AddEntry(EC_shower_eDIS,"eDIS*1000","l");
  leg8->AddEntry(EC_shower_pim,Form("bggen #pi^{-} 8 deg; total rate=%f kHz",rate_pim),"l");
  leg8->AddEntry(EC_shower_pip,Form("bggen #pi^{+} 8 deg; total rate=%f kHz",rate_pip),"l");
  leg8->AddEntry(EC_shower_pi0,Form("bggen #pi^{0} 8 deg; total rate=%f kHz",rate_pi0),"l");
  leg8->AddEntry(EC_shower_beamOn,Form("BeamOnTarget 8 deg; total rate=%f kHz",rate_beamOn),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
  cout<<"rate eAll="<<rate_eAll<<"  "<<"rate_pim="<<rate_pim<<"  "<<"rate_pip="<<rate_pip<<endl;
 c[1] = new TCanvas("c[1]","c[1]",1000,800);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_pip->SetLineColor(2);
 EC_preshower_pip->Scale(0.001);
 EC_preshower_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
// EC_preshower_pip->GetXaxis()->SetRangeUser(0,50);
 EC_preshower_pip->GetYaxis()->SetTitle("rate (kHz)");
 EC_preshower_pip->SetTitle("preshower Edep");
 EC_preshower_pip->Draw("HIST");
double rate_pip_pre= EC_preshower_pip->Integral();
 EC_preshower_pim->Scale(0.001);
 EC_preshower_pim->SetLineColor(1);
 EC_preshower_pim->Draw("same HIST");
double rate_pim_pre= EC_preshower_pim->Integral();
 EC_preshower_pi0->Scale(0.001);
 EC_preshower_pi0->SetLineColor(kGreen+3);
 EC_preshower_pi0->Draw("same HIST");
double rate_pi0_pre= EC_preshower_pi0->Integral();
 EC_preshower_eAll->SetLineColor(4);
 EC_preshower_eAll->Scale(0.001);
 EC_preshower_eAll->Rebin(rebinfac);
 EC_preshower_eAll->Draw(" same HIST");
double rate_eAll_pre= EC_preshower_eAll->Integral();
 EC_preshower_beamOn->Scale(0.0001);
 EC_preshower_beamOn->SetLineColor(6);
 EC_preshower_beamOn->Draw("same HIST");
double rate_beamOn_pre= EC_preshower_beamOn->Integral();
  TLegend *leg1 = new TLegend(0.25,0.7,0.8,0.88);
  leg1->AddEntry(EC_preshower_eAll,Form("eAll 8 deg with Q^{2}>10 MeV^{2}; total rate=%f kHz",rate_eAll_pre),"l");
  leg1->AddEntry(EC_preshower_pim,Form("bggen #pi^{-} 8 deg; total rate=%f kHz",rate_pim_pre),"l");
  leg1->AddEntry(EC_preshower_pip,Form("bggen #pi^{+} 8 deg; total rate=%f kHz",rate_pip_pre),"l");
  leg1->AddEntry(EC_preshower_pi0,Form("bggen #pi^{0} 8 deg; total rate=%f kHz",rate_pi0_pre),"l");
  leg1->AddEntry(EC_preshower_beamOn,Form("BeamOnTarget 8 deg; total rate=%f kHz",rate_beamOn_pre),"l");
  leg1->SetTextSize(0.03);
  leg1->SetBorderSize(0);
  leg1->SetFillColor(0);
  leg1->Draw("text same");
 c[2] = new TCanvas("c[2]","c[2]",1000,1000);
 c[2]->Divide(1,2);
 c[2]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc1_pip->SetLineColor(2);
 sc1_pip->Rebin(rebinfac);
 sc1_pip->Scale(0.001);
 sc1_pip->GetYaxis()->SetTitle("rate (kHz)");
 sc1_pip->SetTitle("SC0");
 sc1_pip->GetXaxis()->SetTitle("Edep (MeV)");
// sc1_pip->GetXaxis()->SetRangeUser(0,100);
 sc1_pip->GetYaxis()->SetRangeUser(1e-2,1e6);
 sc1_pip->Draw("HIST");
 double rate_pip_sc1= sc1_pip->Integral();
 sc1_pim->SetLineColor(1);
 sc1_pim->Scale(0.001);
 sc1_pim->Rebin(rebinfac);
 sc1_pim->Draw("same HIST");
 double rate_pim_sc1= sc1_pim->Integral();
 sc1_eAll->SetLineColor(4);
 sc1_eAll->Scale(0.001);
 sc1_eAll->Rebin(rebinfac);
 sc1_eAll->Draw("same HIST");
 double rate_eAll_sc1= sc1_eAll->Integral();
 sc1_pi0->SetLineColor(kGreen+3);
 sc1_pi0->Scale(0.001);
 sc1_pi0->Rebin(rebinfac);
 sc1_pi0->Draw("same HIST");
 double rate_pi0_sc1= sc1_pi0->Integral();
  TLegend *leg21 = new TLegend(0.25,0.7,0.8,0.88);
  leg21->AddEntry(sc1_eAll,Form("eAll 8 deg with  Q^{2}>10 MeV^{2}; total rate=%f kHz",rate_eAll_sc1),"l");
  leg21->AddEntry(sc1_pim,Form("bggen #pi^{-} 8 deg; total rate=%f kHz",rate_pim_sc1),"l");
  leg21->AddEntry(sc1_pip,Form("bggen #pi^{+} 8 deg; total rate=%f kHz",rate_pip_sc1),"l");
  leg21->AddEntry(sc1_pi0,Form("bggen #pi^{0} 8 deg; total rate=%f kHz",rate_pi0_sc1),"l");
  leg21->SetTextSize(0.05);
  leg21->SetBorderSize(0);
  leg21->SetFillColor(0);
  leg21->Draw("text same");
 c[2]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc2_pip->SetLineColor(2);
 sc2_pip->Scale(0.001);
 sc2_pip->Rebin(rebinfac);
 sc2_pip->SetTitle("SC1");
 sc2_pip->GetXaxis()->SetTitle("Edep (MeV)");
 sc2_pip->GetYaxis()->SetTitle("rate (kHz)");
 sc2_pip->GetYaxis()->SetRangeUser(1e-2,1e6);
// sc2_pip->GetXaxis()->SetRangeUser(0,100);
 sc2_pip->Draw("HIST");
 double rate_pip_sc2= sc2_pip->Integral();
 sc2_pim->SetLineColor(1);
 sc2_pim->Scale(0.001);
 sc2_pim->Rebin(rebinfac);
 sc2_pim->Draw("same HIST");
 double rate_pim_sc2= sc2_pim->Integral();
 sc2_eAll->SetLineColor(4);
 sc2_eAll->Scale(0.001);
 sc2_eAll->Rebin(rebinfac);
 sc2_eAll->Draw("same HIST");
 double rate_eAll_sc2= sc2_eAll->Integral();
 sc2_pi0->SetLineColor(kGreen+3);
 sc2_pi0->Scale(0.001);
 sc2_pi0->Rebin(rebinfac);
 sc2_pi0->Draw("same HIST");
 double rate_pi0_sc2= sc2_pi0->Integral();
 leg21->Draw("text same");
 // cout<<"rate eAll_S2="<<rate_eAll_sc2<<"rate eAll_S1="<<rate_eAll_sc1<<"  "<<"rate_pim_s1="<<rate_pim_sc1<<"  "<<"rate_pim_s2="<<rate_pim_sc2<<"rate_pip_s1="<<rate_pip_sc1<<"rate_pip_s2="<<rate_pip_sc2<<endl;
 /*c[2] = new TCanvas("c[2]","c[2]",1000,1000);
 c[2]->Divide(3,2);
 for(int j=2;j<7;j++){
 c[2]->cd(j-1);
  gPad->SetGridx();
  gPad->SetGridy();
 hhit_E_pip[j]->SetLineColor(2);
 hhit_E_pip[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_pip[j]->GetXaxis()->SetTitle("E (GeV)");
 hhit_E_pip[j]->GetYaxis()->SetTitle("rate (Hz)");
 hhit_E_pip[j]->Draw("HIST");
 hhit_E_pim[j]->SetLineColor(1);
 hhit_E_pim[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_pim[j]->Draw("same HIST");
 hhit_p_pim[j]->SetLineColor(6);
 hhit_p_pim[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_p_pim[j]->Draw("same HIST");
 hhit_E_eAll[j]->SetLineColor(4);
 hhit_E_eAll[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_eAll[j]->Scale(1000);
 hhit_E_eAll[j]->Draw("same HIST");
 //leg11->Draw("text same");
 }
 c[2]->cd(1);
  TLegend *leg11 = new TLegend(0.45,0.4,0.8,0.68);
  leg11->AddEntry(hhit_E_eAll[2],"eAll*1000","l");
  leg11->AddEntry(hhit_E_pip[2],"bggen #pi^{+}","l");
  leg11->AddEntry(hhit_E_pim[2],"bggen #pi^{-}","l");
  leg11->AddEntry(hhit_p_pim[2],"bggen #pi^{-}","l");
  leg11->SetTextSize(0.05);
  leg11->SetBorderSize(0);
  leg11->SetFillColor(0);
  leg11->Draw("text same");*/
 c[3] = new TCanvas("c[3]","c[3]",1000,1000);
 c[3]->Divide(1,2);
 c[3]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd1_pip->SetLineColor(2);
  hhit_Edepspd1_pip->Scale(0.001);
  hhit_Edepspd1_pip->Rebin(rebinfac);
  hhit_Edepspd1_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pip->SetTitle("SPD, SC0 and SC1 trigger");
  hhit_Edepspd1_pip->Draw("HIST");
 double rate_pip_spd1= hhit_Edepspd1_pip->Integral();
  hhit_Edepspd1_pim->SetLineColor(1);
  hhit_Edepspd1_pim->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pim->Scale(0.001);
  hhit_Edepspd1_pim->Rebin(rebinfac);
  hhit_Edepspd1_pim->Draw("same HIST");
 double rate_pim_spd1= hhit_Edepspd1_pim->Integral();
  hhit_Edepspd1_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd1_pi0->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pi0->Scale(0.001);
  hhit_Edepspd1_pi0->Rebin(rebinfac);
  hhit_Edepspd1_pi0->Draw("same HIST");
 double rate_pi0_spd1= hhit_Edepspd1_pi0->Integral();
  hhit_Edepspd1_eAll->SetLineColor(4);
  hhit_Edepspd1_eAll->Scale(0.001);
  hhit_Edepspd1_eAll->Rebin(rebinfac);
  hhit_Edepspd1_eAll->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_eAll->Draw("same HIST");
 double rate_eAll_spd1= hhit_Edepspd1_eAll->Integral();
  TLegend *leg13 = new TLegend(0.25,0.7,0.8,0.88);
  leg13->AddEntry(hhit_Edepspd1_eAll,Form("eAll 8 deg with Q^{2}>10 MeV^{2}; total rate=%f kHz",rate_eAll_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pim,Form("bggen #pi^{-} 8 deg; total rate=%f kHz",rate_pim_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pip,Form("bggen #pi^{+} 8 deg; total rate=%f kHz",rate_pip_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pi0,Form("bggen #pi^{0} 8 deg; total rate=%f kHz",rate_pi0_spd1),"l");
  leg13->SetTextSize(0.06);
  leg13->SetBorderSize(0);
  leg13->SetFillColor(0);
  leg13->Draw("text same");
  c[3]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd2_pip->SetLineColor(2);
  hhit_Edepspd2_pip->Scale(0.001);
  hhit_Edepspd2_pip->Rebin(rebinfac);
  hhit_Edepspd2_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pip->SetTitle("LASPD, SC0 and SC1 trigger");
  hhit_Edepspd2_pip->Draw("HIST");
 double rate_pip_spd2= hhit_Edepspd2_pip->Integral();
  hhit_Edepspd2_pim->SetLineColor(1);
  hhit_Edepspd2_pim->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pim->Scale(0.001);
  hhit_Edepspd2_pim->Rebin(rebinfac);
  hhit_Edepspd2_pim->Draw("same HIST");
 double rate_pim_spd2= hhit_Edepspd2_pim->Integral();
  hhit_Edepspd2_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd2_pi0->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pi0->Scale(0.001);
  hhit_Edepspd2_pi0->Rebin(rebinfac);
  hhit_Edepspd2_pi0->Draw("same HIST");
 double rate_pi0_spd2= hhit_Edepspd2_pi0->Integral();
  hhit_Edepspd2_eAll->SetLineColor(4);
  hhit_Edepspd2_eAll->Scale(0.001);
  hhit_Edepspd2_eAll->Rebin(rebinfac);
  hhit_Edepspd2_eAll->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_eAll->Draw("same HIST");
 double rate_eAll_spd2= hhit_Edepspd2_eAll->Integral();
  TLegend *leg14 = new TLegend(0.25,0.7,0.8,0.88);
  leg14->AddEntry(hhit_Edepspd2_eAll,Form("eAll 8 deg with Q^{2}>10 MeV^{2}; total rate=%f kHz",rate_eAll_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pim,Form("bggen #pi^{-} 8 deg; total rate=%f kHz",rate_pim_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pip,Form("bggen #pi^{+} 8 deg; total rate=%f kHz",rate_pip_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pi0,Form("bggen #pi^{0} 8 deg; total rate=%f kHz",rate_pi0_spd2),"l");
  leg14->SetTextSize(0.06);
  leg14->SetBorderSize(0);
  leg14->SetFillColor(0);
  leg14->Draw("text same");
 c[4] = new TCanvas("c[4]","c[4]",1000,1000);
 c[4]->Divide(3,2);
 c[4]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_pim->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_preshower_pim->SetTitle("8 deg"); 
 EC_preshower_pim->Rebin(rebinfac2);
// EC_preshower_pim->SetLineColor(1); 
 EC_preshower_pim->Draw("HIST"); 
 EC_preshower_pip->Rebin(rebinfac2);
// EC_preshower_pip->SetLineColor(2); 
 EC_preshower_pip->Draw("same HIST"); 
  TLegend *leg223 = new TLegend(0.45,0.7,0.85,0.88);
  leg223->AddEntry(EC_preshower_pim,"bggen #pi^{-}","l");
  leg223->AddEntry(EC_preshower_pip,"bggen #pi^{+}","l");
  leg223->SetTextSize(0.06);
  leg223->SetBorderSize(0);
  leg223->SetFillColor(0);
  leg223->Draw("same");
 c[4]->cd(4);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_preshower_pip_clone =(TH1F*)EC_preshower_pip->Clone();
 EC_preshower_pip_clone->Divide(EC_preshower_pim);
 EC_preshower_pip_clone->SetTitle("8 deg"); 
 EC_preshower_pip_clone->GetYaxis()->SetRangeUser(0,10);
 EC_preshower_pip_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_preshower_pip_clone->Draw("HIST"); 
 c[4]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_pim_35deg->Scale(0.001); 
 EC_preshower_pim_35deg->SetTitle("35 deg"); 
 EC_preshower_pim_35deg->SetLineColor(1); 
 EC_preshower_pim_35deg->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_preshower_pim_35deg->Rebin(rebinfac2);
 EC_preshower_pim_35deg->Draw("HIST"); 
 EC_preshower_pip_35deg->SetLineColor(2); 
 EC_preshower_pip_35deg->Scale(0.001); 
 EC_preshower_pip_35deg->Rebin(rebinfac2);
 EC_preshower_pip_35deg->Draw("same HIST"); 
  leg223->Draw("text same");
 c[4]->cd(5);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_preshower_pip_35deg_clone =(TH1F*)EC_preshower_pip_35deg->Clone();
 EC_preshower_pip_35deg_clone->Divide(EC_preshower_pim_35deg);
 EC_preshower_pip_35deg_clone->SetTitle("35 deg"); 
 EC_preshower_pip_35deg_clone->GetYaxis()->SetRangeUser(0,10);
 EC_preshower_pip_35deg_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_preshower_pip_35deg_clone->Draw("HIST"); 

 c[4]->cd(3);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_pim_82deg->Scale(0.001); 
 EC_preshower_pim_82deg->SetTitle("82 deg"); 
 EC_preshower_pim_82deg->SetLineColor(1); 
 EC_preshower_pim_82deg->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_preshower_pim_82deg->Rebin(rebinfac2);
 EC_preshower_pim_82deg->Draw("HIST"); 
 EC_preshower_pip_82deg->SetLineColor(2); 
 EC_preshower_pip_82deg->Scale(0.001); 
 EC_preshower_pip_82deg->Rebin(rebinfac2);
 EC_preshower_pip_82deg->Draw("same HIST"); 
  leg223->Draw("text same");
 c[4]->cd(6);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_preshower_pip_82deg_clone =(TH1F*)EC_preshower_pip_82deg->Clone();
 EC_preshower_pip_82deg_clone->Divide(EC_preshower_pim_82deg);
 EC_preshower_pip_82deg_clone->SetTitle("82 deg"); 
 EC_preshower_pip_82deg_clone->GetYaxis()->SetRangeUser(0,10);
 EC_preshower_pip_82deg_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_preshower_pip_82deg_clone->Draw("HIST"); 
/*EC_shower_2D_eAll->Draw("COLZ");
 EC_shower_2D_pim->SetMarkerColor(2);
 EC_shower_2D_pim->Draw("same");
 EC_shower_2D_pip->SetMarkerColor(6);
 EC_shower_2D_pip->Draw("same");
 EC_shower_2D_pi0->SetMarkerColor(3);
 EC_shower_2D_pi0->Draw("same");
  TLegend *leg223 = new TLegend(0.3,0.35,0.8,0.68);
  leg223->AddEntry(EC_shower_2D_eAll,"eAll","p");
  leg223->AddEntry(EC_shower_2D_pim,"bggen #pi^{-}","p");
  leg223->AddEntry(EC_shower_2D_pip,"bggen #pi^{+}","p");
  leg223->AddEntry(EC_shower_2D_pi0,"bggen #pi^{0}","p");
  leg223->SetTextSize(0.06);
  leg223->SetBorderSize(0);
  leg223->SetFillColor(0);
  leg223->Draw("text same");*/
 c[5] = new TCanvas("c[5]","c[5]",1000,1000);
 c[5]->Divide(3,2);
 c[5]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_shower_pim->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_shower_pim->SetTitle("8 deg"); 
 EC_shower_pim->Rebin(rebinfac2);
 EC_shower_pim->Draw("HIST"); 
 EC_shower_pip->Rebin(rebinfac2);
 EC_shower_pip->Draw("same HIST"); 
  leg223->Draw("text same");
 c[5]->cd(4);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_shower_pip_clone =(TH1F*)EC_shower_pip->Clone();
 EC_shower_pip_clone->Divide(EC_shower_pim);
 EC_shower_pip_clone->GetYaxis()->SetRangeUser(0,10);
 EC_shower_pip_clone->SetTitle("8 deg"); 
 EC_shower_pip_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_shower_pip_clone->Draw("HIST"); 
 c[5]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_shower_pim_35deg->Scale(0.001); 
 EC_shower_pim_35deg->SetLineColor(1); 
 EC_shower_pim_35deg->SetTitle("35 deg"); 
 EC_shower_pim_35deg->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_shower_pim_35deg->Rebin(rebinfac2);
 EC_shower_pim_35deg->Draw("HIST"); 
 EC_shower_pip_35deg->SetLineColor(2); 
 EC_shower_pip_35deg->Scale(0.001); 
 EC_shower_pip_35deg->Rebin(rebinfac2);
 EC_shower_pip_35deg->Draw("same HIST"); 
  leg223->Draw("text same");
 c[5]->cd(5);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_shower_pip_35deg_clone =(TH1F*)EC_shower_pip_35deg->Clone();
 EC_shower_pip_35deg_clone->Divide(EC_shower_pim_35deg);
 EC_shower_pip_35deg_clone->SetTitle("35 deg"); 
 EC_shower_pip_35deg_clone->GetYaxis()->SetRangeUser(0,10);
 EC_shower_pip_35deg_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_shower_pip_35deg_clone->Draw("HIST"); 

 c[5]->cd(3);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_shower_pim_82deg->Scale(0.001); 
 EC_shower_pim_82deg->SetLineColor(1); 
 EC_shower_pim_82deg->SetTitle("82 deg"); 
 EC_shower_pim_82deg->GetYaxis()->SetTitle("Rate (kHz)"); 
 EC_shower_pim_82deg->Rebin(rebinfac2);
 EC_shower_pim_82deg->Draw("HIST"); 
 EC_shower_pip_82deg->SetLineColor(2); 
 EC_shower_pip_82deg->Scale(0.001); 
 EC_shower_pip_82deg->Rebin(rebinfac2);
 EC_shower_pip_82deg->Draw("same HIST"); 
  leg223->Draw("text same");
 c[5]->cd(6);
  gPad->SetGridx();
  gPad->SetGridy();
 TH1F *EC_shower_pip_82deg_clone =(TH1F*)EC_shower_pip_82deg->Clone();
 EC_shower_pip_82deg_clone->Divide(EC_shower_pim_82deg);
 EC_shower_pip_82deg_clone->GetYaxis()->SetRangeUser(0,10);
 EC_shower_pip_82deg_clone->SetTitle("82 deg"); 
 EC_shower_pip_82deg_clone->GetYaxis()->SetTitle("Rate_{#pi^{+}}/Rate_{#pi^{-}}"); 
 EC_shower_pip_82deg_clone->Draw("HIST"); 
 for(int a=0;a<6;a++){
    c[a]->SaveAs(Form("c%d.pdf",a));
    }
             gSystem->Exec("pdfunite ./c*.pdf ./HallC_trigger_rate_comparison_ratio.pdf");
             gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
