
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_rate_sangle_BLshielding_right_fork(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	//TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet_Yaxis2deg/HallC_beamtest_BeamOnTarget_4.99e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_Yaxis2deg_reduce_tree_rate_gem_Etotalcut.root");
	TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_4deg_Cfoil/HallC_beamtest_bggen_Cfoil_pi0_4deg_filenum1000_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f5 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Dan/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_newCH_Dan_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f5 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e9_8deg_80uA_target_chamber_zhiwen_reduce_tree_rate_test.root");
	TFile *f5 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_30deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_30deg_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e9_8deg_80uA_targetonly_reduce_tree_rate.root");
	//TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e9_8deg_80uA_target_chamber_reduce_tree_rate_test.root");
	//TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_sangle/HallC_beamtest_bggen_LH2_pi0_8deg_filenum19880_newCh_reduce_tree_rate_gem.root");
	TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_GEM12cmAl/HallC_beamtest_BeamOnTarget_4.22e8_8deg_80uA_target_right_step_BLshielding2x4x190_12cmAl_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f7 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_sangle/HallC_beamtest_eAll_sangle_8deg_filenum100_newCH_8GeV_reduce_tree_rate_gem.root");
	//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_1cmpb/HallC_beamtest_BeamOnTarget_0.997e11_8deg_80uA_newCH_25cmPb_reduce_tree_rate_gem.root");
	TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield7in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y7inDZ30inBS_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f7 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_Poly_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_poly_reduce_tree_rate_gem.root");
	//TFile *f7 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_0.979e11_8deg_80uA_newCH_1cmAl_reduce_tree_rate_gem.root");
	//TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_0.96e9_8deg_80uA_reduce_tree_rate_Q2L1.root");
	TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_TGonly/HallC_beamtest_BeamOnTarget_0.95e10_8deg_80uA_target_air_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_2inVINYL_10x10/HallC_beamtest_BeamOnTarget_4.915e8_8deg_80uA_target_step_right_fork_20deg_2inVINYL_10x10_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_3inpoly/HallC_beamtest_BeamOnTarget_4.63e8_8deg_80uA_target_step_right_fork_20deg_3inpoly_far_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_2inpoly/HallC_beamtest_BeamOnTarget_4.99e8_8deg_80uA_target_step_right_fork_20deg_2inpoly_reduce_tree_rate_gem_Etotcut.root");
	TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_3inVINYL/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_20deg_3inVINYL_reduce_tree_rate_gem_Etotcut.root");
	
//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_reduce_tree_rate_gem.root");
	//TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_2.435e11_8deg_80uA_newCH_reduce_tree_rate_gem.root");
	//TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_6.005e11_8deg_80uA_newCH_reduce_tree_rate_gem.root");
	//TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ70inBS_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_15deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_15deg_BLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet_Yaxis5deg/HallC_beamtest_BeamOnTarget_4.477e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_Yaxis5deg_reduce_tree_rate_gem_Etotalcut.root");
	TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_4deg_Cfoil/HallC_beamtest_bggen_Cfoil_pip_4deg_filenum1000_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield7in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y7inDZ52inBS_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_0.81e10_8deg_80uA_nobeampipe_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_20deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_20deg_BLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_3inpoly_BLLcoli850/HallC_beamtest_BeamOnTarget_4.47e8_8deg_80uA_target_step_right_fork_20deg_3inpoly_850cmBLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_4inpolynear/HallC_beamtest_BeamOnTarget_3.405e8_8deg_80uA_target_step_right_fork_20deg_4inpolynear_reduce_tree_rate_gem_Etotcut.root");
//	TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_3inpolynear/HallC_beamtest_BeamOnTarget_3.79e8_8deg_80uA_target_step_right_fork_20deg_3inpolynear_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_650cmBLLcoli_4inpoly_20deg/HallC_beamtest_BeamOnTarget_4.965e8_8deg_80uA_target_step_right_fork_20deg_650cmBLLcoli_4inpoly_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_BLshield7feet_r13m/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_5x10SC_20deg_BLshield7feet_r13m_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_r10m_BLsh9feet/HallC_beamtest_BeamOnTarget_3.991e8_8deg_80uA_5x10SC_20deg_r10m_BLsh9feet_alongZ_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_8deg_r10m_BLsh7feet/HallC_beamtest_BeamOnTarget_3.993e8_8deg_80uA_5x10SC_8deg_r10m_BLsh7feet_4degYaxis_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_8deg_r10m/HallC_beamtest_BeamOnTarget_4e8_8deg_80uA_5x10SC_8deg_r10m_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_8deg_r10m_BLsh4feet/HallC_beamtest_BeamOnTarget_3.742e8_8deg_80uA_5x10SC_8deg_r10m_BLsh4feet_82degYaxis_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_8deg_r10m_BLsh7feet_Yaxis20deg/HallC_beamtest_BeamOnTarget_3.87e8_8deg_80uA_5x10SC_8deg_r10m_BLsh7feet_20degYaxis_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon/HallC_beamtest_BeamOnTarget_4.884e8_4deg_80uA_5x10SC_r10m_cfoil_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet_Yaxis6deg/HallC_beamtest_BeamOnTarget_4.814e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_Yaxis6deg_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet/HallC_beamtest_BeamOnTarget_4.928e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_LD2_r10m/HallC_beamtest_BeamOnTarget_4.968e8_8deg_80uA_5x10SC_20deg_r10m_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_LD2_r20m_5cmpoly_30x30/HallC_beamtest_BeamOnTarget_5e8_80uA_5x10SC_20deg_r20m_5cmpoly_reduce_tree_rate_gem_Etotalcut.root");
	TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r10m_carbon/HallC_beamtest_BeamOnTarget_2.594e9_7deg_80uA_5x10SC_r10m_cfoil_10.6GeV_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet_Yaxis6deg/HallC_beamtest_BeamOnTarget_4.814e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_Yaxis6deg_reduce_tree_rate_gem_Etotalcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_750cmBLLcoli_3inpoly_20deg/HallC_beamtest_BeamOnTarget_4.905e8_8deg_80uA_target_step_right_fork_20deg_750cmBLLcoli_3inpoly_reduce_tree_rate_gem_Etotcut.root");

	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_850cmBLLcoli_20deg/HallC_beamtest_BeamOnTarget_4.945e8_8deg_80uA_target_step_right_fork_20deg_850cmBLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_850cmBLLcoli_20deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_20deg_750cmBLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg_2inVINYL_BLcoli/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_20deg_BLLcoli_2inVINYL_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_650cmBLLcoli_20deg/HallC_beamtest_BeamOnTarget_4.66e8_8deg_80uA_target_step_right_fork_20deg_650cmBLLcoli_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in_dz40in/HallC_beamtest_BeamOnTarget_1.01e10_8deg_80uA_Y5inDZ80inBS_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_3x30x30inpoly_r13m/HallC_beamtest_BeamOnTarget_4.89e8_8deg_80uA_5x10SC_20deg_3x30x30inpoly_r13m_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_20deg_2x30x30inpoly_r13m/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_5x10SC_20deg_2x30x30inpoly_r13m_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon_BLsh7feet_Yaxis5deg_1inpoly/HallC_beamtest_BeamOnTarget_4.828e8_4deg_80uA_5x10SC_r10m_cfoil_BLsh7feet_Yaxis5deg_1inpoly_reduce_tree_rate_gem_Etotalcut.root");
	TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_4deg_Cfoil/HallC_beamtest_bggen_Cfoil_pim_4deg_filenum1000_reduce_tree_rate_gem_Etotalcut.root");
	TFile *f12 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_step_less/HallC_beamtest_BeamOnTarget_9.445e8_8deg_80uA_newCH_CAD_reduce_tree_rate_gem_Etotcut.root");
	//TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_8deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_8deg_BLLcoli_reduce_tree_rate_gem_Etotcut.root");
        TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_4deg_r10m_carbon/HallC_beamtest_BeamOnTarget_4.884e8_4deg_80uA_5x10SC_r10m_cfoil_reduce_tree_rate_gem_Etotalcut.root");

	TTree *tree_pip = (TTree*) f5->Get("T");
	TTree *tree_pim = (TTree*) f4->Get("T");
	TTree *tree_pi0 = (TTree*) f6->Get("T"); //abs(phicut) <5 deg
	TTree *tree_eAll = (TTree*) f7->Get("T");
	TTree *tree_beam = (TTree*) f8->Get("T");
	TTree *tree_beam_Edep = (TTree*) f18->Get("T");
	TTree *tree_beam_more = (TTree*) f9->Get("T");
	TTree *tree_beam_1cm = (TTree*) f10->Get("T");
	TTree *tree_beam_15cm = (TTree*) f11->Get("T");
	TTree *tree_beam_config2 = (TTree*) f12->Get("T");
	TTree *tree_beam_config2r = (TTree*) f13->Get("T");
	const int rebinfac=1;
	/*	int ndata = tree_eAll->Draw("(GEM00_x-GEM10_x):(GEM00_y-GEM10_y)",
		"GEM00_n>0 && GEM10_n>0","");
		TGraph* g1 = new TGraph(ndata, tree_eAll->GetV2(),tree_eAll->GetV1());
		int ndata2 = tree_eAll_beamline->Draw("(GEM00_x-GEM10_x):(GEM00_y-GEM10_y)",
		"GEM00_n>0 && GEM10_n>0","");
		TGraph* g2 = new TGraph(ndata2, tree_eAll_beamline->GetV2(),tree_eAll_beamline->GetV1());
		*/
        /*tree_pip->Draw("ShowerSum>>shower_pip(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_pip_hist = (TH1F*)gROOT->FindObject("shower_pip");
        tree_pim->Draw("ShowerSum>>shower_pim(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_pim_hist = (TH1F*)gROOT->FindObject("shower_pim");
        tree_pi0->Draw("ShowerSum>>shower_pi0(4000,0,1000)","rate*( ShowerSum>0)","goff");
	TH1F *shower_pi0_hist = (TH1F*)gROOT->FindObject("shower_pi0");
        tree_eAll->Draw("ShowerSum>>shower_eAll(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_eAll_hist = (TH1F*)gROOT->FindObject("shower_eAll");
        tree_beam->Draw("ShowerSum>>shower_beam(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_hist = (TH1F*)gROOT->FindObject("shower_beam");
        tree_beam_more->Draw("ShowerSum>>shower_beam_more(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_more_hist = (TH1F*)gROOT->FindObject("shower_beam_more");
        tree_beam_1cm->Draw("ShowerSum>>shower_beam_1cm(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_1cm_hist = (TH1F*)gROOT->FindObject("shower_beam_1cm");
        tree_beam_15cm->Draw("ShowerSum>>shower_beam_15cm(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_15cm_hist = (TH1F*)gROOT->FindObject("shower_beam_15cm");
        //tree_beam->Draw("ShowerSum>>shower_SC0_SC1_beam(4000,0,1000)","rate*(SC0_Eendsum>0 && SC1_Eendsum>0)","goff");
	//TH1F *shower_beam_SC_cut_hist = (TH1F*)gROOT->FindObject("shower_SC0_SC1_beam");
        tree_pip->Draw("Npesum>>Npesum_pip(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pip_hist = (TH1F*)gROOT->FindObject("Npesum_pip");
        tree_pim->Draw("Npesum>>Npesum_pim(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_pi0->Draw("Npesum>>Npesum_pi0(100,0,100)","rate*( ShowerSum>0)","goff");
	TH1F *Npesum_pi0_hist = (TH1F*)gROOT->FindObject("Npesum_pi0");
        tree_eAll->Draw("Npesum>>Npesum_eAll(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_eAll_hist = (TH1F*)gROOT->FindObject("Npesum_eAll");
        tree_beam->Draw("Npesum>>Npesum_beam(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_beam_hist = (TH1F*)gROOT->FindObject("Npesum_beam");
        tree_pip->Draw("GEM10_x>>GEM00_pip(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_pip_hist = (TH1F*)gROOT->FindObject("GEM00_pip");
        tree_pim->Draw("GEM10_x>>GEM00_pim(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_pim_hist = (TH1F*)gROOT->FindObject("GEM00_pim");
        tree_pi0->Draw("GEM10_x>>GEM00_pi0(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_pi0_hist = (TH1F*)gROOT->FindObject("GEM00_pi0");
        tree_eAll->Draw("GEM10_x>>GEM00_eAll(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_eAll_hist = (TH1F*)gROOT->FindObject("GEM00_eAll");
        tree_beam->Draw("GEM10_x>>GEM00_beam(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_beam_hist = (TH1F*)gROOT->FindObject("GEM00_beam");
        tree_beam_more->Draw("GEM10_x>>GEM00_beam_more(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_beam_more_hist = (TH1F*)gROOT->FindObject("GEM00_beam_more");
        tree_beam_1cm->Draw("GEM10_x>>GEM00_beam_1cm(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_beam_1cm_hist = (TH1F*)gROOT->FindObject("GEM00_beam_1cm");
        tree_beam_15cm->Draw("GEM10_x>>GEM00_beam_15cm(256,-5.12,5.12)","rate","goff");
	TH1F *GEM00_beam_15cm_hist = (TH1F*)gROOT->FindObject("GEM00_beam_15cm");*/
        tree_pim->Draw("SC0_Eendsum>>shower_pim(500,0,100)","rate*(SC0_Eendsum>0.88)","goff");
	TH1F *shower_pim_hist = (TH1F*)gROOT->FindObject("shower_pim");
        tree_beam_more->Draw("SC0_Eendsum>>shower_beam_more(500,0,100)","rate*(SC0_Eendsum>0.88)","goff");
	TH1F *shower_beam_more_hist = (TH1F*)gROOT->FindObject("shower_beam_more");
        tree_beam_1cm->Draw("SC0_Eendsum>>shower_beam_1cm(500,0,100)","rate*(SC0_Eendsum>0.88)","goff");
	TH1F *shower_beam_1cm_hist = (TH1F*)gROOT->FindObject("shower_beam_1cm");
        tree_beam_15cm->Draw("SC0_Eendsum>>shower_beam_15cm(500,0,100)","rate*(SC0_Eendsum>0.88)","goff");
	TH1F *shower_beam_15cm_hist = (TH1F*)gROOT->FindObject("shower_beam_15cm");
        tree_beam_config2r->Draw("SC0_Eendsum>>shower_beam_config2r(500,0,100)","rate*(SC0_Eendsum>0.88)","goff");
	TH1F *shower_beam_config2r_hist = (TH1F*)gROOT->FindObject("shower_beam_config2r");
        /*tree_beam_more->Draw("ShowerSum>>shower_beam_more(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_more_hist = (TH1F*)gROOT->FindObject("shower_beam_more");
        tree_beam_1cm->Draw("ShowerSum>>shower_beam_1cm(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_1cm_hist = (TH1F*)gROOT->FindObject("shower_beam_1cm");
        tree_beam_15cm->Draw("ShowerSum>>shower_beam_15cm(4000,0,1000)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_15cm_hist = (TH1F*)gROOT->FindObject("shower_beam_15cm");
        tree_beam->Draw("ShowerSum>>shower_SC0_SC1_beam(4000,0,1000)","rate*(SC0_Eendsum>4 && SC1_Eendsum>4)","goff");
	TH1F *shower_beam_SC_cut_hist = (TH1F*)gROOT->FindObject("shower_SC0_SC1_beam");*/
        tree_pim->Draw("SC1_Eendsum>>Npesum_pim(500,0,100)","rate*(SC1_Eendsum>0.88)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_beam_more->Draw("SC1_Eendsum>>Npesum_beam_more(500,0,100)","rate*(SC1_Eendsum>0.88)","goff");
	TH1F *Npesum_beam_more_hist = (TH1F*)gROOT->FindObject("Npesum_beam_more");
        tree_beam_config2r->Draw("SC1_Eendsum>>Npesum_beam_config2r(500,0,100)","rate*(SC1_Eendsum>0.88)","goff");
	TH1F *Npesum_beam_config2r_hist = (TH1F*)gROOT->FindObject("Npesum_beam_config2r");
        tree_beam_1cm->Draw("SC1_Eendsum>>Npesum_beam_1cm(500,0,100)","rate*(SC1_Eendsum>0.88)","goff");
	TH1F *Npesum_beam_1cm_hist = (TH1F*)gROOT->FindObject("Npesum_beam_1cm");
        tree_beam_15cm->Draw("SC1_Eendsum>>Npesum_beam_15cm(500,0,100)","rate*(SC1_Eendsum>0.88)","goff");
	TH1F *Npesum_beam_15cm_hist = (TH1F*)gROOT->FindObject("Npesum_beam_15cm");
        tree_pip->Draw("GEM00_x>>GEM00_pip(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_pip_hist = (TH1F*)gROOT->FindObject("GEM00_pip");
        tree_pim->Draw("GEM00_x>>GEM00_pim(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_pim_hist = (TH1F*)gROOT->FindObject("GEM00_pim");
        tree_pi0->Draw("GEM00_x>>GEM00_pi0(256,-5.12,5.12)","rate*( GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_pi0_hist = (TH1F*)gROOT->FindObject("GEM00_pi0");
        tree_eAll->Draw("GEM00_x>>GEM00_eAll(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_eAll_hist = (TH1F*)gROOT->FindObject("GEM00_eAll");
        tree_beam->Draw("GEM00_x>>GEM00_beam(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_hist = (TH1F*)gROOT->FindObject("GEM00_beam");
        tree_beam_Edep->Draw("GEM00_x>>GEM00_beam_Edep(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_Edep_hist = (TH1F*)gROOT->FindObject("GEM00_beam_Edep");
        tree_beam_more->Draw("GEM00_x>>GEM00_beam_more(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_more_hist = (TH1F*)gROOT->FindObject("GEM00_beam_more");
        tree_beam_1cm->Draw("GEM00_x>>GEM00_beam_1cm(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_1cm_hist = (TH1F*)gROOT->FindObject("GEM00_beam_1cm");
        tree_beam_15cm->Draw("GEM00_x>>GEM00_beam_15cm(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_15cm_hist = (TH1F*)gROOT->FindObject("GEM00_beam_15cm");
        tree_beam_config2->Draw("GEM00_x>>GEM00_beam_config2(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_config2_hist = (TH1F*)gROOT->FindObject("GEM00_beam_config2");
        tree_beam_config2r->Draw("GEM00_x>>GEM00_beam_config2r(256,-5.12,5.12)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_config2r_hist = (TH1F*)gROOT->FindObject("GEM00_beam_config2r");
        //TH1F *eAll_clone_hist = (TH1F*)shower_eAll_hist->Clone(); 
        tree_pip->Draw("GEM10_x>>GEM10_pip(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pip_hist = (TH1F*)gROOT->FindObject("GEM10_pip");
        tree_pim->Draw("GEM10_x>>GEM10_pim(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pim_hist = (TH1F*)gROOT->FindObject("GEM10_pim");
        tree_pi0->Draw("GEM10_x>>GEM10_pi0(256,-5.12,5.12)","rate*( GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pi0_hist = (TH1F*)gROOT->FindObject("GEM10_pi0");
        tree_eAll->Draw("GEM10_x>>GEM10_eAll(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_eAll_hist = (TH1F*)gROOT->FindObject("GEM10_eAll");
        tree_beam->Draw("GEM10_x>>GEM10_beam(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_hist = (TH1F*)gROOT->FindObject("GEM10_beam");
        tree_beam_Edep->Draw("GEM10_x>>GEM10_beam_Edep(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_Edep_hist = (TH1F*)gROOT->FindObject("GEM10_beam_Edep");
        tree_beam_more->Draw("GEM10_x>>GEM10_beam_more(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_more_hist = (TH1F*)gROOT->FindObject("GEM10_beam_more");
        tree_beam_1cm->Draw("GEM10_x>>GEM10_beam_1cm(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_1cm_hist = (TH1F*)gROOT->FindObject("GEM10_beam_1cm");
        tree_beam_15cm->Draw("GEM10_x>>GEM10_beam_15cm(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_15cm_hist = (TH1F*)gROOT->FindObject("GEM10_beam_15cm");
        tree_beam_config2->Draw("GEM10_x>>GEM10_beam_config2(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_config2_hist = (TH1F*)gROOT->FindObject("GEM10_beam_config2");
        tree_beam_config2r->Draw("GEM10_x>>GEM10_beam_config2r(256,-5.12,5.12)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_config2r_hist = (TH1F*)gROOT->FindObject("GEM10_beam_config2r");
        tree_pim->Draw("SPD_Eendsum>>SPD_pim(200,0,50)","rate*(SPD_Eendsum>0 && SC1_Eendsum>0.88)","goff");
	TH1F *SPD_pim_hist = (TH1F*)gROOT->FindObject("SPD_pim");
        tree_beam_more->Draw("SPD_Eendsum>>SPD_beam_more(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *SPD_beam_more_hist = (TH1F*)gROOT->FindObject("SPD_beam_more");
        tree_beam_1cm->Draw("SPD_Eendsum>>SPD_beam_1cm(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *SPD_beam_1cm_hist = (TH1F*)gROOT->FindObject("SPD_beam_1cm");
        tree_beam_15cm->Draw("SPD_Eendsum>>SPD_beam_15cm(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *SPD_beam_15cm_hist = (TH1F*)gROOT->FindObject("SPD_beam_15cm");
        tree_beam_config2r->Draw("SPD_Eendsum>>SPD_beam_config2r(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *SPD_beam_config2r_hist = (TH1F*)gROOT->FindObject("SPD_beam_config2r");
        tree_pim->Draw("LASPD_Eendsum>>LASPD_pim(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *LASPD_pim_hist = (TH1F*)gROOT->FindObject("LASPD_pim");
        tree_beam_more->Draw("LASPD_Eendsum>>LASPD_beam_more(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *LASPD_beam_more_hist = (TH1F*)gROOT->FindObject("LASPD_beam_more");
        tree_beam_1cm->Draw("LASPD_Eendsum>>LASPD_beam_1cm(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *LASPD_beam_1cm_hist = (TH1F*)gROOT->FindObject("LASPD_beam_1cm");
        tree_beam_15cm->Draw("LASPD_Eendsum>>LASPD_beam_15cm(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *LASPD_beam_15cm_hist = (TH1F*)gROOT->FindObject("LASPD_beam_15cm");
        tree_beam_config2r->Draw("LASPD_Eendsum>>LASPD_beam_config2r(200,0,50)","rate*(SPD_Eendsum>0 &&SC1_Eendsum>0.88)","goff");
	TH1F *LASPD_beam_config2r_hist = (TH1F*)gROOT->FindObject("LASPD_beam_config2r");
        TCanvas *c[10];
	c[0] = new TCanvas("c[0]","c[0]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        shower_beam_config2r_hist->SetLineColor(6);
        shower_beam_config2r_hist->GetXaxis()->SetTitle("SC0 Eend");
        shower_beam_config2r_hist->GetYaxis()->SetTitle("Rate (MHz)");
        shower_beam_config2r_hist->Scale(0.000001);
        shower_beam_config2r_hist->Rebin(rebinfac);
        shower_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e13);
        shower_beam_config2r_hist->Draw("HIST");
        double rate_beam_config2r= shower_beam_config2r_hist->Integral();
        shower_pim_hist->SetLineColor(1);
        shower_pim_hist->Scale(0.000001);
        shower_pim_hist->Rebin(rebinfac);
        shower_pim_hist->Draw("same HIST");
        double rate_pim= shower_pim_hist->Integral();
        shower_beam_more_hist->SetLineColor(3);
        shower_beam_more_hist->Scale(0.000001);
        shower_beam_more_hist->Rebin(rebinfac);
        shower_beam_more_hist->Draw("same HISt");
        double rate_proton_more= shower_beam_more_hist->Integral();
        shower_beam_1cm_hist->SetLineColor(7);
        shower_beam_1cm_hist->Scale(0.000001);
        shower_beam_1cm_hist->Rebin(rebinfac);
        shower_beam_1cm_hist->Draw("same HISt");
        double rate_proton_1cm= shower_beam_1cm_hist->Integral();
        shower_beam_15cm_hist->SetLineColor(kOrange+3);
        shower_beam_15cm_hist->Scale(0.000001);
        shower_beam_15cm_hist->Rebin(rebinfac);
        shower_beam_15cm_hist->Draw("same HISt");
        double rate_proton_15cm= shower_beam_15cm_hist->Integral();
  TLegend *leg8 = new TLegend(0.45,0.6,0.8,0.88);
  leg8->AddEntry(shower_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",rate_beam_config2r),"l");
  leg8->AddEntry(shower_beam_more_hist,Form("7feet shielding 5deg along Y-axis ; total rate=%f MHz",rate_proton_more),"l");
  //leg8->AddEntry(shower_beam_1cm_hist,Form(" 7feet shielding 0deg alog Y-axis; total rate=%f MHz",rate_proton_1cm),"l");
  leg8->AddEntry(shower_beam_1cm_hist,Form(" 5 uA C-foil 7 deg; total rate=%f MHz",rate_proton_1cm),"l");
  leg8->AddEntry(shower_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",rate_proton_15cm),"l");
  leg8->AddEntry(shower_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",rate_pim),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        Npesum_beam_config2r_hist->SetLineColor(6);
        Npesum_beam_config2r_hist->GetXaxis()->SetTitle("Npe");
        Npesum_beam_config2r_hist->GetYaxis()->SetTitle("Rate (kHz)");
        Npesum_beam_config2r_hist->Scale(0.000001);
        Npesum_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        Npesum_beam_config2r_hist->Draw("HIST");
        double rate_SC1_config2r= Npesum_beam_config2r_hist->Integral();
        Npesum_beam_more_hist->SetLineColor(2);
        Npesum_beam_more_hist->Scale(0.000001);
        Npesum_beam_more_hist->Draw("same HIST");
        double rate_SC1_beam_more= Npesum_beam_more_hist->Integral();
        Npesum_pim_hist->SetLineColor(1);
        Npesum_pim_hist->Scale(0.000001);
        Npesum_pim_hist->Draw("same HIST");
        double rate_SC1_pim= Npesum_pim_hist->Integral();
        Npesum_beam_1cm_hist->SetLineColor(8);
        Npesum_beam_1cm_hist->Scale(0.000001);
        Npesum_beam_1cm_hist->Draw("same HIST");
        double rate_SC1_beam_1cm= Npesum_beam_1cm_hist->Integral();
        Npesum_beam_15cm_hist->SetLineColor(4);
        Npesum_beam_15cm_hist->Scale(0.000001);
        Npesum_beam_15cm_hist->Draw("same HIST");
        double rate_SC1_beam_15cm= Npesum_beam_15cm_hist->Integral();
  TLegend *leg7 = new TLegend(0.45,0.6,0.8,0.88);
  leg7->AddEntry(Npesum_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",rate_SC1_config2r),"l");
  leg7->AddEntry(Npesum_beam_more_hist,Form("7feet shielding 5deg along Y-axis; total rate=%f MHz",rate_SC1_beam_more),"l");
  //leg7->AddEntry(Npesum_beam_1cm_hist,Form("7feet shielding 0deg along Y-axis; total rate=%f MHz",rate_SC1_beam_1cm),"l");
  leg7->AddEntry(Npesum_beam_1cm_hist,Form("5uA C-foil; total rate=%f MHz",rate_SC1_beam_1cm),"l");
  leg7->AddEntry(Npesum_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",rate_SC1_beam_15cm),"l");
  leg7->AddEntry(Npesum_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",rate_SC1_pim),"l");
  leg7->SetTextSize(0.03);
  leg7->SetBorderSize(0);
  leg7->SetFillColor(0);
  leg7->Draw("text same");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        GEM00_beam_config2r_hist->SetLineColor(6);
        GEM00_beam_config2r_hist->GetXaxis()->SetTitle("GEM00_x (cm)");
        GEM00_beam_config2r_hist->GetYaxis()->SetTitle("Rate (MHz)");
        GEM00_beam_config2r_hist->Scale(0.000001);
        GEM00_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        GEM00_beam_config2r_hist->Draw("same HIST");
        double rate_proton_gem_config2r= GEM00_beam_config2r_hist->Integral();
        GEM00_pip_hist->SetLineColor(4);
        GEM00_pip_hist->Scale(0.000001);
    //    GEM00_pip_hist->Draw("same HIST");
     //   double rate_pip_gem= GEM00_pip_hist->Integral();
        GEM00_pim_hist->SetLineColor(1);
        GEM00_pim_hist->Scale(0.000001);
        GEM00_pim_hist->Draw("same HIST");
        double rate_pim_gem= GEM00_pim_hist->Integral();
        GEM00_pi0_hist->SetLineColor(2);
        GEM00_pi0_hist->Scale(0.000001);
        GEM00_pi0_hist->Draw("same HIST");
        double rate_pi0_gem= GEM00_pi0_hist->Integral();
        GEM00_beam_more_hist->SetLineColor(3);
        GEM00_beam_more_hist->Scale(0.000001);
        GEM00_beam_more_hist->Draw("same HIST");
        double rate_proton_gem_more= GEM00_beam_more_hist->Integral();
        GEM00_beam_1cm_hist->SetLineColor(7);
        GEM00_beam_1cm_hist->Scale(0.000001);
        GEM00_beam_1cm_hist->Draw("same HIST");
        double rate_proton_gem_1cm= GEM00_beam_1cm_hist->Integral();
        GEM00_beam_15cm_hist->SetLineColor(kOrange-3);
        GEM00_beam_15cm_hist->Scale(0.000001);
        GEM00_beam_15cm_hist->Draw("same HIST");
        double rate_proton_gem_15cm= GEM00_beam_15cm_hist->Integral();
        GEM00_beam_Edep_hist->SetLineColor(kMagenta-2);
        GEM00_beam_Edep_hist->Scale(0.000001);
   //     GEM00_beam_Edep_hist->Draw("same HIST");
   //     double rate_proton_gem_Edep= GEM00_beam_Edep_hist->Integral();
  TLegend *leg9 = new TLegend(0.45,0.6,0.8,0.88);
  leg9->AddEntry(GEM00_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",rate_proton_gem_config2r),"l");
  //leg9->AddEntry(GEM00_pip_hist,Form(" no shielding; total rate=%f MHz",rate_pip_gem),"l");
  leg9->AddEntry(GEM00_beam_more_hist,Form("7feet shielding 5deg along Y-axis; total rate=%f MHz",rate_proton_gem_more),"l");
  //leg9->AddEntry(GEM00_beam_1cm_hist,Form("7deg feet shielding 0deg along Y-axis; total rate=%f MHz",rate_proton_gem_1cm),"l");
  leg9->AddEntry(GEM00_beam_1cm_hist,Form("5uA C-foil; total rate=%f MHz",rate_proton_gem_1cm),"l");
  leg9->AddEntry(GEM00_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",rate_proton_gem_15cm),"l");
  leg9->AddEntry(GEM00_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",rate_pim_gem),"l");
 // leg9->AddEntry(GEM00_beam_Edep_hist,Form("2in 10x10 cm^{2} poly GEM00 step HMS 4deg; total rate=%f MHz",rate_proton_gem_Edep),"l");
  leg9->SetTextSize(0.03);
  leg9->SetBorderSize(0);
  leg9->SetFillColor(0);
  leg9->Draw("text same");
	c[3] = new TCanvas("c[3]","c[3]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        GEM10_beam_config2r_hist->SetLineColor(6);
        GEM10_beam_config2r_hist->GetXaxis()->SetTitle("GEM10_x (cm)");
        GEM10_beam_config2r_hist->GetYaxis()->SetTitle("Rate (MHz)");
        GEM10_beam_config2r_hist->Scale(0.000001);
        GEM10_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        GEM10_beam_config2r_hist->Draw("same HIST");
        double rate_proton_gem_config2r= GEM10_beam_config2r_hist->Integral();
        GEM10_pip_hist->SetLineColor(4);
        GEM10_pip_hist->Scale(0.000001);
    //    GEM10_pip_hist->Draw("same HIST");
    //    double rate_pip_gem= GEM10_pip_hist->Integral();
        GEM10_pim_hist->SetLineColor(1);
        GEM10_pim_hist->Scale(0.000001);
        GEM10_pim_hist->Draw("same HIST");
        double rate_pim_gem= GEM10_pim_hist->Integral();
        GEM10_pi0_hist->SetLineColor(2);
        GEM10_pi0_hist->Scale(0.000001);
        GEM10_pi0_hist->Draw("same HIST");
        double rate_pi0_gem= GEM10_pi0_hist->Integral();
        GEM10_beam_more_hist->SetLineColor(3);
        GEM10_beam_more_hist->Scale(0.000001);
        GEM10_beam_more_hist->Draw("same HIST");
        double rate_proton_gem_more= GEM10_beam_more_hist->Integral();
        GEM10_beam_1cm_hist->SetLineColor(7);
        GEM10_beam_1cm_hist->Scale(0.000001);
        GEM10_beam_1cm_hist->Draw("same HIST");
        double rate_proton_gem_1cm= GEM10_beam_1cm_hist->Integral();
        GEM10_beam_15cm_hist->SetLineColor(kOrange-3);
        GEM10_beam_15cm_hist->Scale(0.000001);
        GEM10_beam_15cm_hist->Draw("same HIST");
        double rate_proton_gem_15cm= GEM10_beam_15cm_hist->Integral();
        GEM10_beam_Edep_hist->SetLineColor(kMagenta-2);
        GEM10_beam_Edep_hist->Scale(0.000001);
      //  GEM10_beam_Edep_hist->Draw("same HIST");
      //  double rate_proton_gem_Edep= GEM10_beam_Edep_hist->Integral();
  TLegend *leg19 = new TLegend(0.45,0.6,0.8,0.88);
  leg19->AddEntry(GEM10_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",rate_proton_gem_config2r),"l");
  //leg19->AddEntry(GEM10_pip_hist,Form(" no shielding; total rate=%f MHz",rate_pip_gem),"l");
  leg19->AddEntry(GEM10_beam_more_hist,Form("7feet shielding 5deg along Y-axis; total rate=%f MHz",rate_proton_gem_more),"l");
  //leg19->AddEntry(GEM10_beam_1cm_hist,Form("7feet shielding 0deg along Y-axis; total rate=%f MHz",rate_proton_gem_1cm),"l");
  leg19->AddEntry(GEM10_beam_1cm_hist,Form("5uA C-foil; total rate=%f MHz",rate_proton_gem_1cm),"l");
  leg19->AddEntry(GEM10_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",rate_proton_gem_15cm),"l");
  leg19->AddEntry(GEM10_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",rate_pim_gem),"l");
 // leg19->AddEntry(GEM10_beam_Edep_hist,Form("2in 10x10 cm^{2} poly GEM10 step HMS 4deg; total rate=%f MHz",rate_proton_gem_Edep),"l");
  leg19->SetTextSize(0.03);
  leg19->SetBorderSize(0);
  leg19->SetFillColor(0);
  leg19->Draw("text same");
	c[4] = new TCanvas("c[4]","c[4]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SPD_beam_config2r_hist->SetLineColor(6);
        SPD_beam_config2r_hist->GetXaxis()->SetTitle("SPD Eend");
        SPD_beam_config2r_hist->GetYaxis()->SetTitle("Rate (MHz)");
        SPD_beam_config2r_hist->Scale(0.000001);
        SPD_beam_config2r_hist->Rebin(rebinfac);
        SPD_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e13);
        SPD_beam_config2r_hist->Draw("HIST");
        double SPD_rate_beam_config2r= SPD_beam_config2r_hist->Integral();
        SPD_pim_hist->SetLineColor(1);
        SPD_pim_hist->Scale(0.000001);
        SPD_pim_hist->Rebin(rebinfac);
        SPD_pim_hist->Draw("same HIST");
        double SPD_rate_pim= SPD_pim_hist->Integral();
        SPD_beam_more_hist->SetLineColor(3);
        SPD_beam_more_hist->Scale(0.000001);
        SPD_beam_more_hist->Rebin(rebinfac);
        SPD_beam_more_hist->Draw("same HISt");
        double SPD_rate_proton_more= SPD_beam_more_hist->Integral();
        SPD_beam_1cm_hist->SetLineColor(7);
        SPD_beam_1cm_hist->Scale(0.000001);
        SPD_beam_1cm_hist->Rebin(rebinfac);
        SPD_beam_1cm_hist->Draw("same HISt");
        double SPD_rate_proton_1cm= SPD_beam_1cm_hist->Integral();
        SPD_beam_15cm_hist->SetLineColor(kOrange+3);
        SPD_beam_15cm_hist->Scale(0.000001);
        SPD_beam_15cm_hist->Rebin(rebinfac);
        SPD_beam_15cm_hist->Draw("same HISt");
        double SPD_rate_proton_15cm= SPD_beam_15cm_hist->Integral();
  TLegend *leg18 = new TLegend(0.45,0.6,0.8,0.88);
  leg18->AddEntry(SPD_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",SPD_rate_beam_config2r),"l");
  leg18->AddEntry(SPD_beam_more_hist,Form("7feet shielding 5deg along Y-axis; total rate=%f MHz",SPD_rate_proton_more),"l");
  //leg18->AddEntry(SPD_beam_1cm_hist,Form(" 7feet shielding 0deg along Y-axis; total rate=%f MHz",SPD_rate_proton_1cm),"l");
  leg18->AddEntry(SPD_beam_1cm_hist,Form("5 uA C-foil; total rate=%f MHz",SPD_rate_proton_1cm),"l");
  leg18->AddEntry(SPD_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",SPD_rate_proton_15cm),"l");
  leg18->AddEntry(SPD_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",SPD_rate_pim),"l");
  leg18->SetTextSize(0.03);
  leg18->SetBorderSize(0);
  leg18->SetFillColor(0);
  leg18->Draw("text same");
	c[5] = new TCanvas("c[5]","c[5]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        LASPD_beam_config2r_hist->SetLineColor(6);
        LASPD_beam_config2r_hist->GetXaxis()->SetTitle("LASPD Eend");
        LASPD_beam_config2r_hist->GetYaxis()->SetTitle("Rate (MHz)");
        LASPD_beam_config2r_hist->Scale(0.000001);
        LASPD_beam_config2r_hist->Rebin(rebinfac);
        LASPD_beam_config2r_hist->GetYaxis()->SetRangeUser(1e-2,1e13);
        LASPD_beam_config2r_hist->Draw("HIST");
        double LASPD_rate_beam_config2r= LASPD_beam_config2r_hist->Integral();
        LASPD_pim_hist->SetLineColor(1);
        LASPD_pim_hist->Scale(0.000001);
        LASPD_pim_hist->Rebin(rebinfac);
        LASPD_pim_hist->Draw("same HIST");
        double LASPD_rate_pim= LASPD_pim_hist->Integral();
        LASPD_beam_more_hist->SetLineColor(3);
        LASPD_beam_more_hist->Scale(0.000001);
        LASPD_beam_more_hist->Rebin(rebinfac);
        LASPD_beam_more_hist->Draw("same HISt");
        double LASPD_rate_proton_more= LASPD_beam_more_hist->Integral();
        LASPD_beam_1cm_hist->SetLineColor(7);
        LASPD_beam_1cm_hist->Scale(0.000001);
        LASPD_beam_1cm_hist->Rebin(rebinfac);
        LASPD_beam_1cm_hist->Draw("same HISt");
        double LASPD_rate_proton_1cm= LASPD_beam_1cm_hist->Integral();
        LASPD_beam_15cm_hist->SetLineColor(kOrange+3);
        LASPD_beam_15cm_hist->Scale(0.000001);
        LASPD_beam_15cm_hist->Rebin(rebinfac);
        LASPD_beam_15cm_hist->Draw("same HISt");
        double LASPD_rate_proton_15cm= LASPD_beam_15cm_hist->Integral();
  TLegend *leg28 = new TLegend(0.45,0.6,0.8,0.88);
  leg28->AddEntry(LASPD_beam_config2r_hist,Form("no shielding ; total rate=%f MHz",LASPD_rate_beam_config2r),"l");
  leg28->AddEntry(LASPD_beam_more_hist,Form("7feet shielding 5deg along Y-axis; total rate=%f MHz",LASPD_rate_proton_more),"l");
  //leg28->AddEntry(LASPD_beam_1cm_hist,Form(" 7feet shielding 0deg along Y-axis; total rate=%f MHz",LASPD_rate_proton_1cm),"l");
  leg28->AddEntry(LASPD_beam_1cm_hist,Form(" 5uA C-foil; total rate=%f MHz",LASPD_rate_proton_1cm),"l");
  leg28->AddEntry(LASPD_beam_15cm_hist,Form("7feet shielding 5deg along Y-axis 1x30x30 in3 GEM00; total rate=%f MHz",LASPD_rate_proton_15cm),"l");
  leg28->AddEntry(LASPD_pim_hist,Form("7feet shielding 5deg along Y-axis 2x30x30 in3 GEM00; total rate=%f MHz",LASPD_rate_pim),"l");
  leg28->SetTextSize(0.03);
  leg28->SetBorderSize(0);
  leg28->SetFillColor(0);
  leg28->Draw("text same");
	for(int a=0;a<3;a++){
		c[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_comparison_BLshielding.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
