
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_rate_Cer_newCh_7deg(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	//TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7degsurvey_r20m_carbon_even_gamma_400MeV/HallC_beamtest_BeamOnTarget_1e6_7degsurvey_5uA_4SC_r20m_cfoil_even_gamma_400MeV_reduce_tree_rate_gem1_Etotalcut.root");
	//TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_20deg_LD_21m//HallC_beamtest_bggen_LD2_pip_20deg_filenum40090_21m_shielding_reduce_tree_rate_preshower_Etotalcut_40uA_tid1.root");
	TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_18deg_LD_21m_30degcut/HallC_beamtest_bggen_LD2_pip_18deg_filenum52290_21m_shielding_30degcut_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_20deg_LD2_21m_30x30x5cm3/HallC_beamtest_eAll_LD2_20deg_filenum1401_1.401e8_10.6GeV_reduce_tree_rate_gem1_Etotalcut_Q210MeV.root");
	TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3/HallC_beamtest_eAll_LD2_18deg_filenum9992_9.992e8_10.6GeV_shielding_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_20deg_LD2_21m_shielding/HallC_beamtest_eAll_LD2_20deg_filenum1994_1.995e7_10.6GeV_shielding_reduce_tree_rate_gem1_Etotalcut_debug.root");
	//TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_20deg_LD_21m/HallC_beamtest_bggen_LD2_pi0_20deg_filenum33520_21m_shielding_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_18deg_LD_21m_30degcut/HallC_beamtest_bggen_LD2_pi0_18deg_filenum25480_21m_shielding_30degcut_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding/HallC_beamtest_BeamOnTarget_1.9918e9_60uA_4SCs_20deg_r20m_LD2_shielding_reduce_tree_rate_gem1_Etotalcut_40uA.root");
	//TFile *f28 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30x5cm3/HallC_beamtest_BeamOnTarget_9.909e8_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x5cm3_reduce_tree_rate_preshower_Etotalcut_electron_40uA.root");
//	TFile *f38 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30x5cm3/HallC_beamtest_BeamOnTarget_9.909e8_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x5cm3_reduce_tree_rate_preshower_Etotalcut_gamma_40uA.root");
	//TFile *f28 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_18deg_LD2_r20m_shielding_30x30x2.54cm3/");
	TFile *f28 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30cm2_1inch/HallC_beamtest_BeamOnTarget_1.9885e9_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x2.54cm3_reduce_tree_rate_preshower_Etotalcut_electroni_40uA.root");
	//TFile *f38 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30cm2_1inch/HallC_beamtest_BeamOnTarget_1.9885e9_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x2.54cm3_reduce_tree_rate_preshower_Etotalcut_gamma_40uA.root");
	//TFile *f38 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_20deg_LD_21m_30degcut/HallC_beamtest_bggen_LD2_pi0_20deg_filenum25470_21m_shielding_30degcut_reduce_tree_rate_preshower_Etotalcut_positron.root");
	TFile *f38 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_18deg_LD_21m_30degcut/HallC_beamtest_bggen_LD2_pi0_18deg_filenum25480_21m_shielding_30degcut_reduce_tree_rate_preshower_Etotalcut_positron.root");
	//TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7degsurvey_r20m_carbon_even_gamma_400MeV/HallC_beamtest_BeamOnTarget_1e6_7degsurvey_5uA_4SC_r20m_cfoil_even_gamma_400MeV_reduce_tree_rate_gem1_Etotalcut.root");
	TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_18deg_LD2_r20m_shielding_30x30x2.54cm3/HallC_beamtest_BeamOnTarget_3.5934e9_60uA_4SCs_18deg_r20m_LD2_shielding_30x30x2.54cm3_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_20deg_LD_21m/HallC_beamtest_bggen_LD2_pim_20deg_filenum19430_21m_shielding_reduce_tree_rate_preshower_Etotalcut_40uA_tid1.root");
	TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_18deg_LD_21m_30degcut/HallC_beamtest_bggen_LD2_pim_18deg_filenum26270_21m_shielding_30degcut_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m/HallC_beamtest_BeamOnTarget_9.976e8_60uA_4SCs_20deg_r20m_LD2_wronggem1_reduce_tree_rate_gem1_Etotalcut_debug.root");
	//TFile *f29 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30x1cm3/HallC_beamtest_BeamOnTarget_1.9919e9_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x1cm3_reduce_tree_rate_gem1_Etotalcut_40uA.root");
	TFile *f29 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_18deg_LD2_r20m_shielding_30x30x2.54cm3/HallC_beamtest_BeamOnTarget_1.9972e9_60uA_4SCs_18deg_r20m_LD2_shielding_30x30x2.54cm3_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
        //change
	TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30x5cm3/HallC_beamtest_BeamOnTarget_9.909e8_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x5cm3_reduce_tree_rate_gem1_Etotalcut_40uA.root");
	//TFile *f50 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30cm2_1inch/HallC_beamtest_BeamOnTarget_1.9885e9_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x2.54cm3_reduce_tree_rate_gem1_Etotalcut_40uA.root");
	//TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30cm2_1inch/HallC_beamtest_BeamOnTarget_4.861e8_60uA_4SCs_20deg_r20m_LD2_shielding_30x30cm2_1inch_reduce_tree_rate_gem1_Etotalcut_debug.root");
	TFile *f14 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m_30x30x2.5cm3/HallC_beamtest_eAll_LD2_18deg_filenum9992_9.992e8_10.6GeV_shielding_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f50 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_18deg_LD2_20m/HallC_beamtest_eAll_LD2_18deg_filenum9953_9.953e8_10.6GeV_shielding_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TTree *tree_beam = (TTree*) f8->Get("T");
	TTree *tree_beam_18 = (TTree*) f50->Get("T");
	TTree *tree_beam_old = (TTree*) f28->Get("T");
	TTree *tree_beam_5cm = (TTree*) f29->Get("T");
	TTree *tree_beam_1in = (TTree*) f14->Get("T");
	TTree *tree_beam_r = (TTree*) f38->Get("T");
	TTree *tree_beam_gamma = (TTree*) f18->Get("T");
	TTree *tree_beam_e = (TTree*) f14->Get("T");
	TTree *tree_SC1_electron = (TTree*) f2->Get("T");
	TTree *tree_SC1_e = (TTree*) f3->Get("T");
	TTree *tree_SC1_gamma = (TTree*) f4->Get("T"); //abs(phicut) <5 deg
	const int rebinfac=5;
	const int rebinfac1=1;
        tree_SC1_e->Draw("SC_A_Eendsum>>SC0_e(500,0,50)","rate*(SC_A_Eendsum>0.99 )","goff");
	TH1F *SC0_e_hist = (TH1F*)gROOT->FindObject("SC0_e");
        tree_SC1_electron->Draw("SC_A_Eendsum>>SC0_electron(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_electron_hist = (TH1F*)gROOT->FindObject("SC0_electron");
        tree_SC1_gamma->Draw("SC_A_Eendsum>>SC0_gamma(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_gamma_hist = (TH1F*)gROOT->FindObject("SC0_gamma");
        tree_beam->Draw("SC_A_Eendsum>>SC0_beam(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_beam_hist = (TH1F*)gROOT->FindObject("SC0_beam");
        tree_beam_gamma->Draw("SC_A_Eendsum>>SC0_beam_gamma(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_beam_gamma_hist = (TH1F*)gROOT->FindObject("SC0_beam_gamma");
        tree_beam_e->Draw("SC_A_Eendsum>>SC0_beam_e(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_beam_e_hist = (TH1F*)gROOT->FindObject("SC0_beam_e");
        tree_beam_5cm->Draw("SC_A_Eendsum>>SC0_beam_5cm(500,0,50)","rate*(SC_A_Eendsum>0.99)","goff");
	TH1F *SC0_beam_5cm_hist = (TH1F*)gROOT->FindObject("SC0_beam_5cm");

        tree_SC1_e->Draw("SC_D_Eendsum>>SC1_e(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_e_hist = (TH1F*)gROOT->FindObject("SC1_e");
        tree_SC1_electron->Draw("SC_D_Eendsum>>SC1_electron(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_electron_hist = (TH1F*)gROOT->FindObject("SC1_electron");
        tree_SC1_gamma->Draw("SC_D_Eendsum>>SC1_gamma(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_gamma_hist = (TH1F*)gROOT->FindObject("SC1_gamma");
        tree_beam->Draw("SC_D_Eendsum>>SC1_beam(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_beam_hist = (TH1F*)gROOT->FindObject("SC1_beam");
        tree_beam_gamma->Draw("SC_D_Eendsum>>SC1_beam_gamma(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_beam_gamma_hist = (TH1F*)gROOT->FindObject("SC1_beam_gamma");
        tree_beam_e->Draw("SC_D_Eendsum>>SC1_beam_e(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_beam_e_hist = (TH1F*)gROOT->FindObject("SC1_beam_e");
        tree_beam_5cm->Draw("SC_D_Eendsum>>SC1_beam_5cm(500,0,50)","rate*(SC_D_Eendsum>1.75)","goff");
	TH1F *SC1_beam_5cm_hist = (TH1F*)gROOT->FindObject("SC1_beam_5cm");
        tree_SC1_e->Draw("SC_C_Eendsum>>SC2_e(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_e_hist = (TH1F*)gROOT->FindObject("SC2_e");
        tree_SC1_electron->Draw("SC_C_Eendsum>>SC2_electron(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_electron_hist = (TH1F*)gROOT->FindObject("SC2_electron");
        tree_SC1_gamma->Draw("SC_C_Eendsum>>SC2_gamma(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_gamma_hist = (TH1F*)gROOT->FindObject("SC2_gamma");
        tree_beam->Draw("SC_C_Eendsum>>SC2_beam(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_beam_hist = (TH1F*)gROOT->FindObject("SC2_beam");
        tree_beam_gamma->Draw("SC_C_Eendsum>>SC2_beam_gamma(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_beam_gamma_hist = (TH1F*)gROOT->FindObject("SC2_beam_gamma");
        tree_beam_e->Draw("SC_C_Eendsum>>SC2_beam_e(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_beam_e_hist = (TH1F*)gROOT->FindObject("SC2_beam_e");
        tree_beam_5cm->Draw("SC_C_Eendsum>>SC2_beam_5cm(500,0,50)","rate*(SC_C_Eendsum>1.75)","goff");
	TH1F *SC2_beam_5cm_hist = (TH1F*)gROOT->FindObject("SC2_beam_5cm");

        tree_SC1_e->Draw("SC_B_Eendsum>>SC3_e(100,0,10)","rate*(SC_B_Eendsum>0.99 )","goff");
	TH1F *SC3_e_hist = (TH1F*)gROOT->FindObject("SC3_e");
        tree_SC1_electron->Draw("SC_B_Eendsum>>SC3_electron(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_electron_hist = (TH1F*)gROOT->FindObject("SC3_electron");
        tree_SC1_gamma->Draw("SC_B_Eendsum>>SC3_gamma(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_gamma_hist = (TH1F*)gROOT->FindObject("SC3_gamma");
        tree_beam->Draw("SC_B_Eendsum>>SC3_beam(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_beam_hist = (TH1F*)gROOT->FindObject("SC3_beam");
        tree_beam_gamma->Draw("SC_B_Eendsum>>SC3_beam_gamma(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_beam_gamma_hist = (TH1F*)gROOT->FindObject("SC3_beam_gamma");
        tree_beam_e->Draw("SC_B_Eendsum>>SC3_beam_e(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_beam_e_hist = (TH1F*)gROOT->FindObject("SC3_beam_e");
        tree_beam_5cm->Draw("SC_B_Eendsum>>SC3_beam_5cm(100,0,10)","rate*(SC_B_Eendsum>0.99)","goff");
	TH1F *SC3_beam_5cm_hist = (TH1F*)gROOT->FindObject("SC3_beam_5cm");

        /*tree_SC1_e->Draw("SC_B_Eendsum>>SC3_e(100,0,10)","rate*(SC_B_Eendsum>0.99 && ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_e_hist = (TH1F*)gROOT->FindObject("SC3_e");
        tree_SC1_electron->Draw("SC_B_Eendsum>>SC3_electron(100,0,10)","rate*(SC_B_Eendsum>0.99&& ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_electron_hist = (TH1F*)gROOT->FindObject("SC3_electron");
        tree_SC1_gamma->Draw("SC_B_Eendsum>>SC3_gamma(100,0,10)","rate*(SC_B_Eendsum>0.99&& ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_gamma_hist = (TH1F*)gROOT->FindObject("SC3_gamma");
        tree_beam->Draw("SC_B_Eendsum>>SC3_beam(100,0,10)","rate*(SC_B_Eendsum>0.99&& ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_beam_hist = (TH1F*)gROOT->FindObject("SC3_beam");
        tree_beam_gamma->Draw("SC_B_Eendsum>>SC3_beam_gamma(100,0,10)","rate*(SC_B_Eendsum>0.99&& ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_beam_gamma_hist = (TH1F*)gROOT->FindObject("SC3_beam_gamma");
        tree_beam_e->Draw("SC_B_Eendsum>>SC3_beam_e(100,0,10)","rate*(SC_B_Eendsum>0.99&& ShowerSum>20 && SC_D_Eendsum>1.75)","goff");
	TH1F *SC3_beam_e_hist = (TH1F*)gROOT->FindObject("SC3_beam_e");*/
        tree_SC1_e->Draw("LASPD_Eendsum>>LASPD_e(400,0,200)","rate*(LASPD_Eendsum>1.75 )","goff");
	TH1F *LASPD_e_hist = (TH1F*)gROOT->FindObject("LASPD_e");
        tree_SC1_electron->Draw("LASPD_Eendsum>>LASPD_electron(400,0,200)","rate*(LASPD_Eendsum>1.75)","goff");
	TH1F *LASPD_electron_hist = (TH1F*)gROOT->FindObject("LASPD_electron");
        tree_SC1_gamma->Draw("LASPD_Eendsum>>LASPD_gamma(400,0,200)","rate*(LASPD_Eendsum>1.75)","goff");
	TH1F *LASPD_gamma_hist = (TH1F*)gROOT->FindObject("LASPD_gamma");
        tree_beam->Draw("LASPD_Eendsum>>LASPD_beam(400,0,200)","rate*(LASPD_Eendsum>1.75)","goff");
	TH1F *LASPD_beam_hist = (TH1F*)gROOT->FindObject("LASPD_beam");
        tree_beam_gamma->Draw("LASPD_Eendsum>>LASPD_beam_gamma(400,0,200)","rate*(LASPD_Eendsum>1.75)","goff");
	TH1F *LASPD_beam_gamma_hist = (TH1F*)gROOT->FindObject("LASPD_beam_gamma");
        tree_beam_e->Draw("LASPD_Eendsum>>LASPD_beam_e(400,0,200)","rate*(LASPD_Eendsum>1.75)","goffnfac1");
	TH1F *LASPD_beam_e_hist = (TH1F*)gROOT->FindObject("LASPD_beam_e");
        tree_beam_5cm->Draw("LASPD_Eendsum>>LASPD_beam_5cm(400,0,200)","rate*(LASPD_Eendsum>1.75)","goff");
	TH1F *LASPD_beam_5cm_hist = (TH1F*)gROOT->FindObject("LASPD_beam_5cm");

        tree_SC1_e->Draw("Npesum>>CC_e(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_e_hist = (TH1F*)gROOT->FindObject("CC_e");
        tree_SC1_electron->Draw("Npesum>>CC_electron(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_electron_hist = (TH1F*)gROOT->FindObject("CC_electron");
        tree_SC1_gamma->Draw("Npesum>>CC_gamma(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_gamma_hist = (TH1F*)gROOT->FindObject("CC_gamma");
        tree_beam->Draw("Npesum>>CC_beam(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_beam_hist = (TH1F*)gROOT->FindObject("CC_beam");
        tree_beam_gamma->Draw("Npesum>>CC_beam_gamma(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_beam_gamma_hist = (TH1F*)gROOT->FindObject("CC_beam_gamma");
        tree_beam_e->Draw("Npesum>>CC_beam_e(90,0,90)","rate*(Npesum>0)","goffnfac1");
	TH1F *CC_beam_e_hist = (TH1F*)gROOT->FindObject("CC_beam_e");
        tree_beam_5cm->Draw("Npesum>>CC_beam_5cm(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_beam_5cm_hist = (TH1F*)gROOT->FindObject("CC_beam_5cm");
        tree_beam_1in->Draw("Npesum>>CC_beam_1in(90,0,90)","rate*(Npesum>0)","goff");
	TH1F *CC_beam_1in_hist = (TH1F*)gROOT->FindObject("CC_beam_1in");

        tree_SC1_e->Draw("PreShSum>>preshower_e(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_e_hist = (TH1F*)gROOT->FindObject("preshower_e");
        tree_SC1_electron->Draw("PreShSum>>preshower_electron(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_electron_hist = (TH1F*)gROOT->FindObject("preshower_electron");
        tree_SC1_gamma->Draw("PreShSum>>preshower_gamma(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_gamma_hist = (TH1F*)gROOT->FindObject("preshower_gamma");
        tree_beam->Draw("PreShSum>>preshower_beam(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_beam_hist = (TH1F*)gROOT->FindObject("preshower_beam");
        tree_beam_gamma->Draw("PreShSum>>preshower_beam_gamma(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_beam_gamma_hist = (TH1F*)gROOT->FindObject("preshower_beam_gamma");
        tree_beam_e->Draw("PreShSum>>preshower_beam_e(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_beam_e_hist = (TH1F*)gROOT->FindObject("preshower_beam_e");
        tree_beam_5cm->Draw("PreShSum>>preshower_beam_5cm(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_beam_5cm_hist = (TH1F*)gROOT->FindObject("preshower_beam_5cm");
        tree_beam_18->Draw("PreShSum>>preshower_beam_18(800,0,400)","rate*(PreShSum>1.75)","goff");
	TH1F *preshower_beam_18_hist = (TH1F*)gROOT->FindObject("preshower_beam_18");
       
        tree_SC1_e->Draw("ShowerSum>>shower_e(1000,0,1000)","rate*(ShowerSum>70 )","goff");
	TH1F *shower_e_hist = (TH1F*)gROOT->FindObject("shower_e");
        tree_SC1_electron->Draw("ShowerSum>>shower_electron(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_electron_hist = (TH1F*)gROOT->FindObject("shower_electron");
        tree_SC1_gamma->Draw("ShowerSum>>shower_gamma(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_gamma_hist = (TH1F*)gROOT->FindObject("shower_gamma");
        tree_beam->Draw("ShowerSum>>shower_beam(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_hist = (TH1F*)gROOT->FindObject("shower_beam");
        tree_beam_gamma->Draw("ShowerSum>>shower_beam_gamma(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_gamma_hist = (TH1F*)gROOT->FindObject("shower_beam_gamma");
        tree_beam_e->Draw("ShowerSum>>shower_beam_e(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_e_hist = (TH1F*)gROOT->FindObject("shower_beam_e");
        tree_beam_old->Draw("ShowerSum>>shower_beam_old(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_old_hist = (TH1F*)gROOT->FindObject("shower_beam_old");
        tree_beam_r->Draw("ShowerSum>>shower_beam_r(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_r_hist = (TH1F*)gROOT->FindObject("shower_beam_r");
        tree_beam_5cm->Draw("ShowerSum>>shower_beam_5cm(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_5cm_hist = (TH1F*)gROOT->FindObject("shower_beam_5cm");
        tree_beam_18->Draw("ShowerSum>>shower_beam_18(1000,0,1000)","rate*(ShowerSum>70)","goff");
	TH1F *shower_beam_18_hist = (TH1F*)gROOT->FindObject("shower_beam_18");

        tree_beam->Draw("ShowerSum:SC_B_Eendsum>>shower_vs_SC3(20,0,10,1000,0,1000)","rate","goff");
	TH2F *ShowerSum_vs_SC3_hist = (TH2F*)gROOT->FindObject("shower_vs_SC3");
        tree_SC1_e->Draw("ShowerSum:SC_B_Eendsum>>shower_vs_SC3_400(20,0,10,1000,0,1000)","rate","goff");
	TH2F *ShowerSum_vs_SC3_400_hist = (TH2F*)gROOT->FindObject("shower_vs_SC3_400");


        tree_beam->Draw("(7.105*ShowerSum+6.5*PreShSum)/PreShP:PreShP>>Etotal_vs_p_electron(110,0,11000,20,0,2.0)","rate*(ShowerSum>0&&PreShSum>0)","goff");
	TH2F *Etotal_vs_p_electron_hist = (TH2F*)gROOT->FindObject("Etotal_vs_p_electron");
        tree_SC1_e->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_e(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_e_hist = (TH1F*)gROOT->FindObject("E_e");
        tree_SC1_electron->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_electron(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_electron_hist = (TH1F*)gROOT->FindObject("E_electron");
        tree_SC1_gamma->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_gamma(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_gamma_hist = (TH1F*)gROOT->FindObject("E_gamma");
        tree_SC1_e->Draw("(7.105*ShowerSum+6.5*PreShSum)/PreShP:PreShP>>Etotal_vs_p_gamma(110,0,11000,20,0,2.0)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH2F *Etotal_vs_p_gamma_hist = (TH2F*)gROOT->FindObject("Etotal_vs_p_gamma");
        tree_beam->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_beam(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_beam_hist = (TH1F*)gROOT->FindObject("E_beam");
        tree_beam_gamma->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_beam_gamma(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_beam_gamma_hist = (TH1F*)gROOT->FindObject("E_beam_gamma");
        tree_beam_e->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_beam_e(900,0,900)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_beam_e_hist = (TH1F*)gROOT->FindObject("E_beam_e");



      /*  tree_pip->Draw("Npesum>>Npesum_pip(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pip_hist = (TH1F*)gROOT->FindObject("Npesum_pip");
        tree_pim->Draw("Npesum>>Npesum_pim(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_pi0->Draw("Npesum>>Npesum_pi0(100,0,100)","rate*( ShowerSum>0)","goff");
	TH1F *Npesum_pi0_hist = (TH1F*)gROOT->FindObject("Npesum_pi0");
        tree_eAll->Draw("Npesum>>Npesum_eAll(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_eAll_hist = (TH1F*)gROOT->FindObject("Npesum_eAll");
        tree_beam->Draw("Npesum>>Npesum_beam(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_beam_hist = (TH1F*)gROOT->FindObject("Npesum_beam");*/
        tree_SC1_electron->Draw("GEM00_x>>GEM00_pip(320,-8,8)","rate*(GEM00_Edep>35e-6 )","goff");
	TH1F *GEM00_pip_hist = (TH1F*)gROOT->FindObject("GEM00_pip");
        tree_beam_gamma->Draw("GEM00_x>>GEM00_pim(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_pim_hist = (TH1F*)gROOT->FindObject("GEM00_pim");
        tree_SC1_gamma->Draw("GEM00_x>>GEM00_pi0(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_pi0_hist = (TH1F*)gROOT->FindObject("GEM00_pi0");
        tree_SC1_e->Draw("GEM00_x>>GEM00_eAll(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_eAll_hist = (TH1F*)gROOT->FindObject("GEM00_eAll");
        tree_beam->Draw("GEM00_x>>GEM00_beam(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_hist = (TH1F*)gROOT->FindObject("GEM00_beam");
        tree_beam_e->Draw("GEM00_x>>GEM00_beam_e(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_e_hist = (TH1F*)gROOT->FindObject("GEM00_beam_e");
        tree_beam_5cm->Draw("GEM00_x>>GEM00_beam_5cm(320,-8,8)","rate*(GEM00_Edep>35e-6)","goff");
	TH1F *GEM00_beam_5cm_hist = (TH1F*)gROOT->FindObject("GEM00_beam_5cm");
        /*tree_pip->Draw("ShowerSum>>shower_pip(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_pip_hist = (TH1F*)gROOT->FindObject("shower_pip");
        tree_pim->Draw("ShowerSum>>shower_pim(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_pim_hist = (TH1F*)gROOT->FindObject("shower_pim");
        tree_pi0->Draw("ShowerSum>>shower_pi0(4000,0,2000)","rate*( ShowerSum>4)","goff");
	TH1F *shower_pi0_hist = (TH1F*)gROOT->FindObject("shower_pi0");
        tree_eAll->Draw("ShowerSum>>shower_eAll(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_eAll_hist = (TH1F*)gROOT->FindObject("shower_eAll");
        tree_beam->Draw("ShowerSum>>shower_beam(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_beam_hist = (TH1F*)gROOT->FindObject("shower_beam");
        tree_pip->Draw("Npesum>>Npesum_pip(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_pip_hist = (TH1F*)gROOT->FindObject("Npesum_pip");
        tree_pim->Draw("Npesum>>Npesum_pim(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_pi0->Draw("Npesum>>Npesum_pi0(200,0,100)","rate*( ShowerSum>4)","goff");
	TH1F *Npesum_pi0_hist = (TH1F*)gROOT->FindObject("Npesum_pi0");
        tree_eAll->Draw("Npesum>>Npesum_eAll(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_eAll_hist = (TH1F*)gROOT->FindObject("Npesum_eAll");
        tree_beam->Draw("Npesum>>Npesum_beam(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_beam_hist = (TH1F*)gROOT->FindObject("Npesum_beam");*/
        tree_SC1_electron->Draw("GEM10_x>>GEM10_pip(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pip_hist = (TH1F*)gROOT->FindObject("GEM10_pip");
        tree_beam_gamma->Draw("GEM10_x>>GEM10_pim(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pim_hist = (TH1F*)gROOT->FindObject("GEM10_pim");
        tree_SC1_gamma->Draw("GEM10_x>>GEM10_pi0(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_pi0_hist = (TH1F*)gROOT->FindObject("GEM10_pi0");
        tree_SC1_e->Draw("GEM10_x>>GEM10_eAll(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_eAll_hist = (TH1F*)gROOT->FindObject("GEM10_eAll");
        tree_beam->Draw("GEM10_x>>GEM10_beam(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_hist = (TH1F*)gROOT->FindObject("GEM10_beam");
        tree_beam_e->Draw("GEM10_x>>GEM10_beam_e(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_e_hist = (TH1F*)gROOT->FindObject("GEM10_beam_e");
        tree_beam_5cm->Draw("GEM10_x>>GEM10_beam_5cm(320,-8,8)","rate*(GEM10_Edep>35e-6)","goff");
	TH1F *GEM10_beam_5cm_hist = (TH1F*)gROOT->FindObject("GEM10_beam_5cm");
        TCanvas *c[10];
	c[0] = new TCanvas("c[0]","c[0]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC0_beam_hist->SetLineColor(6);
        SC0_beam_hist->GetXaxis()->SetTitle("SC_A Edep (MeV)");
        SC0_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        SC0_beam_hist->Scale(0.001);
        SC0_beam_hist->Rebin(rebinfac);
        SC0_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e6);
        SC0_beam_hist->Draw("HISt");
        double rate_proton= SC0_beam_hist->Integral()/1e0;
        SC0_e_hist->SetLineColor(2);
        SC0_e_hist->Scale(0.000667);
        SC0_e_hist->Rebin(rebinfac);
        SC0_e_hist->Draw("same HIST");
        double rate_e= SC0_e_hist->Integral()/1e0;
        SC0_electron_hist->SetLineColor(1);
        SC0_electron_hist->Scale(0.000667);
        SC0_electron_hist->Rebin(rebinfac);
        SC0_electron_hist->Draw("same HIST");
        double rate_electron= SC0_electron_hist->Integral()/1e0;
        SC0_gamma_hist->SetLineColor(8);
        SC0_gamma_hist->Scale(0.000667);
        SC0_gamma_hist->Rebin(rebinfac);
        SC0_gamma_hist->Draw("same HIST");
        double rate_gamma= SC0_gamma_hist->Integral()/1e0;
        SC0_beam_gamma_hist->SetLineColor(4);
        SC0_beam_gamma_hist->Scale(0.000667);
        SC0_beam_gamma_hist->Rebin(rebinfac);
        SC0_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma= SC0_beam_gamma_hist->Integral()/1e0;
        SC0_beam_e_hist->SetLineColor(kOrange-3);
        SC0_beam_e_hist->Scale(0.001);
        SC0_beam_e_hist->Rebin(rebinfac);
        SC0_beam_e_hist->Draw("same HIST");
        double rate_beam_e= SC0_beam_e_hist->Integral()/1e0;
        SC0_beam_5cm_hist->SetLineColor(7);
        SC0_beam_5cm_hist->Scale(0.001);
        SC0_beam_5cm_hist->Rebin(rebinfac);
       // SC0_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm= SC0_beam_5cm_hist->Integral()/1e0;
  TLegend *leg8 = new TLegend(0.15,0.7,0.5,0.88);
  leg8->AddEntry(SC0_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron),"l");
  leg8->AddEntry(SC0_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton),"l");
  //leg8->AddEntry(SC0_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_e),"l");
 // leg8->AddEntry(SC0_beam_5cm_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_5cm),"l");
  leg8->AddEntry(SC0_e_hist,Form("from eAll; total rate=%f kHz",rate_e),"l");
  leg8->AddEntry(SC0_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma),"l");
  leg8->AddEntry(SC0_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        CC_beam_hist->SetLineColor(6);
        CC_beam_hist->GetXaxis()->SetTitle("CC Npe ");
        CC_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        CC_beam_hist->Scale(0.001);
        //CC_beam_hist->Rebin(rebinfac);
        CC_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e6);
        CC_beam_hist->Draw("HISt");
        double rate_proton_CC= CC_beam_hist->Integral()/1e0;
        CC_e_hist->SetLineColor(2);
        CC_e_hist->Scale(0.000667);
       // CC_e_hist->Rebin(rebinfac);
        CC_e_hist->Draw("same HIST");
        double rate_e_CC= CC_e_hist->Integral()/1e0;
        CC_electron_hist->SetLineColor(1);
        CC_electron_hist->Scale(0.000667);
        //CC_electron_hist->Rebin(rebinfac);
        CC_electron_hist->Draw("same HIST");
        double rate_electron_CC= CC_electron_hist->Integral()/1e0;
        CC_gamma_hist->SetLineColor(8);
        CC_gamma_hist->Scale(0.000667);
       // CC_gamma_hist->Rebin(rebinfac);
        CC_gamma_hist->Draw("same HIST");
        double rate_gamma_CC= CC_gamma_hist->Integral()/1e0;
        CC_beam_gamma_hist->SetLineColor(4);
        CC_beam_gamma_hist->Scale(0.000667);
       // CC_beam_gamma_hist->Rebin(rebinfac);
        CC_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_CC= CC_beam_gamma_hist->Integral()/1e0;
        CC_beam_e_hist->SetLineColor(kOrange-3);
        CC_beam_e_hist->Scale(0.001);
        CC_beam_e_hist->Draw("same HIST");
        double rate_beam_e_CC= CC_beam_e_hist->Integral()/1e0;
        CC_beam_5cm_hist->SetLineColor(7);
        CC_beam_5cm_hist->Scale(0.001);
   //     CC_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_CC= CC_beam_5cm_hist->Integral()/1e0;
        CC_beam_1in_hist->SetLineColor(28);
        CC_beam_1in_hist->Scale(0.001);
     //   CC_beam_1in_hist->Draw("same HIST");
        double rate_beam_1in_CC= CC_beam_1in_hist->Integral()/1e0;
  TLegend *leg1 = new TLegend(0.13,0.7,0.5,0.89);
  leg1->AddEntry(CC_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_CC),"l");
  leg1->AddEntry(CC_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_CC),"l");
//  leg1->AddEntry(CC_beam_e_hist,Form("from 20 deg BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_e_CC),"l");
 // leg1->AddEntry(CC_beam_5cm_hist,Form("from 18 deg BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_5cm_CC),"l");
  //leg1->AddEntry(CC_beam_1in_hist,Form("from BeamOnTarget+30x30x2.54cm3 poly; total rate=%f kHz",rate_beam_1in_CC),"l");
  leg1->AddEntry(CC_e_hist,Form("from eAll; total rate=%f kHz",rate_e_CC),"l");
  leg1->AddEntry(CC_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_CC),"l");
  leg1->AddEntry(CC_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_CC),"l");
  leg1->SetTextSize(0.025);
  leg1->SetBorderSize(0);
  leg1->SetFillColor(0);
  leg1->Draw("text same");
	c[3] = new TCanvas("c[3]","c[3]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC1_beam_hist->SetLineColor(6);
        SC1_beam_hist->GetXaxis()->SetTitle("SC_D Edep (MeV)");
        SC1_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        SC1_beam_hist->Scale(0.001);
        SC1_beam_hist->Rebin(rebinfac);
        SC1_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e6);
        SC1_beam_hist->Draw("HISt");
        double rate_proton_SC1= SC1_beam_hist->Integral()/1e0;
        SC1_e_hist->SetLineColor(2);
        SC1_e_hist->Scale(0.000667);
        SC1_e_hist->Rebin(rebinfac);
        SC1_e_hist->Draw("same HIST");
        double rate_e_SC1= SC1_e_hist->Integral()/1e0;
        SC1_electron_hist->SetLineColor(1);
        SC1_electron_hist->Scale(0.000667);
        SC1_electron_hist->Rebin(rebinfac);
        SC1_electron_hist->Draw("same HIST");
        double rate_electron_SC1= SC1_electron_hist->Integral()/1e0;
        SC1_gamma_hist->SetLineColor(8);
        SC1_gamma_hist->Scale(0.000667);
        SC1_gamma_hist->Rebin(rebinfac);
        SC1_gamma_hist->Draw("same HIST");
        double rate_gamma_SC1= SC1_gamma_hist->Integral()/1e0;
        SC1_beam_gamma_hist->SetLineColor(4);
        SC1_beam_gamma_hist->Scale(0.000667);
        SC1_beam_gamma_hist->Rebin(rebinfac);
        SC1_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_SC1= SC1_beam_gamma_hist->Integral()/1e0;
        SC1_beam_e_hist->SetLineColor(kOrange-3);
        SC1_beam_e_hist->Scale(0.001);
        SC1_beam_e_hist->Rebin(rebinfac);
        //SC1_beam_e_hist->Draw("same HIST");
        double rate_beam_e_SC1= SC1_beam_e_hist->Integral()/1e0;
        SC1_beam_5cm_hist->SetLineColor(7);
        SC1_beam_5cm_hist->Scale(0.001);
        SC1_beam_5cm_hist->Rebin(rebinfac);
        //SC1_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_SC1= SC1_beam_5cm_hist->Integral()/1e0;
  TLegend *leg9 = new TLegend(0.15,0.7,0.5,0.88);
  leg9->AddEntry(SC1_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_SC1),"l");
  leg9->AddEntry(SC1_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_SC1),"l");
  //leg9->AddEntry(SC1_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_beam_e_SC1),"l");
  //leg9->AddEntry(SC1_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_beam_5cm_SC1),"l");
  leg9->AddEntry(SC1_e_hist,Form("from eAll; total rate=%f kHz",rate_e_SC1),"l");
  leg9->AddEntry(SC1_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_SC1),"l");
  leg9->AddEntry(SC1_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_SC1),"l");
  leg9->SetTextSize(0.03);
  leg9->SetBorderSize(0);
  leg9->SetFillColor(0);
  leg9->Draw("text same");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC2_beam_hist->SetLineColor(6);
        SC2_beam_hist->GetXaxis()->SetTitle("SC_C Edep (MeV)");
        SC2_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        SC2_beam_hist->Scale(0.001);
        SC2_beam_hist->Rebin(rebinfac);
        SC2_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e6);
        SC2_beam_hist->Draw("HISt");
        double rate_proton_SC2= SC2_beam_hist->Integral()/1e0;
        SC2_e_hist->SetLineColor(2);
        SC2_e_hist->Scale(0.000667);
        SC2_e_hist->Rebin(rebinfac);
        SC2_e_hist->Draw("same HIST");
        double rate_e_SC2= SC2_e_hist->Integral()/1e0;
        SC2_electron_hist->SetLineColor(1);
        SC2_electron_hist->Scale(0.000667);
        SC2_electron_hist->Rebin(rebinfac);
        SC2_electron_hist->Draw("same HIST");
        double rate_electron_SC2= SC2_electron_hist->Integral()/1e0;
        SC2_gamma_hist->SetLineColor(8);
        SC2_gamma_hist->Scale(0.000667);
        SC2_gamma_hist->Rebin(rebinfac);
        SC2_gamma_hist->Draw("same HIST");
        double rate_gamma_SC2= SC2_gamma_hist->Integral()/1e0;
        SC2_beam_gamma_hist->SetLineColor(4);
        SC2_beam_gamma_hist->Scale(0.000667);
        SC2_beam_gamma_hist->Rebin(rebinfac);
        SC2_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_SC2= SC2_beam_gamma_hist->Integral()/1e0;
        SC2_beam_e_hist->SetLineColor(kOrange-3);
        SC2_beam_e_hist->Scale(0.001);
        SC2_beam_e_hist->Rebin(rebinfac);
    //    SC2_beam_e_hist->Draw("same HIST");
        double rate_beam_e_SC2= SC2_beam_e_hist->Integral()/1e0;
        SC2_beam_5cm_hist->SetLineColor(7);
        SC2_beam_5cm_hist->Scale(0.001);
        SC2_beam_5cm_hist->Rebin(rebinfac);
     //   SC2_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_SC2= SC2_beam_5cm_hist->Integral()/1e0;
  TLegend *leg18 = new TLegend(0.15,0.7,0.5,0.88);
  leg18->AddEntry(SC2_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_SC2),"l");
  leg18->AddEntry(SC2_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_SC2),"l");
 // leg18->AddEntry(SC2_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3 shielding; total rate=%f kHz",rate_beam_e_SC2),"l");
  //leg18->AddEntry(SC2_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3 shielding; total rate=%f kHz",rate_beam_5cm_SC2),"l");
  leg18->AddEntry(SC2_e_hist,Form("from eAll; total rate=%f kHz",rate_e_SC2),"l");
  leg18->AddEntry(SC2_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_SC2),"l");
  leg18->AddEntry(SC2_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_SC2),"l");
  leg18->SetTextSize(0.03);
  leg18->SetBorderSize(0);
  leg18->SetFillColor(0);
  leg18->Draw("text same");
	c[4] = new TCanvas("c[4]","c[4]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        LASPD_beam_hist->SetLineColor(6);
        LASPD_beam_hist->GetXaxis()->SetTitle("LASPDsum Edep (MeV)");
        LASPD_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        LASPD_beam_hist->Scale(0.001);
        LASPD_beam_hist->Rebin(rebinfac);
        LASPD_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e6);
        LASPD_beam_hist->Draw("HISt");
        double rate_proton_LASPD= LASPD_beam_hist->Integral()/1e0;
        LASPD_e_hist->SetLineColor(2);
        LASPD_e_hist->Scale(0.000667);
        LASPD_e_hist->Rebin(rebinfac);
        LASPD_e_hist->Draw("same HIST");
        double rate_e_LASPD= LASPD_e_hist->Integral()/1e0;
        LASPD_electron_hist->SetLineColor(1);
        LASPD_electron_hist->Scale(0.000667);
        LASPD_electron_hist->Rebin(rebinfac);
        LASPD_electron_hist->Draw("same HIST");
        double rate_electron_LASPD= LASPD_electron_hist->Integral()/1e0;
        LASPD_gamma_hist->SetLineColor(8);
        LASPD_gamma_hist->Scale(0.000667);
        LASPD_gamma_hist->Rebin(rebinfac);
        LASPD_gamma_hist->Draw("same HIST");
        double rate_gamma_LASPD= LASPD_gamma_hist->Integral()/1e0;
        LASPD_beam_gamma_hist->SetLineColor(4);
        LASPD_beam_gamma_hist->Scale(0.000667);
        LASPD_beam_gamma_hist->Rebin(rebinfac);
        LASPD_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_LASPD= LASPD_beam_gamma_hist->Integral()/1e0;
        LASPD_beam_e_hist->SetLineColor(kOrange-3);
        LASPD_beam_e_hist->Scale(0.001);
        LASPD_beam_e_hist->Rebin(rebinfac);
     //   LASPD_beam_e_hist->Draw("same HIST");
        double rate_beam_e_LASPD= LASPD_beam_e_hist->Integral()/1e0;
        LASPD_beam_5cm_hist->SetLineColor(7);
        LASPD_beam_5cm_hist->Scale(0.001);
        LASPD_beam_5cm_hist->Rebin(rebinfac);
   //     LASPD_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_LASPD= LASPD_beam_5cm_hist->Integral()/1e0;
  TLegend *leg58 = new TLegend(0.15,0.7,0.5,0.88);
  leg58->AddEntry(LASPD_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_LASPD),"l");
  leg58->AddEntry(LASPD_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_LASPD),"l");
//  leg58->AddEntry(LASPD_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3 ploly; total rate=%f kHz",rate_beam_e_LASPD),"l");
 // leg58->AddEntry(LASPD_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3 ploly; total rate=%f kHz",rate_beam_5cm_LASPD),"l");
  leg58->AddEntry(LASPD_e_hist,Form("from eAll; total rate=%f kHz",rate_e_LASPD),"l");
  leg58->AddEntry(LASPD_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_LASPD),"l");
  leg58->AddEntry(LASPD_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_LASPD),"l");
  leg58->SetTextSize(0.03);
  leg58->SetBorderSize(0);
  leg58->SetFillColor(0);
  leg58->Draw("text same");
	c[5] = new TCanvas("c[5]","c[5]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        preshower_beam_hist->SetLineColor(6);
        preshower_beam_hist->GetXaxis()->SetTitle("preshowersum Edep (MeV)");
        preshower_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        preshower_beam_hist->Scale(0.001);
        preshower_beam_hist->Rebin(rebinfac);
        preshower_beam_hist->GetYaxis()->SetRangeUser(1e-10,5e6);
        preshower_beam_hist->Draw("HISt");
        double rate_proton_preshower= preshower_beam_hist->Integral()/1e0;
        preshower_e_hist->SetLineColor(2);
        preshower_e_hist->Scale(0.000667);
        preshower_e_hist->Rebin(rebinfac);
        preshower_e_hist->Draw("same HIST");
        double rate_e_preshower= preshower_e_hist->Integral()/1e0;
        preshower_electron_hist->SetLineColor(1);
        preshower_electron_hist->Scale(0.000667);
        preshower_electron_hist->Rebin(rebinfac);
        preshower_electron_hist->Draw("same HIST");
        double rate_electron_preshower= preshower_electron_hist->Integral()/1e0;
        preshower_gamma_hist->SetLineColor(8);
        preshower_gamma_hist->Scale(0.000667);
        preshower_gamma_hist->Rebin(rebinfac);
        preshower_gamma_hist->Draw("same HIST");
        double rate_gamma_preshower= preshower_gamma_hist->Integral()/1e0;
        preshower_beam_gamma_hist->SetLineColor(4);
        preshower_beam_gamma_hist->Scale(0.000667);
        preshower_beam_gamma_hist->Rebin(rebinfac);
        preshower_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_preshower= preshower_beam_gamma_hist->Integral()/1e0;
        preshower_beam_e_hist->SetLineColor(kOrange-3);
        preshower_beam_e_hist->Scale(0.001);
        preshower_beam_e_hist->Rebin(rebinfac);
   //     preshower_beam_e_hist->Draw("same HIST");
        double rate_beam_e_preshower= preshower_beam_e_hist->Integral()/1e0;
        preshower_beam_5cm_hist->SetLineColor(7);
        preshower_beam_5cm_hist->Scale(0.001);
        preshower_beam_5cm_hist->Rebin(rebinfac);
       // preshower_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_preshower= preshower_beam_5cm_hist->Integral()/1e0;
        preshower_beam_18_hist->SetLineColor(28);
        preshower_beam_18_hist->Scale(0.000667);
        preshower_beam_18_hist->Rebin(rebinfac);
      //  preshower_beam_18_hist->Draw("same HIST");
        double rate_beam_18_preshower= preshower_beam_18_hist->Integral()/1e0;
  TLegend *leg28 = new TLegend(0.15,0.7,0.5,0.88);
  leg28->AddEntry(preshower_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_preshower),"l");
  leg28->AddEntry(preshower_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_preshower),"l");
 // leg28->AddEntry(preshower_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3 ploly; total rate=%f kHz",rate_beam_e_preshower),"l");
 // leg28->AddEntry(preshower_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3 ploly; total rate=%f kHz",rate_beam_5cm_preshower),"l");
 // leg28->AddEntry(preshower_beam_18_hist,Form("from 18deg eAll; total rate=%f kHz",rate_beam_18_preshower),"l");
  leg28->AddEntry(preshower_e_hist,Form("from eAll; total rate=%f kHz",rate_e_preshower),"l");
  leg28->AddEntry(preshower_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_preshower),"l");
  leg28->AddEntry(preshower_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_preshower),"l");
  leg28->SetTextSize(0.03);
  leg28->SetBorderSize(0);
  leg28->SetFillColor(0);
  leg28->Draw("text same");
	c[6] = new TCanvas("c[6]","c[6]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        shower_beam_hist->SetLineColor(6);
        shower_beam_hist->GetXaxis()->SetTitle("shower Edep (MeV)");
        shower_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        shower_beam_hist->Scale(0.001);
        shower_beam_hist->Rebin(rebinfac);
        shower_beam_hist->GetYaxis()->SetRangeUser(1e-10,5e6);
        shower_beam_hist->Draw("HISt");
        double rate_proton_shower= shower_beam_hist->Integral()/1e0;
        shower_e_hist->SetLineColor(2);
        shower_e_hist->Scale(0.000667);
        shower_e_hist->Rebin(rebinfac);
        shower_e_hist->Draw("same HIST");
        double rate_e_shower= shower_e_hist->Integral()/1e0;
        shower_electron_hist->SetLineColor(1);
        shower_electron_hist->Scale(0.000667);
        shower_electron_hist->Rebin(rebinfac);
        shower_electron_hist->Draw("same HIST");
        double rate_electron_shower= shower_electron_hist->Integral()/1e0;
        shower_gamma_hist->SetLineColor(8);
        shower_gamma_hist->Scale(0.000667);
        shower_gamma_hist->Rebin(rebinfac);
        shower_gamma_hist->Draw("same HIST");
        double rate_gamma_shower= shower_gamma_hist->Integral()/1e0;
        shower_beam_gamma_hist->SetLineColor(4);
        shower_beam_gamma_hist->Scale(0.000667);
        shower_beam_gamma_hist->Rebin(rebinfac);
        shower_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_shower= shower_beam_gamma_hist->Integral()/1e0;
        shower_beam_e_hist->SetLineColor(kOrange-3);
        shower_beam_e_hist->Scale(0.001);
        shower_beam_e_hist->Rebin(rebinfac);
  //      shower_beam_e_hist->Draw("same HIST");
        double rate_beam_e_shower= shower_beam_e_hist->Integral()/1e0;
        shower_beam_old_hist->SetLineColor(7);
        shower_beam_old_hist->Scale(0.001);
        shower_beam_old_hist->Rebin(rebinfac);
        shower_beam_old_hist->Draw("same HIST");
        double rate_beam_old_shower= shower_beam_old_hist->Integral()/1e0;
        shower_beam_r_hist->SetLineColor(28);
        shower_beam_r_hist->Scale(0.000667);
        shower_beam_r_hist->Rebin(rebinfac);
        shower_beam_r_hist->Draw("same HIST");
        shower_beam_gamma_hist->Draw("same HIST");
        double rate_beam_r_shower= shower_beam_r_hist->Integral()/1e0;
        shower_beam_5cm_hist->SetLineColor(7);
        shower_beam_5cm_hist->Scale(0.001);
        shower_beam_5cm_hist->Rebin(rebinfac);
        //shower_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_shower= shower_beam_5cm_hist->Integral()/1e0;
        shower_beam_18_hist->SetLineColor(28);
        shower_beam_18_hist->Scale(0.000667);
        shower_beam_18_hist->Rebin(rebinfac);
       // shower_beam_18_hist->Draw("same HIST");
        double rate_beam_18_shower= shower_beam_18_hist->Integral()/1e0;
  TLegend *leg29 = new TLegend(0.13,0.7,0.4,0.88);
  leg29->AddEntry(shower_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_shower),"l");
  leg29->AddEntry(shower_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_shower),"l");
 leg29->AddEntry(shower_beam_old_hist,Form("e^{#pm} from BeamOnTarget+2.5cm poly; total rate=%f kHz",rate_beam_old_shower),"l");
 leg29->AddEntry(shower_beam_r_hist,Form("e^{+} from #pi^{0}; total rate=%f kHz",rate_beam_r_shower),"l");
//  leg29->AddEntry(shower_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_e_shower),"l");
//  leg29->AddEntry(shower_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_beam_5cm_shower),"l");
//  leg29->AddEntry(shower_beam_18_hist,Form("from 18deg eAll; total rate=%f kHz",rate_beam_18_shower),"l");
  leg29->AddEntry(shower_e_hist,Form("from eAll; total rate=%f kHz",rate_e_shower),"l");
  leg29->AddEntry(shower_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_shower),"l");
  leg29->AddEntry(shower_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_shower),"l");
  leg29->SetTextSize(0.03);
  leg29->SetBorderSize(0);
  leg29->SetFillColor(0);
  leg29->Draw("text same");
	/*c[6] = new TCanvas("c[6]","c[6]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        Etotal_beam_hist->SetLineColor(6);
        Etotal_beam_hist->GetXaxis()->SetTitle("Etotal Edep (MeV)");
        Etotal_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        Etotal_beam_hist->Rebin(rebinfac);
        Etotal_beam_hist->GetYaxis()->SetRangeUser(1e-5,1e5);
        Etotal_beam_hist->Draw("HISt");
        double rate_proton_Etotal= Etotal_beam_hist->Integral()/1e0;
        Etotal_e_hist->SetLineColor(2);
        Etotal_e_hist->Rebin(rebinfac);
        Etotal_e_hist->Draw("same HIST");
        double rate_e_Etotal= Etotal_e_hist->Integral()/1e0;
        Etotal_electron_hist->SetLineColor(1);
        Etotal_electron_hist->Rebin(rebinfac);
        Etotal_electron_hist->Draw("same HIST");
        double rate_electron_Etotal= Etotal_electron_hist->Integral()/1e0;
        Etotal_gamma_hist->SetLineColor(8);
        Etotal_gamma_hist->Rebin(rebinfac);
        Etotal_gamma_hist->Draw("same HIST");
        double rate_gamma_Etotal= Etotal_gamma_hist->Integral()/1e0;
        Etotal_beam_gamma_hist->SetLineColor(4);
        Etotal_beam_gamma_hist->Rebin(rebinfac);
        Etotal_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_Etotal= Etotal_beam_gamma_hist->Integral()/1e0;
        Etotal_beam_e_hist->SetLineColor(kOrange-3);
        Etotal_beam_e_hist->Rebin(rebinfac);
        Etotal_beam_e_hist->Draw("same HIST");
        double rate_beam_e_Etotal= Etotal_beam_e_hist->Integral()/1e0;
  TLegend *leg49 = new TLegend(0.5,0.5,0.88,0.88);
  leg49->AddEntry(Etotal_electron_hist,Form("from 400 MeV #gamma; #frac{all}{1e0}=%f ",rate_electron_Etotal),"l");
  leg49->AddEntry(Etotal_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e0}=%f ",rate_proton_Etotal),"l");
  leg49->AddEntry(Etotal_beam_e_hist,Form("e^{#pm} from 400 MeV #gamma; #frac{e^{#pm}}{1e0}=%f ",rate_beam_e_Etotal),"l");
  leg49->AddEntry(Etotal_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e0}=%f ",rate_e_Etotal),"l");
  leg49->AddEntry(Etotal_beam_gamma_hist,Form("#gamma from 400 MeV #gamma; #frac{#gamma}{1e0}=%f ",rate_beam_gamma_Etotal),"l");
  leg49->AddEntry(Etotal_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e0}=%f ",rate_gamma_Etotal),"l");
  leg49->SetTextSize(0.03);
  leg49->SetBorderSize(0);
  leg49->SetFillColor(0);
  leg49->Draw("text same");
	c[7] = new TCanvas("c[7]","c[7]",1000,1000);
        c[7]->Divide(1,2);
        c[7]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        Etotal_vs_p_electron_hist->GetXaxis()->SetTitle("p (MeV/c)");
        Etotal_vs_p_electron_hist->SetTitle("from BeamOnTarget");
        Etotal_vs_p_electron_hist->GetYaxis()->SetTitle("#frac{Etotal}{p} (MeV)");
        Etotal_vs_p_electron_hist->Draw("COLZ");
        c[7]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        Etotal_vs_p_gamma_hist->GetXaxis()->SetTitle("p (MeV/c)");
        Etotal_vs_p_gamma_hist->SetTitle("from eAll");
        Etotal_vs_p_gamma_hist->GetYaxis()->SetTitle("#frac{Etotal}{p} (MeV)");
        Etotal_vs_p_gamma_hist->Draw("COLZ");*/
	c[9] = new TCanvas("c[9]","c[9]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC3_beam_hist->SetLineColor(6);
        SC3_beam_hist->GetXaxis()->SetTitle("SC_B Edep (MeV)");
        SC3_beam_hist->GetYaxis()->SetTitle("Rate_kHz");
        SC3_beam_hist->Scale(0.001);
        SC3_beam_hist->Rebin(rebinfac1);
        SC3_beam_hist->GetYaxis()->SetRangeUser(1e-5,5e7);
        SC3_beam_hist->Draw("HISt");
        double rate_proton_SC3= SC3_beam_hist->Integral()/1e0;
        SC3_e_hist->SetLineColor(2);
        SC3_e_hist->Scale(0.000667);
        SC3_e_hist->Rebin(rebinfac1);
        SC3_e_hist->Draw("same HIST");
        double rate_e_SC3= SC3_e_hist->Integral()/1e0;
        SC3_electron_hist->SetLineColor(1);
        SC3_electron_hist->Scale(0.000667);
        SC3_electron_hist->Rebin(rebinfac1);
        SC3_electron_hist->Draw("same HIST");
        double rate_electron_SC3= SC3_electron_hist->Integral()/1e0;
        SC3_gamma_hist->SetLineColor(8);
        SC3_gamma_hist->Scale(0.000667);
        SC3_gamma_hist->Rebin(rebinfac1);
        SC3_gamma_hist->Draw("same HIST");
        double rate_gamma_SC3= SC3_gamma_hist->Integral()/1e0;
        SC3_beam_gamma_hist->SetLineColor(4);
        SC3_beam_gamma_hist->Scale(0.000667);
        SC3_beam_gamma_hist->Rebin(rebinfac1);
        SC3_beam_gamma_hist->Draw("same HIST");
        double rate_beam_gamma_SC3= SC3_beam_gamma_hist->Integral()/1e0;
        SC3_beam_e_hist->SetLineColor(kOrange-3);
        SC3_beam_e_hist->Scale(0.001);
        SC3_beam_e_hist->Rebin(rebinfac1);
       // SC3_beam_e_hist->Draw("same HIST");
        double rate_beam_e_SC3= SC3_beam_e_hist->Integral()/1e0;
        SC3_beam_5cm_hist->SetLineColor(7);
        SC3_beam_5cm_hist->Scale(0.001);
        SC3_beam_5cm_hist->Rebin(rebinfac1);
      //  SC3_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_SC3= SC3_beam_5cm_hist->Integral()/1e0;
  TLegend *leg19 = new TLegend(0.15,0.7,0.55,0.88);
  leg19->AddEntry(SC3_electron_hist,Form("from bggen #pi^{+}; total rate=%f kHz",rate_electron_SC3),"l");
  leg19->AddEntry(SC3_beam_hist,Form("from BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_proton_SC3),"l");
//  leg19->AddEntry(SC3_beam_e_hist,Form("from 20deg BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_beam_e_SC3),"l");
//  leg19->AddEntry(SC3_beam_5cm_hist,Form("from 18deg BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_beam_5cm_SC3),"l");
  leg19->AddEntry(SC3_e_hist,Form("from eAll; total rate=%f kHz",rate_e_SC3),"l");
  leg19->AddEntry(SC3_beam_gamma_hist,Form("from bggen #pi^{-}; total rate=%f kHz",rate_beam_gamma_SC3),"l");
  leg19->AddEntry(SC3_gamma_hist,Form("from bggen #pi^{0}; total rate=%f kHz",rate_gamma_SC3),"l");
  leg19->SetTextSize(0.03);
  leg19->SetBorderSize(0);
  leg19->SetFillColor(0);
  leg19->Draw("text same");
	c[7] = new TCanvas("c[7]","c[7]",1000,1000);
        /*c[7]->Divide(1,2);
        c[7]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        ShowerSum_vs_SC3_hist->GetXaxis()->SetTitle("SC_B Edep (MeV)");
        ShowerSum_vs_SC3_hist->SetTitle("from BeamOnTarget");
        ShowerSum_vs_SC3_hist->GetYaxis()->SetTitle("ShowerSum Edep (MeV)");
        ShowerSum_vs_SC3_hist->Draw("COLZ");
        c[7]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        ShowerSum_vs_SC3_400_hist->GetXaxis()->SetTitle("SC_B Edep (MeV)");
        ShowerSum_vs_SC3_400_hist->SetTitle("from eAll");
        ShowerSum_vs_SC3_400_hist->GetYaxis()->SetTitle("ShowerSum Edep (MeV)");
        ShowerSum_vs_SC3_400_hist->Draw("COLZ");*/
/*	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        Npesum_beam_hist->SetLineColor(6);
        Npesum_beam_hist->GetXaxis()->SetTitle("Npe");
        Npesum_beam_hist->GetYaxis()->SetTitle("Rate (kHz)");
        Npesum_beam_hist->Scale(0.001);
        Npesum_beam_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        Npesum_beam_hist->Draw("HIST");
        Npesum_pip_hist->SetLineColor(2);
        Npesum_pip_hist->Scale(0.001);
        Npesum_pip_hist->Draw("same HIST");
        Npesum_pim_hist->SetLineColor(1);
        Npesum_pim_hist->Scale(0.001);
        Npesum_pim_hist->Draw("same HIST");
        Npesum_pi0_hist->SetLineColor(8);
        Npesum_pi0_hist->Scale(0.001);
        Npesum_pi0_hist->Draw("same HIST");
        Npesum_eAll_hist->SetLineColor(4);
        Npesum_eAll_hist->Scale(0.001);
        Npesum_eAll_hist->Draw("same HIST");
  TLegend *leg7 = new TLegend(0.45,0.6,0.8,0.88);
  leg7->AddEntry(Npesum_eAll_hist,Form("from eAll"),"l");
  leg7->AddEntry(Npesum_pim_hist,Form("from bggen #pi^{-}"),"l");
  leg7->AddEntry(Npesum_pip_hist,Form("from bggen #pi^{+}"),"l");
  leg7->AddEntry(Npesum_pi0_hist,Form("from bggen #pi^{0}"),"l");
  leg7->AddEntry(Npesum_beam_hist,Form("from BeamOnTarget"),"l");
  leg7->SetTextSize(0.03);
  leg7->SetBorderSize(0);
  leg7->SetFillColor(0);
  leg7->Draw("text same");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);*/
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        GEM00_beam_hist->SetLineColor(6);
        GEM00_beam_hist->GetXaxis()->SetTitle("Npe");
        GEM00_beam_hist->GetYaxis()->SetTitle("Rate (kHz)");
        GEM00_beam_hist->Scale(0.001);
        GEM00_beam_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        GEM00_beam_hist->Draw("HIST");
        double rate_proton_gem= GEM00_beam_hist->Integral();
        GEM00_pip_hist->SetLineColor(2);
        GEM00_pip_hist->Scale(0.000667);
        GEM00_pip_hist->Draw("same HIST");
        double rate_pip_gem= GEM00_pip_hist->Integral();
        GEM00_pim_hist->SetLineColor(1);
        GEM00_pim_hist->Scale(0.000667);
        GEM00_pim_hist->Draw("same HIST");
        double rate_pim_gem= GEM00_pim_hist->Integral();
        GEM00_pi0_hist->SetLineColor(8);
        GEM00_pi0_hist->Scale(0.000667);
        GEM00_pi0_hist->Draw("same HIST");
        double rate_pi0_gem= GEM00_pi0_hist->Integral();
        GEM00_eAll_hist->SetLineColor(4);
        GEM00_eAll_hist->Scale(0.000667);
        GEM00_eAll_hist->Draw("same HIST");
        double rate_eAll_gem= GEM00_eAll_hist->Integral();
        GEM00_beam_e_hist->SetLineColor(kOrange-3);
        GEM00_beam_e_hist->Scale(0.001);
        //GEM00_beam_e_hist->Draw("same HIST");
        double rate_beam_e_gem= GEM00_beam_e_hist->Integral();
        GEM00_beam_5cm_hist->SetLineColor(7);
        GEM00_beam_5cm_hist->Scale(0.001);
       // GEM00_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_gem= GEM00_beam_5cm_hist->Integral()/1e0;
  TLegend *leg90 = new TLegend(0.15,0.6,0.6,0.88);
  leg90->AddEntry(GEM00_eAll_hist,Form("eAll; total rate=%f kHz",rate_eAll_gem),"l");
  leg90->AddEntry(GEM00_pim_hist,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_gem),"l");
  leg90->AddEntry(GEM00_pip_hist,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_gem),"l");
  leg90->AddEntry(GEM00_pi0_hist,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_gem),"l");
  leg90->AddEntry(GEM00_beam_hist,Form("BeamOnTarget+30x30x2.5cm3 poly; total rate=%f kHz",rate_proton_gem),"l");
  //leg90->AddEntry(GEM00_beam_e_hist,Form("20deg BeamOnTarget 30x30x2.5cm3; total rate=%f kHz",rate_beam_e_gem),"l");
  //leg90->AddEntry(GEM00_beam_5cm_hist,Form("18deg BeamOnTarget 30x30x2.5cm3; total rate=%f kHz",rate_beam_5cm_gem),"l");
  leg90->SetTextSize(0.03);
  leg90->SetBorderSize(0);
  leg90->SetFillColor(0);
  leg90->Draw("text same");
	c[8] = new TCanvas("c[8]","c[8]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        GEM10_beam_hist->SetLineColor(6);
        GEM10_beam_hist->GetXaxis()->SetTitle("Npe");
        GEM10_beam_hist->GetYaxis()->SetTitle("Rate (kHz)");
        GEM10_beam_hist->Scale(0.001);
        GEM10_beam_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        GEM10_beam_hist->Draw("HIST");
        double rate_proton_gem1= GEM10_beam_hist->Integral();
        GEM10_pip_hist->SetLineColor(2);
        GEM10_pip_hist->Scale(0.000667);
        GEM10_pip_hist->Draw("same HIST");
        double rate_pip_gem1= GEM10_pip_hist->Integral();
        GEM10_pim_hist->SetLineColor(1);
        GEM10_pim_hist->Scale(0.000667);
        GEM10_pim_hist->Draw("same HIST");
        double rate_pim_gem1= GEM10_pim_hist->Integral();
        GEM10_pi0_hist->SetLineColor(8);
        GEM10_pi0_hist->Scale(0.000667);
        GEM10_pi0_hist->Draw("same HIST");
        double rate_pi0_gem1= GEM10_pi0_hist->Integral();
        GEM10_eAll_hist->SetLineColor(4);
        GEM10_eAll_hist->Scale(0.000667);
        GEM10_eAll_hist->Draw("same HIST");
        double rate_eAll_gem1= GEM10_eAll_hist->Integral();
        GEM10_beam_e_hist->SetLineColor(kOrange-3);
        GEM10_beam_e_hist->Scale(0.001);
      //  GEM10_beam_e_hist->Draw("same HIST");
        double rate_beam_e_gem1= GEM10_beam_e_hist->Integral();
        GEM10_beam_5cm_hist->SetLineColor(7);
        GEM10_beam_5cm_hist->Scale(0.001);
      //  GEM10_beam_5cm_hist->Draw("same HIST");
        double rate_beam_5cm_gem1= GEM10_beam_5cm_hist->Integral()/1e0;
  TLegend *leg91 = new TLegend(0.15,0.6,0.6,0.88);
  leg91->AddEntry(GEM10_eAll_hist,Form("eAll; total rate=%f kHz",rate_eAll_gem1),"l");
  leg91->AddEntry(GEM10_pim_hist,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_gem1),"l");
  leg91->AddEntry(GEM10_pip_hist,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_gem1),"l");
  leg91->AddEntry(GEM10_pi0_hist,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_gem1),"l");
  leg91->AddEntry(GEM10_beam_hist,Form("BeamOnTarget+30x30x2.5cm3; total rate=%f kHz",rate_proton_gem1),"l");
 // leg91->AddEntry(GEM10_beam_e_hist,Form("BeamOnTarget 30x30x2.5cm3; total rate=%f kHz",rate_beam_e_gem1),"l");
 // leg91->AddEntry(GEM10_beam_5cm_hist,Form("18deg BeamOnTarget 30x30x2.5cm3; total rate=%f kHz",rate_beam_5cm_gem1),"l");
  leg91->SetTextSize(0.03);
  leg91->SetBorderSize(0);
  leg91->SetFillColor(0);
  leg91->Draw("text same");


	for(int a=0;a<10;a++){
		c[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_comparison_Edep_rate_20deg_21m_40uA.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
