
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_rate_sangle_newCh(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	//TFile *f1 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_2/HallC_beamtest_even_e_18deg_filenumber11_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f2 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_2/HallC_beamtest_even_gamma_18deg_filenum11_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f2 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_1GeV/HallC_beamtest_even_gamma_18deg_1GeV_filenum51_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f1 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_1GeV/HallC_beamtest_even_e_18deg_1GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_2GeV/HallC_beamtest_even_gamma_18deg_2GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f3 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_2GeV/HallC_beamtest_even_e_18deg_2GeV_filenum51_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_3GeV/HallC_beamtest_even_gamma_18deg_3GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f5 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_3GeV/HallC_beamtest_even_e_18deg_3GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_4GeV/HallC_beamtest_even_gamma_18deg_4GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_4GeV/HallC_beamtest_even_e_18deg_4GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_5GeV/HallC_beamtest_even_gamma_18deg_5GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_e_18deg_5GeV/HallC_beamtest_even_e_18deg_5GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q2100MeV.root");
	TFile *f11 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_1GeV/HallC_beamtest_even_pim_18deg_1GeV_filenum51_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	TFile *f12 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_2GeV/HallC_beamtest_even_pim_18deg_2GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_3GeV/HallC_beamtest_even_pim_18deg_3GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_4GeV/HallC_beamtest_even_pim_18deg_4GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_5GeV/HallC_beamtest_even_pim_18deg_5GeV_filenum50_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	TFile *f15 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_gamma_18deg_4.7_5.3/HallC_beamtest_even_gamma_18deg_5GeVsmear_filenum51_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");
	//TFile *f15 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_even_pion_18deg_4.7_5.3/HallC_beamtest_even_pion_18deg_5GeVsmear_filenum51_reduce_tree_rate_gem1_Etotalcut_40uA_Q210MeV.root");




	TTree *tree_e = (TTree*) f1->Get("T");
	TTree *tree_gamma = (TTree*) f2->Get("T");
	TTree *tree_pion = (TTree*) f11->Get("T");
	TTree *tree_e_2GeV = (TTree*) f3->Get("T");
	TTree *tree_gamma_2GeV = (TTree*) f4->Get("T");
	TTree *tree_pion_2GeV = (TTree*) f12->Get("T");
	TTree *tree_e_3GeV = (TTree*) f5->Get("T");
	TTree *tree_gamma_3GeV = (TTree*) f6->Get("T");
	TTree *tree_pion_3GeV = (TTree*) f13->Get("T");
	TTree *tree_e_4GeV = (TTree*) f7->Get("T");
	TTree *tree_gamma_4GeV = (TTree*) f8->Get("T");
	TTree *tree_pion_4GeV = (TTree*) f14->Get("T");
	TTree *tree_e_5GeV = (TTree*) f9->Get("T");
	TTree *tree_gamma_5GeV = (TTree*) f10->Get("T");
	TTree *tree_pion_5GeV = (TTree*) f15->Get("T");
	const int rebinfac=1;
        TCut pCut1 = "ShowerSum>450 && Shower_l/ShowerSum>0.85";
        tree_e->Draw("ShowerSum>>ShSum_e(1000,0,1000)","","goff");
	TH1F *ShowerSum_e_hist = (TH1F*)gROOT->FindObject("ShSum_e");
        tree_gamma->Draw("ShowerSum>>ShSum_gamma(1000,0,1000)","","goff");
	TH1F *ShowerSum_gamma_hist = (TH1F*)gROOT->FindObject("ShSum_gamma");
        tree_pion->Draw("ShowerSum>>ShSum_pion(1000,0,1000)","","goff");
	TH1F *ShowerSum_pion_hist = (TH1F*)gROOT->FindObject("ShSum_pion");
      
        tree_e_2GeV->Draw("ShowerSum>>ShSum_e_2GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_e_2GeV_hist = (TH1F*)gROOT->FindObject("ShSum_e_2GeV");
        tree_gamma_2GeV->Draw("ShowerSum>>ShSum_gamma_2GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_gamma_2GeV_hist = (TH1F*)gROOT->FindObject("ShSum_gamma_2GeV");
        tree_pion_2GeV->Draw("ShowerSum>>ShSum_pion_2GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_pion_2GeV_hist = (TH1F*)gROOT->FindObject("ShSum_pion_2GeV");
        tree_e_3GeV->Draw("ShowerSum>>ShSum_e_3GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_e_3GeV_hist = (TH1F*)gROOT->FindObject("ShSum_e_3GeV");
        tree_gamma_3GeV->Draw("ShowerSum>>ShSum_gamma_3GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_gamma_3GeV_hist = (TH1F*)gROOT->FindObject("ShSum_gamma_3GeV");
        tree_pion_3GeV->Draw("ShowerSum>>ShSum_pion_3GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_pion_3GeV_hist = (TH1F*)gROOT->FindObject("ShSum_pion_3GeV");
        tree_e_4GeV->Draw("ShowerSum>>ShSum_e_4GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_e_4GeV_hist = (TH1F*)gROOT->FindObject("ShSum_e_4GeV");
        tree_gamma_4GeV->Draw("ShowerSum>>ShSum_gamma_4GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_gamma_4GeV_hist = (TH1F*)gROOT->FindObject("ShSum_gamma_4GeV");
        tree_pion_4GeV->Draw("ShowerSum>>ShSum_pion_4GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_pion_4GeV_hist = (TH1F*)gROOT->FindObject("ShSum_pion_4GeV");
        tree_e_5GeV->Draw("ShowerSum>>ShSum_e_5GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_e_5GeV_hist = (TH1F*)gROOT->FindObject("ShSum_e_5GeV");
        tree_gamma_5GeV->Draw("ShowerSum>>ShSum_gamma_5GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_gamma_5GeV_hist = (TH1F*)gROOT->FindObject("ShSum_gamma_5GeV");
        tree_pion_5GeV->Draw("ShowerSum>>ShSum_pion_5GeV(1000,0,1000)","","goff");
	TH1F *ShowerSum_pion_5GeV_hist = (TH1F*)gROOT->FindObject("ShSum_pion_5GeV");
        
        tree_e_2GeV->Draw("Shower_l>>Shr_e(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerR_e_hist = (TH1F*)gROOT->FindObject("Shr_e");
        tree_gamma_2GeV->Draw("Shower_l>>Shr_gamma(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerR_gamma_hist = (TH1F*)gROOT->FindObject("Shr_gamma");
        tree_e->Draw("Shower_l>>Shl_e(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_e_hist = (TH1F*)gROOT->FindObject("Shl_e");
        tree_gamma->Draw("Shower_l>>Shl_gamma(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_gamma_hist = (TH1F*)gROOT->FindObject("Shl_gamma");
        tree_e_3GeV->Draw("Shower_l>>Sht_e(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerT_e_hist = (TH1F*)gROOT->FindObject("Sht_e");
        tree_gamma_3GeV->Draw("Shower_l>>Sht_gamma(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerT_gamma_hist = (TH1F*)gROOT->FindObject("Sht_gamma");
        tree_e_4GeV->Draw("Shower_l>>Shl_e_4GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_e_4GeV_hist = (TH1F*)gROOT->FindObject("Shl_e_4GeV");
        tree_gamma_4GeV->Draw("Shower_l>>Shl_gamma_4GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_gamma_4GeV_hist = (TH1F*)gROOT->FindObject("Shl_gamma_4GeV");
        tree_e_5GeV->Draw("Shower_l>>Shl_e_5GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_e_5GeV_hist = (TH1F*)gROOT->FindObject("Shl_e_5GeV");
        tree_gamma_5GeV->Draw("Shower_l>>Shl_gamma_5GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_gamma_5GeV_hist = (TH1F*)gROOT->FindObject("Shl_gamma_5GeV");
        tree_pion->Draw("Shower_l>>Shl_pion(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_pion_hist = (TH1F*)gROOT->FindObject("Shl_pion");
        tree_pion_2GeV->Draw("Shower_l>>Shl_pion_2GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_pion_2GeV_hist = (TH1F*)gROOT->FindObject("Shl_pion_2GeV");
        tree_pion_3GeV->Draw("Shower_l>>Shl_pion_3GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_pion_3GeV_hist = (TH1F*)gROOT->FindObject("Shl_pion_3GeV");
        tree_pion_4GeV->Draw("Shower_l>>Shl_pion_4GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_pion_4GeV_hist = (TH1F*)gROOT->FindObject("Shl_pion_4GeV");
        tree_pion_5GeV->Draw("Shower_l>>Shl_pion_5GeV(1000,0,1000)","Shower_l/ShowerSum>0.85","goff");
	TH1F *ShowerL_pion_5GeV_hist = (TH1F*)gROOT->FindObject("Shl_pion_5GeV");





        tree_e->Draw("PreShSum>>PreSum_e_cut(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_e_cut_hist = (TH1F*)gROOT->FindObject("PreSum_e_cut");
        tree_gamma->Draw("ShowerSum>>PreSum_gamma_cut(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_gamma_cut_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_cut");
        tree_e_2GeV->Draw("PreShSum>>PreSum_e_cut2GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_e_cut2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_cut2GeV");
        tree_gamma_2GeV->Draw("ShowerSum>>PreSum_gamma_cut2GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_gamma_cut2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_cut2GeV");
        tree_e_3GeV->Draw("PreShSum>>PreSum_e_cut3GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_e_cut3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_cut3GeV");
        tree_gamma_3GeV->Draw("ShowerSum>>PreSum_gamma_cut3GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_gamma_cut3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_cut3GeV");
        tree_e_4GeV->Draw("PreShSum>>PreSum_e_cut4GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_e_cut4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_cut4GeV");
        tree_gamma_4GeV->Draw("ShowerSum>>PreSum_gamma_cut4GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_gamma_cut4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_cut4GeV");
        tree_e_5GeV->Draw("PreShSum>>PreSum_e_cut5GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_e_cut5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_cut5GeV");
        tree_gamma_5GeV->Draw("ShowerSum>>PreSum_gamma_cut5GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_gamma_cut5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_cut5GeV");
        tree_pion->Draw("ShowerSum>>PreSum_pion_cut(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_pion_cut_hist = (TH1F*)gROOT->FindObject("PreSum_pion_cut");
        tree_pion_2GeV->Draw("ShowerSum>>PreSum_pion_cut2GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_pion_cut2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_cut2GeV");
        tree_pion_3GeV->Draw("ShowerSum>>PreSum_pion_cut3GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_pion_cut3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_cut3GeV");
        tree_pion_4GeV->Draw("ShowerSum>>PreSum_pion_cut4GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_pion_cut4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_cut4GeV");
        tree_pion_5GeV->Draw("ShowerSum>>PreSum_pion_cut5GeV(2000,0,200)",pCut1,"goff");
	TH1F *PreShSum_pion_cut5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_cut5GeV");




        TCanvas *c[10];
        tree_e->Draw("PreShSum>>PreSum_e(2000,0,200)","","goff");
	TH1F *PreShSum_e_hist = (TH1F*)gROOT->FindObject("PreSum_e");
        tree_gamma->Draw("PreShSum>>PreSum_gamma(2000,0,200)","","goff");
	TH1F *PreShSum_gamma_hist = (TH1F*)gROOT->FindObject("PreSum_gamma");

        tree_e_2GeV->Draw("PreShSum>>PreSum_e_2GeV(2000,0,200)","","goff");
	TH1F *PreShSum_e_2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_2GeV");
        tree_gamma_2GeV->Draw("PreShSum>>PreSum_gamma_2GeV(2000,0,200)","","goff");
	TH1F *PreShSum_gamma_2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_2GeV");
        tree_e_3GeV->Draw("PreShSum>>PreSum_e_3GeV(2000,0,200)","","goff");
	TH1F *PreShSum_e_3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_3GeV");
        tree_gamma_3GeV->Draw("PreShSum>>PreSum_gamma_3GeV(2000,0,200)","","goff");
	TH1F *PreShSum_gamma_3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_3GeV");
        tree_e_4GeV->Draw("PreShSum>>PreSum_e_4GeV(2000,0,200)","","goff");
	TH1F *PreShSum_e_4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_4GeV");
        tree_gamma_4GeV->Draw("PreShSum>>PreSum_gamma_4GeV(2000,0,200)","","goff");
	TH1F *PreShSum_gamma_4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_4GeV");
        tree_e_5GeV->Draw("PreShSum>>PreSum_e_5GeV(2000,0,200)","","goff");
	TH1F *PreShSum_e_5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_e_5GeV");
        tree_gamma_5GeV->Draw("PreShSum>>PreSum_gamma_5GeV(2000,0,200)","","goff");
	TH1F *PreShSum_gamma_5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_gamma_5GeV");
        tree_pion->Draw("PreShSum>>PreSum_pion(2000,0,200)","","goff");
	TH1F *PreShSum_pion_hist = (TH1F*)gROOT->FindObject("PreSum_pion");
        tree_pion_2GeV->Draw("PreShSum>>PreSum_pion_2GeV(2000,0,200)","","goff");
	TH1F *PreShSum_pion_2GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_2GeV");
        tree_pion_3GeV->Draw("PreShSum>>PreSum_pion_3GeV(2000,0,200)","","goff");
	TH1F *PreShSum_pion_3GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_3GeV");
        tree_pion_4GeV->Draw("PreShSum>>PreSum_pion_4GeV(2000,0,200)","","goff");
	TH1F *PreShSum_pion_4GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_4GeV");
        tree_pion_5GeV->Draw("PreShSum>>PreSum_pion_5GeV(2000,0,200)","","goff");
	TH1F *PreShSum_pion_5GeV_hist = (TH1F*)gROOT->FindObject("PreSum_pion_5GeV");
 


     
        tree_e_2GeV->Draw("PreSh_l>>Prer_e(2000,0,200)","","goff");
	TH1F *PreShR_e_hist = (TH1F*)gROOT->FindObject("Prer_e");
        tree_gamma_2GeV->Draw("PreSh_l>>Prer_gamma(2000,0,200)","","goff");
	TH1F *PreShR_gamma_hist = (TH1F*)gROOT->FindObject("Prer_gamma");
        tree_e->Draw("PreSh_l>>Prel_e(2000,0,200)","","goff");
	TH1F *PreShL_e_hist = (TH1F*)gROOT->FindObject("Prel_e");
        tree_gamma->Draw("PreSh_l>>Prel_gamma(2000,0,200)","","goff");
	TH1F *PreShL_gamma_hist = (TH1F*)gROOT->FindObject("Prel_gamma");
        tree_e_3GeV->Draw("PreSh_l>>Pret_e(2000,0,200)","","goff");
	TH1F *PreShT_e_hist = (TH1F*)gROOT->FindObject("Pret_e");
        tree_gamma_3GeV->Draw("PreSh_l>>Pret_gamma(2000,0,200)","","goff");
	TH1F *PreShT_gamma_hist = (TH1F*)gROOT->FindObject("Pret_gamma");
        tree_e_4GeV->Draw("PreSh_l>>Prel_e_4GeV(2000,0,200)","","goff");
	TH1F *PreShL_e_4GeV_hist = (TH1F*)gROOT->FindObject("Prel_e_4GeV");
        tree_gamma_4GeV->Draw("PreSh_l>>Prel_gamma_4GeV(2000,0,200)","","goff");
	TH1F *PreShL_gamma_4GeV_hist = (TH1F*)gROOT->FindObject("Prel_gamma_4GeV");
        tree_e_5GeV->Draw("PreSh_l>>Prel_e_5GeV(2000,0,200)","","goff");
	TH1F *PreShL_e_5GeV_hist = (TH1F*)gROOT->FindObject("Prel_e_5GeV");
        tree_gamma_5GeV->Draw("PreSh_l>>Prel_gamma_5GeV(2000,0,200)","","goff");
	TH1F *PreShL_gamma_5GeV_hist = (TH1F*)gROOT->FindObject("Prel_gamma_5GeV");

        tree_pion->Draw("PreSh_l>>Prer_pion(2000,0,200)","","goff");
	TH1F *PreShL_pion_hist = (TH1F*)gROOT->FindObject("Prer_pion");
        tree_pion_2GeV->Draw("PreSh_l>>Prer_pion_2GeV(2000,0,200)","","goff");
	TH1F *PreShL_pion_2GeV_hist = (TH1F*)gROOT->FindObject("Prer_pion_2GeV");
        tree_pion_3GeV->Draw("PreSh_l>>Prer_pion_3GeV(2000,0,200)","","goff");
	TH1F *PreShL_pion_3GeV_hist = (TH1F*)gROOT->FindObject("Prer_pion_3GeV");
        tree_pion_4GeV->Draw("PreSh_l>>Prer_pion_4GeV(2000,0,200)","","goff");
	TH1F *PreShL_pion_4GeV_hist = (TH1F*)gROOT->FindObject("Prer_pion_4GeV");
        tree_pion_5GeV->Draw("PreSh_l>>Prer_pion_5GeV(2000,0,200)","","goff");
	TH1F *PreShL_pion_5GeV_hist = (TH1F*)gROOT->FindObject("Prer_pion_5GeV");

	c[5] = new TCanvas("c[5]","c[5]",1000,1000);
        c[5]->Divide(2,3);
        c[5]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerSum_e_hist->SetLineColor(6);
        ShowerSum_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerSum_e_hist->SetTitle("e^{-} at ShowerowerSum");
        ShowerSum_e_hist->GetYaxis()->SetTitle("Event");
        ShowerSum_e_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerSum_e_hist->Rebin(rebinfac);
        ShowerSum_e_hist->Draw("HIST");
        ShowerSum_e_2GeV_hist->SetLineColor(2);
        ShowerSum_e_2GeV_hist->Rebin(rebinfac);
        ShowerSum_e_2GeV_hist->Scale(ShowerSum_e_hist->Integral()/ShowerSum_e_2GeV_hist->Integral());
        ShowerSum_e_2GeV_hist->Draw("HIST same");
        ShowerSum_e_3GeV_hist->SetLineColor(4);
        ShowerSum_e_3GeV_hist->Rebin(rebinfac);
        ShowerSum_e_3GeV_hist->Scale(ShowerSum_e_hist->Integral()/ShowerSum_e_3GeV_hist->Integral());
        ShowerSum_e_3GeV_hist->Draw("HIST same");
        ShowerSum_e_4GeV_hist->SetLineColor(7);
        ShowerSum_e_4GeV_hist->Rebin(rebinfac);
        ShowerSum_e_4GeV_hist->Scale(ShowerSum_e_hist->Integral()/ShowerSum_e_4GeV_hist->Integral());
        ShowerSum_e_4GeV_hist->Draw("HIST same");
        ShowerSum_e_5GeV_hist->SetLineColor(3);
        ShowerSum_e_5GeV_hist->Rebin(rebinfac);
        ShowerSum_e_5GeV_hist->Scale(ShowerSum_e_hist->Integral()/ShowerSum_e_5GeV_hist->Integral());
        ShowerSum_e_5GeV_hist->Draw("HIST same");
        ShowerSum_gamma_hist->SetLineColor(1);
        ShowerSum_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerSum_gamma_hist->SetTitle("#gamma at ShowerowerSum");
        ShowerSum_gamma_hist->GetYaxis()->SetTitle("Event");
        ShowerSum_gamma_hist->Rebin(rebinfac);
        ShowerSum_gamma_hist->Scale(ShowerSum_e_hist->Integral()/ShowerSum_gamma_hist->Integral());
        //ShowerSum_gamma_hist->Draw("HIST same");
        ShowerSum_gamma_2GeV_hist->SetLineColor(4);
        ShowerSum_gamma_2GeV_hist->Rebin(rebinfac);
        //ShowerSum_gamma_2GeV_hist->Draw("HIST same");
  TLegend *leg8 = new TLegend(0.15,0.7,0.4,0.88);
  leg8->AddEntry(ShowerSum_e_hist,"1GeV e^{-} in front of Shower","l");
 // leg8->AddEntry(ShowerSum_gamma_hist,"1GeV #gamma in front of Shower","l");
  leg8->AddEntry(ShowerSum_e_2GeV_hist,"2GeV e^{-} in front of Shower","l");
  leg8->AddEntry(ShowerSum_e_3GeV_hist,"3GeV e^{-} in front of Shower","l");
  leg8->AddEntry(ShowerSum_e_4GeV_hist,"4GeV e^{-} in front of Shower","l");
  leg8->AddEntry(ShowerSum_e_5GeV_hist,"5GeV e^{-} in front of Shower","l");
 // leg8->AddEntry(ShowerSum_gamma_2GeV_hist,"2GeV #gamma in front of Shower","l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
        c[5]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerL_e_hist->SetLineColor(6);
        ShowerL_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerL_e_hist->SetTitle("e^{-} at ShowerowerL");
        ShowerL_e_hist->GetYaxis()->SetTitle("Event");
        ShowerL_e_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerL_e_hist->Rebin(rebinfac);
        ShowerL_e_hist->Draw("HIST");
        ShowerR_e_hist->SetLineColor(2);
        ShowerR_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerR_e_hist->SetTitle("#gamma at ShowerowerL");
        ShowerR_e_hist->Scale(ShowerL_e_hist->Integral()/ShowerR_e_hist->Integral());
        ShowerR_e_hist->GetYaxis()->SetTitle("Event");
        ShowerR_e_hist->Rebin(rebinfac);
        ShowerR_e_hist->Draw("HIST same");
        ShowerT_e_hist->Rebin(rebinfac);
        ShowerT_e_hist->SetLineColor(4);
        ShowerT_e_hist->Scale(ShowerL_e_hist->Integral()/ShowerT_e_hist->Integral());
        ShowerT_e_hist->Draw("HIST same");
        ShowerL_e_4GeV_hist->Rebin(rebinfac);
        ShowerL_e_4GeV_hist->SetLineColor(7);
        ShowerL_e_4GeV_hist->Scale(ShowerL_e_hist->Integral()/ShowerL_e_4GeV_hist->Integral());
        ShowerL_e_4GeV_hist->Draw("HIST same");
        ShowerL_e_5GeV_hist->Rebin(rebinfac);
        ShowerL_e_5GeV_hist->SetLineColor(3);
        ShowerL_e_5GeV_hist->Scale(ShowerL_e_hist->Integral()/ShowerL_e_5GeV_hist->Integral());
        ShowerL_e_5GeV_hist->Draw("HIST same");
  TLegend *leg18 = new TLegend(0.15,0.7,0.55,0.88);
  leg18->AddEntry(ShowerL_e_hist,"1GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg18->AddEntry(ShowerR_e_hist,"2GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg18->AddEntry(ShowerT_e_hist,"3GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg18->AddEntry(ShowerL_e_4GeV_hist,"4GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg18->AddEntry(ShowerL_e_5GeV_hist,"5GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg18->SetTextSize(0.03);
  leg18->SetBorderSize(0);
  leg18->SetFillColor(0);
  leg18->Draw("text same");
        c[5]->cd(3);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerSum_gamma_hist->SetLineColor(6);
        ShowerSum_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerSum_gamma_hist->SetTitle("#gamma at ShowerowerSum");
        ShowerSum_gamma_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerSum_gamma_hist->GetYaxis()->SetTitle("Event");
        ShowerSum_gamma_hist->Rebin(rebinfac);
        ShowerSum_gamma_hist->Draw("HIST ");
        ShowerSum_gamma_2GeV_hist->SetLineColor(2);
        ShowerSum_gamma_2GeV_hist->Rebin(rebinfac);
        ShowerSum_gamma_2GeV_hist->Scale(ShowerSum_gamma_hist->Integral()/ShowerSum_gamma_2GeV_hist->Integral());
        ShowerSum_gamma_2GeV_hist->Draw("HIST same");
        ShowerSum_gamma_3GeV_hist->SetLineColor(4);
        ShowerSum_gamma_3GeV_hist->Rebin(rebinfac);
        ShowerSum_gamma_3GeV_hist->Scale(ShowerSum_gamma_hist->Integral()/ShowerSum_gamma_3GeV_hist->Integral());
        ShowerSum_gamma_3GeV_hist->Draw("HIST same");
        ShowerSum_gamma_4GeV_hist->SetLineColor(7);
        ShowerSum_gamma_4GeV_hist->Rebin(rebinfac);
        ShowerSum_gamma_4GeV_hist->Scale(ShowerSum_gamma_hist->Integral()/ShowerSum_gamma_4GeV_hist->Integral());
        ShowerSum_gamma_4GeV_hist->Draw("HIST same");
        ShowerSum_gamma_5GeV_hist->SetLineColor(3);
        ShowerSum_gamma_5GeV_hist->Rebin(rebinfac);
        ShowerSum_gamma_5GeV_hist->Scale(ShowerSum_gamma_hist->Integral()/ShowerSum_gamma_5GeV_hist->Integral());
        ShowerSum_gamma_5GeV_hist->Draw("HIST same");
        c[5]->cd(4);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerL_gamma_hist->SetLineColor(6);
        ShowerL_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerL_gamma_hist->SetTitle("#gamma at ShowerowerL");
        ShowerL_gamma_hist->GetYaxis()->SetTitle("Event");
        ShowerL_gamma_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerL_gamma_hist->Rebin(rebinfac);
        ShowerL_gamma_hist->Draw("HIST");
        ShowerT_gamma_hist->SetLineColor(4);
        ShowerT_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerT_gamma_hist->SetTitle(" #gamma at ShowerowerT");
        ShowerT_gamma_hist->GetYaxis()->SetTitle("Event");
        ShowerT_gamma_hist->Scale(ShowerL_gamma_hist->Integral()/ShowerT_gamma_hist->Integral());
        ShowerT_gamma_hist->Rebin(rebinfac);
        ShowerT_gamma_hist->Draw("HIST same");
        ShowerR_gamma_hist->SetLineColor(2);
        ShowerR_gamma_hist->Scale(ShowerL_gamma_hist->Integral()/ShowerR_gamma_hist->Integral());
        ShowerR_gamma_hist->Rebin(rebinfac);
        ShowerR_gamma_hist->Draw("HIST same");
        ShowerL_gamma_4GeV_hist->SetLineColor(7);
        ShowerL_gamma_4GeV_hist->Scale(ShowerL_gamma_hist->Integral()/ShowerL_gamma_4GeV_hist->Integral());
        ShowerL_gamma_4GeV_hist->Rebin(rebinfac);
        ShowerL_gamma_4GeV_hist->Draw("HIST same");
        ShowerL_gamma_5GeV_hist->SetLineColor(3);
        ShowerL_gamma_5GeV_hist->Scale(ShowerL_gamma_hist->Integral()/ShowerL_gamma_5GeV_hist->Integral());
        ShowerL_gamma_5GeV_hist->Rebin(rebinfac);
        ShowerL_gamma_5GeV_hist->Draw("HIST same");
  TLegend *leg19 = new TLegend(0.15,0.7,0.55,0.88);
  leg19->AddEntry(ShowerL_gamma_hist,"1GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg19->AddEntry(ShowerR_gamma_hist,"2GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg19->AddEntry(ShowerT_gamma_hist,"3GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg19->AddEntry(ShowerL_gamma_4GeV_hist,"4GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg19->AddEntry(ShowerL_gamma_5GeV_hist,"5GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg19->SetTextSize(0.03);
  leg19->SetBorderSize(0);
  leg19->SetFillColor(0);
  leg19->Draw("text same");
        c[5]->cd(5);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerSum_pion_hist->SetLineColor(6);
        ShowerSum_pion_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerSum_pion_hist->SetTitle("#pi^{-} at ShowerowerSum");
        ShowerSum_pion_hist->GetYaxis()->SetTitle("Event");
        ShowerSum_pion_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerSum_pion_hist->Rebin(rebinfac);
        ShowerSum_pion_hist->Draw("HIST");
        ShowerSum_pion_2GeV_hist->SetLineColor(2);
        ShowerSum_pion_2GeV_hist->Rebin(rebinfac);
        ShowerSum_pion_2GeV_hist->Scale(ShowerSum_pion_hist->Integral()/ShowerSum_pion_2GeV_hist->Integral());
        ShowerSum_pion_2GeV_hist->Draw("HIST same");
        ShowerSum_pion_4GeV_hist->SetLineColor(7);
        ShowerSum_pion_4GeV_hist->Rebin(rebinfac);
        ShowerSum_pion_4GeV_hist->Scale(ShowerSum_pion_hist->Integral()/ShowerSum_pion_4GeV_hist->Integral());
        ShowerSum_pion_4GeV_hist->Draw("HIST same");
        ShowerSum_pion_5GeV_hist->SetLineColor(3);
        ShowerSum_pion_5GeV_hist->Rebin(rebinfac);
        ShowerSum_pion_5GeV_hist->Scale(ShowerSum_pion_hist->Integral()/ShowerSum_pion_5GeV_hist->Integral());
        ShowerSum_pion_5GeV_hist->Draw("HIST same");
        ShowerSum_pion_3GeV_hist->SetLineColor(4);
        ShowerSum_pion_3GeV_hist->Rebin(rebinfac);
        ShowerSum_pion_3GeV_hist->Scale(ShowerSum_pion_hist->Integral()/ShowerSum_pion_3GeV_hist->Integral());
        ShowerSum_pion_3GeV_hist->Draw("HIST same");
  TLegend *leg78 = new TLegend(0.15,0.7,0.4,0.88);
  leg78->AddEntry(ShowerSum_pion_hist,"1GeV #pi^{-} in front of Shower","l");
  leg78->AddEntry(ShowerSum_pion_2GeV_hist,"2GeV #pi^{-} in front of Shower","l");
  leg78->AddEntry(ShowerSum_pion_3GeV_hist,"3GeV #pi^{-} in front of Shower","l");
  leg78->AddEntry(ShowerSum_pion_4GeV_hist,"4GeV #pi^{-} in front of Shower","l");
  leg78->AddEntry(ShowerSum_pion_5GeV_hist,"5GeV #pi^{-} in front of Shower","l");
  leg78->SetTextSize(0.03);
  leg78->SetBorderSize(0);
  leg78->SetFillColor(0);
  leg78->Draw("text same");
        c[5]->cd(6);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        ShowerL_pion_hist->SetLineColor(6);
        ShowerL_pion_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerL_pion_hist->SetTitle("#pi^{-} at ShowerowerL");
        ShowerL_pion_hist->GetYaxis()->SetTitle("Event");
        ShowerL_pion_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        ShowerL_pion_hist->Rebin(rebinfac);
        ShowerL_pion_hist->Draw("HIST");
        ShowerL_pion_2GeV_hist->SetLineColor(4);
        ShowerL_pion_2GeV_hist->GetXaxis()->SetTitle("Edep (MeV)");
        ShowerL_pion_2GeV_hist->SetTitle(" #pi^{-} at ShowerowerL");
        ShowerL_pion_2GeV_hist->GetYaxis()->SetTitle("Event");
        ShowerL_pion_2GeV_hist->Scale(ShowerL_pion_hist->Integral()/ShowerL_pion_2GeV_hist->Integral());
        ShowerL_pion_2GeV_hist->Rebin(rebinfac);
        ShowerL_pion_2GeV_hist->Draw("HIST same");
        ShowerL_pion_3GeV_hist->SetLineColor(2);
       // ShowerL_pion_3GeV_hist->Scale(ShowerL_pion_hist->Integral()/ShowerL_pion_3GeV_hist->Integral());
        ShowerL_pion_3GeV_hist->Rebin(rebinfac);
        ShowerL_pion_3GeV_hist->Draw("HIST same");
        ShowerL_pion_4GeV_hist->SetLineColor(7);
        ShowerL_pion_4GeV_hist->Scale(ShowerL_pion_hist->Integral()/ShowerL_pion_4GeV_hist->Integral());
        ShowerL_pion_4GeV_hist->Rebin(rebinfac);
        ShowerL_pion_4GeV_hist->Draw("HIST same");
        ShowerL_pion_5GeV_hist->SetLineColor(3);
        ShowerL_pion_5GeV_hist->Scale(ShowerL_pion_hist->Integral()/ShowerL_pion_5GeV_hist->Integral());
        ShowerL_pion_5GeV_hist->Rebin(rebinfac);
        ShowerL_pion_5GeV_hist->Draw("HIST same");
  TLegend *leg79 = new TLegend(0.15,0.7,0.55,0.88);
  leg79->AddEntry(ShowerL_gamma_hist,"1GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg79->AddEntry(ShowerR_gamma_hist,"2GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg79->AddEntry(ShowerT_gamma_hist,"3GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg79->AddEntry(ShowerL_gamma_4GeV_hist,"4GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg79->AddEntry(ShowerL_gamma_5GeV_hist,"5GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg79->SetTextSize(0.03);
  leg79->SetBorderSize(0);
  leg79->SetFillColor(0);
  leg79->Draw("text same");




	c[6] = new TCanvas("c[6]","c[6]",1000,1000);
        c[6]->Divide(2,3);
        c[6]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShSum_e_hist->SetLineColor(6);
        PreShSum_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShSum_e_hist->SetTitle(" e^{-} at PreShowerSum");
        PreShSum_e_hist->GetYaxis()->SetTitle("Event");
        PreShSum_e_hist->GetYaxis()->SetRangeUser(1e-2,1e5);
        PreShSum_e_hist->Rebin(rebinfac);
        PreShSum_e_hist->Draw("HIST");
        PreShSum_gamma_hist->SetLineColor(1);
        PreShSum_gamma_hist->Rebin(rebinfac);
        PreShSum_gamma_hist->Scale(PreShSum_e_hist->Integral()/PreShSum_gamma_hist->Integral());
        PreShSum_gamma_2GeV_hist->SetLineColor(2);
        PreShSum_gamma_2GeV_hist->Rebin(rebinfac);
        PreShSum_e_2GeV_hist->SetLineColor(2);
        PreShSum_e_2GeV_hist->Rebin(rebinfac);
        PreShSum_e_2GeV_hist->Scale(PreShSum_e_hist->Integral()/PreShSum_e_2GeV_hist->Integral());
        PreShSum_e_2GeV_hist->Draw("HIST same");
        PreShSum_e_3GeV_hist->SetLineColor(4);
        PreShSum_e_3GeV_hist->Rebin(rebinfac);
        PreShSum_e_3GeV_hist->Scale(PreShSum_e_hist->Integral()/PreShSum_e_3GeV_hist->Integral());
        PreShSum_e_3GeV_hist->Draw("HIST same");
        PreShSum_e_4GeV_hist->SetLineColor(7);
        PreShSum_e_4GeV_hist->Rebin(rebinfac);
        PreShSum_e_4GeV_hist->Scale(PreShSum_e_hist->Integral()/PreShSum_e_4GeV_hist->Integral());
        PreShSum_e_4GeV_hist->Draw("HIST same");
        PreShSum_e_5GeV_hist->SetLineColor(3);
        PreShSum_e_5GeV_hist->Rebin(rebinfac);
        PreShSum_e_5GeV_hist->Scale(PreShSum_e_hist->Integral()/PreShSum_e_5GeV_hist->Integral());
        PreShSum_e_5GeV_hist->Draw("HIST same");
  TLegend *leg9 = new TLegend(0.15,0.7,0.55,0.88);
  leg9->AddEntry(PreShSum_e_hist,"1GeV e^{-} in front of PreShower","l");
  leg9->AddEntry(PreShSum_e_2GeV_hist,"2GeV e^{-} in front of PreShower","l");
  leg9->AddEntry(PreShSum_e_3GeV_hist,"3GeV e^{-} in front of PreShower","l");
  leg9->AddEntry(PreShSum_e_4GeV_hist,"4GeV e^{-} in front of PreShower","l");
  leg9->AddEntry(PreShSum_e_5GeV_hist,"5GeV e^{-} in front of PreShower","l");
  leg9->SetTextSize(0.03);
  leg9->SetBorderSize(0);
  leg9->SetFillColor(0);
  leg9->Draw("text same");
        c[6]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_e_hist->SetLineColor(6);
        PreShL_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_e_hist->SetTitle("e^{-} at PreShowerL");
        PreShL_e_hist->GetYaxis()->SetTitle("Event");
        PreShL_e_hist->GetYaxis()->SetRangeUser(1e-2,1e5);
        PreShL_e_hist->Rebin(rebinfac);
        PreShL_e_hist->Draw("HIST");
        PreShT_e_hist->SetLineColor(4);
        PreShT_e_hist->Scale(PreShL_e_hist->Integral()/PreShT_e_hist->Integral());
        PreShT_e_hist->Rebin(rebinfac);
        PreShT_e_hist->Draw("HIST same");
        PreShR_e_hist->SetLineColor(2);
        PreShR_e_hist->Scale(PreShL_e_hist->Integral()/PreShR_e_hist->Integral());
        PreShR_e_hist->Rebin(rebinfac);
        PreShR_e_hist->Draw("HIST same");
        PreShL_e_4GeV_hist->Scale(PreShL_e_hist->Integral()/PreShL_e_4GeV_hist->Integral());
        PreShL_e_4GeV_hist->SetLineColor(7);
        PreShL_e_4GeV_hist->Rebin(rebinfac);
        PreShL_e_4GeV_hist->Draw("HIST same");
        PreShL_e_5GeV_hist->Scale(PreShL_e_hist->Integral()/PreShL_e_5GeV_hist->Integral());
        PreShL_e_5GeV_hist->SetLineColor(3);
        PreShL_e_5GeV_hist->Rebin(rebinfac);
        PreShL_e_5GeV_hist->Draw("HIST same");
  TLegend *leg28 = new TLegend(0.15,0.7,0.55,0.88);
  leg28->AddEntry(PreShL_e_hist,"1GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg28->AddEntry(PreShR_e_hist,"2GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg28->AddEntry(PreShT_e_hist,"3GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg28->AddEntry(PreShL_e_4GeV_hist,"4GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg28->AddEntry(PreShL_e_4GeV_hist,"5GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg28->SetTextSize(0.03);
  leg28->SetBorderSize(0);
  leg28->SetFillColor(0);
  leg28->Draw("text same");
        c[6]->cd(3);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShSum_gamma_hist->SetLineColor(6);
        PreShSum_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShSum_gamma_hist->SetTitle(" #gamma at PreShowerSum");
        PreShSum_gamma_hist->GetYaxis()->SetTitle("Event");
        PreShSum_gamma_hist->Rebin(rebinfac);
        PreShSum_gamma_hist->Draw("HIST");
        PreShSum_gamma_2GeV_hist->SetLineColor(2);
        PreShSum_gamma_2GeV_hist->Rebin(rebinfac);
        PreShSum_gamma_2GeV_hist->Scale(PreShSum_gamma_hist->Integral()/PreShSum_gamma_2GeV_hist->Integral());
        PreShSum_gamma_2GeV_hist->Draw("HIST same");
        PreShSum_gamma_3GeV_hist->SetLineColor(4);
        PreShSum_gamma_3GeV_hist->Rebin(rebinfac);
        PreShSum_gamma_3GeV_hist->Scale(PreShSum_gamma_hist->Integral()/PreShSum_gamma_3GeV_hist->Integral());
        PreShSum_gamma_3GeV_hist->Draw("HIST same");
        PreShSum_gamma_4GeV_hist->SetLineColor(7);
        PreShSum_gamma_4GeV_hist->Rebin(rebinfac);
        PreShSum_gamma_4GeV_hist->Scale(PreShSum_gamma_hist->Integral()/PreShSum_gamma_4GeV_hist->Integral());
        PreShSum_gamma_4GeV_hist->Draw("HIST same");
        PreShSum_gamma_5GeV_hist->SetLineColor(3);
        PreShSum_gamma_5GeV_hist->Rebin(rebinfac);
        PreShSum_gamma_5GeV_hist->Scale(PreShSum_gamma_hist->Integral()/PreShSum_gamma_5GeV_hist->Integral());
        PreShSum_gamma_5GeV_hist->Draw("HIST same");
  leg9->Draw("text same");
        c[6]->cd(4);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_gamma_hist->SetLineColor(6);
        PreShL_gamma_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_gamma_hist->SetTitle("#gamma at PreShowerL");
        PreShL_gamma_hist->GetYaxis()->SetTitle("Event");
        PreShL_gamma_hist->GetYaxis()->SetRangeUser(1e-2,1e5);
        PreShL_gamma_hist->Rebin(rebinfac);
        PreShL_gamma_hist->Draw("HIST");
        PreShT_gamma_hist->SetLineColor(4);
        //PreShT_gamma_hist->Scale(PreShSum_e_hist->Integral()/PreShT_gamma_hist->Integral());
        PreShT_gamma_hist->Rebin(rebinfac);
        PreShT_gamma_hist->Draw("HIST same");
        PreShR_gamma_hist->SetLineColor(2);
        PreShR_gamma_hist->Scale(PreShL_gamma_hist->Integral()/PreShR_gamma_hist->Integral());
        PreShR_gamma_hist->Rebin(rebinfac);
        PreShR_gamma_hist->Draw("HIST same");
        PreShL_gamma_4GeV_hist->SetLineColor(7);
        PreShL_gamma_4GeV_hist->Scale(PreShL_gamma_hist->Integral()/PreShL_gamma_4GeV_hist->Integral());
        PreShL_gamma_4GeV_hist->Rebin(rebinfac);
        PreShL_gamma_4GeV_hist->Draw("HIST same");
        PreShL_gamma_5GeV_hist->SetLineColor(3);
        PreShL_gamma_5GeV_hist->Scale(PreShL_gamma_hist->Integral()/PreShL_gamma_5GeV_hist->Integral());
        PreShL_gamma_5GeV_hist->Rebin(rebinfac);
        PreShL_gamma_5GeV_hist->Draw("HIST same");
  leg9->Draw("text same");
        c[6]->cd(5);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShSum_pion_hist->SetLineColor(6);
        PreShSum_pion_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShSum_pion_hist->SetTitle("#pi^{-} at ShowerowerSum");
        PreShSum_pion_hist->GetYaxis()->SetTitle("Event");
        PreShSum_pion_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShSum_pion_hist->Rebin(rebinfac);
        PreShSum_pion_hist->Draw("HIST");
        PreShSum_pion_2GeV_hist->SetLineColor(2);
        PreShSum_pion_2GeV_hist->Rebin(rebinfac);
        PreShSum_pion_2GeV_hist->Scale(PreShSum_pion_hist->Integral()/PreShSum_pion_2GeV_hist->Integral());
        PreShSum_pion_2GeV_hist->Draw("HIST same");
        PreShSum_pion_4GeV_hist->SetLineColor(7);
        PreShSum_pion_4GeV_hist->Rebin(rebinfac);
        PreShSum_pion_4GeV_hist->Scale(PreShSum_pion_hist->Integral()/PreShSum_pion_4GeV_hist->Integral());
        PreShSum_pion_4GeV_hist->Draw("HIST same");
        PreShSum_pion_5GeV_hist->SetLineColor(3);
        PreShSum_pion_5GeV_hist->Rebin(rebinfac);
        PreShSum_pion_5GeV_hist->Scale(PreShSum_pion_hist->Integral()/PreShSum_pion_5GeV_hist->Integral());
        PreShSum_pion_5GeV_hist->Draw("HIST same");
        PreShSum_pion_3GeV_hist->SetLineColor(4);
        PreShSum_pion_3GeV_hist->Rebin(rebinfac);
        PreShSum_pion_3GeV_hist->Scale(PreShSum_pion_hist->Integral()/PreShSum_pion_3GeV_hist->Integral());
        PreShSum_pion_3GeV_hist->Draw("HIST same");
  leg78->Draw("text same");
        c[6]->cd(6);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_pion_hist->SetLineColor(6);
        PreShL_pion_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_pion_hist->SetTitle("#pi^{-} at ShowerowerL");
        PreShL_pion_hist->GetYaxis()->SetTitle("Event");
        PreShL_pion_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShL_pion_hist->Rebin(rebinfac);
        PreShL_pion_hist->Draw("HIST");
        PreShL_pion_2GeV_hist->SetLineColor(4);
        PreShL_pion_2GeV_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_pion_2GeV_hist->SetTitle(" #pi^{-} at ShowerowerL");
        PreShL_pion_2GeV_hist->GetYaxis()->SetTitle("Event");
        PreShL_pion_2GeV_hist->Scale(PreShL_pion_hist->Integral()/PreShL_pion_2GeV_hist->Integral());
        PreShL_pion_2GeV_hist->Rebin(rebinfac);
        PreShL_pion_2GeV_hist->Draw("HIST same");
        PreShL_pion_3GeV_hist->SetLineColor(2);
        //PreShL_pion_3GeV_hist->Scale(PreShL_pion_hist->Integral()/PreShL_pion_3GeV_hist->Integral());
        PreShL_pion_3GeV_hist->Rebin(rebinfac);
        PreShL_pion_3GeV_hist->Draw("HIST same");
        PreShL_pion_4GeV_hist->SetLineColor(7);
        PreShL_pion_4GeV_hist->Scale(PreShL_pion_hist->Integral()/PreShL_pion_4GeV_hist->Integral());
        PreShL_pion_4GeV_hist->Rebin(rebinfac);
        PreShL_pion_4GeV_hist->Draw("HIST same");
        PreShL_pion_5GeV_hist->SetLineColor(3);
        PreShL_pion_5GeV_hist->Scale(PreShL_pion_hist->Integral()/PreShL_pion_5GeV_hist->Integral());
        PreShL_pion_5GeV_hist->Rebin(rebinfac);
        PreShL_pion_5GeV_hist->Draw("HIST same");
  leg79->Draw("text same");
	c[0] = new TCanvas("c[0]","c[0]",1000,1000);
        c[0]->Divide(1,2);
        c[0]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_e_hist->SetTitle(" e^{-} at PreShowerL");
        PreShL_e_hist->GetYaxis()->SetTitle("Event");
        PreShL_e_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShL_e_hist->Rebin(rebinfac);
        PreShL_e_hist->Draw("HIST");
        TH1F *PreShL_gamma_clone_hist = (TH1F*)PreShL_gamma_hist->Clone(); 
        PreShL_gamma_clone_hist->Rebin(rebinfac);
        PreShL_gamma_clone_hist->SetLineColor(1);
        PreShL_gamma_clone_hist->Draw("HIST same");
        TH1F *PreShL_pion_clone_hist = (TH1F*)PreShL_pion_hist->Clone(); 
        PreShL_pion_clone_hist->Rebin(rebinfac);
        PreShL_pion_clone_hist->SetLineColor(kOrange-3);
        PreShL_pion_clone_hist->Draw("HIST same");
  TLegend *leg2 = new TLegend(0.15,0.7,0.55,0.88);
  leg2->AddEntry(PreShL_e_hist,"1GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg2->AddEntry(PreShL_gamma_clone_hist,"1GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg2->AddEntry(PreShL_pion_clone_hist,"1GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg2->SetTextSize(0.03);
  leg2->SetBorderSize(0);
  leg2->SetFillColor(0);
  leg2->Draw("text same");
        TH1F *PreShL_gamma_clone2_hist = (TH1F*)PreShL_gamma_hist->Clone(); 
        PreShL_gamma_clone2_hist->Scale(PreShL_e_hist->Integral()/PreShL_gamma_clone2_hist->Integral());
        c[0]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_gamma_clone2_hist->Divide(PreShL_e_hist);
        PreShL_gamma_clone2_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_gamma_clone2_hist->GetYaxis()->SetRangeUser(1e-1,4e1);
        PreShL_gamma_clone2_hist->SetTitle(" 1GeV #frac{#gamma}{e^{-}}");
        PreShL_gamma_clone2_hist->GetYaxis()->SetTitle("#frac{#gamma}{e^{-}}");
        PreShL_gamma_clone2_hist->Draw("HIST");
	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
        c[1]->Divide(1,2);
        c[1]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShR_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShR_e_hist->SetTitle(" 2GeV e^{-} at PreShowerL");
        PreShR_e_hist->GetYaxis()->SetTitle("Event");
        PreShR_e_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShR_e_hist->Rebin(rebinfac);
        PreShR_e_hist->Draw("HIST");
        TH1F *PreShR_gamma_clone_hist = (TH1F*)PreShR_gamma_hist->Clone(); 
        PreShR_gamma_clone_hist->Rebin(rebinfac);
        PreShR_gamma_clone_hist->SetLineColor(1);
        PreShR_gamma_clone_hist->Draw("HIST same");
        TH1F *PreShL_pion_2GeV_clone_hist = (TH1F*)PreShL_pion_2GeV_hist->Clone(); 
        PreShL_pion_2GeV_clone_hist->Rebin(rebinfac);
        PreShL_pion_2GeV_clone_hist->SetLineColor(kOrange-3);
        PreShL_pion_2GeV_clone_hist->Draw("HIST same");
  TLegend *leg3 = new TLegend(0.15,0.7,0.55,0.88);
  leg3->AddEntry(PreShR_e_hist,"2GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg3->AddEntry(PreShR_gamma_clone_hist,"2GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg3->AddEntry(PreShL_pion_2GeV_clone_hist,"2GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg3->SetTextSize(0.03);
  leg3->SetBorderSize(0);
  leg3->SetFillColor(0);
  leg3->Draw("text same");
        TH1F *PreShR_gamma_clone2_hist = (TH1F*)PreShR_gamma_hist->Clone(); 
        PreShR_gamma_clone2_hist->Scale(PreShR_e_hist->Integral()/PreShR_gamma_clone2_hist->Integral());
        c[1]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShR_gamma_clone2_hist->Divide(PreShR_e_hist);
        PreShR_gamma_clone2_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShR_gamma_clone2_hist->GetYaxis()->SetRangeUser(1e-1,4e1);
        PreShR_gamma_clone2_hist->SetTitle(" 2GeV #frac{#gamma}{e^{-}}");
        PreShR_gamma_clone2_hist->GetYaxis()->SetTitle("#frac{#gamma}{e^{-}}");
        PreShR_gamma_clone2_hist->Draw("HIST");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);
        c[2]->Divide(1,2);
        c[2]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShT_e_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShT_e_hist->SetTitle(" 3GeV e^{-} at PreShowerL");
        PreShT_e_hist->GetYaxis()->SetTitle("Event");
        PreShT_e_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShT_e_hist->Rebin(rebinfac);
        PreShT_e_hist->Draw("HIST");
        TH1F *PreShT_gamma_clone_hist = (TH1F*)PreShT_gamma_hist->Clone(); 
        PreShT_gamma_clone_hist->Rebin(rebinfac);
        PreShT_gamma_clone_hist->SetLineColor(1);
        PreShT_gamma_clone_hist->Draw("HIST same");
        TH1F *PreShL_pion_3GeV_clone_hist = (TH1F*)PreShL_pion_3GeV_hist->Clone(); 
        PreShL_pion_3GeV_clone_hist->Rebin(rebinfac);
        PreShL_pion_3GeV_clone_hist->SetLineColor(kOrange-3);
        PreShL_pion_3GeV_clone_hist->Draw("HIST same");
  TLegend *leg4 = new TLegend(0.15,0.7,0.55,0.88);
  leg4->AddEntry(PreShT_e_hist,"3GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg4->AddEntry(PreShT_gamma_clone_hist,"3GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg4->AddEntry(PreShL_pion_3GeV_clone_hist,"3GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg4->SetTextSize(0.03);
  leg4->SetBorderSize(0);
  leg4->SetFillColor(0);
  leg4->Draw("text same");
        TH1F *PreShT_gamma_clone2_hist = (TH1F*)PreShT_gamma_hist->Clone(); 
        PreShT_gamma_clone2_hist->Scale(PreShT_e_hist->Integral()/PreShT_gamma_clone2_hist->Integral());
        c[2]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShT_gamma_clone2_hist->Divide(PreShT_e_hist);
        PreShT_gamma_clone2_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShT_gamma_clone2_hist->GetYaxis()->SetRangeUser(1e-1,4e1);
        PreShT_gamma_clone2_hist->SetTitle(" 3GeV #frac{#gamma}{e^{-}}");
        PreShT_gamma_clone2_hist->GetYaxis()->SetTitle("#frac{#gamma}{e^{-}}");
        PreShT_gamma_clone2_hist->Draw("HIST");
	c[3] = new TCanvas("c[3]","c[3]",1000,1000);
        c[3]->Divide(1,2);
        c[3]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_e_4GeV_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_e_4GeV_hist->SetTitle(" 4GeV e^{-} at PreShowerL");
        PreShL_e_4GeV_hist->GetYaxis()->SetTitle("Event");
        PreShL_e_4GeV_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShL_e_4GeV_hist->Rebin(rebinfac);
        PreShL_e_4GeV_hist->Draw("HIST");
        TH1F *PreShL_gamma_4GeV_clone_hist = (TH1F*)PreShL_gamma_4GeV_hist->Clone(); 
        PreShL_gamma_4GeV_clone_hist->Rebin(rebinfac);
        PreShL_gamma_4GeV_clone_hist->SetLineColor(1);
        PreShL_gamma_4GeV_clone_hist->Draw("HIST same");
        TH1F *PreShL_pion_4GeV_clone_hist = (TH1F*)PreShL_pion_4GeV_hist->Clone(); 
        PreShL_pion_4GeV_clone_hist->Rebin(rebinfac);
        PreShL_pion_4GeV_clone_hist->SetLineColor(kOrange-3);
        PreShL_pion_4GeV_clone_hist->Draw("HIST same");
  TLegend *leg5 = new TLegend(0.15,0.7,0.55,0.88);
  leg5->AddEntry(PreShL_e_4GeV_hist,"4GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg5->AddEntry(PreShL_gamma_4GeV_clone_hist,"4GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg5->AddEntry(PreShL_pion_4GeV_clone_hist,"4GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg5->SetTextSize(0.03);
  leg5->SetBorderSize(0);
  leg5->SetFillColor(0);
  leg5->Draw("text same");
        TH1F *PreShL_gamma_4GeV_clone2_hist = (TH1F*)PreShL_gamma_4GeV_hist->Clone(); 
        PreShL_gamma_4GeV_clone2_hist->Scale(PreShL_e_4GeV_hist->Integral()/PreShL_gamma_4GeV_clone2_hist->Integral());
        c[3]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_gamma_4GeV_clone2_hist->Divide(PreShL_e_4GeV_hist);
        PreShL_gamma_4GeV_clone2_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_gamma_4GeV_clone2_hist->GetYaxis()->SetRangeUser(1e-1,4e1);
        PreShL_gamma_4GeV_clone2_hist->SetTitle(" 4GeV #frac{#gamma}{e^{-}}");
        PreShL_gamma_4GeV_clone2_hist->GetYaxis()->SetTitle("#frac{#gamma}{e^{-}}");
        PreShL_gamma_4GeV_clone2_hist->Draw("HIST");
	c[4] = new TCanvas("c[4]","c[4]",1000,1000);
        c[4]->Divide(1,2);
        c[4]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_e_5GeV_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_e_5GeV_hist->SetTitle(" 5GeV e^{-} at PreShowerL");
        PreShL_e_5GeV_hist->GetYaxis()->SetTitle("Event");
        PreShL_e_5GeV_hist->GetYaxis()->SetRangeUser(1e-2,1e7);
        PreShL_e_5GeV_hist->Rebin(rebinfac);
        PreShL_e_5GeV_hist->Draw("HIST");
        TH1F *PreShL_gamma_5GeV_clone_hist = (TH1F*)PreShL_gamma_5GeV_hist->Clone(); 
        PreShL_gamma_5GeV_clone_hist->Rebin(rebinfac);
        PreShL_gamma_5GeV_clone_hist->SetLineColor(1);
        PreShL_gamma_5GeV_clone_hist->Draw("HIST same");
        TH1F *PreShL_pion_5GeV_clone_hist = (TH1F*)PreShL_pion_5GeV_hist->Clone(); 
        PreShL_pion_5GeV_clone_hist->Rebin(rebinfac);
        PreShL_pion_5GeV_clone_hist->SetLineColor(kOrange-3);
        PreShL_pion_5GeV_clone_hist->Draw("HIST same");
  TLegend *leg6 = new TLegend(0.15,0.7,0.55,0.88);
  leg6->AddEntry(PreShL_e_5GeV_hist,"5GeV e^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg6->AddEntry(PreShL_gamma_5GeV_clone_hist,"5GeV #gamma in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg6->AddEntry(PreShL_pion_5GeV_clone_hist,"5GeV #pi^{-} in front of PreShower Shower_l/ShowerSum>0.85","l");
  leg6->SetTextSize(0.03);
  leg6->SetBorderSize(0);
  leg6->SetFillColor(0);
  leg6->Draw("text same");
        TH1F *PreShL_gamma_5GeV_clone2_hist = (TH1F*)PreShL_gamma_5GeV_hist->Clone(); 
        PreShL_gamma_5GeV_clone2_hist->Scale(PreShL_e_5GeV_hist->Integral()/PreShL_gamma_5GeV_clone2_hist->Integral());
        c[4]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_gamma_5GeV_clone2_hist->Divide(PreShL_e_5GeV_hist);
        PreShL_gamma_5GeV_clone2_hist->GetXaxis()->SetTitle("Edep (MeV)");
        PreShL_gamma_5GeV_clone2_hist->GetYaxis()->SetRangeUser(1e-1,4e1);
        PreShL_gamma_5GeV_clone2_hist->SetTitle(" #frac{#gamma}{e^{-}}");
        PreShL_gamma_5GeV_clone2_hist->GetYaxis()->SetTitle("#frac{#gamma}{e^{-}}");
        PreShL_gamma_5GeV_clone2_hist->Draw("HIST");
	c[7] = new TCanvas("c[7]","c[7]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        PreShL_gamma_5GeV_clone2_hist->Draw("HIST");
        PreShL_gamma_4GeV_clone2_hist->Draw("HIST same");
        PreShL_gamma_clone2_hist->Draw("HIST same");
        PreShR_gamma_clone2_hist->Draw("HIST same");
        PreShT_gamma_clone2_hist->Draw("HIST same");
  TLegend *leg38 = new TLegend(0.15,0.7,0.55,0.88);
  leg38->AddEntry(PreShL_gamma_clone2_hist,"1GeV ","l");
  leg38->AddEntry(PreShR_gamma_clone2_hist,"2GeV ","l");
  leg38->AddEntry(PreShT_gamma_clone2_hist,"3GeV ","l");
  leg38->AddEntry(PreShL_gamma_4GeV_clone2_hist,"4GeV ","l");
  leg38->AddEntry(PreShL_gamma_5GeV_clone2_hist,"5GeV ","l");
  leg38->SetTextSize(0.03);
  leg38->SetBorderSize(0);
  leg38->SetFillColor(0);
  leg38->Draw("text same");
	for(int a=0;a<8;a++){
		c[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./Sim_5GeV_e_gamma_comparison.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
