
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_EC_newbeamline(){
gStyle->SetOptStat(0);
gStyle->SetPalette(1);
//TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_20deg_LD2_21m_30x30x5cm3/HallC_beamtest_eAll_LD2_20deg_filenum1401_1.401e8_10.6GeV_output_Nphe_finetime_Q2cut_10MeV.root");
TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_20deg_LD2_21m_shielding/HallC_beamtest_eAll_LD2_20deg_filenum795_7.95e6_10.6GeV_shielding_output_Nphe_finetime_Q2cut_10MeV.root");
TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding/HallC_beamtest_BeamOnTarget_9.941e8_60uA_4SCs_20deg_r20m_LD2_shielding_output_Nphe.root");
TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_60uA_sangle_4SC_20deg_LD2_r20m_shielding_30x30x1cm3/HallC_beamtest_BeamOnTarget_9.951e8_60uA_4SCs_20deg_r20m_LD2_shielding_30x30x1cm3_output_Nphe.root");
TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_20deg_LD_21m/HallC_beamtest_bggen_LD2_pim_20deg_filenum1990_21m_shielding_output_Nphe.root");
TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_20deg_LD_21m/HallC_beamtest_bggen_LD2_pip_20deg_filenum2000_21m_shielding_output_Nphe.root");
TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_20deg_LD_21m/HallC_beamtest_bggen_LD2_pi0_20deg_filenum2000_21m_shielding_output_Nphe.root");
const int rebinfac=10;
const int rebinfac2=10;
TH1F *EC_shower_pim;
TH1F *EC_shower_pip;
TH1F *EC_shower_pi0;
TH1F *EC_shower_eAll;
TH1F *EC_shower_proton;
TH1F *EC_shower_pim_trigger;
TH1F *EC_shower_pip_trigger;
TH1F *EC_shower_pi0_trigger;
TH1F *EC_shower_proton_trigger;
TH1F *EC_shower_eAll_trigger;
TH1F *EC_preshower_pim;
TH1F *EC_preshower_proton;
TH1F *EC_preshower_pip;
TH1F *EC_preshower_pi0;
TH1F *EC_preshower_pi0_all;
TH1F *EC_shower_pi0_all;
TH1F *EC_preshower_pi0_e;
TH1F *EC_preshower_pi0_ep;
TH1F *EC_preshower_pi0_r;
TH1F *EC_shower_pi0_e;
TH1F *EC_shower_pi0_ep;
TH1F *EC_shower_pi0_r;
TH1F *EC_preshower_eAll;
TH1F *EC_preshower_pim_trigger;
TH1F *EC_preshower_proton_trigger;
TH1F *EC_preshower_pip_trigger;
TH1F *EC_preshower_pi0_trigger;
TH1F *EC_preshower_eAll_trigger;
TH1F *EC_preshower_mother_pi0;
TH1F *EC_preshower_mother_pi0_e;
TH1F *EC_preshower_mother_pi0_ep;
TH1F *EC_preshower_mother_pi0_r;
TH1F *EC_shower_mother_pi0_e;
TH1F *EC_shower_mother_pi0_ep;
TH1F *EC_shower_mother_pi0_r;
TH1F *sc1_pim;
TH1F *sc2_pim;
TH1F *sc1_pip;
TH1F *sc1_proton;
TH1F *sc2_proton;
TH1F *sc1_pi0;
TH1F *sc2_pi0;
TH1F *sc2_pip;
TH1F *sc1_eAll;
TH1F *sc2_eAll;
TH1F *hhit_E_pim[7];
TH1F *hhit_p_pim[7];
TH1F *hhit_Edep_pim[7];		  	
TH1F *hhit_E_pip[7];
TH1F *hhit_Edep_pip[7];		  	
TH1F *hhit_E_eAll_nob[12];
TH1F *hhit_p_eAll_nob[12];
TH1F *hhit_E_eAll[12];
TH1F *hhit_p_eAll[12];
TH1F *hhit_Edep_eAll[12];		  	
TH1F *hhit_E_cut_eAll[12];
TH1F *hhit_p_cut_eAll[12];
TH1F *hhit_E_cut_eAll_nob[12];
TH1F *hhit_p_cut_eAll_nob[12];
TH1F *hhit_E_proton[12];
TH1F *hhit_p_proton[12];
TH1F *hhit_E_beam[12];
TH1F *hhit_p_beam[12];
TH1F *hhit_E_proton_nob[12];
TH1F *hhit_p_proton_nob[12];
TH1F *hhit_E_proton_cut[12];
TH1F *hhit_p_proton_cut[12];
TH1F *hhit_E_beam_cut[12];
TH1F *hhit_p_beam_cut[12];
TH1F *hhit_E_proton_cut_nob[12];
TH1F *hhit_p_proton_cut_nob[12];
TH1F *hhit_Edep_proton[12];		  	
TH1F *hhit_E_pim_LD[12];
TH1F *hhit_p_pim_LD[12];
TH1F *hhit_E_pim_LD_nob[12];
TH1F *hhit_p_pim_LD_nob[12];
TH1F *hhit_Edep_pim_LD[12];		  	
TH1F *hhit_Edep_pip_LD[12];		  	
TH1F *hhit_Edep_pi0_LD[12];		  	
TH1F *hhit_E_pim_cut_LD[12];
TH1F *hhit_p_pim_cut_LD[12];
TH1F *hhit_E_pim_cut_LD_nob[12];
TH1F *hhit_p_pim_cut_LD_nob[12];
TH1F *hhit_E_pip_cut_LD[12];
TH1F *hhit_p_pip_cut_LD[12];
TH1F *hhit_E_pip_cut_LD_nob[12];
TH1F *hhit_p_pip_cut_LD_nob[12];
TH1F *hhit_E_pip_LD[12];
TH1F *hhit_p_pip_LD[12];
TH1F *hhit_E_pi0[12];
TH1F *hhit_p_pi0[12];
TH1F *hhit_E_pi0_nob[12];
TH1F *hhit_p_pi0_nob[12];
TH1F *hhit_E_pi0_cut[12];
TH1F *hhit_p_pi0_cut[12];
TH1F *hhit_E_pi0_cut_nob[12];
TH1F *hhit_p_pi0_cut_nob[12];
TH1F *hhit_E_pi0_cutr[12];
TH1F *hhit_p_pi0_cutr[12];
TH1F *hhit_E_pi0_cutr_nob[12];
TH1F *hhit_p_pi0_cutr_nob[12];
TH1F *hhit_E_pi0_cute[12];
TH1F *hhit_p_pi0_cute[12];
TH1F *hhit_E_pi0_cute_nob[12];
TH1F *hhit_p_pi0_cute_nob[12];

TH1F *hhit_pid_pip_LD_nob[12];
TH1F *hhit_pid_pim_LD_nob[12];
TH1F *hhit_pid_proton_LD_nob[12];
TH1F *hhit_mpid_pip_LD_nob[12];
TH1F *hhit_mpid_pim_LD_nob[12];
TH1F *hhit_mpid_proton_LD_nob[12];
TH1F *hhit_procID_pip_LD_nob[12];
TH1F *hhit_procID_pim_LD_nob[12];
TH1F *hhit_procID_proton_LD_nob[12];

TH1F *hhit_Edepspd2_proton;
TH1F *hhit_Edepspd2_pim;
TH1F *hhit_Edepspd2_pi0;
TH1F *hhit_Edepspd2_pip;
TH1F *hhit_Edepspd2_eAll;
TH1F *hhit_Edepspd1_proton;
TH1F *hhit_Edepspd1_pim;
TH1F *hhit_Edepspd1_pi0;
TH1F *hhit_Edepspd1_pip;
TH1F *hhit_Edepspd1_eAll;
TH1F *hhit_Eend_preshower_r_proc;
TH1F *hhit_Eend_preshower_mother_r_proc;
TH1F *hhit_Eend_preshower_e_proc;
TH1F *hhit_Eend_preshower_mother_e_proc;
TH1F *hhit_Eend_preshower_ep_proc;
TH1F *hhit_Eend_preshower_mother_ep_proc;
TH2F *hit_R_vs_vz_eAll_nob[12];
TH2F *hit_R_vs_vz_eAll[12];
TH2F *hit_R_vs_vz_pim_nob[12];
TH2F *hit_R_vs_vz_pim[12];
TH2F *hit_R_vs_vz_pip_nob[12];
TH2F *hit_R_vs_vz_pip[12];
TH2F *hit_R_vs_vz_proton_nob[12];
TH2F *hit_R_vs_vz_proton[12];
TH2F *hit_R_vs_vz_pi0_nob[12];
TH2F *hit_R_vs_vz_pi0[12];
TH2F *EC_shower_2D_pim;
TH2F *EC_shower_2D_pip;
TH2F *EC_shower_2D_pi0;
TH2F *EC_shower_2D_eAll;
TH2F *EC_shower_2D_proton;
TH2F *EC_shower_2D_pim_trigger;
TH2F *EC_shower_2D_pip_trigger;
TH2F *EC_shower_2D_pi0_trigger;
TH2F *EC_shower_2D_eAll_trigger;
TH2F *EC_shower_2D_proton_trigger;
 EC_shower_2D_eAll = (TH2F*)f13->Get("ec_Eend_2D");

 EC_shower_2D_pi0_trigger = (TH2F*)f10->Get("ec_Eend_2D_trigger");
 EC_shower_2D_eAll_trigger = (TH2F*)f13->Get("ec_Eend_2D_trigger");
 EC_shower_2D_proton_trigger = (TH2F*)f7->Get("ec_Eend_2D_trigger");

 hhit_Edepspd2_proton = (TH1F*)f7->Get("hit_Edepspd2");
 hhit_Edepspd2_pim = (TH1F*)f8->Get("hit_Edepspd2");
 hhit_Edepspd2_pip = (TH1F*)f9->Get("hit_Edepspd2");
 hhit_Edepspd2_pi0 = (TH1F*)f10->Get("hit_Edepspd2");
 hhit_Edepspd2_eAll = (TH1F*)f13->Get("hit_Edepspd2");
 hhit_Edepspd1_proton = (TH1F*)f7->Get("hit_Edepspd1");
 hhit_Edepspd1_pim = (TH1F*)f8->Get("hit_Edepspd1");
 hhit_Edepspd1_pip = (TH1F*)f9->Get("hit_Edepspd1");
 hhit_Edepspd1_pi0 = (TH1F*)f10->Get("hit_Edepspd1");
 hhit_Edepspd1_eAll = (TH1F*)f13->Get("hit_Edepspd1");
 EC_shower_pim = (TH1F*)f8->Get("ec_Eend_shower");
 EC_shower_pip = (TH1F*)f9->Get("ec_Eend_shower");
 EC_shower_pi0 = (TH1F*)f10->Get("ec_Eend_shower");
 EC_shower_eAll = (TH1F*)f13->Get("ec_Eend_shower");
 EC_shower_proton = (TH1F*)f7->Get("ec_Eend_shower");
 EC_preshower_pim = (TH1F*)f8->Get("ec_Eend_preshower");
 EC_preshower_proton = (TH1F*)f7->Get("ec_Eend_preshower");
 EC_preshower_pip = (TH1F*)f9->Get("ec_Eend_preshower");
 EC_preshower_pi0 = (TH1F*)f10->Get("ec_Eend_preshower");
 EC_preshower_eAll = (TH1F*)f13->Get("ec_Eend_preshower");
 EC_shower_pim_trigger = (TH1F*)f8->Get("ec_Eend_shower_trigger");
 EC_shower_pi0_trigger = (TH1F*)f10->Get("ec_Eend_shower_trigger");
 EC_shower_proton_trigger = (TH1F*)f7->Get("ec_Eend_shower_trigger");
 EC_shower_pip_trigger = (TH1F*)f9->Get("ec_Eend_shower_trigger");
 EC_shower_eAll_trigger = (TH1F*)f13->Get("ec_Eend_shower_trigger");
 EC_preshower_pim_trigger = (TH1F*)f8->Get("ec_Eend_preshower_trigger");
 EC_preshower_pi0_trigger = (TH1F*)f10->Get("ec_Eend_preshower_trigger");
 EC_preshower_proton_trigger = (TH1F*)f7->Get("ec_Eend_preshower_trigger");
 EC_preshower_pip_trigger = (TH1F*)f9->Get("ec_Eend_preshower_trigger");
 EC_preshower_eAll_trigger = (TH1F*)f13->Get("ec_Eend_preshower_trigger");
 sc1_pim = (TH1F*)f8->Get("hit_Edepsc1_trigger");
 sc2_pim = (TH1F*)f8->Get("hit_Edepsc2_trigger");
 sc1_pip = (TH1F*)f9->Get("hit_Edepsc1_trigger");
 sc2_pip = (TH1F*)f9->Get("hit_Edepsc2_trigger");
 sc1_eAll = (TH1F*)f13->Get("hit_Edepsc1_trigger");
 sc2_eAll = (TH1F*)f13->Get("hit_Edepsc2_trigger");
 sc1_proton = (TH1F*)f7->Get("hit_Edepsc1_trigger");
 sc2_proton = (TH1F*)f7->Get("hit_Edepsc2_trigger");
 sc1_pi0 = (TH1F*)f10->Get("hit_Edepsc1_trigger");
 sc2_pi0 = (TH1F*)f10->Get("hit_Edepsc2_trigger");
 for(int k=0;k<12;k++){
 hhit_E_cut_eAll[k] = (TH1F*)f13->Get(Form("hit_E_cut_%d",k));
 hhit_p_cut_eAll[k] = (TH1F*)f13->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_eAll[k] = (TH1F*)f13->Get(Form("hit_E_%d",k));
 hhit_p_eAll[k] = (TH1F*)f13->Get(Form("hit_momentum_%d",k));
 hit_R_vs_vz_eAll[k]= (TH2F*)f13->Get(Form("hit_R_vs_vz_%d",k));
 hhit_Edep_eAll[k] = (TH1F*)f13->Get(Form("hit_Edep_%d",k));
 hhit_E_proton[k] = (TH1F*)f7->Get(Form("hit_E_%d",k));
 hhit_p_proton[k] = (TH1F*)f7->Get(Form("hit_momentum_%d",k));
 hhit_E_beam[k] = (TH1F*)f17->Get(Form("hit_E_%d",k));
 hhit_p_beam[k] = (TH1F*)f17->Get(Form("hit_momentum_%d",k));
 hhit_E_pi0[k] = (TH1F*)f10->Get(Form("hit_E_%d",k));
 hhit_p_pi0[k] = (TH1F*)f10->Get(Form("hit_momentum_%d",k));
 hit_R_vs_vz_proton[k]= (TH2F*)f7->Get(Form("hit_R_vs_vz_%d",k));
 hhit_Edep_proton[k] = (TH1F*)f7->Get(Form("hit_Edep_%d",k));
 hhit_E_pim_LD[k] = (TH1F*)f8->Get(Form("hit_E_%d",k));
 hhit_p_pim_LD[k] = (TH1F*)f8->Get(Form("hit_momentum_%d",k));
 hhit_Edep_pim_LD[k] = (TH1F*)f8->Get(Form("hit_Edep_%d",k));
 hhit_E_pim_cut_LD[k] = (TH1F*)f8->Get(Form("hit_E_cut_%d",k));
 hhit_p_pim_cut_LD[k] = (TH1F*)f8->Get(Form("hit_momentum_cut_%d",k));
 hit_R_vs_vz_pim[k]= (TH2F*)f8->Get(Form("hit_R_vs_vz_%d",k));
 hhit_E_pip_LD[k] = (TH1F*)f9->Get(Form("hit_E_%d",k));
 hhit_p_pip_LD[k] = (TH1F*)f9->Get(Form("hit_momentum_%d",k));
 hhit_Edep_pip_LD[k] = (TH1F*)f9->Get(Form("hit_Edep_%d",k));
 hhit_E_pip_cut_LD[k] = (TH1F*)f9->Get(Form("hit_E_cut_%d",k));
 hhit_p_pip_cut_LD[k] = (TH1F*)f9->Get(Form("hit_momentum_cut_%d",k));
 hit_R_vs_vz_pip[k]= (TH2F*)f9->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_pi0[k]= (TH2F*)f10->Get(Form("hit_R_vs_vz_%d",k));
 hhit_E_proton_cut[k] = (TH1F*)f7->Get(Form("hit_E_cut_%d",k));
 hhit_p_proton_cut[k] = (TH1F*)f7->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_beam_cut[k] = (TH1F*)f17->Get(Form("hit_E_cut_%d",k));
 hhit_p_beam_cut[k] = (TH1F*)f17->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pi0_cut[k] = (TH1F*)f10->Get(Form("hit_E_cut_%d",k));
 hhit_p_pi0_cut[k] = (TH1F*)f10->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pi0_cute[k] = (TH1F*)f10->Get(Form("hit_E_cute_%d",k));
 hhit_p_pi0_cute[k] = (TH1F*)f10->Get(Form("hit_momentum_cute_%d",k));
 hhit_E_pi0_cutr[k] = (TH1F*)f10->Get(Form("hit_E_cutr_%d",k));
 hhit_p_pi0_cutr[k] = (TH1F*)f10->Get(Form("hit_momentum_cutr_%d",k));
 }
 TCanvas *c[17];
 c[8] = new TCanvas("c[8]","c[8]",1000,1000);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
 EC_shower_pip->Scale(0.001);
 EC_shower_pip->Rebin(rebinfac);
 EC_shower_pip->GetYaxis()->SetRangeUser(1e-3,1e1);
 EC_shower_pip->GetXaxis()->SetRangeUser(0,100);
 EC_shower_pip->GetYaxis()->SetTitle("rate (kHz)");
 EC_shower_pip->SetLineColor(2);
 EC_shower_pip->SetTitle("shower Edep");
 EC_shower_pip->Draw("HIST");
double rate_pip= EC_shower_pip->Integral();
 EC_shower_pim->Scale(0.001);
 EC_shower_pim->Rebin(rebinfac);
 EC_shower_pim->SetLineColor(1);
 EC_shower_pim->Draw(" same HIST");
double rate_pim= EC_shower_pim->Integral();
 EC_shower_pi0->Scale(0.001);
 EC_shower_pi0->Rebin(rebinfac);
 EC_shower_pi0->SetLineColor(kGreen+3);
 EC_shower_pi0->Draw(" same HIST");
double rate_pi0= EC_shower_pi0->Integral();
 EC_shower_eAll->SetLineColor(4);
 EC_shower_eAll->Rebin(rebinfac);
 EC_shower_eAll->Draw(" same HIST");
double rate_eAll= EC_shower_eAll->Integral();
 EC_shower_proton->Scale(0.001);
 EC_shower_proton->SetLineColor(6);
 EC_shower_proton->Rebin(rebinfac);
 EC_shower_proton->Draw(" same HIST");
double rate_proton= EC_shower_proton->Integral();
  TLegend *leg8 = new TLegend(0.45,0.6,0.8,0.88);
  leg8->AddEntry(EC_shower_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll),"l");
  leg8->AddEntry(EC_shower_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim),"l");
  leg8->AddEntry(EC_shower_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip),"l");
  leg8->AddEntry(EC_shower_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0),"l");
  leg8->AddEntry(EC_shower_proton,Form("bggen proton; total rate=%f kHz",rate_proton),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
  cout<<"rate eAll="<<rate_eAll<<"  "<<"rate_pim="<<rate_pim<<"  "<<"rate_pip="<<rate_pip<<endl;
 c[7] = new TCanvas("c[7]","c[7]",1000,800);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_pip->SetLineColor(2);
 EC_preshower_pip->Scale(0.001);
 EC_preshower_pip->GetYaxis()->SetRangeUser(1e-3,1e1);
 EC_preshower_pip->GetXaxis()->SetRangeUser(0,50);
 EC_preshower_pip->GetYaxis()->SetTitle("rate (kHz)");
 EC_preshower_pip->SetTitle("preshower Edep");
 EC_preshower_pip->Draw("HIST");
double rate_pip_pre= EC_preshower_pip->Integral();
 EC_preshower_pim->Scale(0.001);
 EC_preshower_pim->SetLineColor(1);
 EC_preshower_pim->Draw("same HIST");
double rate_pim_pre= EC_preshower_pim->Integral();
 EC_preshower_pi0->Scale(0.001);
 EC_preshower_pi0->SetLineColor(kGreen+3);
 EC_preshower_pi0->Draw("same HIST");
double rate_pi0_pre= EC_preshower_pi0->Integral();
 EC_preshower_eAll->SetLineColor(4);
// EC_preshower_eAll->Scale(1000);
 //EC_preshower_eAll->Rebin(rebinfac);
 EC_preshower_eAll->Draw(" same HIST");
double rate_eAll_pre= EC_preshower_eAll->Integral();
 EC_preshower_proton->Scale(0.001);
 EC_preshower_proton->SetLineColor(6);
 EC_preshower_proton->Rebin(rebinfac);
 EC_preshower_proton->Draw(" same HIST");
double rate_proton_pre= EC_preshower_proton->Integral();
  TLegend *leg1 = new TLegend(0.45,0.6,0.8,0.88);
  leg1->AddEntry(EC_preshower_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_pre),"l");
  leg1->AddEntry(EC_preshower_proton,Form("bggen proton; total rate=%f kHz",rate_proton_pre),"l");
  leg1->AddEntry(EC_preshower_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_pre),"l");
  leg1->AddEntry(EC_preshower_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_pre),"l");
  leg1->AddEntry(EC_preshower_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_pre),"l");
  leg1->SetTextSize(0.03);
  leg1->SetBorderSize(0);
  leg1->SetFillColor(0);
  leg1->Draw("text same");
 c[6] = new TCanvas("c[6]","c[6]",1000,1000);
 c[6]->Divide(1,2);
 c[6]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc1_pip->SetLineColor(2);
 sc1_pip->Scale(0.001);
 sc1_pip->GetYaxis()->SetTitle("rate (kHz)");
 sc1_pip->SetTitle("SC0");
 sc1_pip->GetXaxis()->SetTitle("Edep (MeV)");
 sc1_pip->GetXaxis()->SetRangeUser(0,100);
 sc1_pip->GetYaxis()->SetRangeUser(1e-2,1e1);
 sc1_pip->Draw("HIST");
 double rate_pip_sc1= sc1_pip->Integral();
 sc1_pim->SetLineColor(1);
 sc1_pim->Scale(0.001);
 sc1_pim->Draw("same HIST");
 double rate_pim_sc1= sc1_pim->Integral();
 sc1_eAll->SetLineColor(4);
 //sc1_eAll->Scale(1000);
 sc1_eAll->Draw("same HIST");
 double rate_eAll_sc1= sc1_eAll->Integral();
 sc1_proton->SetLineColor(6);
 sc1_proton->Scale(0.001);
 sc1_proton->Draw("same HIST");
 double rate_proton_sc1= sc1_proton->Integral();
 sc1_pi0->SetLineColor(kGreen+3);
 sc1_pi0->Scale(0.001);
 sc1_pi0->Draw("same HIST");
 double rate_pi0_sc1= sc1_pi0->Integral();
  TLegend *leg21 = new TLegend(0.45,0.4,0.8,0.68);
  leg21->AddEntry(sc1_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_sc1),"l");
  leg21->AddEntry(sc1_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_sc1),"l");
  leg21->AddEntry(sc1_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_sc1),"l");
  leg21->AddEntry(sc1_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_sc1),"l");
  leg21->AddEntry(sc1_proton,Form("bggen proton; total rate=%f kHz",rate_proton_sc1),"l");
  leg21->SetTextSize(0.05);
  leg21->SetBorderSize(0);
  leg21->SetFillColor(0);
  leg21->Draw("text same");
 c[6]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc2_pip->SetLineColor(2);
 sc2_pip->Scale(0.001);
 sc2_pip->SetTitle("SC1");
 sc2_pip->GetXaxis()->SetTitle("Edep (MeV)");
 sc2_pip->GetYaxis()->SetTitle("rate (kHz)");
 sc2_pip->GetYaxis()->SetRangeUser(1e-2,1e1);
 sc2_pip->GetXaxis()->SetRangeUser(0,100);
 sc2_pip->Draw("HIST");
 double rate_pip_sc2= sc2_pip->Integral();
 sc2_pim->SetLineColor(1);
 sc2_pim->Scale(0.001);
 sc2_pim->Draw("same HIST");
 double rate_pim_sc2= sc2_pim->Integral();
 sc2_eAll->SetLineColor(4);
 sc2_eAll->Draw("same HIST");
 double rate_eAll_sc2= sc2_eAll->Integral();
 sc2_proton->SetLineColor(6);
 sc2_proton->Scale(0.001);
 sc2_proton->Draw("same HIST");
 sc2_pi0->SetLineColor(kGreen+3);
 sc2_pi0->Scale(0.001);
 sc2_pi0->Draw("same HIST");
 double rate_pi0_sc2= sc2_pi0->Integral();
 leg21->Draw("text same");
  cout<<"rate eAll_S2="<<rate_eAll_sc2<<"rate eAll_S1="<<rate_eAll_sc1<<"  "<<"rate_pim_s1="<<rate_pim_sc1<<"  "<<"rate_pim_s2="<<rate_pim_sc2<<"rate_pip_s1="<<rate_pip_sc1<<"rate_pip_s2="<<rate_pip_sc2<<endl;
 /*c[2] = new TCanvas("c[2]","c[2]",1000,1000);
 c[2]->Divide(3,2);
 for(int j=2;j<7;j++){
 c[2]->cd(j-1);
  gPad->SetGridx();
  gPad->SetGridy();
 hhit_E_pip[j]->SetLineColor(2);
 hhit_E_pip[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_pip[j]->GetXaxis()->SetTitle("E (GeV)");
 hhit_E_pip[j]->GetYaxis()->SetTitle("rate (Hz)");
 hhit_E_pip[j]->Draw("HIST");
 hhit_E_pim[j]->SetLineColor(1);
 hhit_E_pim[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_pim[j]->Draw("same HIST");
 hhit_p_pim[j]->SetLineColor(6);
 hhit_p_pim[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_p_pim[j]->Draw("same HIST");
 hhit_E_eAll[j]->SetLineColor(4);
 hhit_E_eAll[j]->GetXaxis()->SetRangeUser(0,2);
 hhit_E_eAll[j]->Scale(1000);
 hhit_E_eAll[j]->Draw("same HIST");
 //leg11->Draw("text same");
 }
 c[2]->cd(1);
  TLegend *leg11 = new TLegend(0.45,0.4,0.8,0.68);
  leg11->AddEntry(hhit_E_eAll[2],"eAll*1000","l");
  leg11->AddEntry(hhit_E_pip[2],"bggen #pi^{+}","l");
  leg11->AddEntry(hhit_E_pim[2],"bggen #pi^{-}","l");
  leg11->AddEntry(hhit_p_pim[2],"bggen #pi^{-}","l");
  leg11->SetTextSize(0.05);
  leg11->SetBorderSize(0);
  leg11->SetFillColor(0);
  leg11->Draw("text same");*/
 c[5] = new TCanvas("c[5]","c[5]",1000,1000);
 c[5]->Divide(1,2);
 c[5]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd1_pip->SetLineColor(2);
  hhit_Edepspd1_pip->Scale(0.001);
  hhit_Edepspd1_pip->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd1_pip->SetTitle("SPD, SC0 and SC1 trigger");
  hhit_Edepspd1_pip->Draw("HIST");
 double rate_pip_spd1= hhit_Edepspd1_pip->Integral();
  hhit_Edepspd1_pim->SetLineColor(1);
  hhit_Edepspd1_pim->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd1_pim->Scale(0.001);
  hhit_Edepspd1_pim->Draw("same HIST");
 double rate_pim_spd1= hhit_Edepspd1_pim->Integral();
  hhit_Edepspd1_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd1_pi0->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd1_pi0->Scale(0.001);
  hhit_Edepspd1_pi0->Draw("same HIST");
 double rate_pi0_spd1= hhit_Edepspd1_pi0->Integral();
  hhit_Edepspd1_proton->SetLineColor(6);
  hhit_Edepspd1_proton->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd1_proton->Scale(0.001);
  hhit_Edepspd1_proton->Draw("same HIST");
 double rate_proton_spd1= hhit_Edepspd1_proton->Integral();
  hhit_Edepspd1_eAll->SetLineColor(4);
  hhit_Edepspd1_eAll->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd1_eAll->Draw("same HIST");
 double rate_eAll_spd1= hhit_Edepspd1_eAll->Integral();
  TLegend *leg13 = new TLegend(0.45,0.4,0.8,0.68);
  leg13->AddEntry(hhit_Edepspd1_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_proton,Form("bggen proton; total rate=%f kHz",rate_proton_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_spd1),"l");
  leg13->SetTextSize(0.06);
  leg13->SetBorderSize(0);
  leg13->SetFillColor(0);
  leg13->Draw("text same");
  c[5]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd2_pip->SetLineColor(2);
  hhit_Edepspd2_pip->Scale(0.001);
  hhit_Edepspd2_pip->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd2_pip->SetTitle("LASPD, SC0 and SC1 trigger");
  hhit_Edepspd2_pip->Draw("HIST");
 double rate_pip_spd2= hhit_Edepspd2_pip->Integral();
  hhit_Edepspd2_pim->SetLineColor(1);
  hhit_Edepspd2_pim->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd2_pim->Scale(0.001);
  hhit_Edepspd2_pim->Draw("same HIST");
 double rate_pim_spd2= hhit_Edepspd2_pim->Integral();
  hhit_Edepspd2_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd2_pi0->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd2_pi0->Scale(0.001);
  hhit_Edepspd2_pi0->Draw("same HIST");
 double rate_pi0_spd2= hhit_Edepspd2_pi0->Integral();
  hhit_Edepspd2_proton->SetLineColor(6);
  hhit_Edepspd2_proton->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd2_proton->Scale(0.001);
  hhit_Edepspd2_proton->Draw("same HIST");
 double rate_proton_spd2= hhit_Edepspd2_proton->Integral();
  hhit_Edepspd2_eAll->SetLineColor(4);
  hhit_Edepspd2_eAll->GetYaxis()->SetRangeUser(1e-3,1e1);
  hhit_Edepspd2_eAll->Draw("same HIST");
 double rate_eAll_spd2= hhit_Edepspd2_eAll->Integral();
  TLegend *leg14 = new TLegend(0.15,0.4,0.8,0.68);
  leg14->AddEntry(hhit_Edepspd2_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_proton,Form("bggen proton; total rate=%f kHz",rate_proton_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_spd2),"l");
  leg14->SetTextSize(0.06);
  leg14->SetBorderSize(0);
  leg14->SetFillColor(0);
  leg14->Draw("text same");
 c[0] = new TCanvas("c[0]","c[0]",1000,1000);
/* hhit_Edepspd2_proton->SetLineColor(2);
 hhit_Edepspd2_proton->Draw("HIST");
 hhit_Edepspd2_pim->SetLineColor(1);
 hhit_Edepspd2_pim->Draw("same HIST");*/
 c[0]->Divide(3,4);
 for(int m=0;m<12;m++){
  c[0]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
  gPad->SetLogy();
  hhit_p_proton_cut[m]->SetLineColor(kOrange-3);
  hhit_p_proton_cut[m]->GetXaxis()->SetTitle("FP_tid1 momentum (GeV)");
  hhit_p_proton_cut[m]->GetYaxis()->SetTitle("rate (kHz)");
  hhit_p_proton_cut[m]->GetYaxis()->SetLabelSize(0.04);
  hhit_p_proton_cut[m]->GetXaxis()->SetLabelSize(0.04);
  hhit_p_proton_cut[m]->Scale(0.001);
  hhit_p_proton_cut[m]->Rebin(rebinfac2);
  hhit_p_proton_cut[m]->GetYaxis()->SetRangeUser(1e-4,1e5);
  hhit_p_proton_cut[m]->GetXaxis()->SetRangeUser(0,7);
  hhit_p_proton_cut[m]->Draw("HIST");
  hhit_p_pip_cut_LD[m]->SetLineColor(2);
  hhit_p_pip_cut_LD[m]->Scale(0.001);
  hhit_p_pip_cut_LD[m]->Rebin(rebinfac2);
  hhit_p_pip_cut_LD[m]->Draw("same HIST");
  hhit_p_pim_cut_LD[m]->SetLineColor(1);
  hhit_p_pim_cut_LD[m]->Scale(0.001);
  hhit_p_pim_cut_LD[m]->Rebin(rebinfac2);
  hhit_p_pim_cut_LD[m]->Draw("same HIST");
  hhit_p_pi0_cut[m]->SetLineColor(6);
  hhit_p_pi0_cut[m]->Scale(0.001);
  hhit_p_pi0_cut[m]->Rebin(rebinfac2);
  hhit_p_pi0_cut[m]->Draw("same HIST");
  hhit_p_pi0_cutr[m]->SetLineColor(8);
  hhit_p_pi0_cutr[m]->Scale(0.001);
  hhit_p_pi0_cutr[m]->Rebin(rebinfac2);
  hhit_p_pi0_cutr[m]->Draw("same HIST");
  hhit_p_cut_eAll[m]->SetLineColor(4);
  //hhit_p_cut_eAll[m]->Scale(0.001);
  hhit_p_cut_eAll[m]->Rebin(rebinfac2);
  hhit_p_cut_eAll[m]->Draw("same HIST");
  hhit_p_beam_cut[m]->SetLineColor(7);
  hhit_p_beam_cut[m]->Scale(0.001);
  hhit_p_beam_cut[m]->Rebin(rebinfac2);
  hhit_p_beam_cut[m]->Draw("same HIST");
  }
 c[0]->cd(1);
  TLegend *leg12 = new TLegend(0.15,0.6,0.6,0.88);
  leg12->AddEntry(hhit_p_cut_eAll[2]," e^{-} from eAll*1000","l");
  leg12->AddEntry(hhit_p_pip_cut_LD[2],"#pi^{+} from bggen #pi^{+}","l");
  leg12->AddEntry(hhit_p_pim_cut_LD[2],"#pi^{-} from bggen #pi^{-}","l");
  leg12->AddEntry(hhit_p_pi0_cut[2]," e^{-} and e^{+} from  #pi^{0}","l");
  leg12->AddEntry(hhit_p_pi0_cutr[2]," #gamma from #pi^{0}","l");
  leg12->AddEntry(hhit_p_proton_cut[2],"from BeamOnTarget","l");
  leg12->AddEntry(hhit_p_beam_cut[2],"from BeamOnTarget+30x30x1cm3 ploly","l");
  leg12->SetTextSize(0.07);
  leg12->SetBorderSize(0);
  leg12->SetFillColor(0);
  leg12->Draw("text same");
 c[2] = new TCanvas("c[2]","c[2]",1000,1000);
 c[2]->Divide(3,4);
 for(int m=0;m<12;m++){
  c[2]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
  gPad->SetLogy();
  hhit_E_proton[m]->SetLineColor(kOrange-3);
  hhit_E_proton[m]->GetXaxis()->SetTitle("total_E (GeV)");
  hhit_E_proton[m]->GetYaxis()->SetTitle("rate (kHz)");
  hhit_E_proton[m]->Rebin(rebinfac2);
  hhit_E_proton[m]->Scale(0.001);
  hhit_E_proton[m]->GetYaxis()->SetRangeUser(1e-4,1e5);
  hhit_E_proton[m]->GetXaxis()->SetRangeUser(0,7);
  hhit_E_proton[m]->GetYaxis()->SetLabelSize(0.04);
  hhit_E_proton[m]->GetXaxis()->SetLabelSize(0.04);
  hhit_E_proton[m]->Draw("HIST");
  hhit_E_pip_LD[m]->SetLineColor(2);
  hhit_E_pip_LD[m]->Rebin(rebinfac2);
  hhit_E_pip_LD[m]->Scale(0.001);
  hhit_E_pip_LD[m]->Draw("same HIST");
  hhit_E_pim_LD[m]->SetLineColor(1);
  hhit_E_pim_LD[m]->Rebin(rebinfac2);
  hhit_E_pim_LD[m]->Scale(0.001);
  hhit_E_pim_LD[m]->Draw("same HIST");
  hhit_E_eAll[m]->SetLineColor(4);
  hhit_E_eAll[m]->Rebin(rebinfac2);
//  hhit_E_eAll[m]->Scale(0.001);
  hhit_E_eAll[m]->Draw("same HIST");
  hhit_E_pi0[m]->SetLineColor(6);
  hhit_E_pi0[m]->Rebin(rebinfac2);
  hhit_E_pi0[m]->Scale(0.001);
  hhit_E_pi0[m]->Draw("same HIST");
  hhit_E_beam[m]->SetLineColor(7);
  hhit_E_beam[m]->Scale(0.001);
  hhit_E_beam[m]->Rebin(rebinfac2);
  hhit_E_beam[m]->Draw("same HIST");
  }
 c[2]->cd(2);
  TLegend *leg122 = new TLegend(0.15,0.5,0.65,0.88);
  leg122->AddEntry(hhit_E_eAll[2],"from eAll*1000","l");
  leg122->AddEntry(hhit_E_pip_LD[2],"from bggen #pi^{+}","l");
  leg122->AddEntry(hhit_E_pim_LD[2],"from bggen #pi^{-}","l");
  leg122->AddEntry(hhit_E_proton[2],"from BeamOnTarget","l");
  leg122->AddEntry(hhit_E_beam[2],"from BeamOnTarget+30x30x1cm3 poly","l");
  leg122->AddEntry(hhit_E_pi0[2],"from bggen #pi^{0}","l");
  leg122->SetTextSize(0.06);
  leg122->SetBorderSize(0);
  leg122->SetFillColor(0);
  leg122->Draw("text same");
 c[3] = new TCanvas("c[3]","c[3]",1000,1000);
 c[3]->Divide(3,3);
 for(int m=0;m<9;m++){
  c[3]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
 gPad->SetLogy();
  hhit_p_proton[m]->SetLineColor(8);
  hhit_p_proton[m]->GetXaxis()->SetTitle("momentum (GeV/c)");
  hhit_p_proton[m]->GetYaxis()->SetTitle("rate (kHz)");
  hhit_p_proton[m]->Scale(0.001);
  hhit_p_proton[m]->GetYaxis()->SetRangeUser(1e-3,1e7);
  hhit_p_proton[m]->Draw("HIST");
  hhit_p_pip_LD[m]->SetLineColor(2);
  hhit_p_pip_LD[m]->Scale(0.001);
  hhit_p_pip_LD[m]->Draw("same HIST");
  hhit_p_pim_LD[m]->SetLineColor(1);
  hhit_p_pim_LD[m]->Scale(0.001);
  hhit_p_pim_LD[m]->Draw("same HIST");
  hhit_p_eAll[m]->SetLineColor(4);
  hhit_p_eAll[m]->Scale(0.001);
  hhit_p_eAll[m]->Draw("same HIST");
  hhit_p_pi0[m]->SetLineColor(6);
  hhit_p_pi0[m]->Scale(0.001);
  hhit_p_pi0[m]->Draw("same HIST");
 }
 c[3]->cd(2);
 leg122->Draw("text same");

 c[1] = new TCanvas("c[1]","c[1]",1000,1000);
 c[1]->Divide(3,4);
 for(int m=0;m<12;m++){
  c[1]->cd(m+1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_E_proton_cut[m]->SetLineColor(kOrange-3);
  hhit_E_proton_cut[m]->GetXaxis()->SetTitle("FP_tid1 momentum (GeV)");
  hhit_E_proton_cut[m]->GetYaxis()->SetTitle("rate (kHz)");
  hhit_E_proton_cut[m]->GetYaxis()->SetLabelSize(0.04);
  hhit_E_proton_cut[m]->GetXaxis()->SetLabelSize(0.04);
  hhit_E_proton_cut[m]->Scale(0.001);
  hhit_E_proton_cut[m]->Rebin(rebinfac2);
  hhit_E_proton_cut[m]->GetYaxis()->SetRangeUser(1e-4,1e5);
  hhit_E_proton_cut[m]->GetXaxis()->SetRangeUser(0,7);
  hhit_E_proton_cut[m]->Draw("HIST");
  hhit_E_cut_eAll[m]->SetLineColor(4);
  hhit_E_cut_eAll[m]->Rebin(rebinfac2);
//  hhit_E_cut_eAll[m]->Scale(0.001);
  hhit_E_cut_eAll[m]->GetYaxis()->SetRangeUser(1e-4,1e3);
  hhit_E_cut_eAll[m]->GetXaxis()->SetRangeUser(0,7);
  hhit_E_cut_eAll[m]->Draw("same HIST");
  hhit_E_pip_cut_LD[m]->SetLineColor(2);
  hhit_E_pip_cut_LD[m]->Rebin(rebinfac2);
  hhit_E_pip_cut_LD[m]->Scale(0.001);
  hhit_E_pip_cut_LD[m]->Draw("same HIST");
  hhit_E_pim_cut_LD[m]->SetLineColor(1);
  hhit_E_pim_cut_LD[m]->Rebin(rebinfac2);
  hhit_E_pim_cut_LD[m]->Scale(0.001);
  hhit_E_pim_cut_LD[m]->Draw("same HIST");
  hhit_E_pi0_cutr[m]->SetLineColor(8);
  hhit_E_pi0_cutr[m]->Rebin(rebinfac2);
  hhit_E_pi0_cutr[m]->Scale(0.001);
  hhit_E_pi0_cutr[m]->Draw("same HIST");
  hhit_E_pi0_cut[m]->SetLineColor(6);
  hhit_E_pi0_cut[m]->Rebin(rebinfac2);
  hhit_E_pi0_cut[m]->Scale(0.001);
  hhit_E_pi0_cut[m]->Draw("same HIST");
  hhit_E_pi0_cute[m]->SetLineColor(7);
  hhit_E_pi0_cute[m]->Rebin(rebinfac2);
  hhit_E_pi0_cute[m]->Scale(0.001);
  //hhit_E_pi0_cute[m]->Draw("same HIST");
  hhit_E_beam_cut[m]->SetLineColor(7);
  hhit_E_beam_cut[m]->Scale(0.001);
  hhit_E_beam_cut[m]->Rebin(rebinfac2);
  hhit_E_beam_cut[m]->Draw("same HIST");
}
 c[1]->cd(1);
 /* TLegend *leg120 = new TLegend(0.45,0.6,0.8,0.88);
  leg120->AddEntry(hhit_E_pi0_cut[2],"e^{+} from #pi^{0}","l");
  leg120->AddEntry(hhit_E_pi0_cute[2],"e^{-} from #pi^{0}","l");
  leg120->AddEntry(hhit_E_pi0_cutr[2],"#gamma from #pi^{0}","l");
  leg120->SetTextSize(0.06);
  leg120->SetBorderSize(0);
  leg120->SetFillColor(0);*/
  leg12->Draw("text same");
 c[4] = new TCanvas("c[4]","c[4]",1000,1000);
 c[4]->Divide(3,3);
 for(int m=0;m<9;m++){
  c[4]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
  hit_R_vs_vz_pim[m]->Draw("COLZ"); 
  hit_R_vs_vz_pim[m]->GetXaxis()->SetTitle("vertex z (cm)"); 
  hit_R_vs_vz_pim[m]->GetYaxis()->SetTitle("vertex R (cm)"); 
  //hhit_pid_proton_LD_nob[m]->GetXaxis()->SetRangeUser(-25,25);
  /*hhit_pid_proton_LD_nob[m]->GetXaxis()->SetTitle("particle ID");
  hhit_pid_proton_LD_nob[m]->GetYaxis()->SetTitle("rate (Hz)");
  hhit_pid_proton_LD_nob[m]->Draw(); */
  }
/* c[11] = new TCanvas("c[11]","c[11]",1000,1000);
 c[11]->Divide(3,3);
 for(int m=0;m<9;m++){
  c[11]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
 gPad->SetLogy();
  hhit_mpid_proton_LD_nob[m]->GetXaxis()->SetTitle("mother particle ID");
  hhit_mpid_proton_LD_nob[m]->GetYaxis()->SetTitle("rate (Hz)");
  hhit_mpid_proton_LD_nob[m]->Draw(); 
  }
 c[12] = new TCanvas("c[12]","c[12]",1000,1000);
 c[12]->Divide(3,3);
 for(int m=0;m<9;m++){
 c[12]->cd(m+1);
gPad->SetGridx();
gPad->SetGridy();
 gPad->SetLogy();
  hhit_procID_proton_LD_nob[m]->GetXaxis()->SetTitle("process ID");
  hhit_procID_proton_LD_nob[m]->GetYaxis()->SetTitle("rate (Hz)");
  hhit_procID_proton_LD_nob[m]->Draw(); 
  }*/
 /*c[13] = new TCanvas("c[13]","c[13]",1000,1000);
 EC_shower_2D_eAll->Draw("COLZ");
// EC_shower_2D_pim_trigger->SetMarkerColor(2);
 EC_shower_2D_pim->SetMarkerColor(2);
 EC_shower_2D_pim->Draw("same");
 EC_shower_2D_pip->SetMarkerColor(6);
 EC_shower_2D_pip->Draw("same");
 EC_shower_2D_pi0->SetMarkerColor(3);
 EC_shower_2D_pi0->Draw("same");
 EC_shower_2D_proton->SetMarkerColor(7);
 EC_shower_2D_proton->Draw("same");
  TLegend *leg223 = new TLegend(0.4,0.35,0.8,0.68);
  leg223->AddEntry(EC_shower_2D_eAll,"eAll","p");
  leg223->AddEntry(EC_shower_2D_pim,"bggen #pi^{-}","p");
  leg223->AddEntry(EC_shower_2D_pip,"bggen #pi^{+}","p");
  leg223->AddEntry(EC_shower_2D_pi0,"bggen #pi^{0}","p");
  leg223->AddEntry(EC_shower_2D_proton,"bggen proton","p");
  leg223->SetTextSize(0.06);
  leg223->SetBorderSize(0);
  leg223->SetFillColor(0);
  leg223->Draw("text same");*/

  /*c[0]->cd(1);
  TLegend *leg22 = new TLegend(0.4,0.35,0.8,0.48);
  leg22->AddEntry(hit_R_vs_vz_pip[1],"bggen #pi^{0}","p");
  leg22->SetTextSize(0.06);
  leg22->SetBorderSize(0);
  leg22->SetFillColor(0);
  leg22->Draw("text same");*/
 /*c[14] = new TCanvas("c[14]","c[14]",1000,1000);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
 TH1F *EC_preshower_gamma_e =(TH1F*) EC_preshower_pi0_r->Clone();
 EC_preshower_gamma_e ->Add(EC_preshower_pi0_e);
 EC_preshower_gamma_e ->Add(EC_preshower_pi0_ep);
 EC_preshower_pi0_all->SetLineColor(4); 
 EC_preshower_pi0_all->GetYaxis()->SetTitle("rate (kHZ)");
 EC_preshower_pi0_all->GetXaxis()->SetTitle("preshower Eend (MeV)"); 
 EC_preshower_pi0_all->SetTitle("Prehower Scintillator, #pi^{0} file"); 
 EC_preshower_pi0_all->GetYaxis()->SetTitleOffset(1.1);; 
 EC_preshower_pi0_all->Scale(0.001);
 EC_preshower_pi0_all->GetYaxis()->SetRangeUser(1e-3,2e1);; 
 EC_preshower_pi0_all->Draw("HIST");
 EC_preshower_pi0_r->SetLineColor(46); 
 EC_preshower_pi0_r->Scale(0.001);
 EC_preshower_pi0_r->Draw("same HIST");
 EC_preshower_mother_pi0_r->SetLineColor(1); 
 EC_preshower_mother_pi0_r->Scale(0.001);
 EC_preshower_mother_pi0_r->Draw("same HIST");
 EC_preshower_mother_pi0_ep->SetLineColor(2); 
 EC_preshower_mother_pi0_ep->Scale(0.001);
 EC_preshower_mother_pi0_ep->Draw("same HIST");
 EC_preshower_mother_pi0_e->SetLineColor(6); 
 EC_preshower_mother_pi0_e->Scale(0.001);
 EC_preshower_mother_pi0_e->Draw("same HIST");
 EC_preshower_pi0_ep->SetLineColor(7); 
 EC_preshower_pi0_ep->Scale(0.001);
 EC_preshower_pi0_ep->Draw("same HIST");
 EC_preshower_pi0_e->SetLineColor(8); 
 EC_preshower_pi0_e->Scale(0.001);
 EC_preshower_pi0_e->Draw("same HIST");
 EC_preshower_gamma_e->Scale(0.001);
 EC_preshower_gamma_e->SetLineColor(5);
// EC_preshower_gamma_e->Draw("same HIST");

  TLegend *leg225 = new TLegend(0.4,0.35,0.8,0.88);
  leg225->AddEntry(EC_preshower_pi0_all,"preshower Eend>0","l");
  leg225->AddEntry(EC_preshower_pi0_r,"#gamma hit on preshower Vplane","l");
  leg225->AddEntry(EC_preshower_pi0_ep,"e^{+} ","l");
  leg225->AddEntry(EC_preshower_pi0_e,"e^{-} ","l");
 // leg225->AddEntry(EC_preshower_gamma_e,"e^{-}+e^{+}+#gamma ","l");
  leg225->AddEntry(EC_preshower_mother_pi0_r,"#gamma from bggen #pi^{0}","l");
  leg225->AddEntry(EC_preshower_mother_pi0_ep,"e^{+} from #gamma","l");
  leg225->AddEntry(EC_preshower_mother_pi0_e,"e^{-} from #gamma","l");
  leg225->SetTextSize(0.06);
  leg225->SetBorderSize(0);
  leg225->SetFillColor(0);
  leg225->Draw("text same");*/
/* c[15] = new TCanvas("c[15]","c[15]",1000,1000);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
 TH1F *EC_shower_gamma_e =(TH1F*) EC_shower_pi0_r->Clone();
 EC_shower_pi0_all->SetLineColor(4); 
 EC_shower_pi0_all->GetYaxis()->SetTitle("rate (kHZ)");
 EC_shower_pi0_all->GetXaxis()->SetTitle("shower Eend (MeV)"); 
 EC_shower_pi0_all->SetTitle("Shower Scintillator, #pi^{0} file"); 
 EC_shower_pi0_all->Scale(0.001);
 EC_shower_pi0_all->GetYaxis()->SetTitleOffset(1.1);; 
 EC_shower_pi0_all->GetYaxis()->SetRangeUser(1e-3,2e1);; 
 EC_shower_pi0_all->Draw("HIST");
 EC_shower_pi0_r->SetLineColor(46); 
 EC_shower_pi0_r->Scale(0.001);
 EC_shower_pi0_r->Draw("same HIST");
 EC_shower_mother_pi0_r->SetLineColor(1); 
 EC_shower_mother_pi0_r->Scale(0.001);
 EC_shower_mother_pi0_r->Draw("same HIST");
 EC_shower_mother_pi0_ep->SetLineColor(2); 
 EC_shower_mother_pi0_ep->Scale(0.001);
 EC_shower_mother_pi0_ep->Draw("same HIST");
 EC_shower_mother_pi0_e->SetLineColor(6); 
 EC_shower_mother_pi0_e->Scale(0.001);
 EC_shower_mother_pi0_e->Draw("same HIST");
 EC_shower_pi0_ep->SetLineColor(7); 
 EC_shower_pi0_ep->Scale(0.001);
 EC_shower_pi0_ep->Draw("same HIST");
 EC_shower_pi0_e->SetLineColor(8); 
 EC_shower_pi0_e->Scale(0.001);
 EC_shower_pi0_e->Draw("same HIST");
 EC_shower_gamma_e->Scale(0.001);
 EC_shower_gamma_e->SetLineColor(5);
// EC_shower_gamma_e->Draw("same HIST");
  TLegend *leg224 = new TLegend(0.4,0.35,0.85,0.88);
  leg224->AddEntry(EC_shower_pi0_all,"shower Eend>0 ","l");
  leg224->AddEntry(EC_shower_pi0_r,"#gamma hit on preshower Vplane","l");
  leg224->AddEntry(EC_shower_pi0_ep,"e^{+} ","l");
  leg224->AddEntry(EC_shower_pi0_e,"e^{-} ","l");
 // leg224->AddEntry(EC_shower_gamma_e,"e^{-}+e^{+}+#gamma ","l");
  leg224->AddEntry(EC_shower_mother_pi0_r,"#gamma from bggen #pi^{0}","l");
  leg224->AddEntry(EC_shower_mother_pi0_ep,"e^{+} from #gamma","l");
  leg224->AddEntry(EC_shower_mother_pi0_e,"e^{-} from #gamma","l");
  leg224->SetTextSize(0.06);
  leg224->SetBorderSize(0);
  leg224->SetFillColor(0);
  leg224->Draw("text same");
 c[16] = new TCanvas("c[16]","c[16]",1000,1000);
 c[16]->Divide(2,2);
 c[16]->cd(1);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
  hhit_Eend_preshower_e_proc->SetLineColor(1);
  hhit_Eend_preshower_e_proc->GetYaxis()->SetTitleOffset(1.1);; 
  hhit_Eend_preshower_e_proc->GetYaxis()->SetTitle("preshower hit");
  hhit_Eend_preshower_e_proc->GetXaxis()->SetTitle("preshower procID");
  hhit_Eend_preshower_e_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_e_proc->Draw("HIST");
  hhit_Eend_preshower_mother_e_proc->SetLineColor(2);
  hhit_Eend_preshower_mother_e_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_mother_e_proc->Draw("same HIST");
  TLegend *leg227 = new TLegend(0.3,0.35,0.85,0.88);
  leg227->AddEntry(hhit_Eend_preshower_e_proc,"e^{-}, bggen #pi^{0} file","l");
  leg227->AddEntry(hhit_Eend_preshower_mother_e_proc,"e^{-} from #gamma, bggen #pi^{0} file ","l");
  leg227->SetTextSize(0.06);
  leg227->SetBorderSize(0);
  leg227->SetFillColor(0);
  leg227->Draw("text same");
 c[16]->cd(2);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
  hhit_Eend_preshower_ep_proc->SetLineColor(1);
 hhit_Eend_preshower_ep_proc->GetYaxis()->SetTitleOffset(1.1);; 
  hhit_Eend_preshower_ep_proc->GetYaxis()->SetTitle("preshower hit");
  hhit_Eend_preshower_ep_proc->GetXaxis()->SetTitle("preshower procID");
  hhit_Eend_preshower_ep_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_ep_proc->Draw("HIST");
  hhit_Eend_preshower_mother_ep_proc->SetLineColor(2);
  hhit_Eend_preshower_mother_ep_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_mother_ep_proc->Draw("same HIST");
 c[16]->cd(3);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
  hhit_Eend_preshower_r_proc->SetLineColor(1);
 hhit_Eend_preshower_r_proc->GetYaxis()->SetTitleOffset(1.1);; 
  hhit_Eend_preshower_r_proc->GetYaxis()->SetTitle("preshower hit");
  hhit_Eend_preshower_r_proc->GetXaxis()->SetTitle("preshower procID");
  hhit_Eend_preshower_r_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_r_proc->Draw("HIST");
  hhit_Eend_preshower_mother_r_proc->SetLineColor(2);
  hhit_Eend_preshower_mother_r_proc->GetXaxis()->SetRangeUser(0,54);
  hhit_Eend_preshower_mother_r_proc->Draw("same HIST");*/
 for(int a=0;a<3;a++){
    c[a]->SaveAs(Form("c%d.pdf",a));
    }
             gSystem->Exec("pdfunite ./c*.pdf ./HallC_trigger_rate_comparison_newbeamline_20deg_21m.pdf");
             gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
