#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_gem_BeamOnTarget_shielding_E(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	TFile *f1 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_output_gem_gammaE_underflow.root");
	//TFile *f1 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_6.005e11_8deg_80uA_newCH_output_gem_gammaE_event.root");
	TFile *f3 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDz30inBS_output_gem_gammaE_underflow.root");
	TFile *f2 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield4in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y4inDZ30inBS_output_gem_gammaE_underflow.root");
	TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield7in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y7inDZ30inBS_output_gem_gammaE_underflow.root");
	//TFile *f5 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ52inBS_output_gem_gammaE_underflow.root");
	TFile *f5 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield7in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y7inDZ52inBS_output_gem_gammaE_underflow.root");
	TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inX4inDZ60inBS_output_gem_gammaE_underflow.root");
	TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_1cmpb/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_45cmPb_5.12times_output_gem_gammaE.root");
	//TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inX4inDZ60inBS_output_gem_gammaE_underflow.root");
	TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in_dz40in/HallC_beamtest_BeamOnTarget_1.01e10_8deg_80uA_Y5inDZ80inBS_output_gem_gammaE_underflow.root");
	TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ70inBS_output_gem_gammaE_underflow.root");
	TFile *f9 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e9_8deg_80uA_targetonly_output_gem_gammaE.root");
	TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e9_8deg_80uA_target_chamber_zhiwen_output_gem_gammaE.root");
	TH1F *hprocid_gem1;       
	TH1F *hpf_gem1;
	TH1F *hE_gem1;
	TH1F *hpf_gem1_1cmAl;
	TH1F *hE_gem1_1inpoly;
	TH1F *hhit_Egem1_procID[11];
	TH1F *hhit_Egem1;
	TH1F *hhit_Egem1_gamma;
	TH1F *hhit_Egem1_electron;
	TH1F *hhit_Egem1_other;
	TH1F *hhit_Egem1_pi0;
	TH1F *hhit_Edepgem1_procID[11];
	TH1F *hhit_Edepgem1;
	TH1F *hhit_Edepgem1_gamma;
	TH1F *hhit_Edepgem1_other;
	TH1F *hhit_Edepgem1_pi0;
	TH1F *hhit_Edepgem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_noB;
	TH1F *hhit_Edepgem1_electron;
	TH1F *hhit_Edepgem12_electron_noTB;
	TH1F *hhit_Edepgem12_electron;
	TH1F *hhit_Edepgem12_electron_test;
	TH1F *hhit_Egem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_1cmAl;
	TH1F *hhit_Edepgem1_electron_1inpoly;
	TH1F *hhit_Edepgem1_electron_25cm;
	TH1F *hhit_Edepgem1_electron_35cm;
	TH1F *hhit_Edepgem1_electron_35cmL;
	TH1F *hhit_Edepgem1_electron_45cm;
	TH1F *hhit_Edepgem1_electron_55cm;

	TH1F *hhit_Edepgem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_noB;
	TH1F *hhit_Edepgem2_electron;
	TH1F *hhit_Egem2_electron;
	TH1F *hhit_Egem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_1cmAl;
	TH1F *hhit_Edepgem2_electron_1inpoly;
	TH1F *hhit_Edepgem2_electron_25cm;
	TH1F *hhit_Edepgem2_electron_35cm;
	TH1F *hhit_Edepgem2_electron_35cmL;
	TH1F *hhit_Edepgem2_electron_45cm;
	TH1F *hhit_Edepgem2_electron_55cm;

	TH1F *hhit_theta_noTB;
	TH1F *hhit_theta_noB;
	TH1F *hhit_theta;
	TH1F *hhit_theta_1cmAl;
	TH1F *hhit_theta_1inpoly;
	TH1F *hhit_theta_25cm;
	TH1F *hhit_theta_35cm;
	TH1F *hhit_theta_35cmL;
	TH1F *hhit_theta_45cm;
	TH1F *hhit_theta_55cm;
	TH1F *hhit_theta_gem2_noTB;
	TH1F *hhit_theta_gem2_noB;
	TH1F *hhit_theta_gem2;
	TH1F *hhit_theta_1cmAl_gem2;
	TH1F *hhit_theta_1inpoly_gem2;
	TH1F *hhit_theta_25cm_gem2;
	TH1F *hhit_theta_35cm_gem2;
	TH1F *hhit_theta_35cmL_gem2;
	TH1F *hhit_theta_45cm_gem2;
	TH1F *hhit_theta_55cm_gem2;

        hprocid_gem1 = (TH1F*)f1->Get("procid_gem1");
        hpf_gem1 = (TH1F*)f1->Get("hpf_gem1");
        hE_gem1 = (TH1F*)f1->Get("hE_gem1");
        hhit_Egem1 = (TH1F*)f1->Get("hit_Egem1");
        hhit_Edepgem1_electron_noTB = (TH1F*)f9->Get("hit_Egem1");
        hhit_Edepgem12_electron_noTB = (TH1F*)f9->Get("hit_Egem12");
        hhit_Edepgem12_electron = (TH1F*)f1->Get("hit_Egem12");
        hhit_Edepgem12_electron_test = (TH1F*)f1->Get("hit_Egem12_test");
        hhit_Edepgem1_electron_noB = (TH1F*)f10->Get("hit_Egem1");
        hhit_Edepgem1_electron = (TH1F*)f1->Get("hit_Egem1");
        hhit_Egem1_electron = (TH1F*)f1->Get("hit_E_gem1");
        hhit_Egem1_electron_noTB = (TH1F*)f9->Get("hit_E_gem1");
        hhit_Edepgem1_electron_1cmAl = (TH1F*)f2->Get("hit_Egem1");
        hhit_Edepgem1_electron_1inpoly = (TH1F*)f3->Get("hit_Egem1");
        hhit_Edepgem1_electron_25cm = (TH1F*)f4->Get("hit_Egem1");
        hhit_Edepgem1_electron_35cm = (TH1F*)f5->Get("hit_Egem1");
        hhit_Edepgem1_electron_35cmL = (TH1F*)f8->Get("hit_Egem1");
        hhit_Edepgem1_electron_45cm = (TH1F*)f6->Get("hit_Egem1");
        hhit_Edepgem1_electron_55cm = (TH1F*)f17->Get("hit_Egem1");
        hhit_Edepgem1_electron_55cmL = (TH1F*)f7->Get("hit_Egem1");

        hhit_theta_noTB = (TH1F*)f9->Get("gen_Theta_gem1");
        hhit_theta_noB = (TH1F*)f10->Get("gen_Theta_gem1");
        hhit_theta = (TH1F*)f1->Get("gen_Theta_gem1");
        hhit_theta_1cmAl = (TH1F*)f2->Get("gen_Theta_gem1");
        hhit_theta_1inpoly = (TH1F*)f3->Get("gen_Theta_gem1");
        hhit_theta_25cm = (TH1F*)f4->Get("gen_Theta_gem1");
        hhit_theta_35cm = (TH1F*)f5->Get("gen_Theta_gem1");
        hhit_theta_35cmL = (TH1F*)f8->Get("gen_Theta_gem1");
        hhit_theta_45cm = (TH1F*)f6->Get("gen_Theta_gem1");
        hhit_theta_55cm = (TH1F*)f17->Get("gen_Theta_gem1");
        hhit_theta_55cmL = (TH1F*)f7->Get("gen_Theta_gem1");

        hhit_Edepgem2_electron_noTB = (TH1F*)f9->Get("hit_Egem2");
        hhit_Edepgem2_electron_noB = (TH1F*)f10->Get("hit_Egem2");
        hhit_Edepgem2_electron = (TH1F*)f1->Get("hit_Egem2");
        hhit_Egem2_electron = (TH1F*)f1->Get("hit_E_gem2");
        hhit_Egem2_electron_noTB = (TH1F*)f9->Get("hit_E_gem2");
        hhit_Edepgem2_electron_1cmAl = (TH1F*)f2->Get("hit_Egem2");
        hhit_Edepgem2_electron_1inpoly = (TH1F*)f3->Get("hit_Egem2");
        hhit_Edepgem2_electron_25cm = (TH1F*)f4->Get("hit_Egem2");
        hhit_Edepgem2_electron_35cm = (TH1F*)f5->Get("hit_Egem2");
        hhit_Edepgem2_electron_35cmL = (TH1F*)f8->Get("hit_Egem2");
        hhit_Edepgem2_electron_45cm = (TH1F*)f6->Get("hit_Egem2");
        hhit_Edepgem2_electron_55cm = (TH1F*)f7->Get("hit_Egem2");
        hhit_Edepgem2_electron_55cmL = (TH1F*)f17->Get("hit_Egem2");
        hhit_theta_gem2_noTB = (TH1F*)f9->Get("gen_Theta_gem2");
        hhit_theta_gem2_noB = (TH1F*)f10->Get("gen_Theta_gem2");
        hhit_theta_gem2 = (TH1F*)f1->Get("gen_Theta_gem2");
        hhit_theta_1cmAl_gem2 = (TH1F*)f2->Get("gen_Theta_gem2");
        hhit_theta_1inpoly_gem2 = (TH1F*)f3->Get("gen_Theta_gem2");
        hhit_theta_25cm_gem2 = (TH1F*)f4->Get("gen_Theta_gem2");
        hhit_theta_35cm_gem2 = (TH1F*)f5->Get("gen_Theta_gem2");
        hhit_theta_35cmL_gem2 = (TH1F*)f8->Get("gen_Theta_gem2");
        hhit_theta_45cm_gem2 = (TH1F*)f6->Get("gen_Theta_gem2");
        hhit_theta_55cm_gem2 = (TH1F*)f17->Get("gen_Theta_gem2");
        hhit_theta_55cmL_gem2 = (TH1F*)f7->Get("gen_Theta_gem2");
        hpf_gem1_1cmAl = (TH1F*)f2->Get("hpf_gem1");
        hE_gem1_1cmAl = (TH1F*)f2->Get("hE_gem1");
        hpf_gem1_1inpoly = (TH1F*)f3->Get("hpf_gem1");
        hE_gem1_1inpoly = (TH1F*)f3->Get("hE_gem1");
	for(int k=0;k<11;k++){
		hhit_Edepgem1_procID[k]=(TH1F*)f1->Get(Form("hit_Edepgem1_procID%d",k));
		hhit_Egem1_procID[k]=(TH1F*)f1->Get(Form("hit_Egem1_procID%d",k));
        }
	TCanvas *c_gem[6];

	c_gem[4] = new TCanvas("c_gem[4]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
        hhit_theta->SetLineColor(6);	
        hhit_theta->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta->SetTitle("gem1");	
        hhit_theta->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta->Scale(0.001);
        hhit_theta->GetYaxis()->SetRangeUser(1e0,2e6);	
        hhit_theta->Draw("HISt");	
        hhit_theta_noTB->SetLineColor(44);	
        hhit_theta_noTB->Scale(0.001);
        hhit_theta_noTB->Draw("same HISt");	
        hhit_theta_noB->SetLineColor(28);	
        hhit_theta_noB->Scale(0.001);
        hhit_theta_noB->Draw("same HISt");	
        hhit_theta_1cmAl->SetLineColor(7);	
        hhit_theta_1cmAl->Scale(0.001);
        hhit_theta_1cmAl->Draw("same HISt");	
        hhit_theta_1inpoly->SetLineColor(kOrange);	
        hhit_theta_1inpoly->Scale(0.001);
        hhit_theta_1inpoly->Draw("same HISt");	
        hhit_theta_25cm->SetLineColor(3);	
        hhit_theta_25cm->Scale(0.001);
        hhit_theta_25cm->Draw("same HISt");	
        hhit_theta_35cm->SetLineColor(2);	
        hhit_theta_35cm->Scale(0.001);
        hhit_theta_35cm->Draw("same HISt");	
        hhit_theta_45cm->SetLineColor(4);	
        hhit_theta_45cm->Scale(0.001);
        hhit_theta_45cm->Draw("same HISt");	
        hhit_theta_55cm->SetLineColor(1);	
        hhit_theta_55cm->Scale(0.001);
        hhit_theta_55cm->Draw("same HISt");	
        hhit_theta_35cmL->SetLineColor(30);	
        hhit_theta_35cmL->Scale(0.001);
        hhit_theta_35cmL->Draw("same HISt");
        hhit_theta_noB->Draw("same HISt");	
        hhit_theta_55cmL->SetLineColor(kMagenta-2);	
        hhit_theta_55cmL->Scale(0.001);
        hhit_theta_55cmL->Draw("same HISt");	
	TLegend *leg1 = new TLegend(0.6,0.6,0.8,0.88);
	leg1->AddEntry(hhit_theta,"no shielding","l");
	leg1->AddEntry(hhit_theta_noTB,"no shielding target only","l");
	leg1->AddEntry(hhit_theta_noB,"no shielding no Beam line","l");
	leg1->AddEntry(hhit_theta_1cmAl,"2 in Pb 4x30 in^{2} Coli ","l");
	leg1->AddEntry(hhit_theta_1inpoly,"2 in Pb 5x30 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_25cm,"2 in Pb 7x30 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_35cm,"2 in Pb 5x52 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_35cmL,"2 in Pb 5x70 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_45cm,"2 in Pb 5x80 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_55cm,"2 in Pb 5x60 in^{2} Coli","l");
	leg1->AddEntry(hhit_theta_55cmL,"4 in Pb 5x60 in^{2} Coli","l");
	leg1->SetTextSize(0.035);
	leg1->SetBorderSize(0);
	leg1->SetFillColor(0);
	leg1->Draw("text same");

	c_gem[5] = new TCanvas("c_gem[5]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
        hhit_theta_gem2->SetLineColor(6);	
        hhit_theta_gem2->Scale(0.001);
        hhit_theta_gem2->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_gem2->SetTitle("gem2");	
        hhit_theta_gem2->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_gem2->GetYaxis()->SetRangeUser(1e0,2e6);	
        hhit_theta_gem2->Draw("HISt");	
        hhit_theta_gem2_noTB->SetLineColor(44);	
        hhit_theta_gem2_noTB->Scale(0.001);
        hhit_theta_gem2_noTB->Draw("same HISt");	
        hhit_theta_gem2_noB->SetLineColor(28);	
        hhit_theta_gem2_noB->Scale(0.001);
        hhit_theta_gem2_noB->Draw("same HISt");	
        hhit_theta_1cmAl_gem2->SetLineColor(7);	
        hhit_theta_1cmAl_gem2->Scale(0.001);
        hhit_theta_1cmAl_gem2->Draw("same HISt");	
        hhit_theta_1inpoly_gem2->SetLineColor(kOrange);	
        hhit_theta_1inpoly_gem2->Scale(0.001);
        hhit_theta_1inpoly_gem2->Draw("same HISt");	
        hhit_theta_25cm_gem2->SetLineColor(3);	
        hhit_theta_25cm_gem2->Scale(0.001);
        hhit_theta_25cm_gem2->Draw("same HISt");	
        hhit_theta_35cm_gem2->SetLineColor(2);	
        hhit_theta_35cm_gem2->Scale(0.001);
        hhit_theta_35cm_gem2->Draw("same HISt");	
        hhit_theta_45cm_gem2->SetLineColor(4);	
        hhit_theta_45cm_gem2->Scale(0.001);
        hhit_theta_45cm_gem2->Draw("same HISt");	
        hhit_theta_55cm_gem2->SetLineColor(1);	
        hhit_theta_55cm_gem2->Scale(0.001);
        hhit_theta_55cm_gem2->Draw("same HISt");	
        hhit_theta_35cmL_gem2->SetLineColor(30);	
        hhit_theta_35cmL_gem2->Scale(0.001);
        hhit_theta_35cmL_gem2->Draw("same HISt");
        hhit_theta_55cmL_gem2->SetLineColor(kMagenta-2);	
        hhit_theta_55cmL_gem2->Scale(0.001);
        hhit_theta_55cmL_gem2->Draw("same HISt");	
	leg1->Draw("text same");
	c_gem[2] = new TCanvas("c_gem[2]", "gem1",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem1_electron->SetLineColor(6);
	hhit_Edepgem1_electron->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_electron->SetTitle("flux E on gem1 virtual plane");
        hhit_Edepgem1_electron->Scale(0.001);
        hhit_Edepgem1_electron->GetYaxis()->SetRangeUser(1e0,2e6);	
	hhit_Edepgem1_electron->Draw("HIST");
	hhit_Edepgem12_electron->SetLineColor(1);
	hhit_Edepgem12_electron->Scale(0.001);
	hhit_Edepgem12_electron_test->SetLineColor(3);
	hhit_Edepgem12_electron_test->Scale(0.001);
	//hhit_Edepgem12_electron->Draw("same HIST");
/*	hhit_Edepgem2_electron->SetLineColor(9);
        hhit_Edepgem2_electron->Scale(0.001);
	hhit_Edepgem2_electron->Draw("same HIST");
	hhit_Edepgem2_electron_noTB->SetLineColor(44);
        hhit_Edepgem2_electron_noTB->Scale(0.001);
	hhit_Edepgem2_electron_noTB->Draw("same HIST");*/
	hhit_Edepgem1_electron_noTB->SetLineColor(44);
        hhit_Edepgem1_electron_noTB->Scale(0.001);
	hhit_Edepgem1_electron_noTB->Draw("same HIST");
	hhit_Edepgem1_electron_noB->SetLineColor(28);
        hhit_Edepgem1_electron_noB->Scale(0.001);
	hhit_Edepgem1_electron_noB->Draw("same HIST");
	hhit_Edepgem1_electron_1cmAl->SetLineColor(7);
        hhit_Edepgem1_electron_1cmAl->Scale(0.001);
	hhit_Edepgem1_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem1_electron_1inpoly->SetLineColor(kOrange);
        hhit_Edepgem1_electron_1inpoly->Scale(0.001);
	hhit_Edepgem1_electron_1inpoly->Draw("same HIST");
	hhit_Edepgem1_electron_25cm->SetLineColor(3);
        hhit_Edepgem1_electron_25cm->Scale(0.001);
	hhit_Edepgem1_electron_25cm->Draw("same HIST");
	hhit_Edepgem1_electron_35cm->SetLineColor(kViolet-4);
        hhit_Edepgem1_electron_35cm->Scale(0.001);
	hhit_Edepgem1_electron_35cm->Draw("same HIST");
	hhit_Edepgem1_electron_45cm->SetLineColor(4);
        hhit_Edepgem1_electron_45cm->Scale(0.001);
	hhit_Edepgem1_electron_45cm->Draw("same HIST");
	hhit_Edepgem1_electron_55cm->SetLineColor(1);
        hhit_Edepgem1_electron_55cm->Scale(0.001);
	hhit_Edepgem1_electron_55cm->Draw("same HIST");
	hhit_Edepgem1_electron_35cmL->SetLineColor(30);
        hhit_Edepgem1_electron_35cmL->Scale(0.001);
	hhit_Edepgem1_electron_35cmL->Draw("same HIST");
	hhit_Edepgem1_electron_55cmL->SetLineColor(kMagenta-2);
        hhit_Edepgem1_electron_55cmL->Scale(0.001);
	hhit_Edepgem1_electron_55cmL->Draw("same HIST");
	hhit_Edepgem1_electron->Draw("same HIST");
	TLegend *leg11 = new TLegend(0.3,0.1,0.55,0.4);
	leg11->AddEntry(hhit_Edepgem1_electron,"no shielding","l");
	//leg11->AddEntry(hhit_Edepgem12_electron,"no shielding hit on gem1 & gem2","l");
	leg11->AddEntry(hhit_Edepgem1_electron_noTB,"no shielding target only","l");
	leg11->AddEntry(hhit_Edepgem1_electron_noB,"no shielding no beam line","l");
	leg11->AddEntry(hhit_Edepgem1_electron_1cmAl,"2 in Pb 4x30 in^{2} Coli ","l");
	leg11->AddEntry(hhit_Edepgem1_electron_1inpoly,"2 in Pb 5x30 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_25cm,"2 in Pb 7x30 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_35cm,"2 in Pb 5x60 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_35cmL,"2 in Pb 5x70 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_45cm,"2 in Pb 5x80 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_55cm,"2 in Pb 5x60 in^{2} Coli","l");
	leg11->AddEntry(hhit_Edepgem1_electron_55cmL,"4 in Pb 5x60 in^{2} Coli","l");
	leg11->SetTextSize(0.035);
	leg11->SetBorderSize(0);
	leg11->SetFillColor(0);
	leg11->Draw("text same");
	c_gem[3] = new TCanvas("c_gem[3]", "gem2",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem2_electron->SetLineColor(6);
	hhit_Edepgem2_electron->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem2_electron->SetTitle("flux E on gem2 virtual plane");
        hhit_Edepgem2_electron->Scale(0.001);
        hhit_Edepgem2_electron->GetYaxis()->SetRangeUser(1e0,2e6);	
	hhit_Edepgem2_electron->Draw("HIST");
	hhit_Edepgem2_electron_noTB->SetLineColor(44);
        hhit_Edepgem2_electron_noTB->Scale(0.001);
	hhit_Edepgem2_electron_noTB->Draw("same HIST");
	hhit_Edepgem2_electron_noB->SetLineColor(28);
        hhit_Edepgem2_electron_noB->Scale(0.001);
	hhit_Edepgem2_electron_noB->Draw("same HIST");
	hhit_Edepgem2_electron_1cmAl->SetLineColor(7);
        hhit_Edepgem2_electron_1cmAl->Scale(0.001);
	hhit_Edepgem2_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem2_electron_1inpoly->SetLineColor(kOrange);
        hhit_Edepgem2_electron_1inpoly->Scale(0.001);
	hhit_Edepgem2_electron_1inpoly->Draw("same HIST");
	hhit_Edepgem2_electron_25cm->SetLineColor(3);
        hhit_Edepgem2_electron_25cm->Scale(0.001);
	hhit_Edepgem2_electron_25cm->Draw("same HIST");
	hhit_Edepgem2_electron_35cm->SetLineColor(2);
        hhit_Edepgem2_electron_35cm->Scale(0.001);
	hhit_Edepgem2_electron_35cm->Draw("same HIST");
	hhit_Edepgem2_electron_45cm->SetLineColor(4);
        hhit_Edepgem2_electron_45cm->Scale(0.001);
	hhit_Edepgem2_electron_45cm->Draw("same HIST");
	hhit_Edepgem2_electron_55cm->SetLineColor(1);
        hhit_Edepgem2_electron_55cm->Scale(0.001);
	hhit_Edepgem2_electron_55cm->Draw("same HIST");
	hhit_Edepgem2_electron_35cmL->SetLineColor(30);
        hhit_Edepgem2_electron_35cmL->Scale(0.001);
	hhit_Edepgem2_electron_35cmL->Draw("same HIST");
	hhit_Edepgem2_electron_55cmL->SetLineColor(kMagenta-2);
        hhit_Edepgem2_electron_55cmL->Scale(0.001);
	hhit_Edepgem2_electron_55cmL->Draw("same HIST");
	hhit_Edepgem2_electron->Draw("same HIST");
	leg11->Draw("text same");
	c_gem[0] = new TCanvas("c_gem[0]", "gem",1800,1000);
        c_gem[0]->Divide(1,2);
        TH1F *hhit_Edepgem_electron = (TH1F*)hhit_Edepgem2_electron->Clone(); 
        TH1F *hhit_Edepgem_electron_noTB = (TH1F*)hhit_Edepgem2_electron_noTB->Clone(); 
       // c_gem[0]->cd(1);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem1_electron->SetLineColor(6);
	hhit_Edepgem1_electron->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_electron->SetTitle("flux E on gems virtual plane");
	hhit_Edepgem1_electron->Draw("HIST");
	hhit_Edepgem2_electron->SetLineColor(6);
	hhit_Edepgem2_electron->Draw("same HIST");
	//hhit_Edepgem12_electron->SetLineColor(3);
	//hhit_Edepgem12_electron->Scale(0.001);
//	hhit_Edepgem12_electron_test->Draw("same HIST");
//	hhit_Edepgem12_electron->Draw("same HIST");
        double int_gem12 = hhit_Edepgem12_electron->GetEntries();
        double int_gem12_test = hhit_Edepgem12_electron_test->GetEntries();
        cout<<"int_gem12="<<int_gem12<<"int_gem12_test="<<int_gem12_test<<endl;
	hhit_Edepgem12_electron_noTB->SetLineColor(4);
	hhit_Edepgem12_electron_noTB->Scale(0.001);
//	hhit_Edepgem12_electron_noTB->Draw("same HIST");
	hhit_Edepgem2_electron_noTB->SetLineColor(44);
	hhit_Edepgem2_electron_noTB->Draw("same HIST");
	hhit_Edepgem1_electron_noTB->SetLineColor(46);
	hhit_Edepgem1_electron_noTB->Draw("same HIST");
	hhit_Egem2_electron->SetLineColor(2);
	hhit_Egem2_electron->Scale(0.001);
	hhit_Egem2_electron->Draw("same HIST");
	hhit_Egem1_electron->SetLineColor(7);
	hhit_Egem1_electron->Scale(0.001);
	hhit_Egem1_electron->Draw("same HIST");
	hhit_Egem1_electron_noTB->SetLineColor(1);
	hhit_Egem1_electron_noTB->Scale(0.001);
//	hhit_Egem1_electron_noTB->Draw("same HIST");
	hhit_Egem2_electron_noTB->SetLineColor(8);
	hhit_Egem2_electron_noTB->Scale(0.001);
//	hhit_Egem2_electron_noTB->Draw("same HIST");
	TLegend *leg111 = new TLegend(0.3,0.1,0.55,0.4);
	leg111->AddEntry(hhit_Edepgem1_electron,"no shielding gem1","l");
	leg111->AddEntry(hhit_Edepgem2_electron,"no shielding gem2","l");
//	leg111->AddEntry(hhit_Edepgem12_electron,"no shielding hit gem1 & gem2","l");
	leg111->AddEntry(hhit_Egem1_electron,"no shielding gem1 Edep>0","l");
	leg111->AddEntry(hhit_Egem2_electron,"no shielding gem2 Edep>0","l");
	leg111->AddEntry(hhit_Edepgem1_electron_noTB,"no shielding target only gem1","l");
	leg111->AddEntry(hhit_Edepgem2_electron_noTB,"no shielding target only gem2","l");
//	leg111->AddEntry(hhit_Edepgem12_electron_noTB,"no shielding target only hit gem1 & gem2","l");
//	leg111->AddEntry(hhit_Egem1_electron_noTB,"no shielding target only gem1 Edep>0","l");
//	leg111->AddEntry(hhit_Egem2_electron_noTB,"no shielding target only gem2 Edep>0","l");
	leg111->SetTextSize(0.035);
	leg111->SetBorderSize(0);
	leg111->SetFillColor(0);
	leg111->Draw("text same");
	c_gem[1] = new TCanvas("c_gem[1]", "gem",1800,1000);
       // c_gem[4]->cd(2);
	gPad->SetGridy();
	gPad->SetGridx();
         hhit_Edepgem_electron->Divide(hhit_Edepgem1_electron);
         hhit_Edepgem_electron_noTB->Divide(hhit_Edepgem1_electron_noTB);
	hhit_Edepgem_electron->SetLineColor(6);
	hhit_Edepgem_electron->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem_electron->SetTitle("Ratio of gem2/gem1");
        hhit_Edepgem_electron->GetYaxis()->SetRangeUser(0,2e0);	
	hhit_Edepgem_electron->Draw("HIST");
	hhit_Edepgem_electron_noTB->SetLineColor(44);
	hhit_Edepgem_electron_noTB->Draw("same HIST");
	TLegend *leg101 = new TLegend(0.1,0.6,0.4,0.8);
	leg101->AddEntry(hhit_Edepgem_electron,"no shielding gem2/gem1","l");
	leg101->AddEntry(hhit_Edepgem_electron_noTB,"no shielding target only gem2/gem1","l");
	leg101->SetTextSize(0.035);
	leg101->SetBorderSize(0);
	leg101->SetFillColor(0);
	leg101->Draw("text same");
      
 	for(int a=2;a<6;a++){
		c_gem[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_BeamOnTarget_8deg_BLshielding_gammaE.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));
}
