#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_gem_BeamOnTarget_BLshielding_E_right_fork(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	TFile *f1 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_output_gem_gammaE_underflow.root");
	TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork/HallC_beamtest_BeamOnTarget_9.8e8_8deg_80uA_target_step_right_output_gem_gammaE_pzcut.root");
	TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding/HallC_beamtest_BeamOnTarget_9.91e8_8deg_80uA_target_right_step_BLshielding2x4x190_output_gem_gammaE_pzcut.root");
	//TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_15deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_15deg_BLLcoli_output_gem_gammaE_pzcut.root");
//	TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_far/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_right_step_BLshielding2x4x190_far_output_gem_gammaE_pzcut.root");
	TFile *f11 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_newCH_output_gem_electronE_pzcut.root");
	TFile *f13 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork/HallC_beamtest_BeamOnTarget_9.8e8_8deg_80uA_target_step_right_output_gem_electronE_pzcut.root");
	TFile *f12 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding/HallC_beamtest_BeamOnTarget_9.91e8_8deg_80uA_target_right_step_BLshielding2x4x190_output_gem_electronE_pzcut.root");
	//TFile *f12 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_far/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_right_step_BLshielding2x4x190_far_output_gem_electronE_pzcut.root");


//	TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_GEM4cmAl/HallC_beamtest_BeamOnTarget_3.85e8_8deg_80uA_target_right_step_BLshielding2x4x190_4cmAl_output_gem_gammaE_pzcut.root");
//	TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_GEM4cmAl/HallC_beamtest_BeamOnTarget_3.85e8_8deg_80uA_target_right_step_BLshielding2x4x190_4cmAl_output_gem_electronE_pzcut.root");

	//TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_floor/HallC_beamtest_BeamOnTarget_2.441e9_8deg_80uA_target_step_right_floor_output_gem_gammaE_pzcut.root");
	//TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_20deg/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_20deg_output_gem_gammaE_pzcut.root");
	TFile *f4 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_8deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_8deg_BLLcoli_output_gem_gammaE_pzcut.root");
	//TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_floor/HallC_beamtest_BeamOnTarget_2.441e9_8deg_80uA_target_step_right_floor_output_gem_electronE_pzcut.root");
	//TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_20deg/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_20deg_output_gem_electronE_pzcut.root");
	TFile *f14 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLLcoli_8deg/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_target_step_right_fork_8deg_BLLcoli_output_gem_electronE_pzcut.root");


	//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inX4inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ60inBS_output_gem_gammaE_underflow.root");
	//TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_GEM45cmPb/HallC_beamtest_BeamOnTarget_4.91e8_8deg_80uA_target_right_step_BLshielding2x4x190_4.5cmPb_output_gem_gammaE_pzcut.root");
	//TFile *f16 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_BLshielding_GEM45cmPb/HallC_beamtest_BeamOnTarget_4.91e8_8deg_80uA_target_right_step_BLshielding2x4x190_4.5cmPb_output_gem_electronE_pzcut.root");
	TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_Bshield5in/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_Y5inDZ70inBS_output_gem_gammaE_underflow.root");
	//TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber/HallC_beamtest_BeamOnTarget_0.99e10_8deg_80uA_target_chamber_output_gem_gammaE_pzcut.root");
	TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber_kryptonite/HallC_beamtest_BeamOnTarget_4.965e8_8deg_80uA_chamber_kryptonite_output_gem_gammaE_pzcut.root");
	//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber_kryptonite_floor/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_chamber_kryptonite_floor_output_gem_gammaE_pzcut.root");
	//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_15deg/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_15deg_output_gem_gammaE_pzcut.root");
	TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_right/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_output_gem_gammaE_pzcut.root");
	//TFile *f9 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_floor/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_floor_output_gem_gammaE_pzcut.root");
	TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_TGonly_kryptonite2/HallC_beamtest_BeamOnTarget_5.59e8_8deg_80uA_air_kryptonite2_output_gem_gammaE_pzcut.root");
	//TFile *f9 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_floor/HallC_beamtest_BeamOnTarget_4.975e8_8deg_80uA_target_step_right_floor_output_gem_gammaE_pzcut.root");
	TFile *f29 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_TGonly_kryptonite_floor/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_TGonly_air_kryptonite_floor_output_gem_gammaE_pzcut.root");
	TFile *f5 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_output_gem_gammaE_pzcut.root");
	//TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_floor/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_target_vacuum_floor_output_gem_gammaE_pzcut.root");
	TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_output_gem_gammaE_pzcut.root");
	//TFile *f110 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber/HallC_beamtest_BeamOnTarget_0.99e10_8deg_80uA_target_chamber_output_gem_electronE_pzcut.root");
	TFile *f110 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber_kryptonite/HallC_beamtest_BeamOnTarget_4.965e8_8deg_80uA_chamber_kryptonite_output_gem_electronE_pzcut.root");
	//TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_chamber_kryptonite_floor/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_chamber_kryptonite_floor_output_gem_electronE_pzcut.root");
	//TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_15deg/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_15deg_output_gem_electronE_pzcut.root");
	TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum_right/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_right_output_gem_electronE_pzcut.root");
	//TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_floor/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_floor_output_gem_electronE_pzcut.root");
	TFile *f19 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_TGonly_kryptonite2/HallC_beamtest_BeamOnTarget_5.59e8_8deg_80uA_air_kryptonite2_output_gem_electronE_pzcut.root");
	//TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_floor/HallC_beamtest_BeamOnTarget_4.975e8_8deg_80uA_target_step_right_floor_output_gem_electronE_pzcut.root");
	TFile *f39 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_TGonly_kryptonite_floor/HallC_beamtest_BeamOnTarget_5e8_8deg_80uA_TGonly_air_kryptonite_floor_output_gem_electronE_pzcut.root");
	TFile *f15 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_output_gem_electronE_pzcut.root");
	//TFile *f16 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_floor/HallC_beamtest_BeamOnTarget_1e11_8deg_80uA_target_vacuum_floor_output_gem_electronE_pzcut.root");
	TFile *f16 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_vacuum_CCvacuum/HallC_beamtest_BeamOnTarget_1e10_8deg_80uA_target_vacuum_CCvacuum_output_gem_electronE_pzcut.root");
	TFile *f40 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_15deg/HallC_beamtest_BeamOnTarget_9.725e8_8deg_80uA_target_step_right_15deg_output_gem_electronE_pzcut.root");
	TFile *f41 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_right_fork_20deg/HallC_beamtest_BeamOnTarget_8.485e8_8deg_80uA_target_step_right_20deg_output_gem_electronE_pzcut.root");
	TH1F *hprocid_gem1;       
	TH1F *hpf_gem1;
	TH1F *hE_gem1;
	TH1F *hpf_gem1_1cmAl;
	TH1F *hE_gem1_1inpoly;
	TH1F *hhit_Egem1_procID[11];
	TH1F *hhit_Egem1;
	TH1F *hhit_Egem1_gamma;
	TH1F *hhit_Egem1_electron;
	TH1F *hhit_Egem1_other;
	TH1F *hhit_Egem1_pi0;
	TH1F *hhit_Edepgem1_procID[11];
	TH1F *hhit_Edepgem1;
	TH1F *hhit_Edepgem1_gamma;
	TH1F *hhit_Edepgem1_other;
	TH1F *hhit_Edepgem1_pi0;
	TH1F *hhit_Edepgem12_electron_noTB;
	TH1F *hhit_Edepgem12_electron;
	TH1F *hhit_Edepgem12_electron_test;
	TH1F *hhit_Egem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_1cmAl;
	TH1F *hhit_Edepgem1_electron_1inpoly;
	TH1F *hhit_Edepgem1_electron_25cm;
	TH1F *hhit_Edepgem1_electron_35cm;
	TH1F *hhit_Edepgem1_electron_35cmL;
	TH1F *hhit_Edepgem1_electron_45cm;
	TH1F *hhit_Edepgem1_electron_55cm;
	TH1F *hhit_Edepgem1_electron_noTB;
	TH1F *hhit_Edepgem1_electron_noB;
	TH1F *hhit_Edepgem1_electron;

	TH1F *hhit_Edepgem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_noB;
	TH1F *hhit_Edepgem2_electron;
	TH1F *hhit_Egem2_electron;
	TH1F *hhit_Egem2_electron_noTB;
	TH1F *hhit_Edepgem2_electron_1cmAl;
	TH1F *hhit_Edepgem2_electron_1inpoly;
	TH1F *hhit_Edepgem2_electron_25cm;
	TH1F *hhit_Edepgem2_electron_35cm;
	TH1F *hhit_Edepgem2_electron_35cmL;
	TH1F *hhit_Edepgem2_electron_45cm;
	TH1F *hhit_Edepgem2_electron_55cm;

	TH1F *hhit_theta_noTB;
	TH1F *hhit_theta_noB;
	TH1F *hhit_theta;
	TH1F *hhit_theta_1cmAl;
	TH1F *hhit_theta_1inpoly;
	TH1F *hhit_theta_25cm;
	TH1F *hhit_theta_25cm_electron;
	TH1F *hhit_theta_35cm;
	TH1F *hhit_theta_35cmL;
	TH1F *hhit_theta_45cm;
	TH1F *hhit_theta_45cm_electron;
	TH1F *hhit_theta_55cm;
	TH1F *hhit_theta_gem2_noTB;
	TH1F *hhit_theta_gem2_noB;
	TH1F *hhit_theta_gem2;
	TH1F *hhit_theta_1cmAl_gem2;
	TH1F *hhit_theta_1inpoly_gem2;
	TH1F *hhit_theta_25cm_gem2;
	TH1F *hhit_theta_25cm_gem2_electron;
	TH1F *hhit_theta_35cm_gem2;
	TH1F *hhit_theta_35cmL_gem2;
	TH1F *hhit_theta_45cm_gem2;
	TH1F *hhit_theta_45cm_gem2_electron;
	TH1F *hhit_theta_55cm_gem2;
	TH1F *hhit_Edepgem1_gamma_noTB;
	TH1F *hhit_Edepgem1_gamma_noB;
	TH1F *hhit_Edepgem1_gamma;
	TH1F *hhit_Egem1_gamma_noTB;
	TH1F *hhit_Edepgem1_gamma_1cmAl;
	TH1F *hhit_Edepgem1_gamma_1inpoly;
	TH1F *hhit_Edepgem1_gamma_35cm;
	TH1F *hhit_Edepgem1_gamma_45cm;
	TH1F *hhit_Edepgem1_gamma_55cm;
	TH1F *hhit_Edepgem1_gamma_25cm;
	TH1F *hhit_Edepgem1_gamma_15deg;
	TH1F *hhit_Edepgem1_gamma_20degv;

	TH1F *hhit_Edepgem2_gamma_noTB;
	TH1F *hhit_Edepgem2_gamma_noB;
	TH1F *hhit_Edepgem2_gamma;
	TH1F *hhit_Egem2_gamma;
	TH1F *hhit_Egem2_gamma_noTB;
	TH1F *hhit_Edepgem2_gamma_1cmAl;
	TH1F *hhit_Edepgem2_gamma_1inpoly;
	TH1F *hhit_Edepgem2_gamma_35cm;
	TH1F *hhit_Edepgem2_gamma_25cm;
	TH1F *hhit_Edepgem2_gamma_45cm;
	TH1F *hhit_Edepgem2_gamma_55cm;
	TH1F *hhit_theta_noTB_electron;
	TH1F *hhit_theta_noB_electron;
	TH1F *hhit_theta_electron;
	TH1F *hhit_theta_1cmAl_electron;
	TH1F *hhit_theta_1inpoly_electron;
	TH1F *hhit_theta_35cm_electron;
	TH1F *hhit_theta_gem2_noTB_electron;
	TH1F *hhit_theta_gem2_noB_electron;
	TH1F *hhit_theta_gem2_electron;
	TH1F *hhit_theta_1cmAl_gem2_electron;
	TH1F *hhit_theta_1inpoly_gem2_electron;
	TH1F *hhit_theta_35cm_gem2_electron;
	TH1F *hhit_Edepgem1_Moller_noTB;
	TH1F *hhit_Edepgem1_Moller_noB;
	TH1F *hhit_Edepgem1_Moller;
	TH1F *hhit_Edepgem1_Moller_1cmAl;
	TH1F *hhit_Edepgem1_Moller_1inpoly;
	TH1F *hhit_Edepgem1_Moller_35cm;
	TH1F *hhit_Edepgem1_compton_noTB;
	TH1F *hhit_Edepgem1_compton_noB;
	TH1F *hhit_Edepgem1_compton;
	TH1F *hhit_Edepgem1_compton_1cmAl;
	TH1F *hhit_Edepgem1_compton_1inpoly;
	TH1F *hhit_Edepgem1_compton_35cm;

        hprocid_gem1 = (TH1F*)f1->Get("procid_gem1");
        hpf_gem1 = (TH1F*)f1->Get("hpf_gem1");
        hE_gem1 = (TH1F*)f1->Get("hE_gem1");
        hhit_Egem1 = (TH1F*)f1->Get("hit_Egem1");
        hhit_Edepgem1_electron_noTB = (TH1F*)f9->Get("hit_Egem1");
        hhit_Edepgem12_electron_noTB = (TH1F*)f9->Get("hit_Egem12");
        hhit_Edepgem12_electron = (TH1F*)f1->Get("hit_Egem12");
        hhit_Edepgem12_electron_test = (TH1F*)f1->Get("hit_Egem12_test");
        hhit_Edepgem1_electron_noB = (TH1F*)f10->Get("hit_Egem1");
        hhit_Edepgem1_electron = (TH1F*)f1->Get("hit_Egem1");
        hhit_Egem1_electron = (TH1F*)f1->Get("hit_E_gem1");
        hhit_Egem1_electron_noTB = (TH1F*)f9->Get("hit_E_gem1");
        hhit_Edepgem1_electron_1cmAl = (TH1F*)f2->Get("hit_Egem1");
        hhit_Edepgem1_electron_1inpoly = (TH1F*)f3->Get("hit_Egem1");
        hhit_Edepgem1_electron_35cm = (TH1F*)f5->Get("hit_Egem1");
        hhit_Edepgem1_electron_25cm = (TH1F*)f4->Get("hit_Egem1");
        hhit_Edepgem1_electron_45cm = (TH1F*)f6->Get("hit_Egem1");
        hhit_Edepgem1_electron_55cm = (TH1F*)f7->Get("hit_Egem1");

        hhit_Edepgem1_Moller_noTB = (TH1F*)f19->Get("hit_E_gem1_Moller");
        hhit_Edepgem1_Moller_noB = (TH1F*)f110->Get("hit_E_gem1_Moller");
        hhit_Edepgem1_Moller_1cmAl = (TH1F*)f12->Get("hit_E_gem1_Moller");
        hhit_Edepgem1_Moller_1inpoly = (TH1F*)f13->Get("hit_E_gem1_Moller");
        hhit_Edepgem1_Moller_35cm = (TH1F*)f15->Get("hit_E_gem1_Moller");

        hhit_Edepgem1_compton_noTB = (TH1F*)f19->Get("hit_E_gem1_Compton");
        hhit_Edepgem1_compton_noB = (TH1F*)f110->Get("hit_E_gem1_Compton");
        hhit_Edepgem1_compton_1cmAl = (TH1F*)f12->Get("hit_E_gem1_Compton");
        hhit_Edepgem1_compton_1inpoly = (TH1F*)f13->Get("hit_E_gem1_Compton");
        hhit_Edepgem1_compton_35cm = (TH1F*)f15->Get("hit_E_gem1_Compton");


        hhit_theta_noTB = (TH1F*)f9->Get("gen_Theta_gem1");
        hhit_theta_noB = (TH1F*)f10->Get("gen_Theta_gem1");
        hhit_theta = (TH1F*)f1->Get("gen_Theta_gem1");
        hhit_theta_1cmAl = (TH1F*)f2->Get("gen_Theta_gem1");
        hhit_theta_1inpoly = (TH1F*)f3->Get("gen_Theta_gem1");
        hhit_Edepgem1_gamma_noTB = (TH1F*)f19->Get("hit_Egem1");
        hhit_Edepgem1_gamma_noB = (TH1F*)f110->Get("hit_Egem1");
        hhit_Edepgem1_gamma = (TH1F*)f11->Get("hit_Egem1");
        hhit_Egem1_gamma = (TH1F*)f11->Get("hit_E_gem1");
        hhit_Egem1_gamma_noTB = (TH1F*)f19->Get("hit_E_gem1");
        hhit_Edepgem1_gamma_1cmAl = (TH1F*)f12->Get("hit_Egem1");
        hhit_Edepgem1_gamma_1inpoly = (TH1F*)f13->Get("hit_Egem1");
        hhit_Edepgem1_gamma_35cm = (TH1F*)f15->Get("hit_Egem1");
        hhit_Edepgem1_gamma_45cm = (TH1F*)f16->Get("hit_Egem1");
        hhit_Edepgem1_gamma_55cm = (TH1F*)f17->Get("hit_Egem1");
        hhit_Edepgem1_gamma_25cm = (TH1F*)f14->Get("hit_Egem1");
        hhit_Edepgem1_gamma_15deg = (TH1F*)f40->Get("hit_Egem1");
        hhit_Edepgem1_gamma_20degv = (TH1F*)f41->Get("hit_Egem1");
        hhit_theta_25cm = (TH1F*)f4->Get("gen_Theta_gem1");
        hhit_theta_25cm_electron = (TH1F*)f14->Get("gen_Theta_gem1");
        hhit_theta_35cm = (TH1F*)f5->Get("gen_Theta_gem1");
        hhit_theta_35cmL = (TH1F*)f8->Get("gen_Theta_gem1");
        hhit_theta_45cm = (TH1F*)f6->Get("gen_Theta_gem1");
        hhit_theta_45cm_electron = (TH1F*)f16->Get("gen_Theta_gem1");
        hhit_theta_55cm = (TH1F*)f17->Get("gen_Theta_gem1");
        hhit_theta_55cmL = (TH1F*)f7->Get("gen_Theta_gem1");

        hhit_Edepgem2_electron_noTB = (TH1F*)f9->Get("hit_Egem2");
        hhit_Edepgem2_electron_noB = (TH1F*)f10->Get("hit_Egem2");
        hhit_Edepgem2_electron = (TH1F*)f1->Get("hit_Egem2");
        hhit_Egem2_electron = (TH1F*)f1->Get("hit_E_gem2");
        hhit_Egem2_electron_noTB = (TH1F*)f9->Get("hit_E_gem2");
        hhit_Edepgem2_electron_1cmAl = (TH1F*)f2->Get("hit_Egem2");
        hhit_Edepgem2_electron_1inpoly = (TH1F*)f3->Get("hit_Egem2");
        hhit_Edepgem2_electron_35cm = (TH1F*)f5->Get("hit_Egem2");
        hhit_Edepgem2_electron_45cm = (TH1F*)f6->Get("hit_Egem2");
        hhit_Edepgem2_electron_25cm = (TH1F*)f4->Get("hit_Egem2");
        hhit_Edepgem2_electron_55cm = (TH1F*)f7->Get("hit_Egem2");
        hhit_theta_gem2_noTB = (TH1F*)f9->Get("gen_Theta_gem2");
        hhit_theta_gem2_noB = (TH1F*)f10->Get("gen_Theta_gem2");
        hhit_theta_gem2 = (TH1F*)f1->Get("gen_Theta_gem2");
        hhit_theta_1cmAl_gem2 = (TH1F*)f2->Get("gen_Theta_gem2");
        hhit_Edepgem2_gamma_noTB = (TH1F*)f19->Get("hit_Egem2");
        hhit_Edepgem2_gamma_noB = (TH1F*)f110->Get("hit_Egem2");
        hhit_Edepgem2_gamma = (TH1F*)f11->Get("hit_Egem2");
        hhit_Egem2_gamma = (TH1F*)f11->Get("hit_E_gem2");
        hhit_Egem2_gamma_noTB = (TH1F*)f19->Get("hit_E_gem2");
        hhit_Edepgem2_gamma_1cmAl = (TH1F*)f12->Get("hit_Egem2");
        hhit_Edepgem2_gamma_1inpoly = (TH1F*)f13->Get("hit_Egem2");
        hhit_Edepgem2_gamma_35cm = (TH1F*)f15->Get("hit_Egem2");
        hhit_Edepgem2_gamma_45cm = (TH1F*)f16->Get("hit_Egem2");
        hhit_Edepgem2_gamma_55cm = (TH1F*)f17->Get("hit_Egem2");
        hhit_Edepgem2_gamma_25cm = (TH1F*)f14->Get("hit_Egem2");
        hhit_theta_1inpoly_gem2 = (TH1F*)f3->Get("gen_Theta_gem2");
        hhit_theta_25cm_gem2 = (TH1F*)f4->Get("gen_Theta_gem2");
        hhit_theta_25cm_gem2_electron = (TH1F*)f14->Get("gen_Theta_gem2");
        hhit_theta_35cm_gem2 = (TH1F*)f5->Get("gen_Theta_gem2");
        hhit_theta_35cmL_gem2 = (TH1F*)f8->Get("gen_Theta_gem2");
        hhit_theta_45cm_gem2 = (TH1F*)f6->Get("gen_Theta_gem2");
        hhit_theta_45cm_gem2_electron = (TH1F*)f16->Get("gen_Theta_gem2");
        hhit_theta_55cm_gem2 = (TH1F*)f17->Get("gen_Theta_gem2");
        hhit_theta_55cmL_gem2 = (TH1F*)f7->Get("gen_Theta_gem2");
        hpf_gem1_1cmAl = (TH1F*)f2->Get("hpf_gem1");
        hE_gem1_1cmAl = (TH1F*)f2->Get("hE_gem1");
        hpf_gem1_1inpoly = (TH1F*)f3->Get("hpf_gem1");
        hE_gem1_1inpoly = (TH1F*)f3->Get("hE_gem1");
        hhit_theta_noTB_electron = (TH1F*)f19->Get("gen_Theta_gem1");
        hhit_theta_noB_electron = (TH1F*)f110->Get("gen_Theta_gem1");
        hhit_theta_electron = (TH1F*)f11->Get("gen_Theta_gem1");
        hhit_theta_1cmAl_electron = (TH1F*)f12->Get("gen_Theta_gem1");
        hhit_theta_1inpoly_electron = (TH1F*)f13->Get("gen_Theta_gem1");
        hhit_theta_35cm_electron = (TH1F*)f15->Get("gen_Theta_gem1");
        hhit_theta_gem2_noTB_electron = (TH1F*)f19->Get("gen_Theta_gem2");
        hhit_theta_gem2_noB_electron = (TH1F*)f110->Get("gen_Theta_gem2");
        hhit_theta_gem2_electron = (TH1F*)f11->Get("gen_Theta_gem2");
        hhit_theta_1cmAl_gem2_electron = (TH1F*)f12->Get("gen_Theta_gem2");
        hhit_theta_1inpoly_gem2_electron = (TH1F*)f13->Get("gen_Theta_gem2");
        hhit_theta_35cm_gem2_electron = (TH1F*)f15->Get("gen_Theta_gem2");
	for(int k=0;k<11;k++){
		hhit_Edepgem1_procID[k]=(TH1F*)f1->Get(Form("hit_Edepgem1_procID%d",k));
		hhit_Egem1_procID[k]=(TH1F*)f1->Get(Form("hit_Egem1_procID%d",k));
        }
	TCanvas *c_gem[10];

	c_gem[4] = new TCanvas("c_gem[4]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
        //hhit_theta_noTB->SetLineColor(6);	
        hhit_theta_1inpoly->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta_1inpoly->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_1inpoly->SetTitle("#gamma in front of gem1");	
        hhit_theta_1inpoly->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_1inpoly->Scale(0.001);
        hhit_theta_1inpoly->GetYaxis()->SetRangeUser(1e0,1e6);	
       // hhit_theta->Draw("HISt");	
        hhit_theta_1inpoly->SetLineColor(1);	
       // hhit_theta_noTB->Scale(0.001);
        hhit_theta_1inpoly->Draw("HISt");	
      /*  hhit_theta_noB->SetLineColor(6);	
        hhit_theta_noB->Scale(0.001);
        hhit_theta_noB->Draw("same HISt");*/	
        hhit_theta_1cmAl->SetLineColor(4);	
        hhit_theta_1cmAl->Scale(0.001);
        hhit_theta_1cmAl->Draw("same HISt");	
       /* hhit_theta_1inpoly->SetLineColor(1);	
        hhit_theta_1inpoly->Scale(0.001);
        hhit_theta_1inpoly->Draw("same HISt");*/	
        double rate_theta_linpoly= hhit_theta_1inpoly->Integral();
       /* hhit_theta_35cm->SetLineColor(2);	
        hhit_theta_35cm->Scale(0.001);
        hhit_theta_35cm->Draw("same HISt");	*/
        hhit_theta_1inpoly->Draw("same HISt");	
        hhit_theta_25cm->SetLineColor(2);	
        hhit_theta_25cm->Scale(0.001);
        hhit_theta_25cm->Draw("same HISt");	
       // hhit_theta_45cm->SetLineColor(28);	
       // hhit_theta_45cm->Scale(0.001);
       // hhit_theta_45cm->Draw("same HISt");	
	TLegend *leg1 = new TLegend(0.45,0.7,0.8,0.9);
//	leg1->AddEntry(hhit_theta_35cm,"no shielding target vacuum","l");
//	leg1->AddEntry(hhit_theta_noTB,"no shielding target air","l");
//	leg1->AddEntry(hhit_theta_noB,"no shielding target+chamber","l");
	//leg1->AddEntry(hhit_theta,"no shielding beamline survey+old simu","l");
	leg1->AddEntry(hhit_theta_1inpoly,Form("NoSh full=target+chamber+beamline step rate=%f kHz",rate_theta_linpoly),"l");
	leg1->AddEntry(hhit_theta_1cmAl,"2x4x190 in^{3} Pb shielding full  ","l");
//	leg1->AddEntry(hhit_theta_45cm,"NoSh target vacuum detector on the floor ","l");
	leg1->AddEntry(hhit_theta_25cm,"1x4x12+2x4x283 in^{3} Pb shielding full","l");
	leg1->SetTextSize(0.035);
	leg1->SetBorderSize(0);
	leg1->SetFillColor(0);
	leg1->Draw("text same");

	c_gem[5] = new TCanvas("c_gem[5]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
      //  hhit_theta_gem2->SetLineColor(6);	
       // hhit_theta_gem2->Scale(0.001);
        hhit_theta_1inpoly_gem2->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta_1inpoly_gem2->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_1inpoly_gem2->SetTitle("#gamma in front of gem2");	
        hhit_theta_1inpoly_gem2->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_1inpoly_gem2->Scale(0.001);
        hhit_theta_1inpoly_gem2->GetYaxis()->SetRangeUser(1e0,1e6);	
       // hhit_theta_gem2->Draw("HISt");	
        hhit_theta_1inpoly_gem2->SetLineColor(1);	
        hhit_theta_1inpoly_gem2->Draw(" HISt");	
       /* hhit_theta_gem2_noB->SetLineColor(6);	
        hhit_theta_gem2_noB->Scale(0.001);
        hhit_theta_gem2_noB->Draw("same HISt");*/	
        hhit_theta_1cmAl_gem2->SetLineColor(4);	
        hhit_theta_1cmAl_gem2->Scale(0.001);
        hhit_theta_1cmAl_gem2->Draw("same HISt");	
        double rate_theta_linpoly_gem2= hhit_theta_1inpoly_gem2->Integral();
       /* hhit_theta_35cm_gem2->SetLineColor(2);	
        hhit_theta_35cm_gem2->Scale(0.001);
        hhit_theta_35cm_gem2->Draw("same HISt");	
        hhit_theta_1inpoly_gem2->Draw("same HISt");*/	
        hhit_theta_25cm_gem2->SetLineColor(2);	
        hhit_theta_25cm_gem2->Scale(0.001);
        hhit_theta_25cm_gem2->Draw("same HISt");	
       /* hhit_theta_45cm_gem2->SetLineColor(28);	
        hhit_theta_45cm_gem2->Scale(0.001);
        hhit_theta_45cm_gem2->Draw("same HISt");*/	
	TLegend *leg01 = new TLegend(0.45,0.7,0.8,0.9);
//	leg01->AddEntry(hhit_theta_35cm_gem2,"no shielding target vacuum","l");
//	leg01->AddEntry(hhit_theta_gem2_noTB,"no shielding target air","l");
//	leg01->AddEntry(hhit_theta_gem2_noB,"no shielding target+chamber","l");
	//leg1->AddEntry(hhit_theta,"no shielding beamline survey+old simu","l");
	leg01->AddEntry(hhit_theta_1inpoly_gem2,"NoSh full=target+chamber+beamline step ","l");
	leg01->AddEntry(hhit_theta_1cmAl_gem2,"2x4x190 in^{3} Pb shielding full  ","l");
//	leg01->AddEntry(hhit_theta_45cm_gem2,"NoSh target vacuum detector on the floor ","l");
	leg01->AddEntry(hhit_theta_25cm_gem2,"1x4x12+2x4x283 in^{3} Pb shielding full","l");
	leg01->SetTextSize(0.035);
	leg01->SetBorderSize(0);
	leg01->SetFillColor(0);
	leg01->Draw("text same");
	c_gem[6] = new TCanvas("c_gem[6]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
       // hhit_theta_electron->SetLineColor(6);	
        hhit_theta_1inpoly_electron->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta_1inpoly_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_1inpoly_electron->SetTitle("e^{-} in front of gem1");	
        hhit_theta_1inpoly_electron->GetXaxis()->SetRangeUser(0,95);	
      //  hhit_theta_electron->Scale(0.001);
        hhit_theta_1inpoly_electron->Scale(0.001);
        hhit_theta_1inpoly_electron->GetYaxis()->SetRangeUser(1e0,1e6);	
       // hhit_theta_electron->Draw("HISt");	
        hhit_theta_1inpoly_electron->SetLineColor(1);	
        hhit_theta_1inpoly_electron->Draw("HISt");	
        double rate_theta_1inpoly_electron= hhit_theta_1inpoly_electron->Integral();
       /* hhit_theta_noB_electron->SetLineColor(6);	
        hhit_theta_noB_electron->Scale(0.001);
        hhit_theta_noB_electron->Draw("same HISt");*/	
        hhit_theta_1cmAl_electron->SetLineColor(4);	
        hhit_theta_1cmAl_electron->Scale(0.001);
        hhit_theta_1cmAl_electron->Draw("same HISt");
     /*   hhit_theta_1inpoly_electron->SetLineColor(1);	
        hhit_theta_1inpoly_electron->Scale(0.001);
        hhit_theta_1inpoly_electron->Draw("same HISt");	
        hhit_theta_35cm_electron->SetLineColor(2);	
        hhit_theta_35cm_electron->Scale(0.001);
        hhit_theta_35cm_electron->Draw("same HISt");*/	
        hhit_theta_25cm_electron->SetLineColor(2);	
        hhit_theta_25cm_electron->Scale(0.001);
        hhit_theta_25cm_electron->Draw("same HISt");	
      /*  hhit_theta_45cm_electron->SetLineColor(28);	
        hhit_theta_45cm_electron->Scale(0.001);
        hhit_theta_45cm_electron->Draw("same HISt");*/	
        hhit_theta_1inpoly_electron->Draw("same HISt");	
	TLegend *leg21 = new TLegend(0.4,0.73,0.8,0.9);
//	leg21->AddEntry(hhit_theta_35cm,"no shielding target vacuum","l");
//	leg21->AddEntry(hhit_theta_noTB,"no shielding target air","l");
//	leg21->AddEntry(hhit_theta_noB,"no shielding target+chamber","l");
//	leg21->AddEntry(hhit_theta,"no shielding beamline survey+old simu","l");
	leg21->AddEntry(hhit_theta_1inpoly,"NoSh full=target+chamber+beamline step ","l");
	leg21->AddEntry(hhit_theta_1cmAl,"2x4x190 in^{3} Pb shielding full ","l");
//	leg21->AddEntry(hhit_theta_45cm,"NoSh target vacuum detector on the floor ","l");
	leg21->AddEntry(hhit_theta_25cm,"1x4x12+2x4x283 in^{3} Pb shielding full","l");
	leg21->SetTextSize(0.035);
	leg21->SetBorderSize(0);
	leg21->SetFillColor(0);
	leg21->Draw("text same");

	c_gem[7] = new TCanvas("c_gem[7]", "flux #theta",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
 //       hhit_theta_gem2_electron->SetLineColor(6);	
 //       hhit_theta_gem2_electron->Scale(0.001);
        hhit_theta_1inpoly_gem2_electron->GetYaxis()->SetTitle("rate (kHz)");	
        hhit_theta_gem2_electron->GetXaxis()->SetTitle("hit #theta");	
        hhit_theta_gem2_electron->SetTitle("e^{-} in front of gem2");	
        hhit_theta_gem2_electron->GetXaxis()->SetRangeUser(0,95);	
        hhit_theta_gem2_electron->Scale(0.001);
        hhit_theta_gem2_electron->GetYaxis()->SetRangeUser(1e0,1e6);	
  //      hhit_theta_gem2_electron->Draw("HISt");	
        hhit_theta_gem2_electron->SetLineColor(1);	
        hhit_theta_gem2_electron->Draw("HISt");	
        hhit_theta_1cmAl_gem2_electron->SetLineColor(4);	
        hhit_theta_1cmAl_gem2_electron->Scale(0.001);
        hhit_theta_1cmAl_gem2_electron->Draw("same HISt");	
        double rate_theta_1inpoly_gem2_electron= hhit_theta_1inpoly_gem2_electron->Integral();
       /* hhit_theta_35cm_gem2_electron->SetLineColor(2);	
        hhit_theta_35cm_gem2_electron->Scale(0.001);
        hhit_theta_35cm_gem2_electron->Draw("same HISt");	
        hhit_theta_1inpoly_gem2_electron->Draw("same HISt");*/	
        hhit_theta_25cm_gem2_electron->SetLineColor(2);	
        hhit_theta_25cm_gem2_electron->Scale(0.001);
        hhit_theta_25cm_gem2_electron->Draw("same HISt");	
        /*hhit_theta_45cm_gem2_electron->SetLineColor(28);	
        hhit_theta_45cm_gem2_electron->Scale(0.001);
        hhit_theta_45cm_gem2_electron->Draw("same HISt");*/	
	TLegend *leg201 = new TLegend(0.4,0.73,0.8,0.9);
//	leg201->AddEntry(hhit_theta_35cm_gem2_electron,"no shielding target vacuum","l");
//	leg201->AddEntry(hhit_theta_gem2_noTB_electron,"no shielding target air","l");
//	leg201->AddEntry(hhit_theta_gem2_noB_electron,"no shielding target+chamber","l");
//	leg201->AddEntry(hhit_theta,"no shielding beamline survey+old simu","l");
	leg201->AddEntry(hhit_theta_1inpoly_gem2_electron,"NoSh full=target+chamber+beamline step ","l");
	leg201->AddEntry(hhit_theta_1cmAl_gem2_electron,"2x4x190 in^{3} Pb shielding full ","l");
//	leg201->AddEntry(hhit_theta_45cm_gem2_electron,"NoSh target vacuum detector on the floor ","l");
	leg201->AddEntry(hhit_theta_25cm_gem2_electron,"1x4x12+2x4x283 in^{3} Pb shielding full","l");
	leg201->SetTextSize(0.035);
	leg201->SetBorderSize(0);
	leg201->SetFillColor(0);
	leg201->Draw("text same");
	c_gem[2] = new TCanvas("c_gem[2]", "gem1",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem1_electron_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_electron_noTB->SetTitle("#gamma on gem1 virtual plane");
        hhit_Edepgem1_electron_noTB->Scale(0.001);
        hhit_Edepgem1_electron_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
	hhit_Edepgem1_electron_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_electron_noTB->Draw("HIST");
	hhit_Edepgem1_electron_noB->SetLineColor(6);
        hhit_Edepgem1_electron_noB->Scale(0.001);
	hhit_Edepgem1_electron_noB->Draw("same HIST");
	hhit_Edepgem1_electron_1cmAl->SetLineColor(4);
        hhit_Edepgem1_electron_1cmAl->Scale(0.001);
	hhit_Edepgem1_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem1_electron_1inpoly->SetLineColor(1);
        hhit_Edepgem1_electron_1inpoly->Scale(0.001);
	hhit_Edepgem1_electron_1inpoly->Draw("same HIST");
        double rate_Edepgem1_electron_1inpoly= hhit_Edepgem1_electron_1inpoly->Integral();
	hhit_Edepgem1_electron_35cm->SetLineColor(2);
        hhit_Edepgem1_electron_35cm->Scale(0.001);
	hhit_Edepgem1_electron_35cm->Draw("same HIST");
	hhit_Edepgem1_electron_25cm->SetLineColor(7);
        hhit_Edepgem1_electron_25cm->Scale(0.001);
	hhit_Edepgem1_electron_25cm->Draw("same HIST");
	hhit_Edepgem1_electron_45cm->SetLineColor(28);
        hhit_Edepgem1_electron_45cm->Scale(0.001);
	hhit_Edepgem1_electron_45cm->Draw("same HIST");
	hhit_Edepgem1_electron_55cm->SetLineColor(38);
        hhit_Edepgem1_electron_55cm->Scale(0.001);
	hhit_Edepgem1_electron_55cm->Draw("same HIST");
	TLegend *leg11 = new TLegend(0.22,0.18,0.58,0.38);
//	leg11->AddEntry(hhit_Edepgem1_electron,"no shielding beamline survey+old simu","l");
	leg11->AddEntry(hhit_Edepgem1_electron_35cm,"no shielding target vacuum","l");
	leg11->AddEntry(hhit_Edepgem1_electron_noTB,"no shielding target air ","l");
	leg11->AddEntry(hhit_Edepgem1_electron_noB,"no shielding target air+chamber","l");
	leg11->AddEntry(hhit_Edepgem1_electron_1inpoly,Form("NoSh full=target+chamber+beamline step rate %f kHz",rate_Edepgem1_electron_1inpoly),"l");
	leg11->AddEntry(hhit_Edepgem1_electron_1cmAl,"2x4x190 in^{3} Pb shielding full ","l");
	leg11->AddEntry(hhit_Edepgem1_electron_45cm,"NoSh target vacuum detector on the floor ","l");
	leg11->AddEntry(hhit_Edepgem1_electron_55cm,"NoSh target air+chamber detector on the floor ","l");
	leg11->AddEntry(hhit_Edepgem1_electron_25cm,"Nosh full=target+chamber+beamline step floor","l");
	leg11->SetTextSize(0.035);
	leg11->SetBorderSize(0);
	leg11->SetFillColor(0);
	leg11->Draw("text same");
	c_gem[8] = new TCanvas("c_gem[8]", "gem1",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem1_Moller_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_Moller_noTB->SetTitle("e^{-} mtid=e^{-} on gem1 virtual plane");
        hhit_Edepgem1_Moller_noTB->Scale(0.001);
        hhit_Edepgem1_Moller_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
	hhit_Edepgem1_Moller_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_Moller_noTB->Draw("HIST");
	hhit_Edepgem1_Moller_noB->SetLineColor(6);
        hhit_Edepgem1_Moller_noB->Scale(0.001);
	hhit_Edepgem1_Moller_noB->Draw("same HIST");
	hhit_Edepgem1_Moller_1cmAl->SetLineColor(4);
        hhit_Edepgem1_Moller_1cmAl->Scale(0.001);
	hhit_Edepgem1_Moller_1cmAl->Draw("same HIST");
	hhit_Edepgem1_Moller_1inpoly->SetLineColor(1);
        hhit_Edepgem1_Moller_1inpoly->Scale(0.001);
	hhit_Edepgem1_Moller_1inpoly->Draw("same HIST");
	hhit_Edepgem1_Moller_35cm->SetLineColor(2);
        hhit_Edepgem1_Moller_35cm->Scale(0.001);
	hhit_Edepgem1_Moller_35cm->Draw("same HIST");
	leg11->Draw("text same");
	c_gem[3] = new TCanvas("c_gem[3]", "gem2",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
//	hhit_Edepgem2_electron->SetLineColor(6);
	hhit_Edepgem2_electron_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem2_electron_noTB->SetTitle("#gamma on gem2 virtual plane");
  //      hhit_Edepgem2_electron->Scale(0.001);
        hhit_Edepgem2_electron_noTB->Scale(0.001);
        hhit_Edepgem2_electron_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
//	hhit_Edepgem2_electron->Draw("HIST");
	hhit_Edepgem2_electron_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem2_electron_noTB->Draw(" HIST");
	hhit_Edepgem2_electron_noB->SetLineColor(6);
        hhit_Edepgem2_electron_noB->Scale(0.001);
	hhit_Edepgem2_electron_noB->Draw("same HIST");
	hhit_Edepgem2_electron_1cmAl->SetLineColor(4);
        hhit_Edepgem2_electron_1cmAl->Scale(0.001);
	hhit_Edepgem2_electron_1cmAl->Draw("same HIST");
	hhit_Edepgem2_electron_1inpoly->SetLineColor(1);
        hhit_Edepgem2_electron_1inpoly->Scale(0.001);
	hhit_Edepgem2_electron_1inpoly->Draw("same HIST");
        double rate_Edepgem2_electron_1inpoly= hhit_Edepgem2_electron_1inpoly->Integral();
	hhit_Edepgem2_electron_35cm->SetLineColor(2);
        hhit_Edepgem2_electron_35cm->Scale(0.001);
	hhit_Edepgem2_electron_35cm->Draw("same HIST");
	hhit_Edepgem2_electron_25cm->SetLineColor(7);
        hhit_Edepgem2_electron_25cm->Scale(0.001);
	hhit_Edepgem2_electron_25cm->Draw("same HIST");
	hhit_Edepgem2_electron_45cm->SetLineColor(28);
        hhit_Edepgem2_electron_45cm->Scale(0.001);
	hhit_Edepgem2_electron_45cm->Draw("same HIST");
	hhit_Edepgem2_electron_55cm->SetLineColor(38);
        hhit_Edepgem2_electron_55cm->Scale(0.001);
	hhit_Edepgem2_electron_55cm->Draw("same HIST");
	TLegend *leg31 = new TLegend(0.22,0.18,0.58,0.38);
//	leg11->AddEntry(hhit_Edepgem1_electron,"no shielding beamline survey+old simu","l");
	leg31->AddEntry(hhit_Edepgem2_electron_35cm,"no shielding target vacuum","l");
	leg31->AddEntry(hhit_Edepgem2_electron_noTB,"no shielding target air ","l");
	leg31->AddEntry(hhit_Edepgem2_electron_noB,"no shielding target air+chamber","l");
	leg31->AddEntry(hhit_Edepgem2_electron_1inpoly,Form("NoSh full=target+chamber+beamline step rate %f kHz",rate_Edepgem2_electron_1inpoly),"l");
	leg31->AddEntry(hhit_Edepgem2_electron_1cmAl,"2x4x190 in^{3} Pb shielding full ","l");
	leg31->AddEntry(hhit_Edepgem2_electron_45cm,"NoSh target vacuum detector on the floor ","l");
	leg31->AddEntry(hhit_Edepgem2_electron_55cm,"NoSh target air+chamber detector on the floor ","l");
	leg31->AddEntry(hhit_Edepgem2_electron_25cm,"Nosh full=target+chamber+beamline step floor","l");
	leg31->SetTextSize(0.035);
	leg31->SetBorderSize(0);
	leg31->SetFillColor(0);
	leg31->Draw("text same");
	c_gem[9] = new TCanvas("c_gem[9]", "gem1",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
	hhit_Edepgem1_compton_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_compton_noTB->SetTitle("e^{-} mtid=#gamma on gem1 virtual plane");
        hhit_Edepgem1_compton_noTB->Scale(0.001);
        hhit_Edepgem1_compton_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
	hhit_Edepgem1_compton_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_compton_noTB->Draw("HIST");
	hhit_Edepgem1_compton_noB->SetLineColor(6);
        hhit_Edepgem1_compton_noB->Scale(0.001);
	hhit_Edepgem1_compton_noB->Draw("same HIST");
	hhit_Edepgem1_compton_1cmAl->SetLineColor(4);
        hhit_Edepgem1_compton_1cmAl->Scale(0.001);
	hhit_Edepgem1_compton_1cmAl->Draw("same HIST");
	hhit_Edepgem1_compton_1inpoly->SetLineColor(1);
        hhit_Edepgem1_compton_1inpoly->Scale(0.001);
	hhit_Edepgem1_compton_1inpoly->Draw("same HIST");
	hhit_Edepgem1_compton_35cm->SetLineColor(2);
        hhit_Edepgem1_compton_35cm->Scale(0.001);
	hhit_Edepgem1_compton_35cm->Draw("same HIST");
	leg11->Draw("text same");
	c_gem[0] = new TCanvas("c_gem[0]", "gem",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
//	hhit_Edepgem1_gamma->SetLineColor(6);
	hhit_Edepgem1_gamma_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem1_gamma_noTB->SetTitle("e^{-} on gem1 virtual plane");
  //      hhit_Edepgem1_gamma->Scale(0.001);
        hhit_Edepgem1_gamma_noTB->Scale(0.001);
        hhit_Edepgem1_gamma_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
//	hhit_Edepgem1_gamma->Draw("HIST");
	hhit_Edepgem1_gamma_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem1_gamma_noTB->Draw("HIST");
        double rate_Edepgem1_gamma_noTB= hhit_Edepgem1_gamma_noTB->Integral();
	hhit_Edepgem1_gamma_noB->SetLineColor(6);
        hhit_Edepgem1_gamma_noB->Scale(0.001);
	hhit_Edepgem1_gamma_noB->Draw("same HIST");
        double rate_Edepgem1_gamma_noB= hhit_Edepgem1_gamma_noB->Integral();
	hhit_Edepgem1_gamma_1cmAl->SetLineColor(4);
        hhit_Edepgem1_gamma_1cmAl->Scale(0.001);
	hhit_Edepgem1_gamma_1cmAl->Draw("same HIST");
	hhit_Edepgem1_gamma_1inpoly->SetLineColor(1);
        hhit_Edepgem1_gamma_1inpoly->Scale(0.001);
	hhit_Edepgem1_gamma_1inpoly->Draw("same HIST");
        double rate_Edepgem1_gamma_1inpoly= hhit_Edepgem1_gamma_1inpoly->Integral();
	hhit_Edepgem1_gamma_35cm->SetLineColor(2);
        hhit_Edepgem1_gamma_35cm->Scale(0.001);
	hhit_Edepgem1_gamma_35cm->Draw("same HIST");
        double rate_Edepgem1_gamma_35cm= hhit_Edepgem1_gamma_35cm->Integral();
	hhit_Edepgem1_gamma_45cm->SetLineColor(28);
        hhit_Edepgem1_gamma_45cm->Scale(0.001);
	hhit_Edepgem1_gamma_45cm->Draw("same HIST");
        double rate_Edepgem1_gamma_45cm= hhit_Edepgem1_gamma_45cm->Integral();
	hhit_Edepgem1_gamma_25cm->SetLineColor(7);
        hhit_Edepgem1_gamma_25cm->Scale(0.001);
	hhit_Edepgem1_gamma_25cm->Draw("same HIST");
        double rate_Edepgem1_gamma_25cm= hhit_Edepgem1_gamma_25cm->Integral();
	hhit_Edepgem1_gamma_55cm->SetLineColor(38);
        hhit_Edepgem1_gamma_55cm->Scale(0.001);
	hhit_Edepgem1_gamma_55cm->Draw("same HIST");
	hhit_Edepgem1_gamma_15deg->SetLineColor(kYellow+1);
        hhit_Edepgem1_gamma_15deg->Scale(0.001);
	hhit_Edepgem1_gamma_15deg->Draw("same HIST");
        double rate_Edepgem1_gamma_15deg= hhit_Edepgem1_gamma_15deg->Integral();
	hhit_Edepgem1_gamma_20degv->SetLineColor(9);
        hhit_Edepgem1_gamma_20degv->Scale(0.001);
	hhit_Edepgem1_gamma_20degv->Draw("same HIST");
        double rate_Edepgem1_gamma_20degv= hhit_Edepgem1_gamma_20degv->Integral();
	TLegend *leg111 = new TLegend(0.22,0.18,0.58,0.38);
//	leg111->AddEntry(hhit_Edepgem1_electron,"no shielding beamline survey+old simu","l");
	leg111->AddEntry(hhit_Edepgem1_gamma_35cm,Form("no shielding target vacuum rate %f kHz",rate_Edepgem1_gamma_35cm),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_noTB,Form("no shielding target air rate %f kHz",rate_Edepgem1_gamma_noTB),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_noB,Form("no shielding target air+chamber rate %f kHz",rate_Edepgem1_gamma_noB),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_1inpoly,Form("NoSh full=target+chamber+beamline step rate %f kHz",rate_Edepgem1_gamma_1inpoly),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_1cmAl,"2x4x190 in^{3} Pb shielding full ","l");
	leg111->AddEntry(hhit_Edepgem1_gamma_45cm,Form("NoSh target vacuum detector on the floor rate %f kHz",rate_Edepgem1_gamma_45cm),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_55cm,"NoSh target air+chamber detector on the floor ","l");
	leg111->AddEntry(hhit_Edepgem1_gamma_25cm,Form("Nosh full=target+chamber+beamline step floor rate %f kHz",rate_Edepgem1_gamma_25cm),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_15deg,Form("Nosh full=target+chamber+beamline step #theta=15deg rate %f kHz",rate_Edepgem1_gamma_15deg),"l");
	leg111->AddEntry(hhit_Edepgem1_gamma_20degv,Form("Nosh target vacuum #theta=20deg rate %f kHz",rate_Edepgem1_gamma_20degv),"l");
	leg111->SetTextSize(0.035);
	leg111->SetBorderSize(0);
	leg111->SetFillColor(0);
	leg111->Draw("text same");
	c_gem[1] = new TCanvas("c_gem[1]", "gem",1800,1000);
	gPad->SetLogy();
	gPad->SetGridy();
	gPad->SetGridx();
//	hhit_Edepgem2_gamma->SetLineColor(6);
	hhit_Edepgem2_gamma_noTB->GetYaxis()->SetTitle("rate (kHz)");
	hhit_Edepgem2_gamma_noTB->SetTitle("e^{-} on gem2 virtual plane");
//        hhit_Edepgem2_gamma->Scale(0.001);
        hhit_Edepgem2_gamma_noTB->Scale(0.001);
        hhit_Edepgem2_gamma_noTB->GetYaxis()->SetRangeUser(1e0,1e6);	
//	hhit_Edepgem2_gamma->Draw("HIST");
	hhit_Edepgem2_gamma_noTB->SetLineColor(kGreen+1);
	hhit_Edepgem2_gamma_noTB->Draw(" HIST");
	hhit_Edepgem2_gamma_noB->SetLineColor(6);
        hhit_Edepgem2_gamma_noB->Scale(0.001);
	hhit_Edepgem2_gamma_noB->Draw("same HIST");
	hhit_Edepgem2_gamma_1cmAl->SetLineColor(4);
        hhit_Edepgem2_gamma_1cmAl->Scale(0.001);
	hhit_Edepgem2_gamma_1cmAl->Draw("same HIST");
	hhit_Edepgem2_gamma_1inpoly->SetLineColor(1);
        hhit_Edepgem2_gamma_1inpoly->Scale(0.001);
	hhit_Edepgem2_gamma_1inpoly->Draw("same HIST");
        double rate_Edepgem2_gamma_1inpoly= hhit_Edepgem2_gamma_1inpoly->Integral();
	hhit_Edepgem2_gamma_35cm->SetLineColor(2);
        hhit_Edepgem2_gamma_35cm->Scale(0.001);
	hhit_Edepgem2_gamma_35cm->Draw("same HIST");
	hhit_Edepgem2_gamma_45cm->SetLineColor(28);
        hhit_Edepgem2_gamma_45cm->Scale(0.001);
	hhit_Edepgem2_gamma_45cm->Draw("same HIST");
	hhit_Edepgem2_gamma_25cm->SetLineColor(7);
        hhit_Edepgem2_gamma_25cm->Scale(0.001);
	hhit_Edepgem2_gamma_25cm->Draw("same HIST");
	hhit_Edepgem2_gamma_55cm->SetLineColor(38);
        hhit_Edepgem2_gamma_55cm->Scale(0.001);
	hhit_Edepgem2_gamma_55cm->Draw("same HIST");
	TLegend *leg41 = new TLegend(0.22,0.18,0.58,0.38);
//	leg111->AddEntry(hhit_Edepgem1_electron,"no shielding beamline survey+old simu","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_35cm,"no shielding target vacuum","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_noTB,"no shielding target air ","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_noB,"no shielding target air+chamber","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_1inpoly,Form("NoSh full=target+chamber+beamline step rate %f kHz",rate_Edepgem2_gamma_1inpoly),"l");
	leg41->AddEntry(hhit_Edepgem2_gamma_1cmAl,"2x4x190 in^{3} Pb shielding full ","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_45cm,"NoSh target vacuum detector on the floor ","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_55cm,"NoSh target air+chamber detector on the floor ","l");
	leg41->AddEntry(hhit_Edepgem2_gamma_25cm,"Nosh full=target+chamber+beamline step floor","l");
	leg41->SetTextSize(0.035);
	leg41->SetBorderSize(0);
	leg41->SetFillColor(0);
	leg41->Draw("text same");
 	for(int a=4;a<8;a++){
		c_gem[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_BeamOnTarget_8deg_BLshielding_tune.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));
}
