
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_rate_Cer_newCh_7deg(){
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC1_Etotalcut_electron.root");
	TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC1_Etotalcut_e.root");
	TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC1_Etotalcut_gamma.root");
	TFile *f5 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC0_Etotalcut_electron.root");
	TFile *f6 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC0_Etotalcut_e.root");
	TFile *f7 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC0_Etotalcut_gamma.root");
	TFile *f8 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_Etotalcut.root");
	TFile *f9 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC2_Etotalcut_electron.root");
	TFile *f10 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC2_Etotalcut_e.root");
	TFile *f11 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC2_Etotalcut_gamma.root");
	TFile *f12 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC3_Etotalcut_electron.root");
	TFile *f13 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC3_Etotalcut_e.root");
	TFile *f14 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_SC3_Etotalcut_gamma.root");
	TFile *f15 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_CC_Etotalcut_electron.root");
	TFile *f16 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_CC_Etotalcut_e.root");
	TFile *f17 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_CC_Etotalcut_gamma.root");
	TFile *f18 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_preshower_Etotalcut_electron.root");
	TFile *f19 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_preshower_Etotalcut_e.root");
	TFile *f20 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_preshower_Etotalcut_gamma.root");
	TFile *f21 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_sangle_5x10SC_7deg_r20m_carbon_even_gamma/HallC_beamtest_BeamOnTarget_1e6_7deg_5uA_4SC_r20m_cfoil_even_gamma_reduce_tree_rate_preshower_Etotalcut_gamma_tid1.root");
	TTree *tree_SC0_electron = (TTree*) f5->Get("T");
	TTree *tree_SC0_e = (TTree*) f6->Get("T");
	TTree *tree_SC0_gamma = (TTree*) f7->Get("T"); //abs(phicut) <5 deg
	TTree *tree_beam = (TTree*) f8->Get("T");
	TTree *tree_SC1_electron = (TTree*) f2->Get("T");
	TTree *tree_SC1_e = (TTree*) f3->Get("T");
	TTree *tree_SC1_gamma = (TTree*) f4->Get("T"); //abs(phicut) <5 deg
	TTree *tree_SC2_electron = (TTree*) f9->Get("T");
	TTree *tree_SC2_e = (TTree*) f10->Get("T");
	TTree *tree_SC2_gamma = (TTree*) f11->Get("T"); //abs(phicut) <5 deg
	TTree *tree_SC3_electron = (TTree*) f12->Get("T");
	TTree *tree_SC3_e = (TTree*) f13->Get("T");
	TTree *tree_SC3_gamma = (TTree*) f14->Get("T"); //abs(phicut) <5 deg
	TTree *tree_CC_electron = (TTree*) f15->Get("T");
	TTree *tree_CC_e = (TTree*) f16->Get("T");
	TTree *tree_CC_gamma = (TTree*) f17->Get("T"); //abs(phicut) <5 deg
	TTree *tree_preshower_electron = (TTree*) f18->Get("T");
	TTree *tree_preshower_e = (TTree*) f19->Get("T");
	TTree *tree_preshower_gamma = (TTree*) f20->Get("T"); //abs(phicut) <5 deg
	TTree *tree_preshower_gamma_tid1 = (TTree*) f21->Get("T"); //abs(phicut) <5 deg
	const int rebinfac=1;
        tree_SC0_e->Draw("SC0_Eendsum>>SC0_e(500,0,50)","rate*(SC0_Eendsum>0)","goff");
	TH1F *SC0_e_hist = (TH1F*)gROOT->FindObject("SC0_e");
        tree_SC0_electron->Draw("SC0_Eendsum>>SC0_electron(500,0,50)","rate*(SC0_Eendsum>0)","goff");
	TH1F *SC0_electron_hist = (TH1F*)gROOT->FindObject("SC0_electron");
        tree_SC0_gamma->Draw("SC0_Eendsum>>SC0_gamma(500,0,50)","rate*(SC0_Eendsum>0)","goff");
	TH1F *SC0_gamma_hist = (TH1F*)gROOT->FindObject("SC0_gamma");
        tree_beam->Draw("SC0_Eendsum>>SC0_beam(500,0,50)","rate*(SC0_Eendsum>0)","goff");
	TH1F *SC0_beam_hist = (TH1F*)gROOT->FindObject("SC0_beam");
        tree_SC1_e->Draw("SC1_Eendsum>>SC1_e(500,0,50)","rate*(SC1_Eendsum>0)","goff");
	TH1F *SC1_e_hist = (TH1F*)gROOT->FindObject("SC1_e");
        tree_SC1_electron->Draw("SC1_Eendsum>>SC1_electron(500,0,50)","rate*(SC1_Eendsum>0)","goff");
	TH1F *SC1_electron_hist = (TH1F*)gROOT->FindObject("SC1_electron");
        tree_SC1_gamma->Draw("SC1_Eendsum>>SC1_gamma(500,0,50)","rate*(SC1_Eendsum>0)","goff");
	TH1F *SC1_gamma_hist = (TH1F*)gROOT->FindObject("SC1_gamma");
        tree_beam->Draw("SC1_Eendsum>>SC1_beam(500,0,50)","rate*(SC1_Eendsum>0)","goff");
	TH1F *SC1_beam_hist = (TH1F*)gROOT->FindObject("SC1_beam");
        tree_SC2_e->Draw("SC2_Eendsum>>SC2_e(500,0,50)","rate*(SC2_Eendsum>0)","goff");
	TH1F *SC2_e_hist = (TH1F*)gROOT->FindObject("SC2_e");
        tree_SC2_electron->Draw("SC2_Eendsum>>SC2_electron(500,0,50)","rate*(SC2_Eendsum>0)","goff");
	TH1F *SC2_electron_hist = (TH1F*)gROOT->FindObject("SC2_electron");
        tree_SC2_gamma->Draw("SC2_Eendsum>>SC2_gamma(500,0,50)","rate*(SC2_Eendsum>0)","goff");
	TH1F *SC2_gamma_hist = (TH1F*)gROOT->FindObject("SC2_gamma");
        tree_beam->Draw("SC2_Eendsum>>SC2_beam(500,0,50)","rate*(SC2_Eendsum>0)","goff");
	TH1F *SC2_beam_hist = (TH1F*)gROOT->FindObject("SC2_beam");
        tree_SC3_e->Draw("SC3_Eendsum>>SC3_e(500,0,50)","rate*(SC3_Eendsum>0)","goff");
	TH1F *SC3_e_hist = (TH1F*)gROOT->FindObject("SC3_e");
        tree_SC3_electron->Draw("SC3_Eendsum>>SC3_electron(500,0,50)","rate*(SC3_Eendsum>0)","goff");
	TH1F *SC3_electron_hist = (TH1F*)gROOT->FindObject("SC3_electron");
        tree_SC3_gamma->Draw("SC3_Eendsum>>SC3_gamma(500,0,50)","rate*(SC3_Eendsum>0)","goff");
	TH1F *SC3_gamma_hist = (TH1F*)gROOT->FindObject("SC3_gamma");
        tree_beam->Draw("SC3_Eendsum>>SC3_beam(500,0,50)","rate*(SC3_Eendsum>0)","goff");
	TH1F *SC3_beam_hist = (TH1F*)gROOT->FindObject("SC3_beam");
        tree_CC_e->Draw("Npesum>>CC_e(50,0,50)","rate*(Npesum>0)","goff");
	TH1F *CC_e_hist = (TH1F*)gROOT->FindObject("CC_e");
        tree_CC_electron->Draw("Npesum>>CC_electron(50,0,50)","rate*(Npesum>0)","goff");
	TH1F *CC_electron_hist = (TH1F*)gROOT->FindObject("CC_electron");
        tree_CC_gamma->Draw("Npesum>>CC_gamma(50,0,50)","rate*(Npesum>0)","goff");
	TH1F *CC_gamma_hist = (TH1F*)gROOT->FindObject("CC_gamma");
        tree_beam->Draw("Npesum>>CC_beam(50,0,50)","rate*(Npesum>0)","goff");
	TH1F *CC_beam_hist = (TH1F*)gROOT->FindObject("CC_beam");
        tree_preshower_e->Draw("PreShSum>>preshower_e(500,0,50)","rate*(PreShSum>0)","goff");
	TH1F *preshower_e_hist = (TH1F*)gROOT->FindObject("preshower_e");
        tree_preshower_electron->Draw("PreShSum>>preshower_electron(500,0,50)","rate*(PreShSum>0)","goff");
	TH1F *preshower_electron_hist = (TH1F*)gROOT->FindObject("preshower_electron");
        tree_preshower_gamma->Draw("PreShSum>>preshower_gamma(500,0,50)","rate*(PreShSum>0)","goff");
	TH1F *preshower_gamma_hist = (TH1F*)gROOT->FindObject("preshower_gamma");
        tree_beam->Draw("PreShSum>>preshower_beam(500,0,50)","rate*(PreShSum>0)","goff");
	TH1F *preshower_beam_hist = (TH1F*)gROOT->FindObject("preshower_beam");
       
        tree_preshower_e->Draw("ShowerSum>>shower_e(500,0,50)","rate*(ShowerSum>0)","goff");
	TH1F *shower_e_hist = (TH1F*)gROOT->FindObject("shower_e");
        tree_preshower_electron->Draw("ShowerSum>>shower_electron(500,0,50)","rate*(ShowerSum>0)","goff");
	TH1F *shower_electron_hist = (TH1F*)gROOT->FindObject("shower_electron");
        tree_preshower_gamma->Draw("ShowerSum>>shower_gamma(500,0,50)","rate*(ShowerSum>0)","goff");
	TH1F *shower_gamma_hist = (TH1F*)gROOT->FindObject("shower_gamma");
        tree_beam->Draw("ShowerSum>>shower_beam(500,0,50)","rate*(ShowerSum>0)","goff");
	TH1F *shower_beam_hist = (TH1F*)gROOT->FindObject("shower_beam");
        tree_beam->Draw("ShowerSum:SC3_Eendsum>>shower_vs_SC3(50,0,10,300,0,60)","rate","goff");
	TH2F *ShowerSum_vs_SC3_hist = (TH2F*)gROOT->FindObject("shower_vs_SC3");
        tree_preshower_electron->Draw("(7.105*ShowerSum+6.5*PreShSum)/PreShP:PreShP>>Etotal_vs_p_electron(200,0,200,150,0,1.5)","rate*(ShowerSum>0&&PreShSum>0)","goff");
	TH2F *Etotal_vs_p_electron_hist = (TH2F*)gROOT->FindObject("Etotal_vs_p_electron");
        tree_preshower_e->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_e(500,0,500)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_e_hist = (TH1F*)gROOT->FindObject("E_e");
        tree_preshower_electron->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_electron(500,0,500)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_electron_hist = (TH1F*)gROOT->FindObject("E_electron");
        tree_preshower_gamma->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_gamma(500,0,500)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_gamma_hist = (TH1F*)gROOT->FindObject("E_gamma");
        tree_preshower_gamma->Draw("(7.105*ShowerSum+6.5*PreShSum)/PreShP:PreShP>>Etotal_vs_p_gamma(210,0,210,150,0,1.5)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_vs_p_gamma_hist = (TH1F*)gROOT->FindObject("Etotal_vs_p_gamma");
        tree_beam->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_beam(500,0,500)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_beam_hist = (TH1F*)gROOT->FindObject("E_beam");
        tree_preshower_gamma_tid1->Draw("(7.105*ShowerSum+6.5*PreShSum)>>E_gamma_tid1(500,0,500)","rate*(ShowerSum>0 && PreShSum>0)","goff");
	TH1F *Etotal_gamma_tid1_hist = (TH1F*)gROOT->FindObject("E_gamma_tid1");


      /*  tree_pip->Draw("Npesum>>Npesum_pip(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pip_hist = (TH1F*)gROOT->FindObject("Npesum_pip");
        tree_pim->Draw("Npesum>>Npesum_pim(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_pi0->Draw("Npesum>>Npesum_pi0(100,0,100)","rate*( ShowerSum>0)","goff");
	TH1F *Npesum_pi0_hist = (TH1F*)gROOT->FindObject("Npesum_pi0");
        tree_eAll->Draw("Npesum>>Npesum_eAll(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_eAll_hist = (TH1F*)gROOT->FindObject("Npesum_eAll");
        tree_beam->Draw("Npesum>>Npesum_beam(100,0,100)","rate*(ShowerSum>0)","goff");
	TH1F *Npesum_beam_hist = (TH1F*)gROOT->FindObject("Npesum_beam");
        tree_pip->Draw("GEM00_x>>GEM00_pip(320,-8,8)","rate*(GEM00_n>0 && GEM10_n>0)","goff");
	TH1F *GEM00_pip_hist = (TH1F*)gROOT->FindObject("GEM00_pip");
        tree_pim->Draw("GEM00_x>>GEM00_pim(320,-8,8)","rate*(GEM00_n>0&& GEM10_n>0)","goff");
	TH1F *GEM00_pim_hist = (TH1F*)gROOT->FindObject("GEM00_pim");
        tree_pi0->Draw("GEM00_x>>GEM00_pi0(320,-8,8)","rate*( GEM00_n>0&& GEM10_n>0)","goff");
	TH1F *GEM00_pi0_hist = (TH1F*)gROOT->FindObject("GEM00_pi0");
        tree_eAll->Draw("GEM00_x>>GEM00_eAll(320,-8,8)","rate*(GEM00_n>0&& GEM10_n>0)","goff");
	TH1F *GEM00_eAll_hist = (TH1F*)gROOT->FindObject("GEM00_eAll");
        tree_beam->Draw("GEM00_x>>GEM00_beam(320,-8,8)","rate*(GEM00_n>0&& GEM10_n>0)","goff");
	TH1F *GEM00_beam_hist = (TH1F*)gROOT->FindObject("GEM00_beam");
        tree_pip->Draw("ShowerSum>>shower_pip(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_pip_hist = (TH1F*)gROOT->FindObject("shower_pip");
        tree_pim->Draw("ShowerSum>>shower_pim(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_pim_hist = (TH1F*)gROOT->FindObject("shower_pim");
        tree_pi0->Draw("ShowerSum>>shower_pi0(4000,0,2000)","rate*( ShowerSum>4)","goff");
	TH1F *shower_pi0_hist = (TH1F*)gROOT->FindObject("shower_pi0");
        tree_eAll->Draw("ShowerSum>>shower_eAll(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_eAll_hist = (TH1F*)gROOT->FindObject("shower_eAll");
        tree_beam->Draw("ShowerSum>>shower_beam(4000,0,2000)","rate*(ShowerSum>4)","goff");
	TH1F *shower_beam_hist = (TH1F*)gROOT->FindObject("shower_beam");
        tree_pip->Draw("Npesum>>Npesum_pip(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_pip_hist = (TH1F*)gROOT->FindObject("Npesum_pip");
        tree_pim->Draw("Npesum>>Npesum_pim(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_pim_hist = (TH1F*)gROOT->FindObject("Npesum_pim");
        tree_pi0->Draw("Npesum>>Npesum_pi0(200,0,100)","rate*( ShowerSum>4)","goff");
	TH1F *Npesum_pi0_hist = (TH1F*)gROOT->FindObject("Npesum_pi0");
        tree_eAll->Draw("Npesum>>Npesum_eAll(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_eAll_hist = (TH1F*)gROOT->FindObject("Npesum_eAll");
        tree_beam->Draw("Npesum>>Npesum_beam(200,0,100)","rate*(ShowerSum>4)","goff");
	TH1F *Npesum_beam_hist = (TH1F*)gROOT->FindObject("Npesum_beam");
        tree_pip->Draw("GEM10_x>>GEM00_pip(320,-8,8)","rate*(ShowerSum>4)","goff");
	TH1F *GEM00_pip_hist = (TH1F*)gROOT->FindObject("GEM00_pip");
        tree_pim->Draw("GEM10_x>>GEM00_pim(320,-8,8)","rate*(ShowerSum>4)","goff");
	TH1F *GEM00_pim_hist = (TH1F*)gROOT->FindObject("GEM00_pim");
        tree_pi0->Draw("GEM10_x>>GEM00_pi0(320,-8,8)","rate*( ShowerSum>4)","goff");
	TH1F *GEM00_pi0_hist = (TH1F*)gROOT->FindObject("GEM00_pi0");
        tree_eAll->Draw("GEM10_x>>GEM00_eAll(320,-8,8)","rate*(ShowerSum>4)","goff");
	TH1F *GEM00_eAll_hist = (TH1F*)gROOT->FindObject("GEM00_eAll");
        tree_beam->Draw("GEM10_x>>GEM00_beam(320,-8,8)","rate*(ShowerSum>4)","goff");
	TH1F *GEM00_beam_hist = (TH1F*)gROOT->FindObject("GEM00_beam");*/
        TCanvas *c[10];
	c[0] = new TCanvas("c[0]","c[0]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC0_beam_hist->SetLineColor(6);
        SC0_beam_hist->GetXaxis()->SetTitle("SC0 Edep (MeV)");
        SC0_beam_hist->GetYaxis()->SetTitle("Events");
        SC0_beam_hist->Rebin(rebinfac);
        SC0_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        SC0_beam_hist->Draw("HISt");
        double rate_proton= SC0_beam_hist->Integral()/1e6;
        SC0_e_hist->SetLineColor(2);
        SC0_e_hist->Rebin(rebinfac);
        SC0_e_hist->Draw("same HIST");
        double rate_e= SC0_e_hist->Integral()/1e6;
        SC0_electron_hist->SetLineColor(1);
        SC0_electron_hist->Rebin(rebinfac);
        SC0_electron_hist->Draw("same HIST");
        double rate_electron= SC0_electron_hist->Integral()/1e6;
        SC0_gamma_hist->SetLineColor(8);
        SC0_gamma_hist->Rebin(rebinfac);
        SC0_gamma_hist->Draw("same HIST");
        double rate_gamma= SC0_gamma_hist->Integral()/1e6;
  TLegend *leg8 = new TLegend(0.45,0.6,0.8,0.88);
  leg8->AddEntry(SC0_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron),"l");
  leg8->AddEntry(SC0_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e),"l");
  leg8->AddEntry(SC0_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma),"l");
  leg8->AddEntry(SC0_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        CC_beam_hist->SetLineColor(6);
        CC_beam_hist->GetXaxis()->SetTitle("CC Npe ");
        CC_beam_hist->GetYaxis()->SetTitle("Events");
        CC_beam_hist->Rebin(rebinfac);
        CC_beam_hist->GetYaxis()->SetRangeUser(1e0,1e5);
        CC_beam_hist->Draw("HISt");
        double rate_proton_CC= CC_beam_hist->Integral()/1e6;
        CC_e_hist->SetLineColor(2);
        CC_e_hist->Rebin(rebinfac);
        CC_e_hist->Draw("same HIST");
        double rate_e_CC= CC_e_hist->Integral()/1e6;
        CC_electron_hist->SetLineColor(1);
        CC_electron_hist->Rebin(rebinfac);
        CC_electron_hist->Draw("same HIST");
        double rate_electron_CC= CC_electron_hist->Integral()/1e6;
        CC_gamma_hist->SetLineColor(8);
        CC_gamma_hist->Rebin(rebinfac);
        CC_gamma_hist->Draw("same HIST");
        double rate_gamma_CC= CC_gamma_hist->Integral()/1e6;
  TLegend *leg1 = new TLegend(0.5,0.6,0.8,0.88);
  leg1->AddEntry(CC_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_CC),"l");
  leg1->AddEntry(CC_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_CC),"l");
  leg1->AddEntry(CC_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_CC),"l");
  leg1->AddEntry(CC_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_CC),"l");
  leg1->SetTextSize(0.03);
  leg1->SetBorderSize(0);
  leg1->SetFillColor(0);
  leg1->Draw("text same");
	c[3] = new TCanvas("c[3]","c[3]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC1_beam_hist->SetLineColor(6);
        SC1_beam_hist->GetXaxis()->SetTitle("SC1 Edep (MeV)");
        SC1_beam_hist->GetYaxis()->SetTitle("Events");
        SC1_beam_hist->Rebin(rebinfac);
        SC1_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        SC1_beam_hist->Draw("HISt");
        double rate_proton_SC1= SC1_beam_hist->Integral()/1e6;
        SC1_e_hist->SetLineColor(2);
        SC1_e_hist->Rebin(rebinfac);
        SC1_e_hist->Draw("same HIST");
        double rate_e_SC1= SC1_e_hist->Integral()/1e6;
        SC1_electron_hist->SetLineColor(1);
        SC1_electron_hist->Rebin(rebinfac);
        SC1_electron_hist->Draw("same HIST");
        double rate_electron_SC1= SC1_electron_hist->Integral()/1e6;
        SC1_gamma_hist->SetLineColor(8);
        SC1_gamma_hist->Rebin(rebinfac);
        SC1_gamma_hist->Draw("same HIST");
        double rate_gamma_SC1= SC1_gamma_hist->Integral()/1e6;
  TLegend *leg9 = new TLegend(0.45,0.6,0.8,0.88);
  leg9->AddEntry(SC1_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_SC1),"l");
  leg9->AddEntry(SC1_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_SC1),"l");
  leg9->AddEntry(SC1_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_SC1),"l");
  leg9->AddEntry(SC1_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_SC1),"l");
  leg9->SetTextSize(0.03);
  leg9->SetBorderSize(0);
  leg9->SetFillColor(0);
  leg9->Draw("text same");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC2_beam_hist->SetLineColor(6);
        SC2_beam_hist->GetXaxis()->SetTitle("SC2 Edep (MeV)");
        SC2_beam_hist->GetYaxis()->SetTitle("Events");
        SC2_beam_hist->Rebin(rebinfac);
        SC2_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        SC2_beam_hist->Draw("HISt");
        double rate_proton_SC2= SC2_beam_hist->Integral()/1e6;
        SC2_e_hist->SetLineColor(2);
        SC2_e_hist->Rebin(rebinfac);
        SC2_e_hist->Draw("same HIST");
        double rate_e_SC2= SC2_e_hist->Integral()/1e6;
        SC2_electron_hist->SetLineColor(1);
        SC2_electron_hist->Rebin(rebinfac);
        SC2_electron_hist->Draw("same HIST");
        double rate_electron_SC2= SC2_electron_hist->Integral()/1e6;
        SC2_gamma_hist->SetLineColor(8);
        SC2_gamma_hist->Rebin(rebinfac);
        SC2_gamma_hist->Draw("same HIST");
        double rate_gamma_SC2= SC2_gamma_hist->Integral()/1e6;
  TLegend *leg18 = new TLegend(0.45,0.6,0.8,0.88);
  leg18->AddEntry(SC2_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_SC2),"l");
  leg18->AddEntry(SC2_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_SC2),"l");
  leg18->AddEntry(SC2_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_SC2),"l");
  leg18->AddEntry(SC2_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_SC2),"l");
  leg18->SetTextSize(0.03);
  leg18->SetBorderSize(0);
  leg18->SetFillColor(0);
  leg18->Draw("text same");
	c[4] = new TCanvas("c[4]","c[4]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        preshower_beam_hist->SetLineColor(6);
        preshower_beam_hist->GetXaxis()->SetTitle("preshowersum Edep (MeV)");
        preshower_beam_hist->GetYaxis()->SetTitle("Events");
        preshower_beam_hist->Rebin(rebinfac);
        preshower_beam_hist->GetYaxis()->SetRangeUser(1e0,1e6);
        preshower_beam_hist->Draw("HISt");
        double rate_proton_preshower= preshower_beam_hist->Integral()/1e6;
        preshower_e_hist->SetLineColor(2);
        preshower_e_hist->Rebin(rebinfac);
        preshower_e_hist->Draw("same HIST");
        double rate_e_preshower= preshower_e_hist->Integral()/1e6;
        preshower_electron_hist->SetLineColor(1);
        preshower_electron_hist->Rebin(rebinfac);
        preshower_electron_hist->Draw("same HIST");
        double rate_electron_preshower= preshower_electron_hist->Integral()/1e6;
        preshower_gamma_hist->SetLineColor(8);
        preshower_gamma_hist->Rebin(rebinfac);
        preshower_gamma_hist->Draw("same HIST");
        double rate_gamma_preshower= preshower_gamma_hist->Integral()/1e6;
  TLegend *leg28 = new TLegend(0.45,0.6,0.8,0.88);
  leg28->AddEntry(preshower_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_preshower),"l");
  leg28->AddEntry(preshower_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_preshower),"l");
  leg28->AddEntry(preshower_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_preshower),"l");
  leg28->AddEntry(preshower_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_preshower),"l");
  leg28->SetTextSize(0.03);
  leg28->SetBorderSize(0);
  leg28->SetFillColor(0);
  leg28->Draw("text same");
	c[5] = new TCanvas("c[5]","c[5]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        shower_beam_hist->SetLineColor(6);
        shower_beam_hist->GetXaxis()->SetTitle("shower Edep (MeV)");
        shower_beam_hist->GetYaxis()->SetTitle("Events");
        shower_beam_hist->Rebin(rebinfac);
        shower_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        shower_beam_hist->Draw("HISt");
        double rate_proton_shower= shower_beam_hist->Integral()/1e6;
        shower_e_hist->SetLineColor(2);
        shower_e_hist->Rebin(rebinfac);
        shower_e_hist->Draw("same HIST");
        double rate_e_shower= shower_e_hist->Integral()/1e6;
        shower_electron_hist->SetLineColor(1);
        shower_electron_hist->Rebin(rebinfac);
        shower_electron_hist->Draw("same HIST");
        double rate_electron_shower= shower_electron_hist->Integral()/1e6;
        shower_gamma_hist->SetLineColor(8);
        shower_gamma_hist->Rebin(rebinfac);
        shower_gamma_hist->Draw("same HIST");
        double rate_gamma_shower= shower_gamma_hist->Integral()/1e6;
  TLegend *leg29 = new TLegend(0.55,0.6,0.8,0.88);
  leg29->AddEntry(shower_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_shower),"l");
  leg29->AddEntry(shower_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_shower),"l");
  leg29->AddEntry(shower_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_shower),"l");
  leg29->AddEntry(shower_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_shower),"l");
  leg29->SetTextSize(0.03);
  leg29->SetBorderSize(0);
  leg29->SetFillColor(0);
  leg29->Draw("text same");
	c[6] = new TCanvas("c[6]","c[6]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        Etotal_beam_hist->SetLineColor(6);
        Etotal_beam_hist->GetXaxis()->SetTitle("Etotal Edep (MeV)");
        Etotal_beam_hist->GetYaxis()->SetTitle("Events");
        Etotal_beam_hist->Rebin(rebinfac);
        Etotal_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        Etotal_beam_hist->Draw("HISt");
        double rate_proton_Etotal= Etotal_beam_hist->Integral()/1e6;
        Etotal_e_hist->SetLineColor(2);
        Etotal_e_hist->Rebin(rebinfac);
        Etotal_e_hist->Draw("same HIST");
        double rate_e_Etotal= Etotal_e_hist->Integral()/1e6;
        Etotal_electron_hist->SetLineColor(1);
        Etotal_electron_hist->Rebin(rebinfac);
        Etotal_electron_hist->Draw("same HIST");
        double rate_electron_Etotal= Etotal_electron_hist->Integral()/1e6;
        Etotal_gamma_hist->SetLineColor(8);
        Etotal_gamma_hist->Rebin(rebinfac);
        Etotal_gamma_hist->Draw("same HIST");
        double rate_gamma_Etotal= Etotal_gamma_hist->Integral()/1e6;
        Etotal_gamma_tid1_hist->SetLineColor(4);
        Etotal_gamma_tid1_hist->Rebin(rebinfac);
     //   Etotal_gamma_tid1_hist->Draw("same HIST");
        double rate_gamma_tid1_Etotal= Etotal_gamma_tid1_hist->Integral()/1e6;
  TLegend *leg49 = new TLegend(0.5,0.6,0.8,0.88);
  leg49->AddEntry(Etotal_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_Etotal),"l");
  leg49->AddEntry(Etotal_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_Etotal),"l");
  leg49->AddEntry(Etotal_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_Etotal),"l");
  //leg49->AddEntry(Etotal_gamma_tid1_hist,Form("#gamma from target from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_tid1_Etotal),"l");
  leg49->AddEntry(Etotal_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_Etotal),"l");
  leg49->SetTextSize(0.03);
  leg49->SetBorderSize(0);
  leg49->SetFillColor(0);
  leg49->Draw("text same");
	c[7] = new TCanvas("c[7]","c[7]",1000,1000);
        c[7]->Divide(1,2);
        c[7]->cd(1);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        Etotal_vs_p_electron_hist->GetXaxis()->SetTitle("p (MeV/c)");
        Etotal_vs_p_electron_hist->SetTitle("e^{-} on the virtual plane of prelead");
        Etotal_vs_p_electron_hist->GetYaxis()->SetTitle("#frac{Etotal}{p} (MeV)");
        Etotal_vs_p_electron_hist->Draw("COLZ");
        c[7]->cd(2);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        Etotal_vs_p_gamma_hist->GetXaxis()->SetTitle("p (MeV/c)");
        Etotal_vs_p_gamma_hist->SetTitle("#gamma on the virtual plane of prelead");
        Etotal_vs_p_gamma_hist->GetYaxis()->SetTitle("#frac{Etotal}{p} (MeV)");
        Etotal_vs_p_gamma_hist->Draw("COLZ");
	c[8] = new TCanvas("c[8]","c[8]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        SC3_beam_hist->SetLineColor(6);
        SC3_beam_hist->GetXaxis()->SetTitle("SC3 Edep (MeV)");
        SC3_beam_hist->GetYaxis()->SetTitle("Events");
        SC3_beam_hist->Rebin(rebinfac);
        SC3_beam_hist->GetYaxis()->SetRangeUser(1e0,1e4);
        SC3_beam_hist->Draw("HISt");
        double rate_proton_SC3= SC3_beam_hist->Integral()/1e6;
        SC3_e_hist->SetLineColor(2);
        SC3_e_hist->Rebin(rebinfac);
        SC3_e_hist->Draw("same HIST");
        double rate_e_SC3= SC3_e_hist->Integral()/1e6;
        SC3_electron_hist->SetLineColor(1);
        SC3_electron_hist->Rebin(rebinfac);
        SC3_electron_hist->Draw("same HIST");
        double rate_electron_SC3= SC3_electron_hist->Integral()/1e6;
        SC3_gamma_hist->SetLineColor(8);
        SC3_gamma_hist->Rebin(rebinfac);
        SC3_gamma_hist->Draw("same HIST");
        double rate_gamma_SC3= SC3_gamma_hist->Integral()/1e6;
  TLegend *leg19 = new TLegend(0.45,0.6,0.8,0.88);
  leg19->AddEntry(SC3_electron_hist,Form("e^{-} from 200 MeV #gamma; #frac{e^{-}}{1e6}=%f ",rate_electron_SC3),"l");
  leg19->AddEntry(SC3_e_hist,Form("e^{#pm} from 200 MeV #gamma; #frac{e^{#pm}}{1e6}=%f ",rate_e_SC3),"l");
  leg19->AddEntry(SC3_gamma_hist,Form("#gamma from 200 MeV #gamma; #frac{#gamma}{1e6}=%f ",rate_gamma_SC3),"l");
  leg19->AddEntry(SC3_beam_hist,Form("from 200 MeV #gamma; #frac{all}{1e6}=%f ",rate_proton_SC3),"l");
  leg19->SetTextSize(0.03);
  leg19->SetBorderSize(0);
  leg19->SetFillColor(0);
  leg19->Draw("text same");
	c[9] = new TCanvas("c[9]","c[9]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogz();
        ShowerSum_vs_SC3_hist->GetXaxis()->SetTitle("SC3 Edep (MeV)");
        ShowerSum_vs_SC3_hist->GetYaxis()->SetTitle("ShowerSum Edep (MeV)");
        ShowerSum_vs_SC3_hist->Draw("COLZ");
/*	c[1] = new TCanvas("c[1]","c[1]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        Npesum_beam_hist->SetLineColor(6);
        Npesum_beam_hist->GetXaxis()->SetTitle("Npe");
        Npesum_beam_hist->GetYaxis()->SetTitle("Rate (kHz)");
        Npesum_beam_hist->Scale(0.001);
        Npesum_beam_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        Npesum_beam_hist->Draw("HIST");
        Npesum_pip_hist->SetLineColor(2);
        Npesum_pip_hist->Scale(0.001);
        Npesum_pip_hist->Draw("same HIST");
        Npesum_pim_hist->SetLineColor(1);
        Npesum_pim_hist->Scale(0.001);
        Npesum_pim_hist->Draw("same HIST");
        Npesum_pi0_hist->SetLineColor(8);
        Npesum_pi0_hist->Scale(0.001);
        Npesum_pi0_hist->Draw("same HIST");
        Npesum_eAll_hist->SetLineColor(4);
        Npesum_eAll_hist->Scale(0.001);
        Npesum_eAll_hist->Draw("same HIST");
  TLegend *leg7 = new TLegend(0.45,0.6,0.8,0.88);
  leg7->AddEntry(Npesum_eAll_hist,Form("from eAll"),"l");
  leg7->AddEntry(Npesum_pim_hist,Form("from bggen #pi^{-}"),"l");
  leg7->AddEntry(Npesum_pip_hist,Form("from bggen #pi^{+}"),"l");
  leg7->AddEntry(Npesum_pi0_hist,Form("from bggen #pi^{0}"),"l");
  leg7->AddEntry(Npesum_beam_hist,Form("from BeamOnTarget"),"l");
  leg7->SetTextSize(0.03);
  leg7->SetBorderSize(0);
  leg7->SetFillColor(0);
  leg7->Draw("text same");
	c[2] = new TCanvas("c[2]","c[2]",1000,1000);
	gPad->SetGridx();
	gPad->SetGridy();
	gPad->SetLogy();
        GEM00_beam_hist->SetLineColor(6);
        GEM00_beam_hist->GetXaxis()->SetTitle("Npe");
        GEM00_beam_hist->GetYaxis()->SetTitle("Rate (kHz)");
        GEM00_beam_hist->Scale(0.001);
        GEM00_beam_hist->GetYaxis()->SetRangeUser(1e-2,1e9);
        GEM00_beam_hist->Draw("HIST");
        double rate_proton_gem= GEM00_beam_hist->Integral();
        GEM00_pip_hist->SetLineColor(2);
        GEM00_pip_hist->Scale(0.001);
        GEM00_pip_hist->Draw("same HIST");
        double rate_pip_gem= GEM00_pip_hist->Integral();
        GEM00_pim_hist->SetLineColor(1);
        GEM00_pim_hist->Scale(0.001);
        GEM00_pim_hist->Draw("same HIST");
        double rate_pim_gem= GEM00_pim_hist->Integral();
        GEM00_pi0_hist->SetLineColor(8);
        GEM00_pi0_hist->Scale(0.001);
        GEM00_pi0_hist->Draw("same HIST");
        double rate_pi0_gem= GEM00_pi0_hist->Integral();
        GEM00_eAll_hist->SetLineColor(4);
        GEM00_eAll_hist->Scale(0.001);
        GEM00_eAll_hist->Draw("same HIST");
        double rate_eAll_gem= GEM00_eAll_hist->Integral();
  TLegend *leg9 = new TLegend(0.45,0.6,0.8,0.88);
  leg9->AddEntry(GEM00_eAll_hist,Form("eAll; total rate=%f kHz",rate_eAll_gem),"l");
  leg9->AddEntry(GEM00_pim_hist,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_gem),"l");
  leg9->AddEntry(GEM00_pip_hist,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_gem),"l");
  leg9->AddEntry(GEM00_pi0_hist,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_gem),"l");
  leg9->AddEntry(GEM00_beam_hist,Form("BeamOnTarget; total rate=%f kHz",rate_proton_gem),"l");
  leg9->SetTextSize(0.03);
  leg9->SetBorderSize(0);
  leg9->SetFillColor(0);
  leg9->Draw("text same");*/
	for(int a=0;a<10;a++){
		c[a]->SaveAs(Form("c%d.pdf",a));
	}
	gSystem->Exec("pdfunite ./c*.pdf ./HallC_comparison_threshod_rate.pdf");
	gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
