
#include <iostream> 
#include <fstream>
#include <cmath> 
#include <math.h> 
#include <TCanvas.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TLorentzVector.h>
#include <TROOT.h>
#include <TStyle.h>
#include <TMinuit.h>
#include <TPaveText.h>
#include <TText.h>
#include <TSystem.h>
#include <TArc.h>
#include <TLegend.h>

using namespace std;

void plot_EC_nobeamline_80uA(){
gStyle->SetOptStat(0);
gStyle->SetPalette(1);
  TFile *f1 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim/output/HallC_beamtest_bggen_LH2_pim_filenum11250_output.root");
  TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip2/HallC_beamtest_bggen_LH2_pip_filenum15700_1.5e8_output.root");
  //TFile *f31 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll/HallC_bggen_LH2_beamtest_full_eAll_filenum100_1e8_output.root");
  //TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_LD2/HallC_bggen_LD2_beamtest_full_eAll_filenum100_1e8_output.root");
  //TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_eAll/output/HallC_bggen_LH2_beamtest_full_eAll_filenum100_1e8_test_output.root");
  TFile *f13 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_80uA/HallC_beamtest_eAll_80uA_filenum99_nobeamline_output_Nphe_finetime_Q2cut_001GeV.root");
  TFile *f3 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_eAll/output/HallC_bggen_LH2_beamtest_full_eAll_filenum100_1e8_nobeamline_output.root");
  TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eDIS_LH2/HallC_bggen_LH2_beamtest_full_eDIS_filenum100_1e8_output.root");
/*  TFile *f1 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LD2_pim/HallC_bggen_LD2_beamtest_full_pim_filenum8200_8.2e7_output.root");
  TFile *f2 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LD2_pip/HallC_beamtest_bggen_LD2_pip_filenum15900_1.5e8_output.root");
  TFile *f3 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eAll_LD2/HallC_bggen_LD2_beamtest_full_eAll_filenum100_1e9_output.root");
  TFile *f4 = new TFile("/volatile/halla/solid/tianye/container/HallC_beamtest_eDIS/HallC_bggen_LD2_beamtest_full_eDIS_filenum100_1e8_output.root");*/
TFile *f5 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_proton/HallC_beamtest_even_LD2_proton_filenum100_output.root");
TFile *f6 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_pim/HallC_beamtest_even_pim_filenum62_output.root");
//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LD2_proton/HallC_beamtest_bggen_LD2_proton_filenum31820_output_break.root");
//TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_proton/output/HallC_beamtest_bggen_LH2_proton_filenum28960_output.root");
TFile *f7 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_beamOntarget_80uA_TGonly/HallC_beamtest_BeamOnTarget_3.974e11_nobeamline_output_Nphe.root");
//TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim/output/HallC_beamtest_bggen_LH2_pim_filenum11250_output.root");
TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim_80uA/HallC_beamtest_bggen_LH2_pim_80uA_filenum19880_nobeamline_output_Nphe.root");
//TFile *f8 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_sangle/HallC_beamtest_bggen_LH2_pip_sangle_filenum9530_output_22deg.root");
//TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip/output/HallC_beamtest_bggen_LH2_pip_filenum16330_output.root");
TFile *f9 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip_80uA/HallC_beamtest_bggen_LH2_pip_80uA_nobeamline_filenum19720_output_Nphe.root");
TFile *f17 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_proton/output/HallC_beamtest_bggen_LH2_proton_filenum28960_nobeamline_output.root");
TFile *f18 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim/output/HallC_beamtest_bggen_LH2_pim_filenum11250_nobeamline_output.root");
TFile *f19 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip/output/HallC_beamtest_bggen_LH2_pip_filenum16330_nobeamline_output.root");
TFile *f27 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_proton/output/HallC_beamtest_bggen_LH2_proton_filenum1750_nobeamline_mother_output.root");
TFile *f28 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pim/output/HallC_beamtest_bggen_LH2_pim_filenum2270_nobeamline_mother_output.root");
TFile *f29 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pip/output/HallC_beamtest_bggen_LH2_pip_filenum2030_nobeamline_mother_output.root");
//TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0/output/HallC_beamtest_bggen_LH2_pi0_filenum15720_output.root");
TFile *f10 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_pi0_80uA/HallC_beamtest_bggen_LH2_pi0_80uA_filenum19590_nobeamline_output_Nphe.root");
TFile *f20 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_nobeamline_pi0_analysis/output/HallC_beamtest_bggen_LH2_nobeamline_pi0_filenum15660_output_positron_all.root");
TFile *f30 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_nobeamline_pi0_analysis/output/HallC_beamtest_bggen_LH2_nobeamline_pi0_filenum15660_output_positron_motherID_test.root");
TFile *f31 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_nobeamline_pi0_analysis/output/HallC_beamtest_bggen_LH2_nobeamline_pi0_filenum15660_output_positron_all_test.root");
TFile *f32 = new TFile("/lustre19/expphy/volatile/halla/solid/tianye/container/HallC_beamtest_bggen_LH2_nobeamline_pi0_analysis/output/HallC_beamtest_bggen_LH2_nobeamline_pi0_filenum15660_output_positron_all_test.root");
const int rebinfac=1;
TH1F *EC_shower_pim;
TH1F *EC_shower_pip;
TH1F *EC_shower_pi0;
TH1F *EC_shower_eAll;
TH1F *EC_shower_eDIS;
TH1F *EC_shower_proton;
TH1F *EC_shower_pim_trigger;
TH1F *EC_shower_pip_trigger;
TH1F *EC_shower_pi0_trigger;
TH1F *EC_shower_proton_trigger;
TH1F *EC_shower_eAll_trigger;
TH1F *EC_preshower_pim;
TH1F *EC_preshower_proton;
TH1F *EC_preshower_pip;
TH1F *EC_preshower_pi0;
TH1F *EC_preshower_pi0_all;
TH1F *EC_shower_pi0_all;
TH1F *EC_preshower_pi0_e;
TH1F *EC_preshower_pi0_ep;
TH1F *EC_preshower_pi0_r;
TH1F *EC_shower_pi0_e;
TH1F *EC_shower_pi0_ep;
TH1F *EC_shower_pi0_r;
TH1F *EC_preshower_eAll;
TH1F *EC_preshower_eDIS;
TH1F *EC_preshower_pim_trigger;
TH1F *EC_preshower_proton_trigger;
TH1F *EC_preshower_pip_trigger;
TH1F *EC_preshower_pi0_trigger;
TH1F *EC_preshower_eAll_trigger;
TH1F *EC_preshower_mother_pi0;
TH1F *EC_preshower_mother_pi0_e;
TH1F *EC_preshower_mother_pi0_ep;
TH1F *EC_preshower_mother_pi0_r;
TH1F *EC_shower_mother_pi0_e;
TH1F *EC_shower_mother_pi0_ep;
TH1F *EC_shower_mother_pi0_r;
TH1F *sc1_pim;
TH1F *sc2_pim;
TH1F *sc1_pip;
TH1F *sc1_proton;
TH1F *sc2_proton;
TH1F *sc1_pi0;
TH1F *sc2_pi0;
TH1F *sc2_pip;
TH1F *sc1_eAll;
TH1F *sc2_eAll;
TH1F *hhit_E_pim[7];
TH1F *hhit_p_pim[7];
TH1F *hhit_Edep_pim[7];		  	
TH1F *hhit_E_pip[7];
TH1F *hhit_Edep_pip[7];		  	
TH1F *hhit_E_eAll_nob[9];
TH1F *hhit_p_eAll_nob[9];
TH1F *hhit_E_eAll[9];
TH1F *hhit_p_eAll[9];
TH1F *hhit_Edep_eAll[9];		  	
TH1F *hhit_E_cut_eAll[9];
TH1F *hhit_p_cut_eAll[9];
TH1F *hhit_E_cut_eAll_nob[9];
TH1F *hhit_p_cut_eAll_nob[9];
TH1F *hhit_E_proton[9];
TH1F *hhit_p_proton[9];
TH1F *hhit_E_proton_nob[9];
TH1F *hhit_p_proton_nob[9];
TH1F *hhit_E_proton_cut[9];
TH1F *hhit_p_proton_cut[9];
TH1F *hhit_E_proton_cut_nob[9];
TH1F *hhit_p_proton_cut_nob[9];
TH1F *hhit_Edep_proton[9];		  	
TH1F *hhit_E_pim_LD[9];
TH1F *hhit_p_pim_LD[9];
TH1F *hhit_E_pim_LD_nob[9];
TH1F *hhit_p_pim_LD_nob[9];
TH1F *hhit_Edep_pim_LD[9];		  	
TH1F *hhit_Edep_pip_LD[9];		  	
TH1F *hhit_Edep_pi0_LD[9];		  	
TH1F *hhit_E_pim_cut_LD[9];
TH1F *hhit_p_pim_cut_LD[9];
TH1F *hhit_E_pim_cut_LD_nob[9];
TH1F *hhit_p_pim_cut_LD_nob[9];
TH1F *hhit_E_pip_cut_LD[9];
TH1F *hhit_p_pip_cut_LD[9];
TH1F *hhit_E_pip_cut_LD_nob[9];
TH1F *hhit_p_pip_cut_LD_nob[9];
TH1F *hhit_E_pip_LD[9];
TH1F *hhit_p_pip_LD[9];
TH1F *hhit_E_pip_LD_nob[9];
TH1F *hhit_p_pip_LD_nob[9];
TH1F *hhit_E_pi0[9];
TH1F *hhit_p_pi0[9];
TH1F *hhit_E_pi0_nob[9];
TH1F *hhit_p_pi0_nob[9];
TH1F *hhit_E_pi0_cut[9];
TH1F *hhit_p_pi0_cut[9];
TH1F *hhit_E_pi0_cut_nob[9];
TH1F *hhit_p_pi0_cut_nob[9];
TH1F *hhit_E_pi0_cutr[9];
TH1F *hhit_p_pi0_cutr[9];
TH1F *hhit_E_pi0_cutr_nob[9];
TH1F *hhit_p_pi0_cutr_nob[9];
TH1F *hhit_E_pi0_cute[9];
TH1F *hhit_p_pi0_cute[9];
TH1F *hhit_E_pi0_cute_nob[9];
TH1F *hhit_p_pi0_cute_nob[9];

TH1F *hhit_pid_pip_LD_nob[9];
TH1F *hhit_pid_pim_LD_nob[9];
TH1F *hhit_pid_proton_LD_nob[9];
TH1F *hhit_mpid_pip_LD_nob[9];
TH1F *hhit_mpid_pim_LD_nob[9];
TH1F *hhit_mpid_proton_LD_nob[9];
TH1F *hhit_procID_pip_LD_nob[9];
TH1F *hhit_procID_pim_LD_nob[9];
TH1F *hhit_procID_proton_LD_nob[9];

TH1F *hhit_Edepspd2_proton;
TH1F *hhit_Edepspd2_pim;
TH1F *hhit_Edepspd2_pi0;
TH1F *hhit_Edepspd2_pip;
TH1F *hhit_Edepspd2_eAll;
TH1F *hhit_Edepspd1_proton;
TH1F *hhit_Edepspd1_pim;
TH1F *hhit_Edepspd1_pi0;
TH1F *hhit_Edepspd1_pip;
TH1F *hhit_Edepspd1_eAll;
TH1F *hhit_Eend_preshower_r_proc;
TH1F *hhit_Eend_preshower_mother_r_proc;
TH1F *hhit_Eend_preshower_e_proc;
TH1F *hhit_Eend_preshower_mother_e_proc;
TH1F *hhit_Eend_preshower_ep_proc;
TH1F *hhit_Eend_preshower_mother_ep_proc;
TH2F *hit_R_vs_vz_eAll_nob[9];
TH2F *hit_R_vs_vz_eAll[9];
TH2F *hit_R_vs_vz_pim_nob[9];
TH2F *hit_R_vs_vz_pim[9];
TH2F *hit_R_vs_vz_pip_nob[9];
TH2F *hit_R_vs_vz_pip[9];
TH2F *hit_R_vs_vz_proton_nob[9];
TH2F *hit_R_vs_vz_proton[9];
TH2F *hit_R_vs_vz_pi0_nob[9];
TH2F *hit_R_vs_vz_pi0[9];
TH2F *EC_shower_2D_pim;
TH2F *EC_shower_2D_pip;
TH2F *EC_shower_2D_pi0;
TH2F *EC_shower_2D_eAll;
TH2F *EC_shower_2D_proton;
TH2F *EC_shower_2D_pim_trigger;
TH2F *EC_shower_2D_pip_trigger;
TH2F *EC_shower_2D_pi0_trigger;
TH2F *EC_shower_2D_eAll_trigger;
TH2F *EC_shower_2D_proton_trigger;
 /*EC_shower_2D_pim = (TH2F*)f18->Get("ec_Eend_2D");
 EC_shower_2D_pip = (TH2F*)f19->Get("ec_Eend_2D");
 EC_shower_2D_pi0 = (TH2F*)f32->Get("ec_Eend_2D");
 EC_shower_2D_eAll = (TH2F*)f13->Get("ec_Eend_2D");
 EC_shower_2D_proton = (TH2F*)f27->Get("ec_Eend_2D");

 EC_shower_2D_pim_trigger = (TH2F*)f1->Get("ec_Eend_2D_trigger");
 EC_shower_2D_pip_trigger = (TH2F*)f2->Get("ec_Eend_2D_trigger");
 EC_shower_2D_pi0_trigger = (TH2F*)f10->Get("ec_Eend_2D_trigger");
 EC_shower_2D_eAll_trigger = (TH2F*)f13->Get("ec_Eend_2D_trigger");
 EC_shower_2D_proton_trigger = (TH2F*)f7->Get("ec_Eend_2D_trigger");*/

 hhit_Edepspd2_proton = (TH1F*)f7->Get("hit_Edepspd2_trigger1");
 hhit_Edepspd2_pim = (TH1F*)f8->Get("hit_Edepspd2_trigger1");
 hhit_Edepspd2_pip = (TH1F*)f9->Get("hit_Edepspd2_trigger1");
 hhit_Edepspd2_pi0 = (TH1F*)f10->Get("hit_Edepspd2_trigger1");
 hhit_Edepspd2_eAll = (TH1F*)f13->Get("hit_Edepspd2_trigger1");
 hhit_Edepspd1_proton = (TH1F*)f7->Get("hit_Edepspd1_trigger1");
 hhit_Edepspd1_pim = (TH1F*)f8->Get("hit_Edepspd1_trigger1");
 hhit_Edepspd1_pip = (TH1F*)f9->Get("hit_Edepspd1_trigger1");
 hhit_Edepspd1_pi0 = (TH1F*)f10->Get("hit_Edepspd1_trigger1");
 hhit_Edepspd1_eAll = (TH1F*)f13->Get("hit_Edepspd1_trigger1");
 EC_shower_pim = (TH1F*)f8->Get("ec_Eend_shower_trigger2");
 EC_shower_pip = (TH1F*)f9->Get("ec_Eend_shower_trigger2");
 EC_shower_pi0 = (TH1F*)f10->Get("ec_Eend_shower_trigger2");
 EC_shower_eAll = (TH1F*)f13->Get("ec_Eend_shower_trigger2");
 EC_shower_eDIS = (TH1F*)f4->Get("ec_Eend_shower_trigger2");
 EC_shower_proton = (TH1F*)f7->Get("ec_Eend_shower_trigger2");
 EC_preshower_pim = (TH1F*)f8->Get("ec_Eend_preshower_trigger2");
 EC_preshower_proton = (TH1F*)f7->Get("ec_Eend_preshower_trigger2");
 EC_preshower_pip = (TH1F*)f9->Get("ec_Eend_preshower_trigger2");
 EC_preshower_pi0 = (TH1F*)f10->Get("ec_Eend_preshower_trigger2");
 EC_preshower_eAll = (TH1F*)f13->Get("ec_Eend_preshower_trigger2");
 EC_preshower_eDIS = (TH1F*)f4->Get("ec_Eend_preshower_trigger2");
 EC_shower_pim_trigger = (TH1F*)f8->Get("ec_Eend_shower_trigger2");
 EC_shower_pi0_trigger = (TH1F*)f10->Get("ec_Eend_shower_trigger2");
 EC_shower_proton_trigger = (TH1F*)f7->Get("ec_Eend_shower_trigger2");
 EC_shower_pip_trigger = (TH1F*)f9->Get("ec_Eend_shower_trigger2");
 EC_shower_eAll_trigger = (TH1F*)f13->Get("ec_Eend_shower_trigger2");
 EC_preshower_pim_trigger = (TH1F*)f8->Get("ec_Eend_preshower_trigger2");
 EC_preshower_pi0_trigger = (TH1F*)f10->Get("ec_Eend_preshower_trigger2");
 EC_preshower_proton_trigger = (TH1F*)f7->Get("ec_Eend_preshower_trigger2");
 EC_preshower_pip_trigger = (TH1F*)f9->Get("ec_Eend_preshower_trigger2");
 EC_preshower_eAll_trigger = (TH1F*)f13->Get("ec_Eend_preshower_trigger2");
/* EC_preshower_pi0_e = (TH1F*)f32->Get("ec_Eend_preshower_e");
 EC_preshower_pi0_ep = (TH1F*)f32->Get("ec_Eend_preshower_ep");
 EC_preshower_pi0_r = (TH1F*)f32->Get("ec_Eend_preshower_r");
 EC_preshower_pi0_all = (TH1F*)f32->Get("ec_Eend_preshower");
 EC_shower_pi0_all = (TH1F*)f32->Get("ec_Eend_shower");
 EC_preshower_mother_pi0_e = (TH1F*)f32->Get("ec_Eend_preshower_mother_e");
 EC_preshower_mother_pi0_ep = (TH1F*)f32->Get("ec_Eend_preshower_mother_ep");
 EC_preshower_mother_pi0_r = (TH1F*)f32->Get("ec_Eend_preshower_mother_r");
 EC_shower_pi0_e = (TH1F*)f32->Get("ec_Eend_shower_e");
 EC_shower_pi0_ep = (TH1F*)f32->Get("ec_Eend_shower_ep");
 EC_shower_pi0_r = (TH1F*)f32->Get("ec_Eend_shower_r");
 EC_shower_mother_pi0_e = (TH1F*)f32->Get("ec_Eend_shower_mother_e");
 EC_shower_mother_pi0_ep = (TH1F*)f32->Get("ec_Eend_shower_mother_ep");
 EC_shower_mother_pi0_r = (TH1F*)f32->Get("ec_Eend_shower_mother_r");
 hhit_Eend_preshower_r_proc = (TH1F*)f32->Get("ec_Eend_preshower_r_proc");
 hhit_Eend_preshower_mother_r_proc = (TH1F*)f32->Get("ec_Eend_preshower_mother_r_proc");
 hhit_Eend_preshower_e_proc = (TH1F*)f32->Get("ec_Eend_preshower_e_proc");
 hhit_Eend_preshower_mother_e_proc = (TH1F*)f32->Get("ec_Eend_preshower_mother_e_proc");
 hhit_Eend_preshower_ep_proc = (TH1F*)f32->Get("ec_Eend_preshower_ep_proc");
 hhit_Eend_preshower_mother_ep_proc = (TH1F*)f32->Get("ec_Eend_preshower_mother_ep_proc");*/
 sc1_pim = (TH1F*)f8->Get("hit_Edepsc1_trigger1");
 sc2_pim = (TH1F*)f8->Get("hit_Edepsc2_trigger1");
 sc1_pip = (TH1F*)f9->Get("hit_Edepsc1_trigger1");
 sc2_pip = (TH1F*)f9->Get("hit_Edepsc2_trigger1");
 sc1_eAll = (TH1F*)f13->Get("hit_Edepsc1_trigger1");
 sc2_eAll = (TH1F*)f13->Get("hit_Edepsc2_trigger1");
 sc1_proton = (TH1F*)f7->Get("hit_Edepsc1_trigger1");
 sc2_proton = (TH1F*)f7->Get("hit_Edepsc2_trigger1");
 sc1_pi0 = (TH1F*)f10->Get("hit_Edepsc1_trigger1");
 sc2_pi0 = (TH1F*)f10->Get("hit_Edepsc2_trigger1");
/* for(int k=0;k<7;k++){
 hhit_E_pim[k] = (TH1F*)f1->Get(Form("hit_E_%d",k));
 hhit_p_pim[k] = (TH1F*)f1->Get(Form("hit_momentum_%d",k));
 hhit_Edep_pim[k] = (TH1F*)f1->Get(Form("hit_Edep_%d",k));
 hhit_E_pip[k] = (TH1F*)f2->Get(Form("hit_E_%d",k));
 hhit_Edep_pip[k] = (TH1F*)f2->Get(Form("hit_Edep_%d",k));
 }
 for(int k=0;k<9;k++){
 hhit_E_cut_eAll[k] = (TH1F*)f13->Get(Form("hit_E_cut_%d",k));
 hhit_p_cut_eAll[k] = (TH1F*)f13->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_eAll[k] = (TH1F*)f13->Get(Form("hit_E_%d",k));
 hhit_p_eAll[k] = (TH1F*)f13->Get(Form("hit_momentum_%d",k));
 hhit_E_cut_eAll_nob[k] = (TH1F*)f3->Get(Form("hit_E_cut_%d",k));
 hhit_p_cut_eAll_nob[k] = (TH1F*)f3->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_eAll_nob[k] = (TH1F*)f3->Get(Form("hit_E_%d",k));
 hhit_p_eAll_nob[k] = (TH1F*)f3->Get(Form("hit_momentum_%d",k));
 hit_R_vs_vz_eAll_nob[k]= (TH2F*)f3->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_eAll[k]= (TH2F*)f13->Get(Form("hit_R_vs_vz_%d",k));
 hhit_Edep_eAll[k] = (TH1F*)f13->Get(Form("hit_Edep_%d",k));
 hhit_E_proton[k] = (TH1F*)f7->Get(Form("hit_E_%d",k));
 hhit_p_proton[k] = (TH1F*)f7->Get(Form("hit_momentum_%d",k));
 hhit_E_proton_nob[k] = (TH1F*)f17->Get(Form("hit_E_%d",k));
 hhit_p_proton_nob[k] = (TH1F*)f17->Get(Form("hit_momentum_%d",k));
 hhit_E_pi0[k] = (TH1F*)f10->Get(Form("hit_E_%d",k));
 hhit_p_pi0[k] = (TH1F*)f10->Get(Form("hit_momentum_%d",k));
 hhit_E_pi0_nob[k] = (TH1F*)f20->Get(Form("hit_E_%d",k));
 hhit_p_pi0_nob[k] = (TH1F*)f20->Get(Form("hit_momentum_%d",k));
 hit_R_vs_vz_proton_nob[k]= (TH2F*)f17->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_proton[k]= (TH2F*)f7->Get(Form("hit_R_vs_vz_%d",k));
 hhit_Edep_proton[k] = (TH1F*)f7->Get(Form("hit_Edep_%d",k));
 hhit_E_pim_LD[k] = (TH1F*)f8->Get(Form("hit_E_%d",k));
 hhit_p_pim_LD[k] = (TH1F*)f8->Get(Form("hit_momentum_%d",k));
 hhit_E_pim_LD_nob[k] = (TH1F*)f18->Get(Form("hit_E_%d",k));
 hhit_p_pim_LD_nob[k] = (TH1F*)f18->Get(Form("hit_momentum_%d",k));
 hhit_Edep_pim_LD[k] = (TH1F*)f8->Get(Form("hit_Edep_%d",k));
 hhit_E_pim_cut_LD[k] = (TH1F*)f8->Get(Form("hit_E_cut_%d",k));
 hhit_p_pim_cut_LD[k] = (TH1F*)f8->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pim_cut_LD_nob[k] = (TH1F*)f18->Get(Form("hit_E_cut_%d",k));
 hhit_p_pim_cut_LD_nob[k] = (TH1F*)f18->Get(Form("hit_momentum_cut_%d",k));
 hit_R_vs_vz_pim_nob[k]= (TH2F*)f18->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_pim[k]= (TH2F*)f8->Get(Form("hit_R_vs_vz_%d",k));
 hhit_E_pip_LD[k] = (TH1F*)f9->Get(Form("hit_E_%d",k));
 hhit_p_pip_LD[k] = (TH1F*)f9->Get(Form("hit_momentum_%d",k));
 hhit_E_pip_LD_nob[k] = (TH1F*)f19->Get(Form("hit_E_%d",k));
 hhit_p_pip_LD_nob[k] = (TH1F*)f19->Get(Form("hit_momentum_%d",k));
 hhit_Edep_pip_LD[k] = (TH1F*)f9->Get(Form("hit_Edep_%d",k));
 hhit_E_pip_cut_LD[k] = (TH1F*)f9->Get(Form("hit_E_cut_%d",k));
 hhit_p_pip_cut_LD[k] = (TH1F*)f9->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pip_cut_LD_nob[k] = (TH1F*)f19->Get(Form("hit_E_cut_%d",k));
 hhit_p_pip_cut_LD_nob[k] = (TH1F*)f19->Get(Form("hit_momentum_cut_%d",k));
 hit_R_vs_vz_pip_nob[k]= (TH2F*)f19->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_pip[k]= (TH2F*)f9->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_pi0_nob[k]= (TH2F*)f20->Get(Form("hit_R_vs_vz_%d",k));
 hit_R_vs_vz_pi0[k]= (TH2F*)f10->Get(Form("hit_R_vs_vz_%d",k));
 hhit_E_proton_cut[k] = (TH1F*)f7->Get(Form("hit_E_cut_%d",k));
 hhit_p_proton_cut[k] = (TH1F*)f7->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_proton_cut_nob[k] = (TH1F*)f17->Get(Form("hit_E_cut_%d",k));
 hhit_p_proton_cut_nob[k] = (TH1F*)f17->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pi0_cut[k] = (TH1F*)f10->Get(Form("hit_E_cut_%d",k));
 hhit_p_pi0_cut[k] = (TH1F*)f10->Get(Form("hit_momentum_cut_%d",k));
 hhit_E_pi0_cut_nob[k] = (TH1F*)f20->Get(Form("hit_E_cut_%d",k));
 hhit_p_pi0_cut_nob[k] = (TH1F*)f20->Get(Form("hit_momentum_cut_%d",k));
 hhit_pid_pip_LD_nob[k] = (TH1F*)f29->Get(Form("hit_pid_%d",k));
 hhit_pid_pim_LD_nob[k] = (TH1F*)f28->Get(Form("hit_pid_%d",k));
 hhit_pid_proton_LD_nob[k] = (TH1F*)f27->Get(Form("hit_pid_%d",k));
 hhit_mpid_pip_LD_nob[k] = (TH1F*)f29->Get(Form("hit_mpid_%d",k));
 hhit_mpid_pim_LD_nob[k] = (TH1F*)f28->Get(Form("hit_mpid_%d",k));
 hhit_mpid_proton_LD_nob[k] = (TH1F*)f27->Get(Form("hit_mpid_%d",k));
 hhit_procID_pip_LD_nob[k] = (TH1F*)f29->Get(Form("hit_procID_%d",k));
 hhit_procID_pim_LD_nob[k] = (TH1F*)f28->Get(Form("hit_procID_%d",k));
 hhit_procID_proton_LD_nob[k] = (TH1F*)f27->Get(Form("hit_procID_%d",k));
 hhit_E_pi0_cute[k] = (TH1F*)f10->Get(Form("hit_E_cute_%d",k));
 hhit_p_pi0_cute[k] = (TH1F*)f10->Get(Form("hit_momentum_cute_%d",k));
 hhit_E_pi0_cute_nob[k] = (TH1F*)f20->Get(Form("hit_E_cute_%d",k));
 hhit_p_pi0_cute_nob[k] = (TH1F*)f20->Get(Form("hit_momentum_cute_%d",k));
 hhit_E_pi0_cutr[k] = (TH1F*)f10->Get(Form("hit_E_cutr_%d",k));
 hhit_p_pi0_cutr[k] = (TH1F*)f10->Get(Form("hit_momentum_cutr_%d",k));
 hhit_E_pi0_cutr_nob[k] = (TH1F*)f20->Get(Form("hit_E_cutr_%d",k));
 hhit_p_pi0_cutr_nob[k] = (TH1F*)f20->Get(Form("hit_momentum_cutr_%d",k));
 }*/
 const int binmin=28.6;
 const int binmin2=28.6;
TLine *lmin5 = new TLine(binmin,0,binmin,1e3); 
lmin5->SetLineWidth(2); 
lmin5->SetLineColor(1); 
lmin5->SetLineStyle(7); 
TLine *lmin4 = new TLine(binmin2,0,binmin2,1e6); 
lmin4->SetLineWidth(2); 
lmin4->SetLineColor(1); 
lmin4->SetLineStyle(7); 
 TCanvas *c[17];
 c[0] = new TCanvas("c[0]","c[0]",1000,1000);
gPad->SetGridx();
gPad->SetGridy();
gPad->SetLogy();
 EC_shower_proton->Scale(0.001);
 EC_shower_proton->GetYaxis()->SetTitle("rate (kHz)");
 EC_shower_proton->GetYaxis()->SetRangeUser(1e-3,1e3);
 EC_shower_proton->SetTitle("shower Edep");
 EC_shower_proton->SetLineColor(6);
 EC_shower_proton->Rebin(rebinfac);
 EC_shower_proton->Draw(" HIST");
double rate_proton= EC_shower_proton->Integral(EC_shower_proton->GetXaxis()->FindBin(binmin),EC_shower_proton->GetXaxis()->FindBin(200));
 EC_shower_pip->Scale(0.001);
 EC_shower_pip->Rebin(rebinfac);
// EC_shower_pip->GetYaxis()->SetRangeUser(1e-3,1e9);
 //EC_shower_pip->GetXaxis()->SetRangeUser(0,100);
 EC_shower_pip->GetYaxis()->SetTitle("rate (kHz)");
 EC_shower_pip->SetLineColor(2);
 EC_shower_pip->SetTitle("shower Edep");
 EC_shower_pip->Draw("same HIST");
double rate_pip= EC_shower_pip->Integral(EC_shower_pip->GetXaxis()->FindBin(binmin),EC_shower_pip->GetXaxis()->FindBin(200));
 EC_shower_pim->Scale(0.001);
 EC_shower_pim->Rebin(rebinfac);
 EC_shower_pim->SetLineColor(1);
 EC_shower_pim->Draw(" same HIST");
double rate_pim= EC_shower_pim->Integral(EC_shower_pim->GetXaxis()->FindBin(binmin),EC_shower_pim->GetXaxis()->FindBin(200));
 EC_shower_pi0->Scale(0.001);
 EC_shower_pi0->Rebin(rebinfac);
 EC_shower_pi0->SetLineColor(kGreen+3);
 EC_shower_pi0->Draw(" same HIST");
double rate_pi0= EC_shower_pi0->Integral(EC_shower_pi0->GetXaxis()->FindBin(binmin),EC_shower_pi0->GetXaxis()->FindBin(200));
 EC_shower_eAll->SetLineColor(4);
 EC_shower_eAll->Rebin(rebinfac);
 EC_shower_eAll->Draw(" same HIST");
double rate_eAll= EC_shower_eAll->Integral(EC_shower_eAll->GetXaxis()->FindBin(binmin),EC_shower_eAll->GetXaxis()->FindBin(200));
  TLegend *leg8 = new TLegend(0.45,0.6,0.8,0.88);
  leg8->AddEntry(EC_shower_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll),"l");
//  leg8->AddEntry(EC_shower_eDIS,"eDIS*1000","l");
  leg8->AddEntry(EC_shower_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim),"l");
  leg8->AddEntry(EC_shower_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip),"l");
  leg8->AddEntry(EC_shower_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0),"l");
  leg8->AddEntry(EC_shower_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton),"l");
  leg8->SetTextSize(0.03);
  leg8->SetBorderSize(0);
  leg8->SetFillColor(0);
  leg8->Draw("text same");
lmin5->Draw("same"); 
  cout<<"rate eAll="<<rate_eAll<<"  "<<"rate_pim="<<rate_pim<<"  "<<"rate_pip="<<rate_pip<<endl;
 c[1] = new TCanvas("c[1]","c[1]",1000,800);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 EC_preshower_proton->SetLineColor(6);
 EC_preshower_proton->Scale(0.001);
 EC_preshower_proton->Rebin(rebinfac);
 EC_preshower_proton->GetYaxis()->SetRangeUser(1e-3,1e3);
// EC_preshower_proton->GetXaxis()->SetRangeUser(0,50);
 EC_preshower_proton->GetYaxis()->SetTitle("rate (kHz)");
 EC_preshower_proton->SetTitle("preshower Edep");
 EC_preshower_proton->Draw("HIST");
double rate_proton_pre= EC_preshower_proton->Integral(EC_preshower_proton->GetXaxis()->FindBin(binmin),EC_preshower_proton->GetXaxis()->FindBin(200));
 EC_preshower_pim->Scale(0.001);
 EC_preshower_pim->SetLineColor(1);
 EC_preshower_pim->Rebin(rebinfac);
 EC_preshower_pim->Draw("same HIST");
double rate_pim_pre= EC_preshower_pim->Integral(EC_preshower_pim->GetXaxis()->FindBin(binmin),EC_preshower_pim->GetXaxis()->FindBin(200));
 EC_preshower_pi0->Scale(0.001);
 EC_preshower_pi0->SetLineColor(kGreen+3);
 EC_preshower_pi0->Rebin(rebinfac);
 EC_preshower_pi0->Draw("same HIST");
double rate_pi0_pre= EC_preshower_pi0->Integral(EC_preshower_pi0->GetXaxis()->FindBin(binmin),EC_preshower_pi0->GetXaxis()->FindBin(200));
 EC_preshower_eAll->SetLineColor(4);
// EC_preshower_eAll->Scale(1000);
 EC_preshower_eAll->Rebin(rebinfac);
 EC_preshower_eAll->Draw(" same HIST");
double rate_eAll_pre= EC_preshower_eAll->Integral(EC_preshower_eAll->GetXaxis()->FindBin(binmin),EC_preshower_eAll->GetXaxis()->FindBin(200));
 EC_preshower_pip->Scale(0.001);
 EC_preshower_pip->SetLineColor(2);
 EC_preshower_pip->Rebin(rebinfac);
 EC_preshower_pip->Draw(" same HIST");
double rate_pip_pre= EC_preshower_pip->Integral(EC_preshower_pip->GetXaxis()->FindBin(binmin),EC_preshower_pip->GetXaxis()->FindBin(200));
  TLegend *leg1 = new TLegend(0.45,0.6,0.8,0.88);
  leg1->AddEntry(EC_preshower_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_pre),"l");
  leg1->AddEntry(EC_preshower_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_pre),"l");
  leg1->AddEntry(EC_preshower_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_pre),"l");
  leg1->AddEntry(EC_preshower_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_pre),"l");
  leg1->AddEntry(EC_preshower_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton_pre),"l");
  leg1->SetTextSize(0.03);
  leg1->SetBorderSize(0);
  leg1->SetFillColor(0);
  leg1->Draw("text same");
lmin5->Draw("same"); 
 c[2] = new TCanvas("c[2]","c[2]",1000,1000);
 c[2]->Divide(1,2);
 c[2]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc1_proton->SetLineColor(6);
 sc1_proton->Scale(0.001);
 sc1_proton->GetYaxis()->SetTitle("rate (kHz)");
 sc1_proton->SetTitle("SC0 triggered");
 sc1_proton->GetXaxis()->SetTitle("Edep (MeV)");
 sc1_proton->GetXaxis()->SetRangeUser(0,100);
 sc1_proton->GetYaxis()->SetRangeUser(1e-2,1e3);
 sc1_proton->Rebin(rebinfac);
 sc1_proton->Draw("HIST");
 double rate_proton_sc1= sc1_proton->Integral(sc1_proton->GetXaxis()->FindBin(binmin2),sc1_proton->GetXaxis()->FindBin(100));
 sc1_pim->SetLineColor(1);
 sc1_pim->Scale(0.001);
 sc1_pim->Rebin(rebinfac);
 sc1_pim->Draw("same HIST");
 double rate_pim_sc1= sc1_pim->Integral(sc1_pim->GetXaxis()->FindBin(binmin2),sc1_pim->GetXaxis()->FindBin(100));
 sc1_eAll->SetLineColor(4);
 //sc1_eAll->Scale(1000);
 sc1_eAll->Rebin(rebinfac);
 sc1_eAll->Draw("same HIST");
 double rate_eAll_sc1= sc1_eAll->Integral();
 sc1_pip->SetLineColor(2);
 sc1_pip->Scale(0.001);
 sc1_pip->Rebin(rebinfac);
 sc1_pip->Draw("same HIST");
 double rate_pip_sc1= sc1_pip->Integral(sc1_pip->GetXaxis()->FindBin(binmin2),sc1_pip->GetXaxis()->FindBin(100));
 sc1_pi0->SetLineColor(kGreen+3);
 sc1_pi0->Scale(0.001);
 sc1_pi0->Rebin(rebinfac);
 sc1_pi0->Draw("same HIST");
lmin4->Draw("same"); 
 double rate_pi0_sc1= sc1_pi0->Integral(sc1_pi0->GetXaxis()->FindBin(binmin2),sc1_pi0->GetXaxis()->FindBin(100));
  TLegend *leg21 = new TLegend(0.45,0.4,0.8,0.68);
  leg21->AddEntry(sc1_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_sc1),"l");
  leg21->AddEntry(sc1_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_sc1),"l");
  leg21->AddEntry(sc1_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_sc1),"l");
  leg21->AddEntry(sc1_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_sc1),"l");
  leg21->AddEntry(sc1_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton_sc1),"l");
  leg21->SetTextSize(0.05);
  leg21->SetBorderSize(0);
  leg21->SetFillColor(0);
  leg21->Draw("text same");
 c[2]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
 sc2_proton->SetLineColor(6);
 sc2_proton->Scale(0.001);
 sc2_proton->SetTitle("SC1 triggered");
 sc2_proton->GetXaxis()->SetTitle("Edep (MeV)");
 sc2_proton->GetYaxis()->SetTitle("rate (kHz)");
 sc2_proton->GetYaxis()->SetRangeUser(1e-2,1e3);
 sc2_proton->GetXaxis()->SetRangeUser(0,100);
 sc2_proton->Rebin(rebinfac);
 sc2_proton->Draw("HIST");
 double rate_pip_sc2= sc2_proton->Integral(sc2_proton->GetXaxis()->FindBin(binmin2),sc2_proton->GetXaxis()->FindBin(100));
 sc2_pim->SetLineColor(1);
 sc2_pim->Scale(0.001);
 sc2_pim->Rebin(rebinfac);
 sc2_pim->Draw("same HIST");
 double rate_pim_sc2= sc2_pim->Integral(sc2_pim->GetXaxis()->FindBin(binmin2),sc2_pim->GetXaxis()->FindBin(100));
 sc2_eAll->SetLineColor(4);
 sc2_eAll->Rebin(rebinfac);
 sc2_eAll->Draw("same HIST");
 double rate_eAll_sc2= sc2_eAll->Integral(sc2_eAll->GetXaxis()->FindBin(binmin2),sc2_eAll->GetXaxis()->FindBin(100));
 sc2_pip->SetLineColor(2);
 sc2_pip->Scale(0.001);
 sc2_pip->Rebin(rebinfac);
 sc2_pip->Draw("same HIST");
 sc2_pi0->SetLineColor(kGreen+3);
 sc2_pi0->Scale(0.001);
 sc2_pi0->Rebin(rebinfac);
 sc2_pi0->Draw("same HIST");
 double rate_pi0_sc2= sc2_pi0->Integral(sc2_pi0->GetXaxis()->FindBin(binmin2),sc2_pi0->GetXaxis()->FindBin(100));
 leg21->Draw("text same");
lmin4->Draw("same"); 
  cout<<"rate eAll_S2="<<rate_eAll_sc2<<"rate eAll_S1="<<rate_eAll_sc1<<"  "<<"rate_pim_s1="<<rate_pim_sc1<<"  "<<"rate_pim_s2="<<rate_pim_sc2<<"rate_pip_s1="<<rate_pip_sc1<<"rate_pip_s2="<<rate_pip_sc2<<endl;
 c[3] = new TCanvas("c[3]","c[3]",1000,1000);
 c[3]->Divide(1,2);
 c[3]->cd(1);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd1_proton->SetLineColor(6);
  hhit_Edepspd1_proton->Scale(0.001);
  hhit_Edepspd1_proton->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_proton->SetTitle("SPD, SC0 and SC1 trigger");
  hhit_Edepspd1_proton->Rebin(rebinfac);
  hhit_Edepspd1_proton->Draw("HIST");
 double rate_proton_spd1= hhit_Edepspd1_proton->Integral();
  hhit_Edepspd1_pim->SetLineColor(1);
  hhit_Edepspd1_pim->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pim->Scale(0.001);
  hhit_Edepspd1_pim->Rebin(rebinfac);
  hhit_Edepspd1_pim->Draw("same HIST");
 double rate_pim_spd1= hhit_Edepspd1_pim->Integral();
  hhit_Edepspd1_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd1_pi0->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pi0->Scale(0.001);
  hhit_Edepspd1_pi0->Rebin(rebinfac);
  hhit_Edepspd1_pi0->Draw("same HIST");
 double rate_pi0_spd1= hhit_Edepspd1_pi0->Integral();
  hhit_Edepspd1_pip->SetLineColor(2);
  hhit_Edepspd1_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_pip->Scale(0.001);
  hhit_Edepspd1_pip->Rebin(rebinfac);
  hhit_Edepspd1_pip->Draw("same HIST");
 double rate_pip_spd1= hhit_Edepspd1_pip->Integral();
  hhit_Edepspd1_eAll->SetLineColor(4);
  hhit_Edepspd1_eAll->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd1_eAll->Rebin(rebinfac);
  hhit_Edepspd1_eAll->Draw("same HIST");
 double rate_eAll_spd1= hhit_Edepspd1_eAll->Integral();
  TLegend *leg13 = new TLegend(0.45,0.6,0.8,0.88);
  leg13->AddEntry(hhit_Edepspd1_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_spd1),"l");
  leg13->AddEntry(hhit_Edepspd1_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_spd1),"l");
  leg13->SetTextSize(0.06);
  leg13->SetBorderSize(0);
  leg13->SetFillColor(0);
  leg13->Draw("text same");
  c[3]->cd(2);
  gPad->SetGridx();
  gPad->SetGridy();
  gPad->SetLogy();
  hhit_Edepspd2_proton->SetLineColor(6);
  hhit_Edepspd2_proton->Scale(0.001);
  hhit_Edepspd2_proton->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_proton->SetTitle("LASPD, SC0 and SC1 trigger");
  hhit_Edepspd2_proton->Rebin(rebinfac);
  hhit_Edepspd2_proton->Draw("HIST");
 double rate_proton_spd2= hhit_Edepspd2_proton->Integral();
  hhit_Edepspd2_pim->SetLineColor(1);
  hhit_Edepspd2_pim->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pim->Scale(0.001);
  hhit_Edepspd2_pim->Rebin(rebinfac);
  hhit_Edepspd2_pim->Draw("same HIST");
 double rate_pim_spd2= hhit_Edepspd2_pim->Integral();
  hhit_Edepspd2_pi0->SetLineColor(kGreen+3);
  hhit_Edepspd2_pi0->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pi0->Scale(0.001);
  hhit_Edepspd2_pi0->Rebin(rebinfac);
  hhit_Edepspd2_pi0->Draw("same HIST");
 double rate_pi0_spd2= hhit_Edepspd2_pi0->Integral();
  hhit_Edepspd2_pip->SetLineColor(2);
  hhit_Edepspd2_pip->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_pip->Scale(0.001);
  hhit_Edepspd2_pip->Rebin(rebinfac);
  hhit_Edepspd2_pip->Draw("same HIST");
 double rate_pip_spd2= hhit_Edepspd2_pip->Integral();
  hhit_Edepspd2_eAll->SetLineColor(4);
  hhit_Edepspd2_eAll->GetYaxis()->SetRangeUser(1e-3,1e6);
  hhit_Edepspd2_eAll->Rebin(rebinfac);
  hhit_Edepspd2_eAll->Draw("same HIST");
 double rate_eAll_spd2= hhit_Edepspd2_eAll->Integral();
  TLegend *leg14 = new TLegend(0.45,0.6,0.8,0.88);
  leg14->AddEntry(hhit_Edepspd2_eAll,Form("eAll*1000; total rate=%f Hz",rate_eAll_spd2),"l");
  //leg14->AddEntry(hhit_Edepspd2_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pim,Form("bggen #pi^{-}; total rate=%f kHz",rate_pim_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pip,Form("bggen #pi^{+}; total rate=%f kHz",rate_pip_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_pi0,Form("bggen #pi^{0}; total rate=%f kHz",rate_pi0_spd2),"l");
  leg14->AddEntry(hhit_Edepspd2_proton,Form("BeamOnTarget; total rate=%f kHz",rate_proton_spd2),"l");
  leg14->SetTextSize(0.06);
  leg14->SetBorderSize(0);
  leg14->SetFillColor(0);
  leg14->Draw("text same");
 for(int a=0;a<4;a++){
    c[a]->SaveAs(Form("c%d.pdf",a));
    }
             gSystem->Exec("pdfunite ./c*.pdf ./HallC_trigger_rate_comparison_BeamOnTarget.pdf");
             gSystem->Exec(Form("rm -rf ./c*.pdf"));

}
